### ISSUE TITLE
Strong Password problem

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [Kumar-laxmi/Algorithms#10]
kindly assign me this Issue

**Comment by Kumar-laxmi** [comment]
Assigned

**Comment by Kumar-laxmi** [comment]
To make a qualifying PR, you need to apply the algorithm in all four mentioned languages:
- C
- C++
- Python
- Java

**Comment by Kumar-laxmi** [comment]
Kindly push your file in Cryptography folder

**Comment by Sulagna-Dutta-Roy** [comment]
Sure I will do it
