### ISSUE TITLE
 add kadane's algorithm in  JAVA and C++ with proper comments.

### ISSUE THREAD

**Issue by GOPAL181** [Kumar-laxmi/Algorithms#1001]
The idea of Kadane’s algorithm is to maintain a variable max_ending_here that stores the maximum sum contiguous subarray ending at current index and a variable max_so_far stores the maximum sum of contiguous subarray found so far, Everytime there is a positive-sum value in max_ending_here compare it with max_so_far and update max_so_far if it is greater than max_so_far.

it uses 0(N) time complexity.

please assign me this task under ssoc.

**Comment by Kumar-laxmi** [comment]
Sorry this algo. has been implemented in C++ & Java.
