### ISSUE TITLE
Adding Prim's and Kruskal's Algorithm 

### ISSUE THREAD

**Issue by KhushiVaiskyar** [Kumar-laxmi/Algorithms#1007]
I want to add  Prim's and Kruskal's Algorithm in Java  in your repo as I don't see it. Kindly assign me this issue. Thank you

**Comment by SubiditaB** [comment]
Please assign me this issue. I want to contribute to this repo.

**Comment by Kumar-laxmi** [comment]
Prims has been implemented in all languages and Kruskal's issue is open
