### ISSUE TITLE
Add "Grey Wolf Optimization (GWO) " Algorithm

### ISSUE THREAD

**Issue by rayarka26** [Kumar-laxmi/Algorithms#1008]
It is a metaheuristic algorithm inspired by the social behavior and hunting dynamics of grey wolves. It mimics the leadership hierarchy and hunting strategies of grey wolf packs to solve optimization problems.

In GWO, a population of candidate solutions (wolves) iteratively searches for the optimal solution by simulating the social behavior of wolves. The algorithm consists of four main steps: initialization, leadership assessment, hunting, and updating.

Please assign me under SSOC23

**Comment by Kumar-laxmi** [comment]
Assigned!
@rayarka26 : C, C++, Python and Java
