### ISSUE TITLE
Adding Kruskal's Algorithm

### ISSUE THREAD

**Issue by Yogeshkarma** [Kumar-laxmi/Algorithms#1010]
Addition Of krukal's algorithm to draw or find the minimum spanning tree

- In Kruskal’s algorithm, sort all edges of the given graph in increasing order. Then it keeps on adding new edges and nodes in the MST if the newly added edge does not form a cycle. It picks the minimum weighted edge at first at the maximum weighted edge at last. Thus we can say that it makes a locally optimal choice in each step in order to find the optimal solution. Hence this is a [Greedy Algorithm]

- The code offered in Python,Java,C++

**Comment by atinder11** [comment]
Can you assign this issue to me

**Comment by SubiditaB** [comment]
Please assign me this issue. I want to do this.

**Comment by Kumar-laxmi** [comment]
refer #683
