### ISSUE TITLE
Wanted to add Backtracking and recursion algorithms in Java Section

### ISSUE THREAD

**Issue by shubhisingh184** [Kumar-laxmi/Algorithms#1012]
**Is your feature request related to a problem? Please describe.**
I want to add different algorithms in backtracking ( like N- Queens, Rat In a Maze etc) and in recursion ( Tower of Hanoi, staircase etc) and also like to add algorithms to some folders like DP, Stacks, Trees and create a new folder for Hashmaps and include some algorithms in that folder too.

**Comment by Kumar-laxmi** [comment]
All the mentioned algo. are already assigned under various issue, kindly raise one issue per algorithm
