### ISSUE TITLE
String:First and last occurence of given letter in string

### ISSUE THREAD

**Issue by SimranLahrani842** [Kumar-laxmi/Algorithms#1014]
**Is your feature request related to a problem? Please describe.**
Given String we need to find the occurence of given letter.It is most commonly asked question in interviews.

**Comment by SaketGudimella** [comment]
**@Kumar-laxmi** Please assign me this issue under SSoC'23. I will implement this using a python program that efficiently finds the first and last occurrence of a given letter in a given string.

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir please assign me this question. I am able to code it using JAVA and its string methods which will simply produce the output .
for eg : coca cola 
here first occurence of letter 'o' is at index 1 and position 2 ,and last occurence of letter 'o' is at index 6 ie at position 7.


kindly assign me to solve this using JAVA string methods.

**Comment by SimranLahrani842** [comment]
@Soumya6Tiwari and @SaketGudimella please find some other issue as I raised this issue for myself.Thankyou.
