### ISSUE TITLE
Longest Common Subsequence in Python

### ISSUE THREAD

**Issue by Inferno2211** [Kumar-laxmi/Algorithms#1015]
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to a problem. I would like to implement Longest Common Subsequence using Python 

Given two strings, S1 and S2, the algorithm will find the length of the longest subsequence present in both of the strings. 

**Describe the solution you'd like**
I would like a solution for Longest Common Subsequence, using Python.

It would have Time Complexity: O(m * n) and Auxiliary Space: O(m * n), solved using Dynamic Programming

I'd like to work on this issue under SSOC 2023. 
Please assign it to me.

**Comment by atinder11** [comment]
Can you assign this issue to me

**Comment by Kumar-laxmi** [comment]
refer #859
