### ISSUE TITLE
Request to add definition of Divide and Conquer in its Section `(readme.md file)` 

### ISSUE THREAD

**Issue by imranaai** [Kumar-laxmi/Algorithms#1020]
**Is your feature request related to a problem? Please describe.**
The `readme.md` file in the Divide and Conquer section doesn't contains the proper definition.

**Describe the solution you'd like**
Adding a proper definitions with visuals will a good start,

**Describe alternatives you've considered**
Not Applicable

**Additional context**
Have a look into this issue, appreciate that you all are doing a great work.

**Comment by SubiditaB** [comment]
Please assign me this issue. I want to contribute to this repo.

**Comment by neerajrpatil** [comment]
@imranaai  I would like to be assigned to this issue. I am familiar with algorithms and I believe that I can help resolve this issue.

**Comment by imranaai** [comment]
> @imranaai  I would like to be assigned to this issue. I am familiar with algorithms and I believe that I can help resolve this issue.
> 

Hi, 
Contribute to this repository by following the guidelines and tag this issue if you are solving this problem and then one of the collaborators will look into the PR and merge if they find it suitable.

**Comment by PadmeshSharma** [comment]
Please assign this issue to me under SSOC'23. @Kumar-laxmi
