### ISSUE TITLE
Addition of BFS and DFS algorithm in graph.

### ISSUE THREAD

**Issue by souravrjpt** [Kumar-laxmi/Algorithms#1021]
Hey @Kumar-laxmi ,

I want to add BFS and DFS search algorithm in graph (with full description). Kindly, assign me this issue under Ssoc'23.

Thank you

**Comment by TusharGagal** [comment]
I have completed this issue.

**Comment by souravrjpt** [comment]
When?

**Comment by souravrjpt** [comment]
@Kumar-laxmi  How can you assign this issue to @TusharGagal ? Is there any point that I missed as I raised this issue 3 days ago?

**Comment by YourFatherDumb** [comment]
sir pls assign this issue to me as it is assigned to me in quine

**Comment by YourFatherDumb** [comment]
i will complete this issue in c, cpp, java, python
