### ISSUE TITLE
Addition of TOPOLOGICAL SORT by KANH's algorithm

### ISSUE THREAD

**Issue by souravrjpt** [Kumar-laxmi/Algorithms#1022]
Hey @Kumar-laxmi ,
I really want to contribute to your valuable project. I want to add TOPOLOGICAL SORT by  using KANH's algorithm. This sort is really helpful for finding the cycle in graph. It basically only works for DAG (Directed-Acyclic-Graph). 
I'll do this task with my all dedication and with proper comments. I'll also make some  clear points so that it can be easily understand by any newbie who wants to learn.

(If you want I can also paste some leetcode, GFG or hackerrank's questions based on TOPO SORT).

Kindly assign me this task. Eagerly waiting for your reply.
Thank you

**Comment by Kumar-laxmi** [comment]
refer #710
