### ISSUE TITLE
Request for addition of README.md file for Graph section.

### ISSUE THREAD

**Issue by souravrjpt** [Kumar-laxmi/Algorithms#1023]
**Is your feature request related to a problem? Please describe.**
Yes, as I believe no one can understand the code until and unless he/she understand the meaning and concept behind the topic. 

 **What will you contribute?**
I'll make an easy description about "What is Graph?", "Why we use it?", its different applications and different algorithm which is use to approach different algorithm.

**How will you do this?**
Okay, I'll make an easy, simple and understandable description about graph with proper jargon (along with their meanings). Also, I'll provide some sources like medium link or You Tube links where anyone can get the deep view about the graph. Of course, there will be visuals and demonstrative examples to show the respective topic .

**ADDONS**
I'll also provide some DSA based question on graph as well. (If you say)

Kindly, assign me this issue for my contribution in Ssoc'23.

Thank you

**Comment by pro-utkarshM** [comment]
Please assign me!
