### ISSUE TITLE
Ukkonen's Algorithm (Substrings) in C, C++, Python and Java

### ISSUE THREAD

**Issue by Trisha-tech** [Kumar-laxmi/Algorithms#1024]
Is your feature request related to a problem? Please describe.
Yes, my feature request is related to a problem. I would like to implement Ukkonen's algorithm using C, C++, Python and Java languages.

Ukkonen's algorithm is a method of constructing the suffix tree of a string in linear time. Suffix trees are useful because they can efficiently answer many questions about a string, such as how many times a given substring occurs within the string.

Describe the solution you'd like
I would like a solution that provides an implementation of the Ukkonen's algorithm using C, C++, Python and Java languages.

I would like to work on this issue under SSOC 2023. Please assign it to me.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Trisha-tech : C, C++, Java & Python

**Comment by Kumar-laxmi** [comment]
@Trisha-tech what is your status on this issue?

**Comment by Aarsh30** [comment]
as this issuse is prolonged if trisha is not doing this code than @Kumar-laxmi  can you assigned it to me

**Comment by Trisha-tech** [comment]
Hey @Aarsh30, I am working on this issue and will raise the PR within 2-3 days.
