### ISSUE TITLE
N-Queens Problem and Sudoku Solver (Backtracking in C) [SSoC'23]

### ISSUE THREAD

**Issue by prernamittal** [Kumar-laxmi/Algorithms#1032]
**N-Queens Problem:**

**Is your feature request related to a problem? Please describe.**
The problem is to find a placement of N queens on an N×N chessboard such that no two queens threaten each other. 

**Describe the solution you'd like**
I would like a solution that can find all possible placements of N queens on the chessboard such that no two queens can attack each other. 

**Describe alternatives you've considered**
One alternative solution would be to use a brute-force approach where we generate all possible permutations of queen placements and then check each permutation for validity. However, this approach is computationally expensive.

**Additional context**
The N-Queens problem is a classic puzzle in computer science and is often used to demonstrate the use of backtracking algorithms. The solution provided will efficiently find all possible valid placements of N queens on the chessboard.

**Sudoku Solver:**

**Is your feature request related to a problem? Please describe.**
The problem is to solve a 9×9 Sudoku puzzle, where the objective is to fill the grid with digits from 1 to 9 such that each column, each row, and each of the nine 3×3 sub-grids contains all of the digits from 1 to 9. 

**Describe the solution you'd like**
I would like a solution that can take an unsolved Sudoku puzzle as input and solve it by filling in the missing digits while adhering to the Sudoku rules.

**Describe alternatives you've considered**
One alternative solution would be to use a brute-force approach where we generate all possible combinations of digit placements and then check each combination for validity. However, this approach is computationally expensive.

**Additional context**
The Sudoku Solver algorithm is a popular application of the backtracking technique. It efficiently solves Sudoku puzzles by incrementally filling in the missing digits while ensuring that the solution is valid according to the Sudoku rules. The provided solution will solve the Sudoku puzzle and print the solved grid.

I would like to provide the above algorithms in C language. I request @Kumar-laxmi to kindly assign this issue to me for SSoC'23. Thanks!

**Comment by Kumar-laxmi** [comment]
refer #836 & #760
