### ISSUE TITLE
Adding chinese Remainder theorem

### ISSUE THREAD

**Issue by kritika2313** [Kumar-laxmi/Algorithms#1035]
the Chinese Remainder Theorem is used to solve modular arithmetic problems efficiently.
Modular arithmetic involves performing arithmetic operations on remainders. For example, if we divide 13 by 5, the remainder is 3. In modular arithmetic notation, we would write this as 13 ≡ 3 (mod 5), which means that 13 is congruent to 3 modulo 5.

The Chinese Remainder Theorem provides a solution for a system of simultaneous congruences. It states that if we have a set of pairwise coprime moduli (i.e., the greatest common divisor between any two moduli is 1), then there exists a unique solution modulo the product of the moduli.

eg; int num[] = { 3, 4, 5 };
      int rem[] = { 0, 1, 1 };
result will be 21.

I can code this in c++,python and java.
@Kumar-laxmi so can u please assign it to me under ssoc23

**Comment by Kumar-laxmi** [comment]
Assigned!
@kritika2313 : C, C++, Python and Java
