### ISSUE TITLE
Updating Stack README.md

### ISSUE THREAD

**Issue by Yashi11** [Kumar-laxmi/Algorithms#1040]
**Is your feature request related to a problem? Please describe.**
There are no theoretical details about the data-structure or algorithm in the  Repository, which can be a bit troublesome for beginners who know very little about the concepts behind the code. 

**Describe the solution you'd like**
I would like to update the Stack README.md file so that it contains an interactive file for over viewing concepts related to stacks.

**Describe alternatives you've considered**
I can take suggestions from other and improve on the concepts, while adding same to other folders as well.

Please assign the same to me under SSOC'23. @Kumar-laxmi

**Comment by PadmeshSharma** [comment]
Please assign this issue to me under SSOC'23. @Kumar-laxmi
