### ISSUE TITLE
Miller-Rabin Primality Test and Tarjan's Strongly Connected Components Algorithm [SSoC'23]

### ISSUE THREAD

**Issue by prernamittal** [Kumar-laxmi/Algorithms#1042]
**Miller-Rabin Primality Test:**

**Is your feature request related to a problem? Please describe.**
Determining whether a given number is prime or composite is a common problem in number theory. Traditional primality tests may be inefficient for large numbers.

**Describe the solution you'd like**
I would like to have an implementation of the Miller-Rabin primality test in C. This algorithm is a probabilistic primality test that efficiently determines whether a given number is prime or composite. It performs multiple iterations using random witnesses to provide a high probability of correctness.

**Describe alternatives you've considered**
Other primality tests, such as the Sieve of Eratosthenes or the Fermat primality test, have their limitations in terms of efficiency or accuracy. The Miller-Rabin primality test is a well-established alternative that provides a good balance between efficiency and accuracy.

**Additional context**
The Miller-Rabin primality test is widely used in various applications, such as cryptography, where efficient primality testing is required. Having a C implementation of this algorithm would be beneficial for developers working on number theory problems or applications that involve prime numbers.

**Tarjan's Strongly Connected Components (SCC) Algorithm:**

**Is your feature request related to a problem? Please describe.**
Understanding the structure of directed graphs and identifying strongly connected components (SCCs) within them is a common problem in graph theory. Efficient algorithms are needed to solve this problem.

**Describe the solution you'd like**
I would like to have an implementation of Tarjan's Strongly Connected Components (SCC) algorithm in C. This algorithm efficiently finds SCCs in a directed graph using depth-first search and low link values. It provides a way to identify clusters of interconnected nodes within the graph.

**Describe alternatives you've considered**
Other algorithms for finding SCCs, such as Kosaraju's algorithm or the path-based strong component algorithm, exist. However, Tarjan's algorithm is known for its efficiency and simplicity, making it a suitable choice for many applications.

**Additional context**
Understanding the structure of directed graphs and identifying SCCs has applications in various domains, including network analysis, social network analysis, and compiler construction. Having a C implementation of Tarjan's SCC algorithm would be valuable for developers working on graph-related problems or applications that involve analyzing graph connectivity.

I request @Kumar-laxmi to kindly assign this issue to me under SSoC'23. Thanks!

**Comment by prernamittal** [comment]
I can implement these algorithms in C++, Java and Python as well

**Comment by Kumar-laxmi** [comment]
Please raise issue pertaining to one algorithm only

**Comment by prernamittal** [comment]
Okay, I'll open 2 issues for the 2 algorithms separately
