### ISSUE TITLE
[SSoC'23] Boggle solver algorithm

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Kumar-laxmi/Algorithms#1044]
**Is your feature request related to a problem? Please describe.**
- The algorithm is to find all possible words in a Boggle board which can be time-consuming and challenging.

**Describe the solution you'd like**
- I would like a Boggle solver algorithm that can efficiently search for valid words on the board.
- I would like a powerful Boggle solver algorithm that quickly and accurately identifies all valid words on the board.

**Describe alternatives you've considered**
- An alternative approach would be to manually search for words on the board, but it would be time-consuming and error-prone. 
- Another alternative is to use brute-force by checking all possible combinations of letters, but it would be inefficient for larger boards.

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi Please assign this task to me to contribute under SSoC'23 program
/assign

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi Please assign this task to me for a successful contribution under SSoC 2.0
I can solve it in C, C++, PYTHON and JAVA.
So, please assign

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi @zugzwang03 @Arun9739 @072arushi 
Sirs, I have created this issue 3 weeks ago and i have done with this project and want to create a pull request and contribute under SSoC 2.0 program

Please assign this task to me for a successful contribution

**Comment by Kumar-laxmi** [comment]
@Avdhesh-Varshney This is not an algorithm, but just a DSA Interview problem
