### ISSUE TITLE
[SSoC'23] Hierholzer’s Algorithm for directed graph

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Kumar-laxmi/Algorithms#1045]
**Is your feature request related to a problem? Please describe.**
- The problem at hand is to find an Eulerian circuit or path in a directed graph, which is a path that traverses each edge exactly once.

**Describe the solution you'd like**
- I would like to employ Hierholzer's Algorithm, a highly efficient algorithm specifically designed for discovering Eulerian circuits or paths in directed or undirected graphs.

**Describe alternatives you've considered**
- Manual exploration of the directed graph to identify an Eulerian circuit or path. However, this approach can be time-consuming and prone to errors.
- Utilizing a brute-force technique that exhaustively examines all possible paths in the graph to determine an Eulerian circuit or path. Nevertheless, this approach becomes increasingly inefficient as the size of the graph grows.

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi please assign this algorithm to solve under the program SSoC'23 
I can solve this algorithm in C++, C, PYTHON & JAVA programming languages.
/assign

**Comment by Kumar-laxmi** [comment]
Assigned!
@Avdhesh-Varshney : C, C++, Python and Java

**Comment by Monishparameswaran** [comment]
@Kumar-laxmi ,I would like to work on this issue as part of SSoC'23. I have experience working with graph problems in Java and I am familiar with the topic. Please assign this to me.
