### ISSUE TITLE
Reverse a LinkedList by Recursive Approach

### ISSUE THREAD

**Issue by Mansi8874** [Kumar-laxmi/Algorithms#1046]
**Is your feature request related to a problem? Please describe.**
Given the head of a singly linked list, reverse the list by Recursive Approach, and return the reversed list.

**Describe the solution you'd like**
The recursive approach to reverse a linked list is simple, just we have to divide the linked lists in two parts and i.e first node and the rest of the linked list, and then call the recursion for the other part by maintaining the connection.

**Describe alternatives you've considered**
Define a recursive function that takes a pointer to the head of the linked list as a parameter.

Check if the head is either NULL or the last node in the list (i.e., the next node is NULL). If either condition is true, return the head itself as it will be the new head of the reversed list.

Call the recursive function recursively with the next node in the list. This will reverse the sublist starting from the next node.

The next node's next pointer should be set to the current node (head) to reverse the direction of the pointer.

Set the current node's next pointer to NULL to mark it as the last node in the reversed list.

Finally, return the new head of the reversed list.

**Additional context**
I want to work on this issue. Please assign this issue to me.

**Comment by Kumar-laxmi** [comment]
Sorry this algorithm has been implemented in all four languages
