### ISSUE TITLE
[ssoc'2023] traveling salesman problem

### ISSUE THREAD

**Issue by rajputsingh808** [Kumar-laxmi/Algorithms#1047]
**Is your feature request related to a problem? Please describe.**
As I haven't seen tsp related problems, so I want to do this.

**Describe the solution you'd like**
want to solve tsp problem using c

**Comment by mayank2mahi** [comment]
@Kumar-laxmi Sir ji please assign me this issue as I eagerly want to contribute to this issue under SSoC'23.

**Comment by anasadh** [comment]
@Kumar-laxmi  Sir please assign me this as I want to contribute in SSOC'23 and I am practicing dsa as well so kindly provide me this.
