### ISSUE TITLE
Remove Nth Node From End of List

### ISSUE THREAD

**Issue by Mansi8874** [Kumar-laxmi/Algorithms#1048]
**Is your feature request related to a problem? Please describe.**
Given the head of a linked list, remove the nth node from the end of the list and return its head.

**Describe the solution you'd like**
Traverse the linked list to determine its size or length.
If the desired position (n) is equal to the size, remove the head node and return the new head.
If the desired position (n) is greater than the size, no removal is required, so return the original head.
Traverse the linked list again, stopping at the node just before the one to be removed (size - n).
Adjust the pointers to skip the nth node and remove it from the list.
Return the original head of the modified linked list.

**Additional context**
I want to work on this issue. Please assign this issue to me

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir sir please assign me this issue. I can solve this problem using C,C++. This would be a good start for me .

**Comment by Kumar-laxmi** [comment]
This operation has been done in algorithm implemented on Singly Linked Lists
