### ISSUE TITLE
[SSoC'23] Heapify {max-heap and min-heap} algorithm

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Kumar-laxmi/Algorithms#1052]
**Is your feature request related to a problem? Please describe.**
- The problem is to efficiently create or maintain a max-heap or min-heap data structure.

**Describe the solution you'd like**
- I would like an algorithm for heapify that can transform an array into a valid max-heap or min-heap. 
- This algorithm will be ensuring that the heap property is satisfied. 
- This would allow for efficient operations such as extracting the maximum or minimum element, or efficiently sorting the elements.

**Describe alternatives you've considered**
- Manually implementing the heapify operation, which can be time-consuming and error-prone.
- Utilizing other data structures or sorting algorithms, but they may not provide the same efficient heap operations or sorting capabilities as a properly heapified structure.

**Additional context**

Efficiently maintaining a heap data structure through heapify is crucial for various applications, such as priority queues, graph algorithms (e.g., Dijkstra's algorithm), and sorting algorithms (e.g., Heap Sort). A reliable heapify algorithm would greatly enhance the performance and versatility of these applications.

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi Please assign this algorithm to me to contribute under the program SSoC'23
/assign

**Comment by SANKOJUKEERTHI** [comment]
Please assign this algorithm to me to contribute under the program SSoC'23
I can solve this algorithm in JAVA.
We will have a BT which needs to be converted into a heap data structure. 
Initially, we will take the leaf element as a heap, and now we will consider an element in the last but one layer and its children and adjust them to form a heap; likewise, we will continue till the root element.

heapify take O(n), which is much faster than creating a heap which takes O(nlogn)

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi Please assign this task to me. I want to create a pull request as i have done this task.
So, please assign this task for a successful contribution under SSoC 2.0

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi please assign this program to me to create a pull request and contribute in this repository under SSoC 2.0 program

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi @zugzwang03 @Arun9739 @072arushi 
Sirs, I have created this issue 3 weeks ago and i have done with this project and want to create a pull request and contribute under SSoC 2.0 program

Please assign this task to me for a successful contribution

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi @zugzwang03 @Arun9739 @072arushi please assign this algorithm to me

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi @zugzwang03 @Arun9739 @072arushi sir, please assign this algorithm to me
i have also ready with the code and want to create a pr under SSoC 2.0
i can solve it in C, C++, JAVA, and PYTHON
