### ISSUE TITLE
Longest Palindromic Subsequence in C++,Java

### ISSUE THREAD

**Issue by dhruti26** [Kumar-laxmi/Algorithms#1057]
**Problem Statement**
A palindromic string is a string that is equal to its reverse. For example: “nitin” is a palindromic string. We need to find the length of the longest palindromic subsequence of a string.
![image](https://github.com/Kumar-laxmi/Algorithms/assets/106862356/59c6bd98-dcd0-4464-8897-37af29449171)
**Describe the solution**
We need to print the length of the longest palindromic subsequence.

**Comment by dhruti26** [comment]
Please assign this issue to me @Kumar-laxmi under SSOC '23

**Comment by mavihsrr** [comment]
@Kumar-laxmi please assign this to me
