### ISSUE TITLE
Optimized solution for Finding length of Linked List.

### ISSUE THREAD

**Issue by Kolwankar-Siddhiraj** [Kumar-laxmi/Algorithms#1059]
[SSoC'23] The Time Complexity of currently written solution for finding length of linked list is O( n ). I want to optimize this solution and bring time complexity as low as O( n/2 ).

Please assign me this issue.

**Comment by Kolwankar-Siddhiraj** [comment]
I have written a optimized solution for this issue. And reduced time complexity of finding length of linked list from O(n) to O(n/2)

**Comment by Khushi-74** [comment]
I have a proper approach with explanation please assign me this under ssoc'23

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir kindly assign me this issue, I can code this using c, c++

**Comment by Soumya6Tiwari** [comment]
> I have written a optimized solution for this issue. And reduced time complexity of finding length of linked list from O(n) to O(n/2).
> 
> Please assign me this issue because I have solution ready to merge for this issue.

Please correct me as I may be wrong but I think time complexity  O(n/2) is equivalent to O(n)  only as here the factor 1/2 is constant so O(kn) =O(n)

**Comment by Kolwankar-Siddhiraj** [comment]
> > I have written a optimized solution for this issue. And reduced time complexity of finding length of linked list from O(n) to O(n/2).
> > 
> > Please assign me this issue because I have solution ready to merge for this issue.
> 
> Please correct me as I may be wrong but I think time complexity  O(n/2) is equivalent to O(n)  only as here the factor 1/2 is constant so O(kn) =O(n) 

I didn't get your point. Can you please explain to me by giving an example.

**Comment by pro-utkarshM** [comment]
Please assign me this!
