### ISSUE TITLE
Cuckoo Hashing

### ISSUE THREAD

**Issue by abhishekmpote** [Kumar-laxmi/Algorithms#1060]
Dear repository maintainers,

I would like to propose the addition of the Cuckoo Hashing algorithm to the repository. Cuckoo Hashing is a powerful hashing technique that offers efficient key-value storage and retrieval operations. It would be a valuable addition to the project's collection of algorithms.

I propose implementing the Cuckoo Hashing algorithm in the following programming languages:

C
C++
Java
Python
Cuckoo Hashing provides constant-time average-case complexity for search, insertion, and deletion operations, making it a highly efficient data structure. It is particularly useful in scenarios where fast key-value lookups are required, such as in hash tables or caches.

I am eager to contribute to this feature and would be thrilled to take ownership of this issue. I will ensure the algorithm's correct implementation, thoroughly test it, and provide comprehensive documentation for each language implementation.

Please assign this issue to me, and I will begin working on it immediately. I am excited to collaborate with the community and make a meaningful contribution to the project.

Thank you!

Best regards,
Abhishek(Ssoc'23)

**Comment by Kumar-laxmi** [comment]
Assigned!
@abhishekmpote : C, C++, Java & Python
