### ISSUE TITLE
XGBoost Algorithm in Python, Java, C++ and Python

### ISSUE THREAD

**Issue by derphalesh** [Kumar-laxmi/Algorithms#1064]
I want to request the addition of the XGBoost algorithm to the repository. XGBoost is a robust machine-learning algorithm that offers exceptional predictive modelling capabilities. Its inclusion would greatly enhance the repository's range of available algorithms and provide users with a valuable tool for various data science tasks.

I would like a solution that provides an implementation of the XGBoost algorithm in Python, Java, C++ and C languages.

I would like to work on this issue under SSOC 2023. Please assign it to me.

**Comment by Kumar-laxmi** [comment]
Assigned!
@derphalesh : C, C++, Java & Python

**Comment by Kumar-laxmi** [comment]
@derphalesh  What is your update on this?

**Comment by derphalesh** [comment]
The python bit is done had some problems in it as I am not using ml libraries.Working on other languages

**Comment by Kumar-laxmi** [comment]
Kindly complete the implementation within next 1 week or else the issue would be closed

**Comment by derphalesh** [comment]
sure sir
