### ISSUE TITLE
Count Primes

### ISSUE THREAD

**Issue by KhushiVaiskyar** [Kumar-laxmi/Algorithms#1065]
If an integer n is given , My code will return the number of prime numbers that are strictly less than n.
Please Assign me this  issue. Thank you

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir please assign me this issue , I really want to make a start in open source, kindly assign me this issue. I can solve it using C, C++,  JAVA

**Comment by RugvedDhabale** [comment]
Would like to contribute in this issue. Please assign me this issue

**Comment by Ashutosh-0506** [comment]
@Kumar-laxmi I would like to contribute to this issue. Please assign me this issue.

**Comment by jinx-vi-0** [comment]
@Kumar-laxmi can you assign me this under SSOC'23

Method 1: A simple solution is to traverse all the numbers, check if current number is prime. If yes, increment the count. Finally, return the count.

Method 2: An efficient solution is to use Sieve of Eratosthenes algorithm to find all primes up to the given limit.

 Time Complexity : O(n * log(log(n)))
 Space Complexity : O(n)
