### ISSUE TITLE
Wrong comments and scanner not closed in Java programs

### ISSUE THREAD

**Issue by yashSingh97** [Kumar-laxmi/Algorithms#1068]
**Is your feature request related to a problem? Please describe.**
I have noticed many java programs:
- have wrong comments used such as caesarcipher.java uses "" not // or /**/ which breaks code. 
- scanner is not closed such as in hillcipher
- few programs uses // and not /**/ for multi line comments, which looks messy.

**Describe the solution you'd like**
I want to fix these issue in all java programs because it either breaks the code or code doesn't look clean.

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir kindly assign me this issue  , I can fix these issues

**Comment by VoidVampire** [comment]
@Kumar-laxmi sorry I forgot to tag you, but can you assign me this issue under SSOC'23? I was the first one to post the issue. 
Thanks!

**Comment by sarmistha-02** [comment]
@Kumar-laxmi sir I can resolve the above mentioned issue. It would be great if you would kindly assign me this issue.
