### ISSUE TITLE
Processing Scheduling Algorithms

### ISSUE THREAD

**Issue by Biswajit-Behera** [Kumar-laxmi/Algorithms#1071]
The activity of process manager handles the removal of the running process from the CPU and the selection of another process on the basis of a particular strategy.
The approach we take :- 
First Come First Serve
Shortest Job First 
Priority 
Round Robin

All the program are in C/CPP

**Comment by Rahul-Talari** [comment]
I have worked on this problems could you please assign me this task .I would solve it efficiently . I can give code in c,c++,java and python.It would be so helpful for me to give a good start for ssoc 23 .

**Comment by MAYURIKOTHARI299** [comment]
@Biswajit-Behera please assign me this issue I have already done this topic and could provide the best code for all the algorithms, under ssoc'23

**Comment by Biswajit-Behera** [comment]
@MAYURIKOTHARI299 and @Rahul-Talari Kindly find some other issue as I am working on this particular issue.  I cannot assign this issue as I am not the owner of this repository
