### ISSUE TITLE
KNN Algorithm in Python, Java, C++ and Python

### ISSUE THREAD

**Issue by SanketPatil7467** [Kumar-laxmi/Algorithms#1072]
The KNN algorithm is widely used for classification and regression tasks, and its inclusion would greatly benefit developers who work with these languages for machine learning applications. 

I would like a solution that provides an implementation of the KNN algorithm in Python, Java, C++ and C languages.

I would like to work on this issue under SSOC 2023. Please assign it to me.

**Comment by Kumar-laxmi** [comment]
Assigned!
@SanketPatil7467 : Java & Python

**Comment by Kumar-laxmi** [comment]
@SanketPatil7467 Kindly complete the implementation within next 3 days or else the issue would be closed
