### ISSUE TITLE
Reverse an array

### ISSUE THREAD

**Issue by avantikachauhann** [Kumar-laxmi/Algorithms#1073]
**Is your feature request related to a problem? Please describe.**
Java program to reverse an array.

**Describe the solution you'd like**
Using Temp array. 

**Describe alternatives you've considered**
The array arr[] is iterated from the first element, and each element of array arr[] is placed in the new array from the back, i.e., the new array is iterated from its last element.

**Additional context**

<img width="1135" alt="Screenshot 2023-06-03 at 3 10 15 PM" src="https://github.com/Kumar-laxmi/Algorithms/assets/101965370/6f21051b-69e4-4b71-8aa1-798122c009e3">

**Comment by imranaai** [comment]
Have you created a PR for this issue already?

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir kindly assign me this issue. I can solve it using C, C++, JAVA.

**Comment by vivekpal24** [comment]
Sir Assign this to me i can solve this issue using C Cpp and Python.

**Comment by kirtilulle** [comment]
Java:
public class ReverseArray{
    static void reverse(int[] arr){
        int i=0,j=arr.length-1;
        while(i<j){
            int t=arr[i];
            arr[i]=arr[j];
            arr[j]=t;
            i++;
            j--;
        }
    }
    public static void main(String[] args){
        int[] arr={2,4,6,8,10,12,14};
        for(int i=0;i<arr.length;i++){
            System.out.print(arr[i] + " ");
        }
        reverse(arr);
        System.out.println();
        for(int i=0;i<arr.length;i++){
            System.out.print(arr[i] + " ");
        }
    }
}
I can write the code in C++, C and Python. Please assign this to me .

**Comment by Ashutosh-0506** [comment]
@Kumar-laxmi I would like to contribute to this issue. Please assign me this issue.

**Comment by jinx-vi-0** [comment]
@Kumar-laxmi can you assign me this under SSOC'23

Is your feature request related to a problem? Please describe.
Java program to reverse an array.

Describe the solution you'd like

Approach : Iterative way
1) Initialize start and end indexes as start = 0, end = n-1 
2) In a loop, swap arr[start] with arr[end] and change start and end as follows : 
start = start +1, end = end – 1

Time Complexity: O(n)
Auxiliary Space: O(1)
