### ISSUE TITLE
AdaBoost algorithm in C,C++,Java and Python

### ISSUE THREAD

**Issue by abhishekmpote** [Kumar-laxmi/Algorithms#1074]
I would like to request the addition of the AdaBoost algorithm to the repository. AdaBoost is a powerful machine-learning algorithm that can be used for both classification and regression tasks. It is based on the principle of boosting, which means that it trains a series of weak learners and then combines them to create a strong learner. AdaBoost has been shown to be very effective on a variety of problems, and its inclusion in the repository would be a valuable addition.

I would like a solution that provides an implementation of the AdaBoost algorithm in Python, Java, C++, and C languages.
I would also like to work on this issue under SSOC 2023. Please assign it to me.

**Comment by Kumar-laxmi** [comment]
Assigned!
@abhishekmpote : C, C++, Java & Python

Please don't use ML Libraries

**Comment by Kumar-laxmi** [comment]
@abhishekmpote  What is your update on this?

**Comment by Kumar-laxmi** [comment]
Kindly complete the implementation within next 3 days or else the issue would be closed
