### ISSUE TITLE
Request to add the code for implementation of `stack` using `queues` in `Java`

### ISSUE THREAD

**Issue by imranaai** [Kumar-laxmi/Algorithms#1079]
**Is your feature request related to a problem? Please describe.**
Make the understanding of the stacks better.

**Describe the solution you'd like**
A clear and concise code of the implementation of stacks using  queues would be a good approach in order to make the people understand the concept of Stacks in depth.

**Describe alternatives you've considered**
At least the definition must be added to make the people understand the implementation of Stacks using queues theoretically.

**Additional context**
Your contributions are appreciated.

**Comment by jinx-vi-0** [comment]
@Kumar-laxmi can you assign me this under SSOC'23

There are two approaches to implement stack using Queue:

1. First, we can make the push operation costly.
2. Second, we can make the pop operation costly.

I will add code in java with detailed comments for easy understandable. I will also add detailed time and space complexity analysis. I will also add the basic definition of the both data structures and detail explanation of the problem.
