### ISSUE TITLE
Sort an array of 0s, 1s and 2s

### ISSUE THREAD

**Issue by Mansi8874** [Kumar-laxmi/Algorithms#1080]
**Is your feature request related to a problem? Please describe.**
Given an array of size N containing only 0s, 1s, and 2s; sort the array in ascending order.

**Describe the solution you'd like**
 We will counts the occurrences of each element and then modifies the array to place the 0s, 1s, and 2s in sorted order.

**Additional context**
I want to work on this issue. Please assign this issue to me @Kumar-laxmi

**Comment by imranaai** [comment]
Hi @Mansi8874 in which programming language do you want to add this question/algorithm?

**Comment by Kumar-laxmi** [comment]
refer #804
