### ISSUE TITLE
  Minimum no. of Jumps to reach end of an array [Implementation in C++[SSOC]]

### ISSUE THREAD

**Issue by AnubhaSharma2709** [Kumar-laxmi/Algorithms#1081]
Given an array of N integers arr[] where each element represents the maximum length of the jump that can be made forward from that element. This means if arr[i] = x, then we can jump any distance y such that y ≤ x.
Find the minimum number of jumps to reach the end of the array (starting from the first element). If an element is 0, then you cannot move through that element.

Pls Assign this issue to me
Under SSoC'23

**Comment by Daksh-Maru** [comment]
Please assign this to me. I would like to solve this problem.

**Comment by vivekpal24** [comment]
Can you Assign this to me I can solve this in three language in C, CPP and python

**Comment by Kumar-laxmi** [comment]
Please don't raise issues to solve LeetCode, gfg or hackerrank questions
