### ISSUE TITLE
[SSoC'23] Bucket Sort Algorithm Implementation

### ISSUE THREAD

**Issue by mohitsingh1011** [Kumar-laxmi/Algorithms#1082]
Bucket sort is mainly useful when input is uniformly distributed over a range. For example, consider the following problem. 
Sort a large set of floating point numbers which are in range from 0.0 to 1.0 and are uniformly distributed across the range. How do we sort the numbers efficiently?
A simple way is to apply a comparison based sorting algorithm. The lower bound for Comparison based sorting algorithm (Merge Sort, Heap Sort, Quick-Sort .. etc) is Ω(n Log n), i.e., they cannot do better than nLogn. 
Can we sort the array in linear time? Counting sort can not be applied here as we use keys as index in counting sort. Here keys are floating point numbers.  
The idea is to use bucket sort. Following is bucket algorithm.

bucketSort(arr[], n)
1) Create n empty buckets (Or lists).
2) Do following for every array element arr[i].
.......a) Insert arr[i] into bucket[n*array[i]]
3) Sort individual buckets using insertion sort.
4) Concatenate all sorted buckets.	

    
	//TIME COMPLEXITY:  O(N) 
	//SPACE COMPLEXITY: O(N)

**Comment by mohitsingh1011** [comment]
@Kumar-laxmi please assign me this under SSoC'23.

**Comment by mohitsingh1011** [comment]
It is already implemented using C and Python. I will do it with C++ and java.

**Comment by Kumar-laxmi** [comment]
refer #674

**Comment by MohitSingh101** [comment]
It's in C and python i will do it with C++ and Java.

**Comment by mohitsingh1011** [comment]
@Kumar-laxmi It's in C and python i will do it with C++ and Java.
