### ISSUE TITLE
[SSoC'23] Binary Search in 2D Array Using C++

### ISSUE THREAD

**Issue by mohitsingh1011** [Kumar-laxmi/Algorithms#1083]
You are given an m x n integer matrix with the following two properties:

    Each row is sorted in non-decreasing order.
    The first integer of each row is greater than the last integer of the previous row.
    Given an integer target, return true if the target is in the matrix or false otherwise.

    You must write a solution in O(log(m * n)) time complexity.

    1.Input: matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 3
    Output: true

    2.Input: matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 13
    Output: false

**Comment by mohitsingh1011** [comment]
@Kumar-laxmi assign this to me under SSoC'23

**Comment by Kumar-laxmi** [comment]
sorry this algo has been implemented in all four languages
