### ISSUE TITLE
ADD:job sequencing algotihms in C , C++, Python

### ISSUE THREAD

**Issue by shravanii2308** [Kumar-laxmi/Algorithms#1087]
**Is your feature request related to a problem? Please describe.**
Job sequencing algorithms are used to solve the Job Sequencing Problem (JSP), which involves scheduling a set of jobs with associated deadlines and profits to maximize the total profit. The objective is to determine the order in which the jobs should be executed to achieve the maximum profit while meeting the given deadlines.

**Describe the solution you'd like**
There are two commonly used algorithms for solving the Job Sequencing Problem:
Greedy Algorithm:
The Greedy Algorithm sorts the jobs in descending order based on their profits and then assigns them to time slots starting from the deadline. It keeps track of the occupied time slots to ensure that a job is not assigned to a slot that is already occupied. This algorithm has a time complexity of O(n^2) and is suitable for cases where all jobs have the same processing time.

Modified Greedy Algorithm:
The Modified Greedy Algorithm is an enhancement of the basic Greedy Algorithm. It also sorts the jobs based on their profits in descending order. However, instead of directly assigning jobs to the time slots, it uses a disjoint set data structure to determine whether a time slot is available for a job. This algorithm has a time complexity of O(n log n) and is suitable for cases where each job can have a different processing time.

Both algorithms aim to maximize the total profit, but they differ in their approach to scheduling the jobs. The choice of algorithm depends on the specific requirements of the problem and the characteristics of the job set.
I would like to add this algorithm in both approaches with comments

**Additional context**
@Kumar-laxmi I request you to assign me this issue

**Comment by Kumar-laxmi** [comment]
Sorry this algorithm has been implemented in all four languages
