### ISSUE TITLE
Otsu's thresholding algorithm

### ISSUE THREAD

**Issue by SanketPatil7467** [Kumar-laxmi/Algorithms#1090]
Currently, there is no built-in support in Python's image processing libraries, such as OpenCV or scikit-image, to directly apply Otsu's thresholding algorithm. 

I would like to request the addition of a native function for implementing Otsu's thresholding algorithm. Having a built-in feature for Otsu's thresholding would empower Python developers to automatically determine an optimal threshold value based on the image's histogram, allowing for accurate image segmentation. 

I would like to work on this issue under SSOC 2023. Please assign it to me.

**Comment by Kumar-laxmi** [comment]
Assigned!
@SanketPatil7467 : Python and Java

Kindly don't use any image processing library to execute this algorithm, you can use simply libraries such as Numpy, etc

**Comment by Kumar-laxmi** [comment]
@SanketPatil7467 What is your update on this issue?
