### ISSUE TITLE
Adding Exponential Search Algorithm

### ISSUE THREAD

**Issue by kritika2313** [Kumar-laxmi/Algorithms#1097]
Exponential search algorithm targets a range of an input array in which it assumes that the required element must be present in and performs a binary search on that particular small range. This algorithm is also known as doubling search or finger search.
 If the element does not match, jump through the array exponentially in the powers of 2. Therefore, now the algorithm compares the element present in the incremental position.
Input:  arr[] = {10, 20, 40, 45, 55}
        x = 45
Output: Element found at index 3

i acn code this in c,c++,java and python.

So @Kumar-laxmi  can you pls assign it to me under ssoc'23

**Comment by Kumar-laxmi** [comment]
Assigned!
@kritika2313 : C, C++, Java & Python
