### ISSUE TITLE
AVL Trees

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#11]
Implement AVL Tree using the following four languages:
- C
- C++
- Python
- Java

**Comment by Paritosh-J** [comment]
I request you to please assign me this issue.

**Comment by Kumar-laxmi** [comment]
Implemention AVL Tree available using the following two languages:

- C
- Java

**Comment by Sowham-3098** [comment]
Please assign this task to me @Kumar-laxmi for C language

**Comment by harshraj9988** [comment]
I request you to please assign this task to me for Java language

**Comment by Kumar-laxmi** [comment]
Assigned!
@Sowham-3098 : C
@harshraj9988 : Java

**Comment by Kumar-laxmi** [comment]
@Sowham-3098 What is your status on this issue

**Comment by Sowham-3098** [comment]
I will do it by today

**Comment by khushigarg1** [comment]
Can you assign me it in C++.
