### ISSUE TITLE
AO* algorithm 

### ISSUE THREAD

**Issue by SimranLahrani842** [Kumar-laxmi/Algorithms#1102]
The AO* method divides any given difficult problem into a smaller group of problems that are then resolved using the AND-OR graph concept. AND OR graphs are specialized graphs that are used in problems that can be divided into smaller problems. The AND side of the graph represents a set of tasks that must be completed to achieve the main goal, while the OR side of the graph represents different methods for accomplishing the same main goal.

**Comment by SimranLahrani842** [comment]
> The AO* method divides any given difficult problem into a smaller group of problems that are then resolved using the AND-OR graph concept. AND OR graphs are specialized graphs that are used in problems that can be divided into smaller problems. The AND side of the graph represents a set of tasks that must be completed to achieve the main goal, while the OR side of the graph represents different methods for accomplishing the same main goal.

@Kumar-laxmi assign me this

**Comment by Kumar-laxmi** [comment]
Assigned!
@SimranLahrani842 : C, C++, Java & Python
