### ISSUE TITLE
rotate a matrix 

### ISSUE THREAD

**Issue by mohitsingh1011** [Kumar-laxmi/Algorithms#1108]
Rotate clockwise and anti-clockwise

This implementation first defines two functions, rotate clockwise and rotate counterclockwise, 
to rotate the image by 90 degrees clockwise and counterclockwise, respectively. 
Each function takes a 2D vector image as input and modifies it in place.

The printImage function is used to print the image for demonstration purposes.

Finally, the main function initializes an example image, prints it, rotates 
it by 90 degrees clockwise, prints it again, rotates it by 90 degrees counterclockwise, 
and prints it one last time to verify that the rotations worked as expected.

**Comment by mohitsingh1011** [comment]
@Kumar-laxmi assign this to me under SSoC'23

**Comment by Kumar-laxmi** [comment]
This is a LeetCode Question, please don't raise issues to solve LeetCode, gfg or hackerrank questions
