### ISSUE TITLE
Left View of Binary Tree in JAVA

### ISSUE THREAD

**Issue by Mansi8874** [Kumar-laxmi/Algorithms#1109]
**Is your feature request related to a problem? Please describe.**
Given a Binary Tree, return Left view of it. Left view of a Binary Tree is set of nodes visible when tree is visited from Left side. The task is to complete the function leftView(), which accepts root of the tree as argument.

Left view of following tree is:

![leftview](https://github.com/Kumar-laxmi/Algorithms/assets/101468475/588f5ff5-6d5b-4091-a7de-2d8e46ef3c81)

Output: 10 20 40
**Additional context**
I want to work on this issue. Please assign this issue to me @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
refer #715
