### ISSUE TITLE
Right View of Binary Tree in JAVA

### ISSUE THREAD

**Issue by Mansi8874** [Kumar-laxmi/Algorithms#1110]
**Is your feature request related to a problem? Please describe.**
Given a Binary Tree, find Right view of it. Right view of a Binary Tree is set of nodes visible when tree is viewed from right side.

Right view of following tree is:

![leftview](https://github.com/Kumar-laxmi/Algorithms/assets/101468475/16dcf58a-9c0c-40b7-9149-30ddbe21235e)

Output: 10 30 60
**Additional context**
I want to work on this issue. Please assign this issue to me @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
refer #715
