### ISSUE TITLE
Top View of Binary Tree in JAVA

### ISSUE THREAD

**Issue by Mansi8874** [Kumar-laxmi/Algorithms#1111]
**Is your feature request related to a problem? Please describe.**
Given below is a binary tree. The task is to print the top view of binary tree. Top view of a binary tree is the set of nodes visible when the tree is viewed from the top. For the given below tree

![leftview](https://github.com/Kumar-laxmi/Algorithms/assets/101468475/b66b3883-d885-4dcb-b907-25da957fdb86)

Top view will be: 40 20 10 30

**Additional context**
I want to work on this issue. Please assign this issue to me @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
refer #715
