### ISSUE TITLE
Request to add `Knights Tour` problem 

### ISSUE THREAD

**Issue by imranaai** [Kumar-laxmi/Algorithms#1118]
**Is your feature request related to a problem? Please describe.**
Knight's tour problem is a very good question to practice and get deep understanding in backtracking. `A knights tour is a sequence of moves of a knight on a chessboard such that the knight visits every square once.`

**Describe the solution you'd like**
We can add the code for this problem using different programming languages in their respective sections, using backtracking we can solve this question in any programming language.

**Describe alternatives you've considered**
At least a clear and concise description would be enough until the code for this problem is not implemented.

**Additional context**
I want to add some labels for the programming languages this problem could be solved, but I am new to `Github` and `Open-Source` and I don't how to it, so someone please let me know how can I do i.

**Comment by keenpaul29** [comment]
Please assign this issue to me. I think I can add the code.
