### ISSUE TITLE
Finding a number is Strong Number or not

### ISSUE THREAD

**Issue by HardikGoyal2003** [Kumar-laxmi/Algorithms#1121]
What is a strong number?
A strong number is a positive integer whose sum of factorials of its digits equals the number itself. In other words, if we take the digits of a number and calculate the factorial of each digit, then sum those factorials, and the result is the same as the original number, then that number is called a strong number.

Hi @Kumar-laxmi , I want to Implement this problem using C , C++ , Python please assign me this task under label SSOC'23

**Comment by SKSADIRUDDIN** [comment]
@Kumar-laxmi  pls assign me 
I can write code in many languages 

I am writing the brute force code for it

int factorial(int num) {
    if (num == 0 || num == 1) {
        return 1;
    } else {
        return num * factorial(num - 1);
    }
}

bool isStrongNumber(int num) {
    int originalNum = num;
    int sum = 0;

    while (num > 0) {
        int digit = num % 10;
        sum += factorial(digit);
        num /= 10;
    }

    return (sum == originalNum);
}

**Comment by Kumar-laxmi** [comment]
Assigned!
@HardikGoyal2003 : C, C++, Python & Java
