### ISSUE TITLE
Sieve of Eratosthenes

### ISSUE THREAD

**Issue by SPARSH1608** [Kumar-laxmi/Algorithms#1123]
### Feature :
Add Sieve of Eratosthenes in competitive programming  in C, C++ and Python.

### Description of solution :
The sieve of Eratosthenes is one of the most efficient ways to find all primes smaller than n when n is smaller than 10 million
Will add Sieve of Eratosthenes with adequate comments for readers to get a clear understanding.
To add in C, C++ and python .

### Alternatives Considered :
Online Resources and Tutorials

Can you assign me this issue under SSoC '23 @Kumar-laxmi ?

**Comment by Kumar-laxmi** [comment]
Sorry this algo has been implemented in all four languages
