### ISSUE TITLE
New Algorithm : Tower Of Hanoi [JAVA] [SSOC'23]

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Kumar-laxmi/Algorithms#1124]
**Is your feature request related to a problem? Please describe.**
I saw that Tower Of Hanoi was not there in JAVA 

**Describe the solution you'd like**
I will be adding Tower of Hanoi Program using Java

Please assign me this issue under SSOC'23

**Comment by Rahul-Talari** [comment]
I have done this. I can give you the optimal code in Java with fewer lines,better understanding, and better readability. Please assign me this issue; it will be so helpful. I have raised so many issues but didn't get a chance, and if you allocate this, it will be a good start for me in ssoc23

**Comment by Kumar-laxmi** [comment]
refer #677
