### ISSUE TITLE
[Adding Algorithm] : Backtracking - Rat in maze and N-queen

### ISSUE THREAD

**Issue by AKACHI-4** [Kumar-laxmi/Algorithms#1125]
**_Hey 👋 I am a SSOC'23 contributor_**

<br>

**Is your feature request related to a problem? Please describe.**
> As I can see in the repository no Backtracking problems are added there. The Folder is Empty.

**Describe the solution you'd like**
> I would like to add Rat in maze and N-queen problem in C++/Backtracking. 

**Additional context**
> I will provide an faster, optimal and descriptive code in c++, which will help folks to understand the algorithm nicely. 

<br>

**_Kindly assign this issue to me 
Thank you .._**

**Comment by Kumar-laxmi** [comment]
refer #760
