### ISSUE TITLE
Daisy Chain Algorithm using c

### ISSUE THREAD

**Issue by namanshah22** [Kumar-laxmi/Algorithms#1126]
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to a problem. The problem is that the current implementation of the Daisy Chain Algorithm in the Algorithms repository does not handle interrupts from multiple devices efficiently. This can lead to performance issues in systems with a large number of I/O devices.

**Describe the solution you'd like.**
I would like to request that you implement a new version of the Daisy Chain Algorithm that handles interrupts from multiple devices more efficiently. This can be done by using a technique called "priority-based interrupt handling." Priority-based interrupt handling allows the CPU to prioritize interrupts so that the most important interrupts are handled first. This can help to improve the performance of systems with a large number of I/O devices.

**Describe alternatives you've considered.**
I have considered two alternative solutions to the problem of inefficient interrupt handling in the current implementation of the Daisy Chain Algorithm. The first alternative is to use a technique called "round-robin interrupt handling." Round-robin interrupt handling allows the CPU to handle interrupts from all devices in a round-robin fashion. This can help to improve the fairness of interrupt handling, but it may not improve the overall performance of the system. The second alternative is to use a technique called "polling." Polling allows the CPU to periodically check all devices for interrupts. This can be a simple and efficient way to handle interrupts, but it may not be able to handle high-priority interrupts in a timely manner.

**Additional context**
I believe that implementing a new version of the Daisy Chain Algorithm that uses priority-based interrupt handling would be a valuable addition to the Algorithms repository. This algorithm would be more efficient than the current implementation and would be able to handle interrupts from multiple devices more effectively.

@Kumar-laxmi, @zugzwang03 and @Arun9739 I would be happy to help you implement this algorithm in the repository if you would like.

**Comment by Kumar-laxmi** [comment]
Please chose one more language to implement
