### ISSUE TITLE
[SSoC'23] Graphs_bfs 

### ISSUE THREAD

**Issue by mohitsingh1011** [Kumar-laxmi/Algorithms#1130]
Graphs Adjacency List implementation for Generic Data.

**Comment by mohitsingh1011** [comment]
@Kumar-laxmi assign this to me.

**Comment by chhavisharma30** [comment]
I can implement BFS on graph by the help of queue. A visited boolean array will be marked as false for all the elements. Then proceeding from a node, it will be printed and it will be marked as true in visited array. After that, until the queue is empty, the front element of queue will be dequeued and if there is a node between any node and this node, then those node will be added to queue and the procedure will be repeated.
Kindly assign me this issue, I can implement this.
