### ISSUE TITLE
[SSoC'23] Linked List  Kth_nodedelete

### ISSUE THREAD

**Issue by mohitsingh1011** [Kumar-laxmi/Algorithms#1132]
Define a Node class to represent each node in the linked list.
Create a function called removeKthFromEnd that accepts the head of the linked list and the value of k as parameters.
Now you can create a linked list and call the removeKthFromEnd function to remove the kth node from the end.

**Comment by mohitsingh1011** [comment]
@Kumar-laxmi assign this to me.

**Comment by Kumar-laxmi** [comment]
Sorry this operation has been implemented
