### ISSUE TITLE
[SSoC'23] linear search string

### ISSUE THREAD

**Issue by mohitsingh1011** [Kumar-laxmi/Algorithms#1133]
Searching a character in a given string.

**Comment by mohitsingh1011** [comment]
@Kumar-laxmi assign this to me.

**Comment by SKSADIRUDDIN** [comment]
@Kumar-laxmi , pls assign me. I can implement through O(log n) T.C.

int binarySearch(const std::string& str, char target, int left, int right) {
    while (left <= right) {
        int mid = left + (right - left) / 2;

        if (str[mid] == target)
            return mid;
        else if (str[mid] < target)
            left = mid + 1;
        else
            right = mid - 1;
    }

    return -1; // Character not found
}

int searchCharacter(const std::string& str, char target) {
    int length = str.length();

    // Convert the string to a sorted array of characters
    std::string sortedStr = str;
    std::sort(sortedStr.begin(), sortedStr.end());

    return binarySearch(sortedStr, target, 0, length - 1);
}
