### ISSUE TITLE
Implementing B-Tree in Python and C++

### ISSUE THREAD

**Issue by dhruvmillu** [Kumar-laxmi/Algorithms#1135]
# Implementing B-Tree in JAVA, python, C and C++
The B-Tree can handle massive amounts of data with ease. When it comes to storing and searching large amounts of data, traditional binary search trees can become impractical due to their poor performance and high memory usage. B-Trees, also known as B-Tree or Balanced Tree, are a type of self-balancing tree that was specifically designed to overcome these limitations. 
![image](https://github.com/Kumar-laxmi/Algorithms/assets/75222710/596adbc6-b777-468e-a3d5-9b3ba9e405b3)

B-Trees are characterized by the large number of keys that they can store in a single node, which is why they are also known as “large key” trees. Each node in a B-Tree can contain multiple keys, which allows the tree to have a larger branching factor and thus a shallower height. This shallow height leads to less disk I/O, which results in faster search and insertion operations. B-Trees are particularly well suited for storage systems that have slow, bulky data access such as hard drives, flash memory, and CD-ROMs.

## **Describe the solution you'd like**
Implementing the following operation in B-Tree
- Search
- Insert
- Delete
 
In following languages
- C++
- Python

**Please Assign this issue to me under SSoC 2.0**

**Comment by Kumar-laxmi** [comment]
Assigned!
@dhruvmillu : Python and C++
