### ISSUE TITLE
[SSOC'23] reverse vowels in a string 

### ISSUE THREAD

**Issue by Nikita06211** [Kumar-laxmi/Algorithms#1137]
**Is your feature request related to a problem? Please describe.**
Given a string s, reverse only all the vowels in the string and return it.

example:
Input: s = "hello"
Output: "holle"

**Describe the solution you'd like**
The solution will be in c++.

please assign me this issue under ssoc'23.

**Comment by Rahul-Talari** [comment]
please assign this issue i have the code in c,c++,java,python

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir I can code it using c, c++ . Kindly assign me this task.

**Comment by Ashutosh-0506** [comment]
@Kumar-laxmi I would like to contribute to this issue. Please assign me this issue.

**Comment by tuhinsunny** [comment]
@Kumar-laxmi please assign me this Issue I would like to contribute

**Comment by Geeks-Arpan** [comment]
Please assign me
