### ISSUE TITLE
Finding Permutation and Combination (PnC)

### ISSUE THREAD

**Issue by SKSADIRUDDIN** [Kumar-laxmi/Algorithms#1139]
I would like to propose the implementation of permutation and combination functions in the SSOC 2.0 repository as part of my contribution to the project. These mathematical concepts are widely used in various domains, including statistics, computer science, and combinatorial optimization. By adding these functions to the repository, we can provide a valuable toolset for future contributors and users of the SSOC project.

Language: Python,C, C++
Preferred implementation approach: It is recommended to implement the permutation and combination functions as standalone functions within a dedicated module.
Unit tests: It is crucial to include comprehensive unit tests to ensure the correctness of the implemented functions.

I am excited to contribute to the SSOC 2.0 project by implementing these essential mathematical functions. I look forward to receiving feedback and guidance on the proposed approach and the best way to proceed with the implementation.

@Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Assigned!
@SKSADIRUDDIN : C, C++, Python and Java
