### ISSUE TITLE
Add Odd-Even Sort / Brick Sort

### ISSUE THREAD

**Issue by shanvijha30** [Kumar-laxmi/Algorithms#1141]
## Odd-Even Sort / Brick Sort : 

This algorithm is divided into two phases- Odd and Even Phase. The algorithm runs until the array elements are sorted and in each iteration two phases occurs- Odd and Even Phases.

## Feature :

Add  Odd-Even Sort / Brick Sort in  C++, C , Java , Python.

## Description of solution :

Will add  Odd-Even Sort / Brick Sort with adequate comments and proper documentation for readers to get a clear understanding.
To be added in C , C++, Java and Python.

## Alternatives Considered :
Could you please assign me this issue under SSoC'23.

**Comment by Kumar-laxmi** [comment]
Assigned!
@shanvijha30 : C, C++, Java & Python

**Comment by Kumar-laxmi** [comment]
@shanvijha30 What is your status on this issue?
