### ISSUE TITLE
Add Cyclic Sort in C

### ISSUE THREAD

**Issue by shanvijha30** [Kumar-laxmi/Algorithms#1142]
## Cyclic Sort in C :

This C Program implements cyclic sort. Cyclic sort is an in-place, unstable sorting algorithm, a comparison sort that is theoretically optimal in terms of the total number of writes to the original array, unlike any other in-place sorting algorithm. It is based on the idea that the permutation to be sorted can be factored into cycles, which can individually be rotated to give a sorted result.

## Feature :

Add Cyclic Sort in C as it present in Java, Python and C++.

## Description of solution :

Will add Cyclic Sort with adequate comments and proper documentation for readers to get a clear understanding.
To be added in C .

Could you please assign me this issue under SSoC'23.

**Comment by Kumar-laxmi** [comment]
Assigned!
@shanvijha30 : C

**Comment by Kumar-laxmi** [comment]
@shanvijha30 What is your status on this issue?

**Comment by Ashutosh-0506** [comment]
@Kumar-laxmi I would like to contribute to this issue. Please assign me this issue.
