### ISSUE TITLE
Counting Bits - Java

### ISSUE THREAD

**Issue by Ayush9951** [Kumar-laxmi/Algorithms#1145]
Hi @Kumar-laxmi, I am a contributor in SSOC'23, I want Implement this algorithm using Java in Maths repositiory.

Counting Bits -

Given an integer n, return an array ans of length n + 1 such that for each i (0 <= i <= n), ans[i] is the number of 1's in the binary representation of i.

Input: n = 2
Output: [0,1,1]

0 --> 0
1 --> 1
2 --> 10

please assign me this task under label ssoc'23

**Comment by Kumar-laxmi** [comment]
Please write a detailed issue description to explain your problem

**Comment by Ayush9951** [comment]
@Kumar-laxmi, I've added the problem description, please check

**Comment by Ayush9951** [comment]
@Kumar-laxmi, can I work on this algorithm?
