### ISSUE TITLE
B+ tree in C,Java,Python

### ISSUE THREAD

**Issue by SimranLahrani842** [Kumar-laxmi/Algorithms#1146]
B + tree is a variation of B-tree data structure. In a B + tree, data pointers are stored only at the leaf nodes of the tree. In a B+ tree structure of a leaf node differs from the structure of internal nodes. The leaf nodes have an entry for every value of the search field, along with a data pointer to the record (or to the block that contains this record). The leaf nodes of the B+ tree are linked together to provide ordered access on the search field to the records. Internal nodes of a B+ tree are used to guide the search.Some search field values from the leaf nodes are repeated in the internal nodes of the B+ tree.

**Comment by Kumar-laxmi** [comment]
Assigned!
@SimranLahrani842 : C, C++, Java & Python

**Comment by Tanyamodi** [comment]
I would like to work on this issue, kindly assign this to me.
