### ISSUE TITLE
ADD: Luhn Algorithm in C,C++,Python and Java

### ISSUE THREAD

**Issue by Ikshvaku24** [Kumar-laxmi/Algorithms#1149]
The **Luhn algorithm**, also known as the mod 10 algorithm, is a simple checksum formula used to validate various identification numbers, such as credit card numbers, IMEI numbers etc.  It is mostly used as a simple method to distinguish valid numbers from mistyped or otherwise incorrect numbers. The Time Complexity of the algorithm is O(n).
It works in steps:
1. Doubling every second digit from right.
2. If doubled digit is greater than add their digits.
3. Take sum of all digits.
4. If total modulo 10 is 0 then number is valid.

Please assign this issue under SSOC'23.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Ikshvaku24 : C, C++, Python & Java
