### ISSUE TITLE
Bellman Ford's Algorithm

### ISSUE THREAD

**Issue by Piyush-onGIT** [Kumar-laxmi/Algorithms#115]
**Is your feature request related to a problem? Please describe.**
This is a graph algorithm to check for the negative cycle.

**Describe the solution you'd like**
I would like to add this algorithm to this repo in C++ language.

Kindly assign me this task.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Piyush-onGIT : C++

**Comment by MaYaNkKashyap681** [comment]
Assign this to me, i can code this in C.

**Comment by Kumar-laxmi** [comment]
Assigned!
@MaYaNkKashyap681 : C
