### ISSUE TITLE
Add K-means Algorithm in C

### ISSUE THREAD

**Issue by namanshah22** [Kumar-laxmi/Algorithms#1152]
**Is your feature request related to a problem? Please describe.**
The current open source lacks an implementation of the K-means++ algorithm, which is a popular and effective initialization technique for the K-means clustering algorithm. The absence of this algorithm limits the project's ability to perform more efficient and accurate clustering on datasets.

**Describe the solution you'd like**
I would like to contribute to this open source project by adding the K-means++ algorithm. K-means++ improves the initial centroid selection in K-means clustering, resulting in better convergence and avoiding suboptimal solutions. By including this algorithm, the project will offer an enhanced and more robust clustering solution.

**Describe alternatives you've considered**
There are alternative initialization techniques for K-means clustering, such as random initialization and the Forgy method. However, K-means++ has been widely recognized as a superior approach due to its ability to select more representative initial centroids, resulting in improved clustering performance.

**Additional context**
I have experience with the K-means++ algorithm and believe it would be a valuable addition to the project. I am familiar with the implementation details and can ensure that the code adheres to the project's coding standards and guidelines. Adding K-means++ will enhance the project's functionality and provide users with a more powerful clustering tool.
@Kumar-laxmi, I would be happy to help you implement this algorithm in the repository if you would like.

**Comment by Kumar-laxmi** [comment]
Assigned!
@namanshah22 : C
