### ISSUE TITLE
Expanded Form Algorithm

### ISSUE THREAD

**Issue by swastik-akhil** [Kumar-laxmi/Algorithms#1153]
This algorithm takes number from the user and returns its expanded form as output. I guess this is one of the Algo which is going to add more beauty to the repo. This code can be implemented in Java, Python, C and C++. Kindly assign me this issue under SSOC'2. 
Admin - @Kumar-laxmi 
![Expanded Form](https://github.com/Kumar-laxmi/Algorithms/assets/126651810/bc531e82-c1ee-4950-9068-2e2fb3f10874)

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir please assign me this issue, I can code it under ssoc 2023 using c, c++, java

**Comment by Kumar-laxmi** [comment]
I think it is too basic to work on
