### ISSUE TITLE
Congruency Algorithm

### ISSUE THREAD

**Issue by swastik-akhil** [Kumar-laxmi/Algorithms#1154]
This algorithm aims to check whether the triangles are congruent or not.
This algorithm takes input of two triangles from user and returns congruency result with explanation.
Kindly allow me to add this in Algorithms repo and assign me this under SSOC'2
Admin - @Kumar-laxmi 
![congruent-triangles](https://github.com/Kumar-laxmi/Algorithms/assets/126651810/bb381ce5-4e4c-4495-ad07-b8503973760f)

**Comment by vivekpal24** [comment]
Sir Kindly assign this to me I can solve this with optimized solution

**Comment by swastik-akhil** [comment]
Congruency is a inseparable part of triangles and this make them more awesome @Kumar-laxmi .

**Comment by Kumar-laxmi** [comment]
Assigned!
@swastik-akhil : C, C++, Python and Java
