### ISSUE TITLE
Heron's Principle

### ISSUE THREAD

**Issue by swastik-akhil** [Kumar-laxmi/Algorithms#1155]
This algorithm finds out the area of triangle using famous Heron's formula. It a one of the most popular formulas which is missing in the repo. Kindly allow me to work on this issue under SSOC'2
![Heron's](https://github.com/Kumar-laxmi/Algorithms/assets/126651810/25d64cb3-46e8-4a02-a246-4c3dd4fcdc6e)

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir please assign me this issue, I want to work upon it using c, c++, Java under ssoc 2023

**Comment by Kumar-laxmi** [comment]
Assigned!
@swastik-akhil : C, C++, Python and Java

**Comment by harshitaaa8** [comment]
please assign this task to me as a beginner for SSOC'2 @Kumar-laxmi sir 
I can work upon it using c, c++, python.

**Comment by Kumar-laxmi** [comment]
@swastik-akhil What is your status on this issue?

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir please assign me this issue. This will be my first PR for ssoc 23

**Comment by swastik-akhil** [comment]
I'll make pr by 18 @Kumar-laxmi

**Comment by harshitaaa8** [comment]
@Kumar-laxmi sir please assign me this issue
I can work in all the languages.
