### ISSUE TITLE
Frievald's Algorithm

### ISSUE THREAD

**Issue by Mukesh751** [Kumar-laxmi/Algorithms#1156]
This algorithm is used to check whether a matrix C is the product of matrix A and matrix B, where matrix A,B,C are given as input.

@Kumar-laxmi

**Comment by swastik-akhil** [comment]
I can implement this code under all 4 languages i.e. Java, C, Python and C++. kindly assign me this issue under SSOC'2
Admin - @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
refer #775
