### ISSUE TITLE
Similar Triangles Algorithm

### ISSUE THREAD

**Issue by swastik-akhil** [Kumar-laxmi/Algorithms#1157]
This algorithm checks whether the two triangles input by the user are similar or not. I returns the answer and it's explanation too to the user. Kindly allow me to work on this issue under SSOC'2.
Admin - @Kumar-laxmi 
![Similar triangles](https://github.com/Kumar-laxmi/Algorithms/assets/126651810/fd2146aa-2ace-403c-82d2-257b560d8b28)

**Comment by swastik-akhil** [comment]
This is a nice issue on which we can work upon @Kumar-laxmi.

**Comment by Kumar-laxmi** [comment]
Assigned!
@swastik-akhil : C, C++, Python and Java
