### ISSUE TITLE
Perimeter

### ISSUE THREAD

**Issue by swastik-akhil** [Kumar-laxmi/Algorithms#1158]
This is a simple algorithm which simple aims to find out the perimeter of any polygon. Kindly assign me this issue under SSOC'2
Admin - @Kumar-laxmi

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  hello sir, sir kindly assign me this issue, I can code it using c, c++, Java... And please assign it to me so that at least I can make a start in open source.

**Comment by Kumar-laxmi** [comment]
I would recommend working on more standard algorithms
