### ISSUE TITLE
The Binomial Theorem

### ISSUE THREAD

**Issue by swastik-akhil** [Kumar-laxmi/Algorithms#1159]
Binomial Theorem is one of the most profunded discoveries of Mathematics. It's various application makes it so important that solving things without it looks like impossible to do. This theorem will make our Algorithms repo more bolder and would impart beauty to it. I request @Kumar-laxmi to kindly assign me the issue under SSOC'2.
![Binomial](https://github.com/Kumar-laxmi/Algorithms/assets/126651810/b2f0bf40-11d5-4299-9c73-7c0d40dcce89)
![The Binomial Theorem](https://github.com/Kumar-laxmi/Algorithms/assets/126651810/a1fb8d42-90db-40ca-ad1c-2478500e6317)

**Comment by Kumar-laxmi** [comment]
Assigned!
@swastik-akhil : C, C++, Python and Java

**Comment by Kumar-laxmi** [comment]
@swastik-akhil What is your status on this issue?

**Comment by swastik-akhil** [comment]
I'll make pr  before 18 @Kumar-laxmi

**Comment by swastik-akhil** [comment]
I've done this but I can't make a new PR before the existing PR gets merged.
Admin: @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
> I've done this but I can't make a new PR before the existing PR gets merged. Admin: @Kumar-laxmi

You can, create a PR from different branch
