### ISSUE TITLE
Kruskal's Algorithm

### ISSUE THREAD

**Issue by Piyush-onGIT** [Kumar-laxmi/Algorithms#116]
**Is your feature request related to a problem? Please describe.**
This is a graph algorithm that uses DSU to make a Minimum Spanning Tree.

**Describe the solution you'd like**
I would like to add this algorithm to this repo in C++ language.

Kindly assign me this task.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Piyush-onGIT : C++

**Comment by MaYaNkKashyap681** [comment]
I want to add the code for this algorithm in C, Please assign this to me.

**Comment by PK284** [comment]
Please Assign me on this for java language

**Comment by sumitkr2000** [comment]
is someone still working on this issue?
If not please assign me in c++ @Kumar-laxmi

**Comment by Piyush-onGIT** [comment]
> is someone still working on this issue? If not please assign me in c++ @Kumar-laxmi

Yes, I am working on it in C++.

**Comment by sumitkr2000** [comment]
okk @Piyush-onGIT

**Comment by Kumar-laxmi** [comment]
@sumitkr2000 Would you like to work on this issue in Python

**Comment by sumitkr2000** [comment]
@Kumar-laxmi i don't know python

**Comment by sitamgithub-MSIT** [comment]
> @sumitkr2000 Would you like to work on this issue in Python

You can assign me the same

**Comment by Kumar-laxmi** [comment]
This algorithm is available in ```C``` and ```Java```
