### ISSUE TITLE
Adding DES (Data Encryption Standard) using python & C++

### ISSUE THREAD

**Issue by mochiron-desu** [Kumar-laxmi/Algorithms#1164]
**Is your feature request related to a problem? Please describe.**
Yes it is.

**Describe the solution you'd like**
I would like to implement the DES in python & C++.

**Additional context**
The Data Encryption Standard (DES) is a symmetric encryption algorithm that operates on 64-bit blocks of data using a 56-bit encryption key. It employs a Feistel network structure, dividing the input data into two halves and applying a series of rounds using subkeys derived from the main key. Each round includes substitutions, permutations, and bitwise operations to ensure diffusion and confusion, making the data resistant to cryptographic attacks.

![image](https://github.com/Kumar-laxmi/Algorithms/assets/72451747/29f37690-18c7-48dc-9571-abb3aeeaf0d9)

**Comment by mochiron-desu** [comment]
@Kumar-laxmi Please assign me this !

**Comment by Kumar-laxmi** [comment]
Assigned!
@mochiron-desu : C++ & Python
