### ISSUE TITLE
Catalan Number using recusion and dp

### ISSUE THREAD

**Issue by kom-senapati** [Kumar-laxmi/Algorithms#1166]
**Is your feature request related to a problem? Please describe.**
Catalan number evaluation is missing in the algorithm.

**Describe the solution you'd like**
Catalan numbers are defined as mathematical sequence that consists of positive integers, which can be used to find the number of possibilities of various combinations. 
I can add solutions both using recursion and dynamic programming.

**Describe alternatives you've considered**
I can code in all four languages.

Assign this issue to me under SSOC 2023.

**Comment by Kumar-laxmi** [comment]
Assigned!
@KOMNOOB : C, C++, Java & Python

**Comment by educationalgamer** [comment]
can you assign to me
