### ISSUE TITLE
Want to add REVERSE ARRAY or REVERSE STRING in C++ 

### ISSUE THREAD

**Issue by Venerablevivek** [Kumar-laxmi/Algorithms#1171]
Given an array, the task is to reverse the array.
Examples →
Input  : arr[] = {34, 12, 23}
Output : arr[] = {23, 12, 34}
Input :  arr[] = {1, 2, 3, 4, 5, 6}
Output : arr[] = {6, 5, 4, 3, 2, 1}

We will be discussing a simple approach to reverse the array in-place. In place means, we will not be using some auxiliary space.
To reverse an array, we will use the concept of swapping. Swapping is a term used for interchanging the values at two different locations with each other.
OPTIMIZED SOLUTION
**Time Complexity: O(n)
Space Complexity: O(1)**

**Comment by Venerablevivek** [comment]
Please Assign this issue to me @Kumar-laxmi ... I want to contribute this

**Comment by avinashvermaaa** [comment]
Please Assign this issue to me @Kumar-laxmi . I want to contribute this in ( Python, C++, C, Java)

**Comment by anurag-327** [comment]
@Kumar-laxmi Sir Kindly assign this issue to me I would like to contribute to it and come up with most optimized solution.

**Comment by vivekpal24** [comment]
Can you Assign this to me i can solve this problem in the c  cpp and python

**Comment by chhavisharma30** [comment]
I can do this by applying two pointers approach where two pointers will be pointing to start and end element of the array respectively and then swapping will be done of starting and ending element.
Then the start pointer will be incremented and end pointer will be decremented. This procedure will be followed until start is smaller than end pointer.
Kindly assign me this issue I can implement this.
