### ISSUE TITLE
Palindrome Number

### ISSUE THREAD

**Issue by avinashvermaaa** [Kumar-laxmi/Algorithms#1172]
Palindrome Number :-  ( A number that remains the same when its digits are reversed, that is it has reflectional symmetry across a vertical axis.)

Ex : -  
original number   :- 123
reversed number :- 321 
as original number is not same as the reversed number, it is not a Palindrome number.

original number   :- 121
reversed number :- 121 
as original number is same as the reversed number, it is a Palindrome number.

I can code this in ( Python, Java, C++, C )
Please assign me this issue under SSOC'23.   @Kumar-laxmi

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir kindly assign this issue to me, I can code it and give an optimized solution

**Comment by anurag-327** [comment]
@Kumar-laxmi Sir kindly assign this issue to me, I will get back to you with the most optimized solution.

**Comment by vivekpal24** [comment]
Sir kindly assigned this to me i can solve this using c and cpp and Python

**Comment by kirtilulle** [comment]
I can write this code in more than one language please assign this to me

**Comment by mayank2mahi** [comment]
@Kumar-laxmi Sir ji please assign me this issue as I eagerly want to contribute to this issue under SSoC'23.

**Comment by chhavisharma30** [comment]
I can code this in all languages. Kindly assign me this issue.
