### ISSUE TITLE
SSOC'23 Fibonacci Sequence upto N [Optimized]

### ISSUE THREAD

**Issue by avinashvermaaa** [Kumar-laxmi/Algorithms#1177]
Fibonacci Sequence ( The Series starts from 0,1 and every next number is the sum of previous two number for example 0,1,1. and the series goes on.... 0,1,1,2,3,5,8,13,21,34,......)

The code will take a number as input from user say 'N' and will print Upto 'N' Fibonacci sequence numbers.

Example  :-
Input = 10
Output : - 0,1,1,2,3,5,8,13,21,34 

I can code this in ( Python, Java, C++, C )

Please assign me this issue under SSOC'23. @Kumar-laxmi

Screenshot : -
![Screenshot (939)](https://github.com/Kumar-laxmi/Algorithms/assets/105039208/d33f9fc6-60d2-460a-bca0-4007ce385f86)

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir kindly assign this issue to me, I can code it using recursion as well as using loops  and will provide an optimize solution. Please assign it to me sir

**Comment by chhavisharma30** [comment]
This can be done using dynamic programming to optimize it. Kindly assign me this issue. I can implement this.
