### ISSUE TITLE
SSoC'23 - Diffie Hellman Algorithm

### ISSUE THREAD

**Issue by Atharvashirsh** [Kumar-laxmi/Algorithms#1180]
**Is your feature request related to a problem? Please describe.**
Diffie Hellman Algorithm is missing in C , C++ and Java 

**Describe the solution you'd like**
Diffie-Hellman is a key exchange algorithm where two parties can establish a shared secret key over an insecure channel. They agree on a prime number and a base, privately choose random numbers, compute public keys, and then combine them with their own secret numbers to calculate the shared key. 

**Describe alternatives you've considered**
I can code this algorithm in all these 3 languages.

Can you please assign this issue to me under SSoC'23 label?

**Comment by Kumar-laxmi** [comment]
refer #687
