### ISSUE TITLE
SSOC'23 Random OTP generator in C,C++,Python, Java

### ISSUE THREAD

**Issue by avinashvermaaa** [Kumar-laxmi/Algorithms#1181]
Random OTP Generator :- ( A random number of user defined length .)

Input format :- user will give a random length of number. 
For example 
input :- Enter length of OTP = 5
output :- Your Random OTP is = 41648

input :- Enter length of OTP = 8
output :- Your Random OTP is = 59874562

This code will generate a random number of given length which can be used as OTP.

I can code this in ( C,C++,Python,Java )
Please assign me this issue under SSOC'23. @Kumar-laxmi
![Screenshot (941)](https://github.com/Kumar-laxmi/Algorithms/assets/105039208/b986e2cd-fc5c-493c-9a68-1fb5cc270c46)

**Comment by vivekpal24** [comment]
sir kindly assign this to me.
