### ISSUE TITLE
SSOC'23 Random Password generator in C,C++,Python, Java

### ISSUE THREAD

**Issue by avinashvermaaa** [Kumar-laxmi/Algorithms#1182]
Random Password Generator :- ( A random password will be generated of user defined length and can be used as initial password for any newly created account.

Input format :- user will give a random length of number.
For example :-
Input :-       length of  password  = 5
Output :-    Your Random Password is = gx@5W

Input :-       length of  password  = 11
Output :-    Your Random Password is = Avin@$h@69*
 
     

Note for Reviewer : - This code will generate a random Passwordof given length which can be used as Initial Password for a newly created account.

I can code this in ( C,C++,Python,Java )

Please assign me this issue under SSOC'23. @Kumar-laxmi

Screenshot : -
![Screenshot (942)](https://github.com/Kumar-laxmi/Algorithms/assets/105039208/266af811-a30b-4ded-ba72-ba8bc80eb844)

**Comment by kirtilulle** [comment]
I can write the Random password generator code in c,cpp,Java and python. Assign this to me
