### ISSUE TITLE
SSOC'23 Absent String in Python, Java, C, C++

### ISSUE THREAD

**Issue by tarunvyshnav777** [Kumar-laxmi/Algorithms#1186]
**Problem:**
You are given N binary strings of length N each.
You need to find a binary string of length N which is different from all of the given strings.
Your task is output any valid binary string following above rules.

**Sample Input 1:**
3
101
110
100
**Sample Output 1:**
111

**Sample Input 2:**
4
1100
1010
0100
0010
**Sample Output 2:**
1101

This helps in understanding binary strings and constructive algorithms.
And I think we need few more algorithms in stings.
I can code in all four languages.
Assign this issue to me under SSOC 2023.

**Comment by vivekpal24** [comment]
please assign me this i can solve this issue .
