### ISSUE TITLE
[SSOC'23] Rotate Array

### ISSUE THREAD

**Issue by Nikita06211** [Kumar-laxmi/Algorithms#1187]
**Describe the solution you'd like**
The algorithm will rotate the given array to right by a given position (say k) in the array. 
The solution will be in c++

**Additional context**
example:
Input:  nums = [-1,-100,3,99], k = 2
Output: [3,99,-1,-100]

Explanation: 
rotate 1 steps to the right: [99,-1,-100,3]
rotate 2 steps to the right: [3,99,-1,-100]

kindly assign me this issue under ssoc'23

**Comment by vivekpal24** [comment]
Sir i can solve this problem in c,cpp,python .kindly assign me

**Comment by imrish4** [comment]
hey, I want to contribute to this issue, Please assign me this issue .

**Comment by himughanakash** [comment]
@Kumar-laxmi please assign this issue to me under ssoc'23 program so that i will start working on it.

**Comment by Geeks-Arpan** [comment]
Please assign me
