### ISSUE TITLE
SSOC'23 Triangular Number

### ISSUE THREAD

**Issue by tarunvyshnav777** [Kumar-laxmi/Algorithms#1189]
**Is your feature request related to a problem? Please describe.**
Triangular Number evaluation is missing in the algorithm.

**Describe the solution you'd like**
A number is termed as triangular number if we can represent it in the form of triangular grid of points such that the points form an **equilateral triangle** and each row contains as many points as the row number, i.e., the first row has one point, second row has two points, third row has three points and so on. The starting triangular numbers are 1, 3 (1+2), 6 (1+2+3), 10 (1+2+3+4).

![triangular-numbers](https://github.com/Kumar-laxmi/Algorithms/assets/105963438/cddc1efe-4874-4a88-8bed-133322a44c86)

**I can add both brute force and optimal solutions.**

I can code in all four languages.
@Kumar-laxmi Assign this issue to me under SSOC 2023.

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir kindly assign me this issue under ssoc 2023 , I can code it and give an optimized solution
