### ISSUE TITLE
Adding M-Coloring Algorithm in C,C++ and Java

### ISSUE THREAD

**Issue by dhruti26** [Kumar-laxmi/Algorithms#1192]
**Description**
This algorithm is used to determine if the undirected graph can be colored with at most m colors such that no two adjacent vertices of the graph are colored with the same color.

![image](https://github.com/Kumar-laxmi/Algorithms/assets/106862356/44e9aba4-027f-433b-81a0-67aa5b5004d0)

**Describe the solution you'd like**
I would like to implement the algorithm in C, C++ and Java

 It is one of the most popular algorithm which is missing in the repo. Kindly allow me to work on this issue under SSOC'23

**Comment by Kumar-laxmi** [comment]
Assigned!
@dhruti26 : C, C++, Python and Java
