### ISSUE TITLE
[SSoC'23] Hopcroft–Karp algorithm

### ISSUE THREAD

**Issue by mohitsingh1011** [Kumar-laxmi/Algorithms#1194]
Initialize Maximal Matching M as empty.
While there exists an Augmenting Path p
Remove matching edges of p from M and add not-matching edges of p to M
(This increases size of M by 1 as p starts and ends with a free vertex)
Return M.

**Comment by mohitsingh1011** [comment]
@Kumar-laxmi assign this to me under SSoC'23

**Comment by Kumar-laxmi** [comment]
refer #794
