### ISSUE TITLE
Hungarian Algorithm in c, c++ , java , python

### ISSUE THREAD

**Issue by rahulrana701** [Kumar-laxmi/Algorithms#1198]
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to a problem. I would like to implement Hungarian algorithm using C, C++, Python and Java languages.

The Hungarian algorithm, also known as the Kuhn-Munkres algorithm, is an optimization algorithm used to solve the assignment problem in combinatorial optimization. The Hungarian algorithm provides an efficient solution to this problem by utilizing the concept of bipartite graphs and the technique of augmenting paths.

**Describe the solution you'd like**
I would like a solution that provides an implementation of the Hungarian algorithm using C, C++, Python and Java languages.

I would like to work on this issue under SSOC 2023. Please assign it to me.

**Comment by Kumar-laxmi** [comment]
Under what category does this algo. lie in?

**Comment by rahulrana701** [comment]
> Under what category does this algo. lie in?

Number Theory

**Comment by rahulrana701** [comment]
@Kumar-laxmi Checkout this issue as well https://github.com/Kumar-laxmi/Algorithms/issues/1089#issue-1745113780

**Comment by rahulrana701** [comment]
@Kumar-laxmi Can you assign me the issue..

**Comment by rahulrana701** [comment]
I want to work on this.
