### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by vijay-kumar-yadav** [Kumar-laxmi/Algorithms#120]
**QuickSort** is a **Divide and Conquer algorithm**.
It picks an element as pivot and partitions the given array around the picked pivot(in case of lomuto partition). 
There are many different versions of quickSort that pick pivot in different ways:-
1. Lometo Partition
2. Hoare Partition 
                                                                                                                                      - definition GFG

**Comment by vijay-kumar-yadav** [comment]
@Kumar-laxmi  assign this issue in c++ to me.

**Comment by Kumar-laxmi** [comment]
Assigned!
@vijay-kumar-yadav : C++

**Comment by Abhishek9229** [comment]
please assign it to me in Java @Kumar-laxmi

**Comment by trushee** [comment]
Please assign it to me (Java & python) @Kumar-laxmi 
Thanks a lot

**Comment by Abhilash1781** [comment]
Please assign it to me in **C**

**Comment by Kumar-laxmi** [comment]
Assigned!
@Abhilash1781 : C
@Abhishek9229 : Java
@trushee : Python

**Comment by Kumar-laxmi** [comment]
@Abhishek9229 What is your status on this issue??

**Comment by shubhamjaiswar43** [comment]
Assign This Me in C++

**Comment by Kumar-laxmi** [comment]
> Assign This Me in C++

@shubhamjaiswar43 This issue is only available in ```Java```

**Comment by shubhamjaiswar43** [comment]
Then Assign This me in java

**Comment by shubhamjaiswar43** [comment]
> > Assign This Me in C++
> 
> @shubhamjaiswar43 This issue is only available in `Java`

Then Assign This me in java

**Comment by Kumar-laxmi** [comment]
Assigned!
@shubhamjaiswar43 : Java

**Comment by Saumya40-codes** [comment]
> Assigned! @shubhamjaiswar43 : Java

Hey if its still open, can you assign me this issue? 
Thanks.
