### ISSUE TITLE
regex to DFA in Python, JAVA, C and C++

### ISSUE THREAD

**Issue by dhruvmillu** [Kumar-laxmi/Algorithms#1201]
**Is your feature request related to a problem? Please describe.**
This program will take in a regular expression with applicable operations i.e `+` , `.` , `()`  and `*` in Python, JAVA, C and C++, and print out the transition table of DFA

**Describe the solution you'd like**
A converter that converts REGEX to DFA and test strings
### sample input:
```
enter input symbols: 0 1
enter regex: 0(0+1)*
enter test string: 0110110101
```
### output:
|present state|  Next state for Input 0 | Next state for Input 1|
|---|---|---|
| &#8594; q0 | q1 | q2 |
|*q1|q1|q1|
```
True
```
---
**please assign this to me under SSoC 2.0**

**Comment by Kumar-laxmi** [comment]
Assigned!
@dhruvmillu : C, C++, Python and Java
