### ISSUE TITLE
SSOC'23 To find Diameter of a Binary Tree in C,C++,Java

### ISSUE THREAD

**Issue by SivaHarshith1303** [Kumar-laxmi/Algorithms#1202]
@Kumar-laxmi 
Please assign me this problem I will explain this problem with proper comments. You can trust me on this.
Approach : Recursion 
Time Complexity : O(N)
Space Complexity : O(N) [Auxiliary Stack Space is Used]

**Comment by kirtilulle** [comment]
I can write a c++, Java code for finding the diameter of a binary tree. Assign this to me .

**Comment by anasadh** [comment]
Assign me this issue. I will code in c,c++ and java.
It would be helpful if there's a step-by-step guide or sample code that I can follow to ensure the correct implementation.

**Comment by shivangi2002** [comment]
@Kumar-laxmi  please assign me this issue.
