### ISSUE TITLE
subset sum problem using backtracking in c,c++

### ISSUE THREAD

**Issue by MohitMourya01** [Kumar-laxmi/Algorithms#1205]
**Is your feature request related to a problem? Please describe.**
This algorithm will determine the subset sum whose value is k selected from a set of elements using backtracking rather than exhaustive search

**Describe the solution you'd like**
I will be using backtracking to solve this problem in C,C++.

**Additional context**
It is one of the basic problem that is solved using backtracking

**Comment by himughanakash** [comment]
@Kumar-laxmi please assign me this issue
