### ISSUE TITLE
Add:Skip List In C++ , C , Python and Java

### ISSUE THREAD

**Issue by shravanii2308** [Kumar-laxmi/Algorithms#1209]
**Is your feature request related to a problem? Please describe.**
The Skip List provides an average time complexity of O(log n) for search, insertion, and deletion operations, similar to balanced search trees, but with a simpler implementation. It offers good performance characteristics, efficient space utilization, and easy scalability.

**Describe the solution you'd like**
Code with comments in  C++ , C , Python and Java

**Additional context**
Please assign me this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@shravanii2308 : C, C++, Java & Python

**Comment by Kumar-laxmi** [comment]
@shravanii2308 What is your status on this issue?

**Comment by shravanii2308** [comment]
> @shravanii2308 What is your status on this issue?

i am working on it
