### ISSUE TITLE
Counting Sort

### ISSUE THREAD

**Issue by vijay-kumar-yadav** [Kumar-laxmi/Algorithms#121]
[Counting sort](http://en.wikipedia.org/wiki/Counting_sort) is a sorting technique based on keys between a specific range. It works by counting the number of objects having distinct key values (kind of hashing). Then doing some arithmetic to calculate the position of each object in the output sequence.

**Comment by vijay-kumar-yadav** [comment]
@Kumar-laxmi  assign this in C++ to me.

**Comment by Kumar-laxmi** [comment]
Assigned!
@vijay-kumar-yadav : C++

**Comment by Abhishek9229** [comment]
Please assign it to me in Java @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Assigned!
@Abhishek9229 : Java

**Comment by stiwari-ds** [comment]
@Kumar-laxmi Please assign it to me for Python.

**Comment by Abhilash1781** [comment]
@Kumar-laxmi Please assign this to me in C .

**Comment by Kumar-laxmi** [comment]
@Abhishek9229 What is your status on this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@stiwari-ds : Python
@Abhilash1781 : C

**Comment by Kumar-laxmi** [comment]
@Abhishek9229 What is your status on this issue?

**Comment by Abhishek9229** [comment]
yes it is in progress i need just a couple of days

**Comment by Kumar-laxmi** [comment]
> yes it is in progress i need just a couple of days

What is the status now?

**Comment by Kumar-laxmi** [comment]
Unassigning @Abhishek9229 due to inactivity

**Comment by Kumar-laxmi** [comment]
Assigned!
@Harshit-Raj-14 : Java
