### ISSUE TITLE
Burrows-Wheeler Transform (BWT) Algorithm

### ISSUE THREAD

**Issue by vaishnavi-3969** [Kumar-laxmi/Algorithms#1211]
**Is your feature request related to a problem? Please describe.**
I would like to request an implementation of the Burrows-Wheeler Transform (BWT) algorithm. The BWT algorithm is commonly used for data compression and text transformation by rearranging characters in a string to improve compression ratios.

**Describe the solution you'd like**
I would like an implementation of the BWT algorithm in [programming language], preferably in [Java and Python]. The implementation will include two functions:

transform(text: String) -> String: This function should take a string as input and return the transformed string using the Burrows-Wheeler Transform. The function should generate all rotations of the input string, sort them lexicographically, and construct the Burrows-Wheeler Transform by extracting the last character of each rotation.
inverseTransform(bwt: String) -> String: This function should take the transformed string (BWT) as input and perform the inverse transform to retrieve the original text. It should count the occurrences of each character, compute the starting positions of each character, and use the next array to reconstruct the original text.

**Describe alternatives you've considered**
I have searched for existing implementations or libraries that provide the BWT algorithm in Java. Although I found some resources, they either lacked the necessary functionalities or did not meet my requirements. Therefore, I am requesting a new implementation specifically tailored to my use case.

**Additional context**
Example:

Input String: banana

Step 1: Generate Rotations
------------------------------
banana
ananab
nanaba
anaban
naban
banan
a

Step 2: Sort Rotations
------------------------------
a
anaban
ananab
banana
banan
nanaba
naban

Step 3: Construct BWT
------------------------------
BWT: anbnbaaa

Application of BWT algorithm:
1. Data compression
2. Text transformation
3. DNA sequencing
4. Data storage and retrieval
5. Cryptography

**Comment by Kumar-laxmi** [comment]
Sorry this algorithm has been implemented in all four languages
