### ISSUE TITLE
Implementation of Skip List Data Structure

### ISSUE THREAD

**Issue by vaishnavi-3969** [Kumar-laxmi/Algorithms#1213]
**Is your feature request related to a problem? Please describe.**
The Skip List is a data structure that provides an efficient way to search, insert, and delete elements in a sorted list. It uses multiple layers of linked lists with skip pointers to improve search times.

**Describe the solution you'd like**
 The implementation would include the following functionalities:

contains(value: T) -> boolean: This function should check whether a given value exists in the Skip List and return true or false accordingly.

insert(value: T): This function should insert a new element with the given value into the Skip List while maintaining the sorted order.

delete(value: T) -> boolean: This function should remove the element with the given value from the Skip List if it exists and return true. If the element does not exist, it should return false.

printList(): This function should print the elements in the Skip List in ascending order.

**Additional context**
Level 3:          3 --------------------> 15 ------------> 25 --------------------> 50 ----------------------> 70
Level 2:          3 ----------> 15 --------------------> 25 ---------------------------------------------> 70
Level 1:          3 --------------------> 15 ---------------------------------------------> 50
Level 0:          3 ---------------------------------------------> 50

horizontal line represents levels
number represents element in skip list

**Comment by Kumar-laxmi** [comment]
refer #1209
