### ISSUE TITLE
Detect loop in a linked list

### ISSUE THREAD

**Issue by Vyshnavi21504** [Kumar-laxmi/Algorithms#122]
Hello, I am Vyshnavi a contributer from SWOC 3.0 . I request you to assign this issue to me

**Comment by goyalh4164** [comment]
I can make a valuable contribution I'm c++ language with neat and clean comments and smooth outputs.

**Comment by MaYaNkKashyap681** [comment]
Assign this to me, please.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Vyshnavi21504 : Java
@goyalh4164 : C++
@MaYaNkKashyap681 : C

**Comment by Vyshnavi21504** [comment]
@Kumar-laxmi 
I was first to ask and i want to contribute in c++

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi I was first to ask and i want to contribute in c++

Done

**Comment by sumitkr2000** [comment]
Hey, @Kumar-laxmi is this issue available in C++? If not, please assign me this issue in C++.

**Comment by Shalini469717** [comment]
Can you assign this issue to me in python?

**Comment by Abhinavcode13** [comment]
Assign this issue to me in all languages c ,python and java @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Assigned!
@Abhinavcode13 : C, Python, Java

**Comment by Abhinavcode13** [comment]
please check I have resolved issue in c , now working on java and python.
