### ISSUE TITLE
4-Queen problems can be added in Backtracking in JAVA

### ISSUE THREAD

**Issue by aviralj02** [Kumar-laxmi/Algorithms#1220]
The N Queen is the problem of placing N chess queens on an N×N chessboard so that no two queens attack each other. The algorithm used is Backtracking.

✅ My code follows the code style of this project.
✅ This PR does not contain plagiarized content.

I can contribute for JAVA program for the 4 Queens problem.

**Comment by Kumar-laxmi** [comment]
refer #760
