### ISSUE TITLE
Fractional Knapsack Problem under Greedy Algorithm in JAVA 

### ISSUE THREAD

**Issue by aviralj02** [Kumar-laxmi/Algorithms#1223]
The Fractional Knapsack problem is a classic optimization problem often solved using a greedy algorithm. It involves selecting items from a set, each with a given weight and value, to maximize the total value while respecting a weight constraint.
Unlike the 0/1 knapsack problem, items can be divided (fractional) to maximize the value. This means that a fraction of an item can be included in the knapsack, rather than just selecting or excluding the entire item.

✅ My code follows the code style of this project.
✅ This PR does not contain plagiarized content.

I would like to contribute by providing JAVA program for this algorithm.

**Comment by Kumar-laxmi** [comment]
Assigned!
@aviralj02 : Java
