### ISSUE TITLE
Comb Sort in C++

### ISSUE THREAD

**Issue by anand-harsh** [Kumar-laxmi/Algorithms#1225]
**Is your feature request related to a problem? Please describe.**
Comb Sort is mainly an improvement over Bubble Sort. Bubble sort always compares adjacent values. So all are removed one by one. Comb Sort improves on Bubble Sort by using a gap of the size of more than 1. The gap starts with a large value and shrinks by a factor of 1.3 in every iteration until it reaches the value 1. Thus Comb Sort removes more than one with one swap and performs better than Bubble Sort.

**Describe the solution you'd like**
A sorting algorithm better than bubble sort

**Describe alternatives you've considered**
I will implement this algorithm in C++

Sample input

`
Enter the length of array
5
`
`
Enter the elements of array
8
9
3
2
5
`

Sample Output:

`
Original array: 
8 9 3 2 5 
`
`
Sorted array:
2 3 5 8 9
`

please assign this to me under SSoC 2.0

**Comment by anand-harsh** [comment]
@Kumar-laxmi please assign me this issue

**Comment by Kumar-laxmi** [comment]
refer #731
