### ISSUE TITLE
Brian Kerningham's Algorithm

### ISSUE THREAD

**Issue by MisterMickey** [Kumar-laxmi/Algorithms#1230]
**Is your feature request related to a problem? Please describe.**

Brian Kerningham's Algorithm is used to count set bits in a number

**Describe the solution you'd like**

I'll make a function implementing this algorithm which will take a number as input and return a count of set bits.

Please assign me this issue under SSOC

**Comment by Kumar-laxmi** [comment]
Assigned!
@MisterMickey : C, C++, Python and Java
