### ISSUE TITLE
Want to add "Particle Swarm Optimization" in Python and C++ in Optimization folder 

### ISSUE THREAD

**Issue by rayarka26** [Kumar-laxmi/Algorithms#1235]
**Is your feature request related to a problem? Please describe.**
This algorithm is not present in the File and works in allocation and transportation problems mainly.

**Describe the solution you'd like**

PSO stands for Particle Swarm Optimization. It is a population-based stochastic optimization algorithm that is inspired by the social behavior of bird flocking or fish schooling. PSO was originally proposed by Eberhart and Kennedy in 1995.

In PSO, a population of particles is used to explore the search space of an optimization problem. Each particle represents a potential solution and moves through the search space to find an optimal or near-optimal solution. The particles adjust their positions and velocities based on their own best-known position (local best) and the global best-known position among all particles.

**Additional context**
I will add the Python and C++ codes

**Comment by Kumar-laxmi** [comment]
Assigned!
@rayarka26 : C++ & Python
