### ISSUE TITLE
Bisection method

### ISSUE THREAD

**Issue by Anirudh3167** [Kumar-laxmi/Algorithms#1236]
**Is your feature request related to a problem? Please describe.**
This is a new feature request which comes under the category of finding roots of a given equation in a specific interval

**Describe the solution you'd like**
The bisection method is a numerical algorithm used to find the root of a function within a specified interval. It is a simple and robust method that repeatedly bisects the interval and narrows it down until the root is found or the desired level of accuracy is achieved.

**Describe alternatives you've considered**
none

**Additional context**
This is the primitive method for finding the roots of an equation

Kindly assign this issue to me

**Comment by Kumar-laxmi** [comment]
Assigned!
@Anirudh3167 : C, C++, Python and Java

**Comment by Anirudh3167** [comment]
#1280 has the Python code of it.

Kindly accept the PR

**Comment by Anirudh3167** [comment]
So sorry for the delay due to my exams I was not able to take out time for contributions. 
Kindly view the PR of it.
