### ISSUE TITLE
Secant method

### ISSUE THREAD

**Issue by Anirudh3167** [Kumar-laxmi/Algorithms#1237]
**Is your feature request related to a problem? Please describe.**
This is an algorithm used for finding the roots of a given equation in a specific interval

**Describe the solution you'd like**
The secant method is a numerical algorithm used to find the root of a function. It is similar to the bisection method but instead of using an interval, it uses a sequence of approximations to the root. The secant method is an iterative process that approximates the root by drawing secant lines between two points on the function curve.

**Describe alternatives you've considered**
None

**Additional context**
This algorithm will find the roots of the equation

Kindly assign this issue to me

**Comment by Kumar-laxmi** [comment]
Assigned!
@Anirudh3167 : C, C++, Python and Java

**Comment by Tanyamodi** [comment]
I would like to work on this issue, kindly assign this to me.
