### ISSUE TITLE
Newton Raphson Method

### ISSUE THREAD

**Issue by Anirudh3167** [Kumar-laxmi/Algorithms#1238]
**Is your feature request related to a problem? Please describe.**
This is a root finding technique for a given equation without the need of specifying the intervals

**Describe the solution you'd like**
The Newton-Raphson method, also known as Newton's method, is a numerical algorithm used to find the root of a function. It is an iterative process that uses the derivative of the function to approximate the root more efficiently than the bisection method or the secant method

**Describe alternatives you've considered**
None

**Additional context**
This method is considered as one of the fastest methods than the Bi section and Secant method as the number of iterations taken will be reduced as quadratic (i.e. Quadratic Convergence)

Kindly assign this issue to me

**Comment by Kumar-laxmi** [comment]
Assigned!
@Anirudh3167 : C, C++, Python and Java

**Comment by VSatwika** [comment]
@Kumar-laxmi Could this issue be assigned to me as it's been over a week.

**Comment by Anirudh3167** [comment]
I have already done the code.

Most of the time was consumed by the function customisation. 

I will submit the PR by tomorrow

**Comment by Tanyamodi** [comment]
I would like to work on this issue, kindly assign this to me.
