### ISSUE TITLE
Zombie__Game in cpp.

### ISSUE THREAD

**Issue by vimarsh11** [Kumar-laxmi/Algorithms#1240]
**Is your feature request related to a problem? Please describe.**
A C++ zombie game where you fight to survive in a post-apocalyptic world, battling hordes of undead while searching for supplies.

**Describe the solution you'd like**

![Screenshot 2023-06-11 190654](https://github.com/Kumar-laxmi/Algorithms/assets/104987339/e5957814-5623-4c17-8378-c0a17c3cc894)
![Screenshot 2023-06-11 190750](https://github.com/Kumar-laxmi/Algorithms/assets/104987339/fa88085b-827d-4afb-a790-8139388bee7d)

**Comment by Kumar-laxmi** [comment]
Please don't raise issue to solve leetcode, gfg or hackerrank questions
