### ISSUE TITLE
Add Bead Sort in Python, C, C++, and Java

### ISSUE THREAD

**Issue by namanshah22** [Kumar-laxmi/Algorithms#1241]
**Is your feature request related to a problem? Please describe.**
Currently, the Bead Sort algorithm is not available in Python, C, C++, and Java. This algorithm is a simple and efficient sorting algorithm that can be useful in certain scenarios. It would be beneficial to have an implementation of Bead Sort in these languages.

**Describe the solution you'd like**
I would like to contribute the implementation of Bead Sort in Python, C, C++, and Java. This would involve writing the necessary code to perform Bead Sort on an array of integers, ensuring that the sorting is done correctly and efficiently. The implementation should be well-documented and adhere to best coding practices.

**Describe alternatives you've considered**
One alternative could be using other sorting algorithms like Bubble Sort or Quick Sort. However, Bead Sort has its unique characteristics and can be advantageous in certain situations, especially when dealing with integers within a specific range.

**Additional context**
Including the Bead Sort algorithm in these programming languages would provide developers with more options when it comes to choosing the right sorting algorithm for their specific use cases. It would also contribute to the overall availability and diversity of sorting algorithms in these languages, allowing developers to explore and compare different approaches to sorting.

**Comment by namanshah22** [comment]
@Kumar-laxmi, I would be happy to help you implement this algorithm in the repository if you would like.

**Comment by namanshah22** [comment]
@Kumar-laxmi please assign me this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@namanshah22 : C, C++, Python and Java
