### ISSUE TITLE
adding trapping rainwater array problem in java

### ISSUE THREAD

**Issue by yashhibare7** [Kumar-laxmi/Algorithms#1247]
**Is your feature request related to a problem? Please describe.**
the feature request is related to the problem of solving the "Trapping Rainwater" array problem in Java.

**Describe the solution you'd like**
I would like a Java solution for the trapping rainwater array problem, where given an array of non-negative integers representing heights, the function calculates the total amount of trapped rainwater.

**Comment by Kumar-laxmi** [comment]
Please don't raise issue to solve leetcode, gfg or hackerrank questions
