### ISSUE TITLE
sink the ship

### ISSUE THREAD

**Issue by vivekpal24** [Kumar-laxmi/Algorithms#1248]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
In this game we create the array which is filled with 0or 1 and for the user it is showing in the star format if the user correct  the guess than its chances will not be deducted but if not than the chances are deducted

**Comment by Kumar-laxmi** [comment]
Please don't raise issue to solve leetcode, gfg or hackerrank questions
