### ISSUE TITLE
[SSoC'23] Buy and Sell Stocks Problem in Java

### ISSUE THREAD

**Issue by Hansika002** [Kumar-laxmi/Algorithms#1249]
**Is your feature request related to a problem? Please describe.**
The feature request is related to finding an efficient algorithm or code implementation to solve the problem of buying and selling stocks in Java.

**Describe the solution you'd like**
The "Buy and Sell Stocks" problem can be efficiently solved using a professional approach in Java. To maximize the profit, we iterate through the array of stock prices, keeping track of the minimum price encountered so far. By subtracting the minimum price from each subsequent price, we calculate the potential profit. We update the maximum profit if the current profit exceeds the previous maximum. Finally, we return the maximum profit achieved from this transaction. If no profit is attainable, we return 0. This solution showcases a time complexity of O(n), where n represents the size of the input array.

**Describe alternatives you've considered**
The alternative is to use dynamic programming, where we track the minimum price and maximum profit at each day, resulting in a more optimized solution

I would like to work on this issue under SSOC 2023 . Please assign it to me.

**Comment by Kumar-laxmi** [comment]
Please don't raise issue to solve leetcode, gfg or hackerrank questions
