### ISSUE TITLE
Adding of Peterson's Algorithm under Concurrent Algorithms section 

### ISSUE THREAD

**Issue by kamalyash2002** [Kumar-laxmi/Algorithms#1253]
Is your feature request related to a problem? Please describe.
Yes, my feature request is related to a problem. I would like to implement Peterson's Algorithm under Concurrent Algorithms section  using C, C++, Python and Java languages.

Peterson's algorithm (or Peterson's solution) is a concurrent programming algorithm for mutual exclusion that allows two or more processes to share a single-use resource without conflict, using only shared memory for communication. It was formulated by Gary L. Peterson in 1981.

Describe the solution you'd like
I would like to present solution that provides an implementation of the Peterson's Algorithm using C, C++, Python and Java languages.

I would like to work on this issue under SSOC 2023. Please assign it to me. @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Assigned!
@kamalyash2002 : C, C++, Python and Java
