### ISSUE TITLE
N-Queens Algorithm (Backtracking) in C++ and Python

### ISSUE THREAD

**Issue by shruti8302** [Kumar-laxmi/Algorithms#1254]
## Is your feature request related to a problem? Please describe.
Yes, I would like to work on this algorithm.

## Describe the solution you'd like
I will add appropriate comments in the code and also properly explain the algorithm

@Kumar-laxmi  As a part of SSOC'23, I would like to work on this algorithm. Kindly assign me this issue.

**Comment by Kumar-laxmi** [comment]
refer #760

**Comment by kirtilulle** [comment]
I would like to work on this algorithm. I have worked on this algorithm . Assign this to me
