### ISSUE TITLE
Convert a Number to Hexadecimal - Java

### ISSUE THREAD

**Issue by Ayush9951** [Kumar-laxmi/Algorithms#1257]
Hi @Kumar-laxmi, I am contributor in SSOC'23.
I want to add this alogorithm in maths repository.

In this problem we will be given an integer value, let's suppose 'n'
Now task is to convert It into Its Hexadecimal form without using any inbuilt functions

for example - Lets say n is 26, so In Hexacimal form It will be 1a
so In the result we will return 1a

If n is a negative number we will use 2's complement method. 

solution - I will use bit manupulation to Implement this alogorithm using Java

please assign me this task under label SSOC'23

**Comment by himughanakash** [comment]
@Kumar-laxmi please assign this issue to me to work on under ssoc'23 program, i will provide the best optimized code.
