### ISSUE TITLE
[SSoC'23] Cube Sort

### ISSUE THREAD

**Issue by mohitsingh1011** [Kumar-laxmi/Algorithms#1258]
// C++ program for the above approach
#include <bits/stdc++.h>
using namespace std;

// Comparator function which returns
// a^3 is less than b^3
bool cmp(int a, int b)
{
	int x = pow(a, 3);
	int y = pow(b, 3);
	return x < y;
}

// Function to sort the cubes of array
bool sortArr(int arr[], int n)
{
	// Sort the array
	sort(arr, arr + n, cmp);

	// Print the array
	for (int i = 0; i < n; i++) {
		cout << arr[i] << " ";
	}
}

// Driver Code
int main()
{
	// Given array
	int arr[] = { 4, -1, 0, -5, 6 };
	int n = sizeof(arr) / sizeof(arr[0]);

	// Function Call
	sortArr(arr, n);
	return 0;
}

**Comment by mohitsingh1011** [comment]
@Kumar-laxmi assign this to me under SSoC'23.

**Comment by Kumar-laxmi** [comment]
Kindly give proper issue description according to the template provided
