### ISSUE TITLE
Stacks and Queue Data Structure 

### ISSUE THREAD

**Issue by VishalS-HK** [Kumar-laxmi/Algorithms#126]
The complete algorithm for Stack and Queue implementation in C

**Comment by goyalh4164** [comment]
I can contribute complete Menu Driven Program in C++ Language....Circular also...with neat and clean and well-defined comments. Please assign it to me

**Comment by samvid2020** [comment]
I can try to explain Stacks and queues in Java precisely can you assign me this? @Kumar-laxmi

**Comment by Rakshit-26** [comment]
I am willing to contribute complete menu driven programs of stacks (using array, Linked List) and queues (linear, circular, priority) in C programming language. Please assign this to me. (SWOC 2023)

**Comment by Kumar-laxmi** [comment]
**@contributors** please follow a template of raising an issue
