### ISSUE TITLE
[SSoC'23] The Ubiquitous Binary Search

### ISSUE THREAD

**Issue by mohitsingh1011** [Kumar-laxmi/Algorithms#1261]
Set low=1,high=array_size
Repeat step 3-4 while  high-low>1
  set mid=low+(high-low)/2
  If array[mid]<=search_item
    low=mid
  else
    high=mid
  if aray[low]=search_item
    Index=low
  else
    Index=right

**Comment by mohitsingh1011** [comment]
@Kumar-laxmi assign this to me under SSoC'23.

**Comment by Kumar-laxmi** [comment]
Kindly raise an issue with proper issue description
