### ISSUE TITLE
[SSoC'23] Maximum Product Subarray 

### ISSUE THREAD

**Issue by mohitsingh1011** [Kumar-laxmi/Algorithms#1262]
Given an integer array, find the subarray that has the maximum product of its elements. The solution should return the maximum product of elements among all possible subarrays.
Input:  { -6, 4, -5, 8, -10, 0, 8 }
Output: 1600
Explanation: The maximum product subarray is {4, -5, 8, -10} having product 1600
 
 
Input:  { 40, 0, -20, -10 }
Output: 200
Explanation: The maximum product subarray is {-20, -10} having product 200

**Comment by mohitsingh1011** [comment]
@Kumar-laxmi assign this to me under SSoC'23.

**Comment by TusharGagal** [comment]
@Kumar-laxmi  please assign me this issue so that i can start contribute in ssoc'23.
