### ISSUE TITLE
[SSoC'23] Bipartite Graph

### ISSUE THREAD

**Issue by mohitsingh1011** [Kumar-laxmi/Algorithms#1263]
Following is a simple algorithm to find out whether a given graph is Bipartite or not using Breadth First Search (BFS). 
1. Assign RED color to the source vertex (putting into set U). 
2. Color all the neighbors with BLUE color (putting into set V). 
3. Color all neighbor’s neighbor with RED color (putting into set U). 
4. This way, assign color to all vertices such that it satisfies all the constraints of m way coloring problem where m = 2. 
5. While assigning colors, if we find a neighbor which is colored with same color as current vertex, then the graph cannot be colored with 2 vertices (or graph is not Bipartite)

**Comment by mohitsingh1011** [comment]
@Kumar-laxmi assign this to me under SSoC'23.

**Comment by TusharGagal** [comment]
@Kumar-laxmi  please assign me this task.
