### ISSUE TITLE
[SSoC'23] Floyd’s Cycle Detection Algorithm

### ISSUE THREAD

**Issue by mohitsingh1011** [Kumar-laxmi/Algorithms#1265]
Floyd’s cycle detection algorithm is a pointer algorithm that uses only two pointers, which move through the sequence at different speeds. The idea is to move the fast pointer twice as quickly as the slow pointer, and the distance between them increases by one at each step. If we both meet at some point, we have found a cycle in the list; otherwise, no cycle is present if the end of the list is reached. It is also called the “tortoise and the hare algorithm”.

**Comment by mohitsingh1011** [comment]
@Kumar-laxmi assign this to me under SSoC'23.

**Comment by Kumar-laxmi** [comment]
refer #761
