### ISSUE TITLE
[SSoC'23] Union–Find Algorithm

### ISSUE THREAD

**Issue by mohitsingh1011** [Kumar-laxmi/Algorithms#1266]
function MakeSet(x)
    x.parent = x
 
function Find(x)
    if x.parent == x
        return x
    else
        return Find(x.parent)
 
function Union(x, y)
    xRoot = Find(x)
    yRoot = Find(y)
    xRoot.parent = yRoot

**Comment by Souravroy99** [comment]
Please assign me to this issue I want to contribute to this repo.
