### ISSUE TITLE
[SSoC'23] Quickselect Algorithm

### ISSUE THREAD

**Issue by mohitsingh1011** [Kumar-laxmi/Algorithms#1267]
Like Quicksort, the quickselect has good average performance but is sensitive to the chosen pivot. With good pivots, meaning ones that consistently decrease the search set by a given fraction, the search set decreases exponentially. By induction (or summing the geometric series), one sees that performance is linear, as each step is linear. The overall time is constant (depending on how quickly the search set reduces). However, if bad pivots are consistently chosen, such as decreasing by only a single element each time, then worst-case performance is quadratic: O(n2). For example, this occurs in searching for the maximum element of a set, using the first element as the pivot, and having sorted data.

Input: [7, 4, 6, 3, 9, 1]
k = 2
 
Output: k’th smallest array element is 3
 
 
Input: [7, 4, 6, 3, 9, 1]
k = 1
 
Output: k’th smallest array element is 1

**Comment by Kumar-laxmi** [comment]
refer #979
