### ISSUE TITLE
Pollard’s Rho Algorithm for Prime Factorization

### ISSUE THREAD

**Issue by Aarsh30** [Kumar-laxmi/Algorithms#1269]
Pollard’s Rho is a prime factorization algorithm, particularly fast for a large composite number with small prime factors. The Rho algorithm’s most remarkable success was the factorization of eighth Fermat number: 1238926361552897 * 93461639715357977769163558199606896584051237541638188580280321. 
The Rho algorithm was a good choice because the first prime factor is much smaller than the other one.

I will be solving this algorithm

@Kumar-laxmi can you please assign me this issue for SSOC 2.0 so that I can send a PR request?

**Comment by Kumar-laxmi** [comment]
Assigned!
@Aarsh30 : C, C++, Python and Java
