### ISSUE TITLE
FCFS disk scheduling algorithm in Java ,python,c,c++

### ISSUE THREAD

**Issue by SimranLahrani842** [Kumar-laxmi/Algorithms#1270]
Given an array of disk track numbers and initial head position, we need to find the total number of seek operations done to access all the requested tracks if First Come First Serve (FCFS) disk scheduling algorithm is used.

First Come First Serve (FCFS) 
FCFS is the simplest [disk scheduling algorithm]. As the name suggests, this algorithm entertains requests in the order they arrive in the disk queue. The algorithm looks very fair and there is no starvation (all requests are serviced sequentially) but generally, it does not provide the fastest service.

**Comment by SimranLahrani842** [comment]
> Given an array of disk track numbers and initial head position, we need to find the total number of seek operations done to access all the requested tracks if First Come First Serve (FCFS) disk scheduling algorithm is used.
> 
> First Come First Serve (FCFS) FCFS is the simplest [disk scheduling algorithm]. As the name suggests, this algorithm entertains requests in the order they arrive in the disk queue. The algorithm looks very fair and there is no starvation (all requests are serviced sequentially) but generally, it does not provide the fastest service.

Assign me this @Kumar-laxmi

**Comment by mayank2mahi** [comment]
@Kumar-laxmi Sir ji please assign me this issue as I eagerly want to contribute to this issue under SSoC'23.
