### ISSUE TITLE
BALANCED BINARY TREE program in Java,python,c,c++

### ISSUE THREAD

**Issue by SimranLahrani842** [Kumar-laxmi/Algorithms#1271]
A balanced binary tree, also referred to as a height-balanced binary tree, is defined as a binary tree in which the height of the left and right subtree of any node differ by not more than 1.
1.difference between the left and the right subtree for any node is not more than one
2.the left subtree is balanced
3.the right subtree is balanced

**Comment by SimranLahrani842** [comment]
> A balanced binary tree, also referred to as a height-balanced binary tree, is defined as a binary tree in which the height of the left and right subtree of any node differ by not more than 1. 1.difference between the left and the right subtree for any node is not more than one 2.the left subtree is balanced 3.the right subtree is balanced

/assign @Kumar-laxmi

**Comment by chhavisharma30** [comment]
I can solve this issue. Kindly allot me this issue.
