### ISSUE TITLE
Dial’s Algorithm in C, C++, PYTHON, JAVA

### ISSUE THREAD

**Issue by anand-harsh** [Kumar-laxmi/Algorithms#1276]
**Is your feature request related to a problem? Please describe.**
Dial’s algorithm is an optimized version of Dijkstra’s algorithm for finding the shortest paths in a graph with non-negative edge weights. It is particularly useful when the range of the edge weights is small, meaning that the weights only take on a small number of distinct values.

**Describe the solution you'd like**
The time complexity of the above implementation is O(V*W). Here V is the number of vertices in the graph and W is the maximum weight of the edge.

Sample Input
    g.addEdge(0, 1, 4);
    g.addEdge(0, 7, 8);
    g.addEdge(1, 2, 8);
    g.addEdge(1, 7, 11);
    g.addEdge(2, 3, 7);
    g.addEdge(2, 8, 2);
    g.addEdge(2, 5, 4);
    g.addEdge(3, 4, 9);
    g.addEdge(3, 5, 14);
    g.addEdge(4, 5, 10);
    g.addEdge(5, 6, 2);
    g.addEdge(6, 7, 1);
    g.addEdge(6, 8, 6);
    g.addEdge(7, 8, 7);

Sample Output

Vertex Distance from Source
0     0
1     4
2     12
3     19
4     21
5     11
6     9
7     8
8     14

Please assign this to me under SSOC'23

**Comment by anand-harsh** [comment]
@Kumar-laxmi please assign me this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@anand-harsh : C, C++, Python and Java
