### ISSUE TITLE
Least Recently Used (LRU) | Caching in C, C++, PYTHON, JAVA

### ISSUE THREAD

**Issue by anand-harsh** [Kumar-laxmi/Algorithms#1277]
**Is your feature request related to a problem? Please describe.**
In Least Recently Used (LRU) algorithm is a Greedy algorithm where the page to be replaced is least recently used. The idea is based on locality of reference, the least recently used page is not likely 

**Describe the solution you'd like**
Average time complexity of set and map operations is O(1) and the worst-case time complexity is O(n) but O(n) is the dominant term.

Sample Input:

`
Enter number of pages: 13
`
`
Enter the pages: 7 0 1 2 0 3 0 4 2 3 0 3 2
`
`
Enter the capacity: 4
`

Sample Output:

`
6
`

Kindly assign me this issue under SSOC'23

**Comment by anand-harsh** [comment]
@Kumar-laxmi please assign me this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@anand-harsh : C, C++, Python and Java
