### ISSUE TITLE
First In First Out (FIFO) | Caching in C, C++, PYTHON, JAVA

### ISSUE THREAD

**Issue by anand-harsh** [Kumar-laxmi/Algorithms#1278]
**Is your feature request related to a problem? Please describe.**
In this algorithm, operating system keeps track of all pages in the memory in a queue, oldest page is in the front of the queue. When a page needs to be replaced page in the front of the queue is selected for removal. 

**Describe the solution you'd like**
Time Complexity is O(n), where n is the number of pages.

Sample Input:

`
Enter number of pages: 13
`
`
Enter the pages: 7 0 1 2 0 3 0 4 2 3 0 3 2
`

Sample Output:
`
7
`

Kindly assign me this issue under SSOC'23

**Comment by anand-harsh** [comment]
@Kumar-laxmi please assign me this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@anand-harsh : C, C++, Python and Java
