### ISSUE TITLE
Bloom-filter algorithm in C++ and Python

### ISSUE THREAD

**Issue by shruti8302** [Kumar-laxmi/Algorithms#1283]
## **Is your feature request related to a problem? Please describe.**
Yes, I would like to work on this algorithm.

## **Describe the solution you'd like**
I will add appropriate comments in the code and also properly explain the algorithm

@Kumar-laxmi As a part of SSOC'23, kindly assign me with this issue, I will do my best.

**Comment by Kumar-laxmi** [comment]
refer #997
