### ISSUE TITLE
SEMAPHORE Algorithm  in OS 

### ISSUE THREAD

**Issue by SimranLahrani842** [Kumar-laxmi/Algorithms#1285]
Semaphores are just normal variables used to coordinate the activities of multiple processes in a computer system. They are used to enforce mutual exclusion, avoid race conditions and implement synchronization between processes.
Semaphores are used to implement critical sections, which are regions of code that must be executed by only one process at a time. By using semaphores, processes can coordinate access to shared resources, such as shared memory or I/O devices.

**Comment by SimranLahrani842** [comment]
> Semaphores are just normal variables used to coordinate the activities of multiple processes in a computer system. They are used to enforce mutual exclusion, avoid race conditions and implement synchronization between processes. Semaphores are used to implement critical sections, which are regions of code that must be executed by only one process at a time. By using semaphores, processes can coordinate access to shared resources, such as shared memory or I/O devices.

Please assign me sir @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Assigned!
@SimranLahrani842 : C, C++, Python and Java

**Comment by Kumar-laxmi** [comment]
@SimranLahrani842 What is your status on this issue?

**Comment by SimranLahrani842** [comment]
> @SimranLahrani842 What is your status on this issue?

Done with the PR sir please review.
