### ISSUE TITLE
Construct Binary Tree from a)Preorder and Inorder Traversal, b) Inorder and Postorder Traversal , c)Preorder and Postorder Traversal

### ISSUE THREAD

**Issue by RashmiK35** [Kumar-laxmi/Algorithms#1295]
Given integer arrays of preorder, postorder and inorder construct and return the binary tree.

**Comment by Ashutosh-0506** [comment]
@Kumar-laxmi I would like to contribute to this issue. Please assign me this issue.

**Comment by Kumar-laxmi** [comment]
Such issue is already open
