### ISSUE TITLE
Prefix Sum of Matrix Algorithm in C++ and Python

### ISSUE THREAD

**Issue by shruti8302** [Kumar-laxmi/Algorithms#1296]
## **Is** your feature request related to a problem? Please describe.
Yes, I would like to work on this algorithm.

## **Describe** the solution you'd like
I will add appropriate comments in the code and also properly explain the algorithm

@Kumar-laxmi As a part of SSOC'23, Kindly assign me this issue to work on.

**Comment by professorabhay** [comment]
Hey @shruti8302, Assign it to me
