### ISSUE TITLE
Egyptian Fraction - A Greedy Algorithm

### ISSUE THREAD

**Issue by dhrupad17** [Kumar-laxmi/Algorithms#1297]
**Is your feature request related to a problem? Please describe.**
I want to work on Egyptian Fraction which is a greedy algorithm

**Describe the solution you'd like**
Here in this algorithm every positive fraction can be represented as sum of unique unit fractions. That representation is called Egyptian Fraction.

For example

```Input```

5/12

```Output```

1/3 + 1/12

**Describe alternatives you've considered**
For a given number of the form n/d we can find the greatest possible unit fraction and then can perform recursion for the remaining part. In this approach ,we can reduce the time-complexity to O(d) (in worst case) where d is the denominator. 

**Additional context**

Code Snippet in Java with Output

![Screenshot (488)](https://github.com/Kumar-laxmi/Algorithms/assets/91726340/649622a0-fb88-45be-8678-60dfbb78fe0c)

![Screenshot (489)](https://github.com/Kumar-laxmi/Algorithms/assets/91726340/6d1de7ce-cc75-4b4e-b3e2-d9e98332f41f)

 @Kumar-laxmi Kindly assign me this issue under SSOC'23

**Comment by Kumar-laxmi** [comment]
refer #1222
