### ISSUE TITLE
Add Pancake sort in c,c++,java and python

### ISSUE THREAD

**Issue by namanshah22** [Kumar-laxmi/Algorithms#1299]
**Is your feature request related to a problem? Please describe.**
Yes, there is a problem with the existing set of sorting algorithms in the open-source project. While they cover a wide range of sorting scenarios, there is a missing implementation for the Pancake Sort algorithm. Pancake Sort is known for its ability to efficiently sort almost sorted or partially ordered datasets by repeatedly flipping the pancakes in a specific manner. The absence of this algorithm limits the options available for users who specifically require Pancake Sort for their sorting needs.

**Describe the solution you'd like**
I would like to contribute the Pancake Sort algorithm to the open-source project as an additional sorting method. By adding Pancake Sort, we can enhance the collection of sorting algorithms and provide users with a reliable and efficient solution for handling almost sorted or partially ordered datasets. This will expand the project's capabilities and ensure that users have access to a wider range of sorting techniques.

**Describe alternatives you've considered**
As part of this contribution, I have considered alternative algorithms such as Bubble Sort and Insertion Sort. However, Pancake Sort stands out as a specialized approach specifically designed to handle almost sorted datasets efficiently. By incorporating Pancake Sort into the open-source project, we can offer users a distinct sorting algorithm that addresses their unique sorting requirements.

**Additional context**
The open-source project aims to provide a comprehensive collection of algorithms for various computational tasks. By including the Pancake Sort algorithm, we can broaden the project's scope and empower users with a well-rounded set of sorting options. This contribution will benefit users who deal with partially ordered datasets and require an algorithm capable of handling such scenarios effectively.
@Kumar-laxmi, I would be happy to help you implement this algorithm in the repository if you would like.

**Comment by Kumar-laxmi** [comment]
Assigned!
@namanshah22 : C, C++, Python and Java

**Comment by Kumar-laxmi** [comment]
@namanshah22 Please open a single PR with all programs, close all other three PRs
