### ISSUE TITLE
Stooge Sort- Java,C++,Python

### ISSUE THREAD

**Issue by dhrupad17** [Kumar-laxmi/Algorithms#1305]
**Is your feature request related to a problem? Please describe.**
It is a recursive algorithm where the array is divided into two overlapping parts (2/3) each.After that it performs sorting in first 2/3 part and then it performs sorting in last 2/3 part. And then, sorting is done on first 2/3 part to ensure that the array is sorted.

**Describe the solution you'd like**
The key idea for the solution is to sort the overlapping parts twice which causes exchange of the elements between the other sections accordingly. It is slower than even bubble sort but it finds a unique way of sorting.

```Input```

2 4 5 3 1

```Output```

1 2 3 4 5

**Additional context**
Here is a code snippet in Java with Input and Output

![Screenshot (490)](https://github.com/Kumar-laxmi/Algorithms/assets/91726340/7dd7bab7-6971-4184-abef-06b9c015c64d)

@Kumar-laxmi Kindly assign this issue to me

**Comment by Kumar-laxmi** [comment]
Since it is an easy algorithm, kindly implement this algorithm in all four languages

Assigned!
@dhrupad17 : C, C++, Python and Java
