### ISSUE TITLE
Add Dutch National Flag Problem Sorting Algorithm in C, C++, Python, Java

### ISSUE THREAD

**Issue by Aryan-d13** [Kumar-laxmi/Algorithms#1308]
Is your feature request related to a problem? Please describe.

Yes, the feature request is related to addressing the problem of sorting an array with three distinct values efficiently. The Dutch National Flag Problem involves arranging the elements in such a way that all elements of the same value are grouped together. This problem arises in various scenarios, and having an open-source implementation of the Dutch National Flag Sorting Algorithm would provide a practical solution for developers who encounter such situations.

Describe the solution you'd like.

I propose the development of an open-source project specifically dedicated to the Dutch National Flag Problem. The project should include a well-documented implementation of the Dutch National Flag Sorting Algorithm in a popular programming language. The implementation should efficiently sort the array, grouping all elements of the same value together. Clear usage instructions and examples should be provided to facilitate easy integration into different projects. Thoroughly testing the algorithm's correctness and efficiency is crucial to ensure reliable performance.

Describe alternatives you've considered.

Before creating a new open-source project, it is important to explore existing alternatives. It is possible that there are already open-source implementations of the Dutch National Flag Sorting Algorithm available. If suitable implementations are found, it may be more efficient to contribute to those projects rather than starting a new one. Evaluating the quality, popularity, and compatibility of existing implementations is necessary to make an informed decision.

Additional context.

The Dutch National Flag Problem, named after the flag of the Netherlands, is a classic computer science problem with diverse applications. It involves sorting an array with three distinct values efficiently. The algorithm's ability to group elements of the same value together has relevance in various scenarios, such as partitioning data or solving related sorting problems. By providing an open-source implementation, we aim to foster collaboration, encourage community support, and offer a readily available solution for developers facing similar challenges.
@Kumar-laxmi, I would be happy to help you implement this algorithm in the repository if you would like. Please assign it to me under SSOC 23 TAG

**Comment by Kumar-laxmi** [comment]
refer #804
