### ISSUE TITLE
Add Fast Fourier Transform (FFT) Algorithm for Signal Processing in C, C++, Java and Python

### ISSUE THREAD

**Issue by Aryan-d13** [Kumar-laxmi/Algorithms#1313]
Title: Add Fast Fourier Transform (FFT) Algorithm for Signal Processing

Description:
The Fast Fourier Transform (FFT) algorithm is a fundamental technique used for efficient signal processing, data analysis, and spectral analysis. Currently, our open-source project lacks an implementation of the FFT algorithm, limiting its capabilities in handling advanced signal processing tasks and spectral analysis.

Problem:
Signal processing tasks, such as filtering, convolution, and frequency analysis, often require the application of the FFT algorithm to efficiently analyze and manipulate signals in the frequency domain. Without the FFT algorithm, our project lacks a crucial component for performing advanced signal processing operations.

Solution Requested:
We propose adding the FFT algorithm to our project. This algorithm transforms a discrete time-domain signal into its equivalent representation in the frequency domain, enabling various spectral analysis and signal processing tasks. The implementation should support different variants of the FFT algorithm, such as Cooley-Tukey or Radix-2, and provide configurable options for handling different signal lengths and data types. Additionally, it should be well-documented, modular, and optimized for performance.

Alternatives Considered:
We have explored alternative algorithms for performing signal processing tasks, such as the Discrete Cosine Transform (DCT) and the Discrete Wavelet Transform (DWT). However, the FFT algorithm stands out as the most widely used and efficient technique for spectral analysis and signal processing in a vast range of applications.

Additional Context:
The FFT algorithm plays a critical role in various fields, including audio and video processing, telecommunications, image processing, and scientific data analysis. By incorporating the FFT algorithm into our project, we can provide developers with a powerful tool for performing advanced signal processing tasks and spectral analysis. The algorithm's efficiency, accuracy, and broad applicability make it an essential addition to our open-source project, empowering users to tackle complex signal processing challenges effectively.

@Kumar-laxmi Please assign me this Issue Under SSOC'23 so I can start working on it ASAP

**Comment by Kumar-laxmi** [comment]
Assigned!
@Aryan-d13 : C, C++, Python and Java
