### ISSUE TITLE
Addition of two Linked-List in C, Java & Python

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1317]
**Is your feature request related to a problem? Please describe.**
Given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.The two numbers do not contain any leading zero, except the number 0 itself.

**Describe the solution you'd like**
Language to implement: C, Java & Python

**Additional context**
Image to understand the logic of implementation:
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/ef54f6db-82dd-42cf-abd3-01772dd5e7ea)

**Comment by harshitaaa8** [comment]
i can work on this in c and python.

**Comment by neerajrpatil** [comment]
this will by my first PR, i would like to solve this.

**Comment by mohitsingh1011** [comment]
@Kumar-laxmi assign this to me will do it in all 4 languages.

**Comment by laxupaddhyay** [comment]
@Kumar-laxmi assign this to me , I love slove such problems.

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir kindly assign this issue to me. I can code this under ssoc 23.Till now it's like I have requested for 30+ issues beforehand but everytime my comment gets ignored due to which till now I haven't even contributed once being a beginner in open source, may be this one will also get ignored  . Please sir consider my request and assign me this issue

**Comment by mrigankabrahma** [comment]
@Kumar-laxmi assign me this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@neerajrpatil : C, Java & Python

**Comment by nazeer-18** [comment]
@Kumar-laxmi as this algo is not yet assigned for cpp I would be happy if i can contribute the algo in c++
can you, please assign this issue to me?

**Comment by harshitaaa8** [comment]
Sir please assign me this issue
I can work in all the languages

**Comment by VISHALGUPTA100803** [comment]
@Kumar-laxmi  Please assign me this issue it will be my first pr i can do it in C++

**Comment by Kumar-laxmi** [comment]
@neerajrpatil What is your status on this issue?

**Comment by neerajrpatil** [comment]
@Kumar-laxmi Do you want it to be menu driven?
