### ISSUE TITLE
Josephus Problem Algorithm

### ISSUE THREAD

**Issue by Devchawla2608** [Kumar-laxmi/Algorithms#1318]
The Josephus Problem is a mathematical problem that involves a group of people standing in a circle, where every nth person is eliminated until only one person remains. The problem is to determine the position of the last remaining person.

Here's an algorithm to solve the Josephus Problem:

Start with a list or an array representing the circle of people, where each person is assigned a unique identifier or position.

Choose a starting position, typically denoted as "k" or "s". This is the position of the first person to be eliminated.

Determine the value of "n", representing the step size or count. This is the number of positions to skip before eliminating the next person.

Repeat the following steps until only one person remains:
a. Start at the current position "k".
b. Count "n" positions in a clockwise direction, skipping any eliminated positions.
c. Eliminate the person at the current position.
d. Update the current position "k" to the next available position after the elimination.

The person remaining after all eliminations is the solution to the Josephus Problem.

**Comment by Devchawla2608** [comment]
@Kumar-laxmi Kindly assign this issue to me

**Comment by Kumar-laxmi** [comment]
Assigned!
@Devchawla2608 : C, C++, Python and Java
