### ISSUE TITLE
Bingo Sort in C, C++, Python, JAVA

### ISSUE THREAD

**Issue by anand-harsh** [Kumar-laxmi/Algorithms#1326]
**Is your feature request related to a problem? Please describe.**
This Sorting Technique is similar to the Selection sort in which we first find the smallest element called Bingo Element, and then we repeatedly iterate the elements of the array to get the correct positions of all the elements. 
In this sorting technique, each distinct element is considered a Bingo value.  And Bingo Values are called out in increasing order. During each pass, if the array element is equal to Bingo element then it is shifted to its correct position.

**Describe the solution you'd like**
Time Complexity is O(M * N) where M is number of distinct elements and N is size of the array

Sample Input

`
Enter the length of array
7
`
`
Enter the elements of array
-4
3
2
-23
90
56
3
`

Sample Output
`
Original array:
-4 3 2 -23 90 56 3
`
`
Sorted array:
-23 -4 2 3 3 56 90
`

Assign me this under SSOC'23

**Comment by anand-harsh** [comment]
@Kumar-laxmi please assign me this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@anand-harsh : C, C++, Python and Java

**Comment by Kumar-laxmi** [comment]
@anand-harsh what is your status on this issue?

**Comment by anand-harsh** [comment]
> @anand-harsh what is your status on this issue?

I will make its PR till tonight
