### ISSUE TITLE
Kadane's Algorithm in C

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1328]
**Is your feature request related to a problem? Please describe.**
Kadane's algorithm revolves around two variables: "max_ending_here," which keeps track of the maximum sum of a subarray that ends at the current index, and "max_so_far," which stores the highest sum encountered thus far in any contiguous subarray. Whenever a positive-sum value is encountered in "max_ending_here," it is compared to "max_so_far," and if it is greater, "max_so_far" is updated accordingly.

**Describe the solution you'd like**
Here's a simple explanation of the approach:
- We start by assuming that the maximum sum found so far is the first element of the array.
- We iterate through the array, considering each element one by one.
- For each element, we update the maximum sum of a subarray ending at that index (max_ending_here) by either adding the current element to the previous sum or starting a new subarray from the current element.
- We also keep track of the maximum sum encountered so far (max_so_far) by comparing the current max_ending_here with the previous max_so_far and updating it if necessary.
- By the end of the iteration, the final max_so_far value will represent the maximum sum of a contiguous subarray within the given array.
- We return the max_so_far value as the result.

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/87676321-c55a-48e3-9b32-0308f0a296e1)

**Comment by SimranLahrani842** [comment]
> **Is your feature request related to a problem? Please describe.** Kadane's algorithm revolves around two variables: "max_ending_here," which keeps track of the maximum sum of a subarray that ends at the current index, and "max_so_far," which stores the highest sum encountered thus far in any contiguous subarray. Whenever a positive-sum value is encountered in "max_ending_here," it is compared to "max_so_far," and if it is greater, "max_so_far" is updated accordingly.
> 
> **Describe the solution you'd like** Here's a simple explanation of the approach:
> 
> * We start by assuming that the maximum sum found so far is the first element of the array.
> * We iterate through the array, considering each element one by one.
> * For each element, we update the maximum sum of a subarray ending at that index (max_ending_here) by either adding the current element to the previous sum or starting a new subarray from the current element.
> * We also keep track of the maximum sum encountered so far (max_so_far) by comparing the current max_ending_here with the previous max_so_far and updating it if necessary.
> * By the end of the iteration, the final max_so_far value will represent the maximum sum of a contiguous subarray within the given array.
> * We return the max_so_far value as the result.
> 
> **Additional context** ![image](https://user-images.githubusercontent.com/76027425/246306149-87676321-c55a-48e3-9b32-0308f0a296e1.png)

Assign me this issue please sir @Kumar-laxmi 
I ll add screenshot of op along with the program ..

**Comment by Kumar-laxmi** [comment]
This issue is for contributors who haven't contributed even once

**Comment by mitali-dxt** [comment]
@Kumar-laxmi I haven't contributed yet and this will be a good first issue for me. Please assign me this issue.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Siddharth015 : C, C++, Python and Java

Kindly complete the implementation withing 1 week or else the issue would be re-assigned

**Comment by SimranLahrani842** [comment]
> This issue is for contributors who haven't contributed even once

Yes I haven't made any single contribution which is merged please assign me on fcfs basis

**Comment by Kumar-laxmi** [comment]
@Siddharth015 What is your status on this issue?

**Comment by Siddharth015** [comment]
I am working on the issue sir. Its almost done
@Kumar-laxmi

**Comment by shanvijha30** [comment]
@Kumar-laxmi I would like to work on this issue. Could you please assign it to me.
Thank you!

**Comment by Kumar-laxmi** [comment]
Assigned!
@shanvijha30 : C

**Comment by Tanyamodi** [comment]
I would like to work on this issue, kindly assign this to me.

**Comment by shivangi2002** [comment]
@Kumar-laxmi .I can work on this issue in cpp.Please assign it to me.
