### ISSUE TITLE
Bogo Sort in C, C++, Java & Python

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1332]
**Is your feature request related to a problem? Please describe.**
BogoSort, also referred to as permutation sort, stupid sort, slow sort, shotgun sort, or monkey sort, is an extremely inefficient algorithm that is hard to believe. It follows a "generate and test" approach, where it repeatedly generates random permutations of the input until it happens to find one that is sorted.

**Describe the solution you'd like**
```
Bogo sort uses 2 steps to sort elements of the array.
1. It throws the number randomly.
2. Check whether the number is sorted or not.
3. If sorted then return the sorted array.
4. Otherwise it again generate another randomization of the numbers until the array is sorted.
```

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/2752a5eb-5279-4e8a-bc00-b6c93ac7e171)

**Comment by PrathamAsrani** [comment]
Dear @Kumar-laxmi 
I would to contribute to this issue, please assign this to me.

**Comment by rohitd2103** [comment]
@Kumar-laxmi Please assign me this issue.

**Comment by Kumar-laxmi** [comment]
Assigned!
@PrathamAsrani : C, C++, Java & Python

**Comment by PrathamAsrani** [comment]
This will be completed in a week thanks for assigning.

**Comment by Kumar-laxmi** [comment]
@PrathamAsrani What is your status on this issue?

**Comment by PrathamAsrani** [comment]
@Kumar-laxmi 
In C/C++ it's completed, from tomorrow I will starting to implement in java.
