### ISSUE TITLE
Fibonacci Search in C, C++, Python and Java

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1333]
**Is your feature request related to a problem? Please describe.**
Fibonacci Search is a search method that relies on Fibonacci numbers and a comparison-based approach to find a specific element within a sorted array.

**Describe the solution you'd like**
```
Here is the algorithm for Fibonacci Search:
- Initialize the Fibonacci numbers fib1 and fib2 to 0 and 1 respectively. Set fib3 as the sum of fib1 and fib2.
- Find the smallest Fibonacci number greater than or equal to the length of the array. This can be done by repeatedly adding fib1 and fib2 and updating the values of fib1, fib2, and fib3 until fib3 becomes greater than or equal to the length of the array.
- Initialize two variables, offset and index, both set to the beginning of the array.
- Compare the element at index index with the target element.
  - If they are equal, the target element has been found. Return the index.
  - If the target element is greater than the element at index index, move the offset by fib2 steps to the right, update fib1 as fib2, fib2 as fib3, and fib3 as the sum of fib1 and fib2. Update index as the sum of offset and fib1.
  - If the target element is less than the element at index index, move the offset by fib1 steps to the right, update fib2 as fib1, fib1 as fib3 minus fib2, and fib3 as the sum of fib1 and fib2. Update index as the sum of offset and fib1.
- Repeat steps 4 until the target element is found or fib1 becomes 1. If fib1 becomes 1 and the target element is not found, the element does not exist in the array.
```

The time complexity of Fibonacci Search is O(log(n)), where n is the length of the array.

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/7dd4ca46-4224-429f-ace2-62518098b7a2)

**Comment by PrathamAsrani** [comment]
I would like to make the code for this. Please assign me for the same.

**Comment by mitali-dxt** [comment]
@Kumar-laxmi this will be first PR in SSOC. I'm a beginner and i would love to solve this.

**Comment by Siddharth015** [comment]
Please assign me this task. As a beginner I would love to complete this task under SSOC 2.0

**Comment by rohitd2103** [comment]
@Kumar-laxmi please assign me this issue I would like to work on it.

**Comment by Kumar-laxmi** [comment]
Assigned!
@mitali-dxt : C, C++, Python and Java

Kindly complete the implementation of this PR within a week or else the issue would be re-assigned

**Comment by VISHALGUPTA100803** [comment]
@Kumar-laxmi  Please assign me this issue it will be my first pr i can do it in C++ C python java

**Comment by Kumar-laxmi** [comment]
@mitali-dxt What is your status on this issue?

**Comment by mitali-dxt** [comment]
@Kumar-laxmi i worked on it but i have a doubt that Fibonacci Search is already present in the repo in all languages.
