### ISSUE TITLE
IDS algorithm in AI in Java and python

### ISSUE THREAD

**Issue by SimranLahrani842** [Kumar-laxmi/Algorithms#1334]
IDDFS combines depth-first search’s space-efficiency and breadth-first search’s fast search (for nodes closer to root). 
IDDFS calls DFS for different depths starting from an initial value. In every call, DFS is restricted from going beyond given depth. So basically we do DFS in a BFS fashion.

**Comment by Kumar-laxmi** [comment]
Kindly give a proper issue description according to the template
