### ISSUE TITLE
Decimal to Binary Converter and vice-versa in C++ & Java

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1336]
**Is your feature request related to a problem? Please describe.**
A Decimal to Binary Converter is a tool or algorithm that converts a decimal number (base 10) into its equivalent binary representation (base 2). In binary representation, numbers are expressed using only two digits: 0 and 1. The converter performs a division and remainder-based approach to convert each digit of the decimal number into its binary equivalent.

**Describe the solution you'd like**
Binary -> Decimal
```
- Start with the binary number that you want to convert.
- Assign a variable decimal with an initial value of 0.
- Iterate through the binary number from right to left, starting with the rightmost digit.
- For each digit encountered:
   - Multiply the digit by 2 raised to the power of its position (starting from 0). For example, if the digit is 1 and it is at position i, calculate 2^i.
   - Add the result to decimal.
- After iterating through all the digits, decimal will hold the decimal representation of the binary number.
```

Decimal -> Binary
```
- Start with the decimal number that you want to convert.
- Initialize an empty string or an array to store the binary digits.
- Divide the decimal number by 2 repeatedly until the quotient becomes 0. Keep track of the remainders obtained from each division.
- For each division, append the remainder to the beginning of the binary string or array.
- Reverse the binary string or array if necessary to obtain the correct binary representation.
- The resulting binary string or array will be the binary representation of the decimal number.
```

**Additional context**
Binary -> Decimal:
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/6c6dadce-700c-4788-ae5a-140beaaa4f54)

Decimal -> Binary: 
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/57eaed4c-1901-4aac-b3b8-b578fd36acd5)

**Comment by aa-d-ya** [comment]
I would like contribute to this issue, please assign this to me.

**Comment by Kumar-laxmi** [comment]
Assigned!
@aa-d-ya : C++ & Java

**Comment by kookie3478** [comment]
I would like to work on this issue please assign me with this task.

**Comment by VISHALGUPTA100803** [comment]
@Kumar-laxmi  Please assign me this issue it will be my first pr i can do it in C++ C python java

**Comment by Kumar-laxmi** [comment]
@aa-d-ya What is your status on this issue?

**Comment by aa-d-ya** [comment]
> @aa-d-ya What is your status on this issue?

The solution is ready, it's just that am new on GitHub so it's being delayed. Will be done within 2 day.
