### ISSUE TITLE
Binary Exponentiation in Java

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1337]
**Is your feature request related to a problem? Please describe.**
As the name suggests, it is the computation of a numerical or a binary component whose result can be as little as zero or as complex as ten raised to 18. The binary exponentiation concept utilizes two pillar extracts of exponentiation. We have learned in our lower grades that every numerical can be expressed in powers of sum or power notation of the numerical.

**Describe the solution you'd like**
```
- Given a base number base and an exponent exponent:
- If the exponent is 0, return 1, as any number raised to the power of 0 is 1.
- If the exponent is 1, return the base, as any number raised to the power of 1 is the number itself.
- Initialize a variable result to 1.
- While the exponent is greater than 0, do the following:
   - If the exponent is odd (exponent % 2 != 0), multiply result by the base.
   - Square the base by multiplying it with itself (base = base * base).
   - Divide the exponent by 2 (exponent = exponent // 2).
- Return the final value of result.
```

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/cc090b50-f156-4c2d-ae5e-1bee6c5c0a6b)

**Comment by aa-d-ya** [comment]
I would like contribute to this issue, please assign this to me.

**Comment by Mrudula1205** [comment]
@Kumar-laxmi I would like to work on this issue, please assign it to me.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Mrudula1205 : C, C++, Python and Java

**Comment by VISHALGUPTA100803** [comment]
@Kumar-laxmi  Please assign me this issue it will be my first pr i can do it in C++ C python java
