### ISSUE TITLE
Frievald's Algorithm in C, C++, Java & Python

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1338]
**Is your feature request related to a problem? Please describe.**
Given three matrices A, B and C, find if C is a product of A and B. 

**Describe the solution you'd like**
```
- Given three matrices: A (n x m), B (m x k), and C (n x k), where the product of A and B should equal C.
- Choose a random vector x (m x 1) consisting of 0s and 1s.
- Calculate a temporary vector y by performing matrix-vector multiplication: y = A * (B * x).
- Calculate another temporary vector z by performing matrix-vector multiplication: z = C * x.
- Subtract the vectors y and z element-wise.
- If the resulting vector has all 0s, return "Product is correct." Otherwise, return "Product is incorrect."
```

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/f58eed6e-d88e-4919-b59a-7f59af712f99)

**Comment by aa-d-ya** [comment]
I would like contribute to this issue, please assign this to me.

**Comment by aadya-21** [comment]
I would like to contribute please @Kumar-laxmi !

**Comment by meghanareddy1808** [comment]
@Kumar-laxmi I would like to contribute, please assign me this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@aadya-21 : C, C++, Java & Python

**Comment by VISHALGUPTA100803** [comment]
@Kumar-laxmi  Please assign me this issue it will be my first pr i can do it in C++ C python java

**Comment by Kumar-laxmi** [comment]
@aadya-21 What is your status on this issue?

**Comment by aadya-21** [comment]
> @aadya-21 What is your status on this issue?

working on it !
