### ISSUE TITLE
Power set of a set of elements in C, C++, Java and Python

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1339]
**Is your feature request related to a problem? Please describe.**
In set theory, the power set (or power set) of a Set A is defined as the set of all subsets of the Set A including the Set itself and the null or empty set. It is denoted by P(A). Basically, this set is the combination of all subsets including null set, of a given set.

**Describe the solution you'd like**
```
- Given a set of elements, let's call it the "original set."
- Initialize an empty list, let's call it the "power set," to store the subsets.
- Calculate the total number of elements in the original set and store it in a variable n.
- Loop through all possible combinations of numbers from 0 to 2^n - 1 (inclusive). This represents all the possible bit patterns of length n, where each bit position indicates whether an element is included or excluded from a subset.
- For each number in the loop:
   - Initialize an empty subset.
   - Iterate through the bit positions from 0 to n-1.
   - If the bit at the current position is set (1), add the corresponding element from the original set to the subset.
   - After the iteration, add the subset to the power set.

- After the loop, the power set will contain all the subsets of the original set.
- Return the power set as the result.
```

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/d67250e4-aa4c-429a-bcdd-db2784dfa6dd)

**Comment by aa-d-ya** [comment]
I would like contribute to this issue, please assign this to me.

**Comment by aadya-21** [comment]
@Kumar-laxmi i would like to contribute to this !

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir kindly assign me this issue under ssoc 23. I can code this using c, c++, java

**Comment by Anushka-gupta496** [comment]
@Kumar-laxmi I would like to contribute to this, kindly assign me this issue.

**Comment by trisharaj06** [comment]
Could you assign this to me, I would like to work on this.

**Comment by adarshmalviy** [comment]
I would like to contribute to this, love to code in C++, Python, Javascript, Go.

**Comment by Kumar-laxmi** [comment]
Assigned!
@aadya-21 : C, C++, Python and Java

**Comment by A-u-usman** [comment]
@Kumar-laxmi I will like to contribute to the issue using Python.

**Comment by VISHALGUPTA100803** [comment]
@Kumar-laxmi  Please assign me this issue it will be my first pr i can do it in C++ C python java

**Comment by Kumar-laxmi** [comment]
@Soumya6Tiwari What is your status on this issue?

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir i already created the pull request for this issue, It is currently under review and i have done it in all 4 programming languages.

**Comment by derphalesh** [comment]
@Kumar-laxmi please assign this issue to me I will do it

**Comment by VISHALGUPTA100803** [comment]
@Kumar-laxmi i have started working on that

**Comment by VISHALGUPTA100803** [comment]
@Kumar-laxmi created a PR
