### ISSUE TITLE
want to add Floyd’s Cycle Finding Algorithm in c++

### ISSUE THREAD

**Issue by saurabhsingh720** [Kumar-laxmi/Algorithms#1340]
![4-300x278](https://github.com/Kumar-laxmi/Algorithms/assets/106748434/5ce8343b-b989-4a79-89fd-cb8742a15d49)
want to add the algorithm that is floyd's cycle finding algo
it is used to find the cycle exists in linked list or not

In this algo we have fast and slow pointer in which faster pointer move two step and slow pointer move one step .
If the both pointer coincide at same node then loop exist
else not.

**Comment by Ashutosh-0506** [comment]
@Kumar-laxmi I would like to contribute to this issue. Please assign me this issue

**Comment by shivam201483101** [comment]
@Kumar-laxmi  i would like to contribute to this issue,Please assign me this issue ,i would do this within a days or faster than that, as soon as i got assigned to this. please consider this request

**Comment by saurabhsingh720** [comment]
@Kumar-laxmi 
please assign me under SSOC'23
