### ISSUE TITLE
Naive Pattern Searching algorithm in c++, java

### ISSUE THREAD

**Issue by saurabhsingh720** [Kumar-laxmi/Algorithms#1342]
![image](https://github.com/Kumar-laxmi/Algorithms/assets/106748434/39a4b918-7b94-477e-9152-08f20d2de8b0)
Description-

1:  It is simple and uses brute force approach.
2:  It compares first character of pattern with searchable text. If match is found, pointers in both strings are advanced. If match not found, pointer of text is incremented and pointer of pattern is reset. This process is repeated until the end of the text.
3:  It directly starts comparing both strings character by character.

**Comment by saurabhsingh720** [comment]
@Kumar-laxmi  please assign me under SSOC,23

**Comment by chhavisharma30** [comment]
I can solve this issue. Kindly assign me this issue.

**Comment by shivangi2002** [comment]
@Kumar-laxmi  I Can solve this. Can you please assign it to me?
