### ISSUE TITLE
Bellman Ford in C, Java & Python

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1350]
**Is your feature request related to a problem? Please describe.**
Given a graph and a source vertex src in the graph, find the shortest paths from src to all vertices in the given graph. The graph may contain negative weight edges. 

**Describe the solution you'd like**
```
- This step initializes distances from the source to all vertices as infinite and distance to the source itself as 0. Create an array dist[] of size |V| with all values as infinite except dist[src] where src is source vertex.
- This step calculates shortest distances. Do following |V|-1 times where |V| is the number of vertices in given graph. Do following for each edge u-v 
   - If dist[v] > dist[u] + weight of edge uv, then update dist[v] to
   - dist[v] = dist[u] + weight of edge uv
- This step reports if there is a negative weight cycle in the graph. Again traverse every edge and do following for each edge u-v 
……If dist[v] > dist[u] + weight of edge uv, then “Graph contains negative weight cycle” 
The idea of step 3 is, step 2 guarantees the shortest distances if the graph doesn’t contain a negative weight cycle. If we iterate through all edges one more time and get a shorter path for any vertex, then there is a negative weight cycle
```

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/fa56aea2-4b77-42cb-949d-596ed4e555b8)

**Comment by Ashutosh-0506** [comment]
@Kumar-laxmi I would like to contribute to this issue. Please assign me this issue.

**Comment by Anushka-gupta496** [comment]
@Kumar-laxmi sir kindly assign me this issue under SSOC'23. I can code this using C, C++,  this will be my first PR

**Comment by tarunvyshnav777** [comment]
> **Is your feature request related to a problem? Please describe.** Given a graph and a source vertex src in the graph, find the shortest paths from src to all vertices in the given graph. The graph may contain negative weight edges.
> 
> **Describe the solution you'd like**
> 
> ```
> - This step initializes distances from the source to all vertices as infinite and distance to the source itself as 0. Create an array dist[] of size |V| with all values as infinite except dist[src] where src is source vertex.
> - This step calculates shortest distances. Do following |V|-1 times where |V| is the number of vertices in given graph. Do following for each edge u-v 
>    - If dist[v] > dist[u] + weight of edge uv, then update dist[v] to
>    - dist[v] = dist[u] + weight of edge uv
> - This step reports if there is a negative weight cycle in the graph. Again traverse every edge and do following for each edge u-v 
> ……If dist[v] > dist[u] + weight of edge uv, then “Graph contains negative weight cycle” 
> The idea of step 3 is, step 2 guarantees the shortest distances if the graph doesn’t contain a negative weight cycle. If we iterate through all edges one more time and get a shorter path for any vertex, then there is a negative weight cycle
> ```
> 
> **Additional context** ![image](https://user-images.githubusercontent.com/76027425/246373629-fa56aea2-4b77-42cb-949d-596ed4e555b8.png)

@Kumar-laxmi assign me this I can code it in C, Java & Python.

**Comment by harshitaaa8** [comment]
please assign me this issue @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
@Anushka-gupta496 Can you also implement this in Python?

**Comment by Anushka-gupta496** [comment]
@Kumar-laxmi Sure, I'll try my best.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Anushka-gupta496 : C, Java & Python

**Comment by Anushka-gupta496** [comment]
@Kumar-laxmi sorry for the delay. I'll complete it today
