### ISSUE TITLE
The Skyline Problem Using Segment Trees

### ISSUE THREAD

**Issue by SPARSH1608** [Kumar-laxmi/Algorithms#1353]
### Feature :
Add solution to the most important question "THE SKYLINE PROBLEM" solved using segment trees in c++

### Description of solution :
Will Add solution to the  "THE SKYLINE PROBLEM"  with adequate comments for readers to get a clear understanding.
To add in C++

### Alternatives Considered :
Online Resources and Tutorials

**Comment by Ashutosh-0506** [comment]
@Kumar-laxmi I would like to contribute to this issue. Please assign me this issue.

**Comment by Kumar-laxmi** [comment]
refer #864
