### ISSUE TITLE
I want to add String Compression Method in C/C++/Java/Python

### ISSUE THREAD

**Issue by atul1510** [Kumar-laxmi/Algorithms#1355]
Problem Statement:
Implement a method to perform basic string compression using the counts of repeated characters. Given a string, return the compressed version of the string. If the compressed string is not shorter than the original string, return the original string. Assume that the input string only contains uppercase and lowercase letters (a-z).

Approach:
Initialize an empty string to store the compressed string. Iterate through the input string character by character. Keep track of the current character and a count variable initialized to 1. Compare the current character with the next character. If they are the same, increase the count. If the characters are different, append the current character and its count to the compressed string.
Could you update the current character to the next character and reset the count to 1. After the iteration is complete, append the last character and its count to the compressed string. If the length of the compressed string is shorter than the original string, return the compressed string. Otherwise, return the original string.

EXAMPLES: 
Input: "aabcccccaaa"
Output: "a2b1c5a3"

Input: "abcdefg"
Output: "abcdefg"
Explanation: The compressed string is not shorter than the original string, so the original string is returned.

![Screenshot (79)](https://github.com/Kumar-laxmi/Algorithms/assets/97626275/08576df3-9975-4c67-9842-cd52cfee34f3)

@Kumar-laxmi sir, @072arushi  @zugzwang03 please assign me this issue.

**Comment by Ashutosh-0506** [comment]
@Kumar-laxmi I would like to contribute to this issue. Please assign me this issue.
