### ISSUE TITLE
Wavelet Tree in C, C++, Python, JAVA

### ISSUE THREAD

**Issue by anand-harsh** [Kumar-laxmi/Algorithms#1356]
**Is your feature request related to a problem? Please describe.**
A wavelet tree is a compact data structure used for efficiently storing and querying information about a sequence of values or symbols. It is particularly useful for handling large datasets or sequences in a space-efficient manner.

The basic idea behind a wavelet tree is to recursively divide the sequence into smaller segments or intervals, representing different levels of resolution or granularity. At each level, the wavelet tree stores information about the frequencies or occurrences of symbols within that interval. This hierarchical structure allows for efficient searching, counting, and range queries on the original sequence.

**Describe the solution you'd like**
Time Complexity is O(log(max(A)) , where max(A) is the maximum element in the array A[]. 

Sample Input

`
Enter size: 5
`
`
Enter the elements: 1 2 3 4 5
`

Sample Output:
`
Answer: 2
`

Please assign me this issue under SSOC'23

**Comment by anand-harsh** [comment]
@Kumar-laxmi please assign me this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@anand-harsh : C, C++, Python and Java
