### ISSUE TITLE
Interval Tree in C, C++, Python, JAVA

### ISSUE THREAD

**Issue by anand-harsh** [Kumar-laxmi/Algorithms#1357]
**Is your feature request related to a problem? Please describe.**
An interval tree is a data structure used for efficiently storing and querying intervals or ranges on a number line. It provides an effective way to handle operations like searching for overlapping intervals, finding the union or intersection of intervals, and inserting or deleting intervals.

The basic idea behind an interval tree is to construct a binary search tree where each node represents an interval. The tree is constructed based on the midpoints of the intervals, ensuring that all intervals to the left of a node's midpoint are completely to the left of the node's interval, and all intervals to the right are completely to the right. This property allows for efficient searching and querying operations.

**Describe the solution you'd like**
Time complexity is O(n*h) i.e. O(n^2) in worst case

Sample Input:
`
Enter intervals:
`
`
15 20
`
`
10 30
`
`
17 19
`
`
5 20
`
`
12 15
`
`
30 40
`

Sample Output:
`
Overlaps with: 5 20
`

Please assign me this issue under SSOC'23

**Comment by anand-harsh** [comment]
@Kumar-laxmi please assign me this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@anand-harsh : C, C++, Python and Java
