### ISSUE TITLE
N-Queen in C, C++, Python, Java

### ISSUE THREAD

**Issue by samratghosh291** [Kumar-laxmi/Algorithms#1363]
**Description of the Problem :**

The N-Queen problem is a classic puzzle that involves placing N queens on an NxN chessboard in such a way that no two queens threaten each other. In other words, no two queens should share the same row, column, or diagonal.

**Example : **

`INPUT:  4`
`OUTPUT: `
`. Q . .`
`. . . Q`
`Q . . .`
`. . Q .`

**Explanation : **

In this example, there are four queens placed on a 4x4 chessboard. Each "Q" represents a queen, and the dots "." represent empty squares. This particular configuration is a valid solution to the 4-Queen problem because no two queens share the same row, column, or diagonal.

The challenge in the N-Queen problem is to find a valid configuration for any given value of N. The solution requires an algorithmic approach, such as backtracking or recursive search, to systematically explore and test different arrangements of queens on the board until a valid solution is found or all possibilities have been exhausted.

**Comment by samratghosh291** [comment]
I would like to work on it.

**Comment by mandliyarajendra11** [comment]
@samratghosh291  @Kumar-laxmi  i can work on this issue in c++

**Comment by Rahul-Talari** [comment]
I had worked on this i can solve in optimal way.please assign me this issue. i can solve it in c,c++, java,python.

**Comment by Kumar-laxmi** [comment]
refer #760
