### ISSUE TITLE
Add Contributing.md file for new contributors

### ISSUE THREAD

**Issue by singodiyashubham87** [Kumar-laxmi/Algorithms#1364]
**Is your feature request related to a problem? Please describe.**

I want to add a CONTRIBUTING.md file for the new contributors to step into the repo for the first time.

**Comment by prajapatihet** [comment]
No

**Comment by prajapatihet** [comment]
# ✨ Contributing to ______________

Thank you for your interest in contributing to ___________! We appreciate your contributions and value your efforts in making this project a valuable resource for learning Flutter layout design.

## Table of Contents

- [:clipboard: Code of Conduct](#code-of-conduct)
- [:rocket: Getting Started](#getting-started)
- [:hammer_and_wrench: How to Contribute](#how-to-contribute)
- [:art: Style Guidelines](#style-guidelines)
- [:bug: Submitting an Issue](#submitting-an-issue)
- [:arrow_up_down: Submitting a Pull Request](#submitting-a-pull-request)

## :clipboard: Code of Conduct

Before you start, please review our [Code of Conduct](./CODE_OF_CONDUCT.md). We are committed to creating a welcoming and inclusive community.

## :rocket: Getting Started

- Fork the _________ repository.
- Clone your forked repository: `git clone 'write your repo name/path' `
- Navigate to the project directory: `cd ____ `
- Install the required dependencies: `flutter pub get`
- Create a new branch for your contribution: `git checkout -b feature-name`

## :hammer_and_wrench: How to Contribute

We encourage contributions in various forms, such as:

- Adding new demo screens showcasing Flutter layout designs.
- Enhancing existing demo screens.
- Improving documentation.
- Refactoring and optimizing code.
- Fixing bugs and issues.

If you're unsure where to start, check the [Issues](https://github.com/your-username/your_project_name/issues) section for open tasks or propose your own ideas. Discussions and planning are also carried out in the [GitHub Discussions](https://github.com/amannyour_username/your_project_name/discussions) area.

## :art: Style Guidelines

Please follow these guidelines when contributing:

- Use consistent code formatting and adhere to the [Dart style guide](https://dart.dev/guides/language/effective-dart/style).
- Include comprehensive documentation for your contributions.
- Ensure your code is well-tested.

## :bug: Submitting an Issue

Before submitting an issue, please:

- Check if a similar issue already exists.
- Provide clear and detailed information about the problem or enhancement you're suggesting.
- Include steps to reproduce any bugs you're reporting.

## :arrow_up_down: Submitting a Pull Request

When you're ready to submit your contribution:

1. Push your changes to your forked repository.
2. Create a pull request (PR) from your fork to the original FlutterUIKit repository.
3. Provide a clear and descriptive title for your PR.
4. Include details in the description about the changes you've made and the problem you're solving.

Your contributions, whether big or small, help improve _________ for everyone. Thank you for being part of our community!

**Comment by prajapatihet** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> I want to add a CONTRIBUTING.md file for the new contributors to step into the repo for the first time.

I have added code/ file

**Comment by prajapatihet** [comment]
ok
