### ISSUE TITLE
Interpolation Search in C, C++, Java & Python

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1366]
**Is your feature request related to a problem? Please describe.**
Given a sorted array of n uniformly distributed values arr[], write a function to search for a particular element x in the array. 
Linear Search finds the element in O(n) time, Jump Search takes O(√n) time and Binary Search  takes O(log n) time. 
The Interpolation Search is an improvement over Binary Search for instances, where the values in a sorted array are uniformly distributed. Interpolation constructs new data points within the range of a discrete set of known data points. Binary Search always goes to the middle element to check. On the other hand, interpolation search may go to different locations according to the value of the key being searched. For example, if the value of the key is closer to the last element, interpolation search is likely to start search toward the end side.

**Describe the solution you'd like**
```
Step1: In a loop, calculate the value of “pos” using the probe position formula. 
Step2: If it is a match, return the index of the item, and exit. 
Step3: If the item is less than arr[pos], calculate the probe position of the left sub-array. Otherwise, calculate the same in the right sub-array. 
Step4: Repeat until a match is found or the sub-array reduces to zero.
```

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/bb3ae901-7bd8-4c88-a54d-d899525e0479)

**Comment by tarunvyshnav777** [comment]
@Kumar-laxmi I can do in all 4 languages assign me

**Comment by mandliyarajendra11** [comment]
@Kumar-laxmi  i want to work on this issue 
i can do in all language or  c++

**Comment by VISHALGUPTA100803** [comment]
Please assign me this issue it will be my first pr i can do it in C++ C python java

**Comment by kumawatvinit** [comment]
@Kumar-laxmi  I can do it in all languages mentioned. Please assign this to me

**Comment by Kumar-laxmi** [comment]
Assigned!
@mandliyarajendra11 : C, C++, Java & Python
