### ISSUE TITLE
Sublist Search in C, C++, Java & Python

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1367]
**Is your feature request related to a problem? Please describe.**
Given two linked lists, the task is to check whether the first list is present in 2nd list or not. 

**Describe the solution you'd like**
```
- Take first node of second list. 
- Start matching the first list from this first node. 
- If whole lists match return true. 
- Else break and take first list to the first node again. 
- And take second list to its second node. 
- Repeat these steps until any of linked lists becomes empty. 
- If first list becomes empty then list found else not.
```

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/d9cd689a-116a-4e19-acc2-739e8cf2478b)

**Comment by tarunvyshnav777** [comment]
@Kumar-laxmi I can do all languages assign me

**Comment by mandliyarajendra11** [comment]
i want to work on this issue , c++ @Kumar-laxmi

**Comment by harshitaaa8** [comment]
i can work in c and python
please assign me this issue
this will be my 1st pr to this repo.

**Comment by Kumar-laxmi** [comment]
Assigned!
@tarunvyshnav777 : C, C++, Python and Java

**Comment by Kumar-laxmi** [comment]
@tarunvyshnav777 What is your status on this issue?

**Comment by tarunvyshnav777** [comment]
> @tarunvyshnav777 What is your status on this issue?

It is ready to push. 
Last night I tried to push but it got messed with the existing pr which is yet to approve by other 2 mentors.

**Comment by mandliyarajendra11** [comment]
> I don't know how to push in different branches @Kumar-laxmi

git checkout -b branch-name

**Comment by tarunvyshnav777** [comment]
> > I don't know how to push in different branches @Kumar-laxmi
> 
> git checkout -b branch-name
 
Branch name can be anything right? 

But For my first pr(which is under review), i didn't give the branch name
Does it work if I can give to 2nd one?

**Comment by mandliyarajendra11** [comment]
> 



> > > I don't know how to push in different branches @Kumar-laxmi
> > 
> > 
> > git checkout -b branch-name
> 
> Branch name can be anything right?
> yes  
> But For my first pr(which is under review), i didn't give the branch name Does it work if I can give to 2nd one?
no

**Comment by tarunvyshnav777** [comment]
Thanks man! @mandliyarajendra11

**Comment by tarunvyshnav777** [comment]
@Kumar-laxmi you did not remove the prolonged label
