### ISSUE TITLE
Quick Select Algorithm in C, C++, Python & Java

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1368]
**Is your feature request related to a problem? Please describe.**
[Quickselect ](https://en.wikipedia.org/wiki/Quickselect)is a selection algorithm to find the k-th smallest element in an unordered list. It is related to the [quick sort](https://www.geeksforgeeks.org/quick-sort/) sorting algorithm.

**Describe the solution you'd like**
```
function quickSelect(list, left, right, k)

   if left = right
      return list[left]

   Select a pivotIndex between left and right

   pivotIndex := partition(list, left, right, 
                                  pivotIndex)
   if k = pivotIndex
      return list[k]
   else if k < pivotIndex
      right := pivotIndex - 1
   else
      left := pivotIndex + 1 
```

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/7cb8df8e-53fc-4751-9036-f44a885c2300)

**Comment by tarunvyshnav777** [comment]
@Kumar-laxmi I can do in all 4 languages assign me

**Comment by mandliyarajendra11** [comment]
i want to work on this issue all languages
if you want to assign in only 1 then in c++

**Comment by harshitaaa8** [comment]
this will be my 1st PR.
please assign me this issue.
i can work in all the 4 languages.

**Comment by VISHALGUPTA100803** [comment]
please assign me this issue it will be my first pr i can do it in c++ python java

**Comment by Kumar-laxmi** [comment]
Assigned!
@mandliyarajendra11 : C, C++, Python and Java

**Comment by Kumar-laxmi** [comment]
@harshitaaa8 What is your status on this issue?

**Comment by harshitaaa8** [comment]
#1525

**Comment by mandliyarajendra11** [comment]
i want to work on this issue @Kumar-laxmi  please assign me
