### ISSUE TITLE
Sorting Algorithms like Bucket Sort, shell sort, 3-way merge sort

### ISSUE THREAD

**Issue by Kinshuk2003** [Kumar-laxmi/Algorithms#137]
**Bucket sort,** or bin sort, is a sorting algorithm that works by distributing the elements of an array into a number of buckets. and buckets are sorted using insertion sort in O(n+k) complexity.

i will like to contribute other sorting algorithms too like:
1. bucket sort using shell sort
2. shell sort
3. 3-way merge sort

please assign this issue to me  @Kumar-laxmi 
Languages : **C, C++, Python**

**Comment by Kumar-laxmi** [comment]
Please open separate issues for separate algorithms so that others can also contribute to them separately
