### ISSUE TITLE
Algorithm Implementations in C++ Using Class: FCFS, SJF, and Round Robin

### ISSUE THREAD

**Issue by divyansh956** [Kumar-laxmi/Algorithms#1375]
**Is your feature request related to a problem? Please describe.**
This outlines the creation of a GitHub repository aimed at providing C++ implementations of three fundamental scheduling algorithms: First-Come, First-Served (FCFS), Shortest Job First (SJF), and Round Robin. These algorithms play a crucial role in operating system design and provide a solid foundation for understanding scheduling concepts. By organizing the implementations into classes, the repository will promote code reusability, modularity, and ease of understanding for developers and students.

**Describe the solution you'd like**
The algorithms will be implemented as classes in C++, utilizing object-oriented programming principles to encapsulate relevant data and operations. Each class will have appropriate member functions and variables to represent the scheduling algorithm's logic. The classes will be designed to be reusable, customizable, and easily integrated into other projects.
**Describe alternatives you've considered**

**Comment by Kumar-laxmi** [comment]
Please raise issue to solve one algorithm per issue
