### ISSUE TITLE
 Adding Longest Increasing Subsequence Algorithm in C,C++ and Java

### ISSUE THREAD

**Issue by dhruti26** [Kumar-laxmi/Algorithms#1376]
**Description**
 We have given an array arr[] of size N, we need to find the length of the Longest Increasing Subsequence (LIS) i.e., the longest possible subsequence in which the elements of the subsequence are sorted in increasing order.

**Describe the solution you'd like**
I would like to implement the algorithm in C,C++ and Java

It is one of the most popular algorithm which is missing in the repo. Kindly allow me to work on this issue under SSOC'23

**Comment by himughanakash** [comment]
Hey @dhruti26 please assign me this issue to work on and resolve it under ssoc'23 program.

**Comment by himughanakash** [comment]
Hey @Kumar-laxmi please assign this issue to me so i can work on this issue under ssoc'23 program.

**Comment by dhruti26** [comment]
@Kumar-laxmi please assign me this issue as it was raised by me and so that I can submit my PR

**Comment by himughanakash** [comment]
@Kumar-laxmi please assign this issue to me so that i can start working on this asap.

**Comment by chhavisharma30** [comment]
I can solve these issue in all three languages. Kindly assign me this issue.

**Comment by dhruti26** [comment]
@Kumar-laxmi Please assign me this issue under SSOC'23
