### ISSUE TITLE
Ternary Search Tree (TST) 

### ISSUE THREAD

**Issue by Devchawla2608** [Kumar-laxmi/Algorithms#1377]
A Ternary Search Tree (TST) is a data structure that is used to efficiently store and search for strings. It is an advanced version of a binary search tree where each node has three children: left, middle, and right. The TST allows for efficient retrieval of strings that match a given prefix or are similar to a given query string.

Algorithm for Ternary Search Tree (TST):
1.) Create a TST node class with character data, left, middle, and right pointers, and an end-of-word flag.
2.) Implement an insert() function that recursively inserts characters into the TST based on comparisons.
3.) Implement a search() function that recursively searches for a string in the TST by comparing characters.
4.) Initialize an empty TST and use the insert() function to add strings to the TST.
5.) Use the search() function to check if a string exists in the TST.

Please assign me this issue under SSOC'23

**Comment by Devchawla2608** [comment]
Please assign me this issue under SSOC'23 . I can work in all the 4 languages.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Devchawla2608 : C, C++, Java & Python
