### ISSUE TITLE
Implement KMP Pattern - Matching Algorithm.

### ISSUE THREAD

**Issue by MaYaNkKashyap681** [Kumar-laxmi/Algorithms#138]
Implement KMP {Knuth-Morris-Pratt} Pattern Matching Algorithm using 
1). C++.
2). C.
3). JAVA.
4). PYTHON.
KMP is the best pattern-matching algorithm with O(n) complexity so it must be there.

Assign this to me in C++ and C.

**Comment by sumitkr2000** [comment]
is someone working on it??
If not please assign me this issue in c++. @Kumar-laxmi

**Comment by stiwari-ds** [comment]
@Kumar-laxmi Please assign it to me for Python.

**Comment by Kumar-laxmi** [comment]
Assigned!
@stiwari-ds : Python

**Comment by sumitkr2000** [comment]
Is anyone working in C++ on this issue? If not please assign me.

**Comment by zugzwang03** [comment]
!Assigned : @sumitkr2000 : C++

**Comment by Kumar-laxmi** [comment]
This issue is left only in ```Java```

**Comment by Kumar-laxmi** [comment]
Assigned!
@Paritosh-J : Java
