### ISSUE TITLE
Adding Morse code

### ISSUE THREAD

**Issue by kritika2313** [Kumar-laxmi/Algorithms#1390]
Morse code is a method used in telecommunication to encode text characters as standardized sequences of two different signal durations, called dots and dashes. Morse Code defines a standard encoding where each letter is mapped to a series of dots and dashes, as follows: “a” maps to “.-“, “b” maps to “-…”, “c” maps to “-.-.”, and so on.

eg: school
output: ... -.-. .... --- --- .-..

i and code this in c++,java and python.

@Kumar-laxmi can you pls assign me under ssoc'23

**Comment by Kumar-laxmi** [comment]
Assigned!
@kritika2313 : C, C++, Java & Python
