### ISSUE TITLE
Affine Cipher

### ISSUE THREAD

**Issue by roblox-codex** [Kumar-laxmi/Algorithms#1396]
Pls assign me this to contribute in Cryptography using C++

**Comment by Ashutosh-0506** [comment]
The Affine cipher is a type of monoalphabetic substitution cipher, wherein each letter in an alphabet is mapped to its numeric equivalent, encrypted using a simple mathematical function, and converted back to a letter. The formula used means that each letter encrypts to one other letter, and back again, meaning the cipher is essentially a standard substitution cipher with a rule governing which letter goes to which.  

Please assign me this issue. @Kumar-laxmi .
