### ISSUE TITLE
Identity Matrix creating function with parameter as the dimension

### ISSUE THREAD

**Issue by Sanitya7** [Kumar-laxmi/Algorithms#140]
**Is your feature request related to a problem? Please describe.**
For generating an identity matrix, numpy is used which takes more steps, instead of this, a direct function can be used.

**Describe the solution you'd like**
A function with the parameter of dimension of the square matrix , and the output is an identity matrix. 

**Describe alternatives you've considered**

**Additional context**

Adding the Code snippet here, 
```

#function for defining a n X n matrix
def create_matrix(dim):
    for i in range(0,dim):
        for j in range(0,dim):
            if i == j :
                if j == (dim - 1):
                    print("1")
                else :
                    print("1", end=",")
            else :
                if j == (dim - 1) :
                    print("0")
                else :
                    print("0", end=",")

n = int(input("Enter the Dimension: "))
create_matrix(n)
```

**Comment by Kumar-laxmi** [comment]
Try contributing standard algorithms that either exists or you are trying to reduce their complexity.

Self made algorithms are also accepted.
