### ISSUE TITLE
[SSoC 2.0] Lucas Lehmer Series

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Kumar-laxmi/Algorithms#1401]
**Is your feature request related to a problem? Please describe.**
- The Lucas-Lehmer series refers to the sequence of numbers generated during the Lucas-Lehmer primality test for Mersenne numbers.

**Describe the solution you'd like**
- The number of iterations in the series is typically p - 2, where p is the exponent in the corresponding Mersenne number 2^p - 1.

**Describe alternatives you've considered**
- Proth's theorem is the alternative of this series but the time and space complexity is much higher as compare to the lucas lehmer series to find the Mersenne numbers.

**Additional context**
I can solve it in C, C++, JAVA, and PYTHON programming languages.

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi please assign this task to me so to work on it and contribute in this repository under SSoC 2.0 program

And requested to also assign 1043, 1044, 1052, and 1053 so that i can create a pull request and give a successful contribution under SSoC 2.0 program
Thanks

**Comment by Kumar-laxmi** [comment]
Assigned!
@Avdhesh-Varshney : C, C++, Python and Java
