### ISSUE TITLE
ADD:Levenshtein Distance in C++,C and Python

### ISSUE THREAD

**Issue by shravanii2308** [Kumar-laxmi/Algorithms#1406]
**Is your feature request related to a problem? Please describe.**
The algorithm to calculate Levenshtein Distance is typically implemented using dynamic programming. It builds a matrix where each cell represents the minimum number of operations required to transform a substring of one string into a substring of the other string. The algorithm fills in the matrix iteratively, considering the possible operations at each step.

**Describe the solution you'd like**
Code with Comments in  C++, C, and Python.

**Additional context**
@Kumar-laxmi please assign me this issue

**Comment by Kumar-laxmi** [comment]
Is this EDIT Distance algorithm?

**Comment by Kumar-laxmi** [comment]
refer #706
