### ISSUE TITLE
Adding Level order Traversal for Binary Tree using C, C++ and Python.

### ISSUE THREAD

**Issue by Maheshmali1** [Kumar-laxmi/Algorithms#1407]
### Describe the solution :

Level order traversal is a popular algorithm used to visit and process each node in a binary tree, where nodes at the same level are visited before moving on to the next level. It ensures that nodes are processed in a breadth-first manner, starting from the root node and moving down through each level until all nodes have been visited.

### Algorithm flow :

- Create an empty queue data structure to store the nodes.
- Enqueue the root node of the binary tree into the queue.
- Start a loop that continues until the queue becomes empty.
- Within the loop, dequeue a node from the front of the queue.
- Process the dequeued node (e.g., print its value, perform some operation, etc.).
- Enqueue the left child of the dequeued node into the queue if it exists.
- Enqueue the right child of the dequeued node into the queue if it exists.
- Repeat steps 4-7 until the queue is empty.
- The algorithm has completed when all nodes in the binary tree have been processed.

### I searched across our algorithms repository but couldn’t find this algorithm and its important Algorithm that we are missing. Please assign me this issue under SSoC23

@Kumar-laxmi Please assign me this issue under SSoC23 as it will be my first open source contribution. Thanks.

**Comment by vedang2003** [comment]
@Kumar-laxmi Please assign me this issue for C,C++.
This shall be my first contribution for SSOC

**Comment by Kumar-laxmi** [comment]
Sorry this has been implemented in all four languages
