### ISSUE TITLE
regarding dynamic programming algorithms

### ISSUE THREAD

**Issue by weaklogics** [Kumar-laxmi/Algorithms#1412]
i would like to add the problems in DP in C++ , java known as coin change-making problem and rod cutting problem 
please look into it and assign me this

**Comment by JAYANTH5775** [comment]
hey,  This will be my first contribution in SSOC 23 , please assign me the work :) I can to the  DP   algorithms of the 1D , 2D (knapsack , coin change , maximum product of  the subarray , climbing stairs)
