### ISSUE TITLE
Scheduling Algorithms in Operating Systems

### ISSUE THREAD

**Issue by roblox-codex** [Kumar-laxmi/Algorithms#1414]
Longest Remaining Time First (LRTF), Longest Job First (LJF), Shortest Job First (SJF), and Shortest Remaining Time (SRT). These algorithms are essential for managing process execution and optimizing resource utilization in computer systems.

**1. LRTF: (Longest Remaining Time First)** is a scheduling algorithm in operating systems that prioritizes the execution of the process with the highest remaining execution time to optimize resource utilization.
**2. LJF: (Longest Job First)** is a scheduling algorithm that prioritizes the execution of processes based on their estimated running time, allowing longer jobs to be completed first.
**3. SJF: (Shortest Job First)** is a scheduling algorithm that selects the process with the shortest burst time for execution, resulting in minimized average waiting time.
**4. SRTF: (Shortest Remaining Time First)** is a scheduling algorithm that selects the process with the shortest remaining burst time for execution, allowing preemption and reducing response time.

**Code Implementations:** Code implementations of LRTF, LJF, SJF, and SRT algorithms in  programming languages like C, C++, Java, and Python. 

@Kumar-laxmi Kindly assign me this issue (feature update)

**Comment by JAYANTH5775** [comment]
hey , this will be my first contribution , i will be able to do the code implementations of LRTF, LJF, SJF, and SRT algorithms in programming languages like C, C++, Java, and Python. please assign me the work

**Comment by Kumar-laxmi** [comment]
You have mentioned all algos in one issue
