### ISSUE TITLE
Lycheral Numbers

### ISSUE THREAD

**Issue by saikiranreddy201** [Kumar-laxmi/Algorithms#1417]
**Is your feature request related to a problem? Please describe.**
I would like to add a math section problem which is **Lycheral Numbers**, I want to implement it in c, c++, Java, and Python.

**Describe the solution you'd like**
I can write a code that has the Time complexity of   **O((end - start) * 50 * d)**, where the start and the end are the range of numbers between which we check Lycheral Numbers.

**Lycheral Number:** A Lychrel number is a natural number that, when repeatedly reversed and added to itself, never forms a palindrome

I want to work under SSOC'23.

**Comment by Kumar-laxmi** [comment]
Assigned!
@saikiranreddy201 : C, C++, Python and Java

**Comment by jahnvisahni31** [comment]
I would like to work on this issue.
I understand the issue. ✅
