### ISSUE TITLE
Diffie-Hellman Algorithm(Cryptography) in Java, C++ and C

### ISSUE THREAD

**Issue by HadiaSamreen** [Kumar-laxmi/Algorithms#1420]
**Is your feature request related to a problem? Please describe.**
While i was browsing, I discovered that Diffie-Hellman Algorithm is not in java ,C and C++ languages yet 

**Describe the solution you'd like**
I want to add Diffie-Hellman algorithm from cryptography section in C,C++ and Java languages

**Additional context**
(About The Diffie-Hellman algorithm)

The Diffie-Hellman algorithm is a key exchange protocol that allows two parties to exchange cryptographic keys over an insecure channel without the keys being exposed to an eavesdropper. The algorithm works by using a mathematical function to generate a shared secret key that can then be used to encrypt and decrypt communications.

This algorithm is a secure and efficient way to exchange cryptographic keys over an insecure channel. It is widely used in a variety of applications, including secure web browsing, email, and file sharing.

Here are some of the benefits of using the Diffie-Hellman algorithm:

~Security: The Diffie-Hellman algorithm is a secure way to exchange cryptographic keys. The keys are not exposed to an eavesdropper, even if the entire communication is intercepted.
~Efficiency: The Diffie-Hellman algorithm is an efficient way to exchange cryptographic keys. The keys can be generated and exchanged quickly, even over a slow network connection.
~Versatility: The Diffie-Hellman algorithm is a versatile algorithm that can be used in a variety of applications. It is widely used in secure web browsing, email, and file sharing.

**Comment by Kumar-laxmi** [comment]
refer #687

**Comment by HadiaSamreen** [comment]
Okay!
