### ISSUE TITLE
[SSoC 2.0] Freivald's Algorithm

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Kumar-laxmi/Algorithms#1424]
**Is your feature request related to a problem? Please describe.**
- To check the entered matrix is a product of any other two matrices or not.

**Describe the solution you'd like**
- By applying ```A * B * x = C * x ``` formula to check the entered matrix is product of other two or not.

**Describe alternatives you've considered**
- If we apply the brute force approch to check, it will time and space consuming and may be give a probilistic answer.
- But using this algorithm, time complexity is O(n log(n)), which gives answer very fastly.

**Additional context**

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi please assign this task to me for a contirbution under SSoC 2.0 program
I can solve this algorithm in C, C++, PYTHON and JAVA languages.
/assign

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi please assign this task to me as i have done with this task and want to create a pull request in this repository for a valuable contribution under SSoC 2.0 program

please /assign

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi I have done with my last issue and already created a pull request.

So, Now i want to work on this algorithm and send a pull request.
Please /assign

**Comment by Kumar-laxmi** [comment]
refer #1338
