### ISSUE TITLE
Brian kernighan algorithm 

### ISSUE THREAD

**Issue by Jyoti040** [Kumar-laxmi/Algorithms#1433]
_**Is your feature request related to a problem? Please describe**_.

The problem is to find the number of set bits in binary representation of a number.

_**Describe the solution you'd like**_

Brian kernighan algorithm is an efficient algorithm which uses bitwise and operation and helps to find number of set bits .
Set bits refer to number of 1s in binary representation of a number.
 Time complexity - O(log N)
  Auxiliary space - O(1)

[**Describe alternatives you've considered**]()

Lookup table method can also be used to solve this problem

_**Additional context**_

I want to work under SSOC'23.
I want to add this algorithm in maths section, please assign this to me.

**Comment by anasadh** [comment]
@Kumar-laxmi  please assign me this
