### ISSUE TITLE
[ssoc '23] First fit algorithm for memory management

### ISSUE THREAD

**Issue by ShanmukhiKairuppala** [Kumar-laxmi/Algorithms#1435]
**Is your feature request related to a problem? Please describe.**
First-Fit Allocation is a memory allocation algorithm used in operating systems to allocate memory to a process. OS  searches through the free blocks of memory, starting from the beginning , until it finds a block that is large enough to accommodate the memory request from the process.

**Describe the solution you'd like**
C program to implement above algorithm.

**Comment by ShanmukhiKairuppala** [comment]
Can you please assign me this issue under ssoc'23?

**Comment by ranjanmangla1** [comment]
please assign me this issue, i have code ready

**Comment by Kumar-laxmi** [comment]
refer #1494
