### ISSUE TITLE
[ssoc'23]Best fit algorithm for memory management

### ISSUE THREAD

**Issue by ShanmukhiKairuppala** [Kumar-laxmi/Algorithms#1436]
**Is your feature request related to a problem? Please describe.**
 In Best-Fit algorithm , the operating system searches through the list of free blocks of memory to find the block that is closest in size to the memory request from the process. It improves memory utilization and reduce fragmentation.

**Describe the solution you'd like**
C program to implement above algorithm

**Comment by ShanmukhiKairuppala** [comment]
Can you please assign me this issue under ssoc'23?

**Comment by jahnvisahni31** [comment]
I would like to work on this issue.
I understand the issue. ✅

**Comment by ranjanmangla1** [comment]
please assign me this issue, i have code ready

**Comment by Kumar-laxmi** [comment]
refer #1493
