### ISSUE TITLE
Affine Cipher Implementation in Java and Python.

### ISSUE THREAD

**Issue by brahmamyv** [Kumar-laxmi/Algorithms#1443]
**Is your feature request related to a problem? Please describe.**
Yes. Affine Cipher is a Cryptographic algorithm.
**Describe the solution you'd like**
I would like to implement the algorithm in Python and in Java.
**Additional context**
Affine Cipher is a monoalphabetic cipher, performs modular arithmetic for mapping the alphabet to a numerical value . It encrypts and decrypts the message letter by letter. It is considered as a standard substitution cipher.

**Encryption:**
Cipher Text, C=(aX+b) mod 26
where a, b are private key values and X is letter to be encrypted.
**Decryption:**
Plain Text, X=[a^-1(C-b)] mod 26

where alphabets from (a-z) are numbered sequentially from (0-25).

![image](https://github.com/Kumar-laxmi/Algorithms/assets/130195097/4c83d6cb-d368-4829-b09b-a88e0ee7536a)

**Example:**

![affin-cipher](https://github.com/Kumar-laxmi/Algorithms/assets/130195097/a8b6a3e8-e22b-47b6-a67f-b4ece5309483)

Please assign me this under SSOC23 @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Since it is an easy issue kindly implement in all four languages

**Comment by Kumar-laxmi** [comment]
Assigned!
@brahmamyv : C, C++, Python and Java
