### ISSUE TITLE
Longest Job First [CPU Scheduling] in C, C++, Python and Java 

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1446]
**Is your feature request related to a problem? Please describe.**
Longest Job First(LJF) scheduling process is just opposite of shortest job first (SJF), as the name suggests this algorithm is based upon the fact that the process with the largest burst time is processed first. Longest Job First is non-preemptive in nature.

**Describe the solution you'd like**
```
- Get the list of processes along with their burst times.
- Sort the list in descending order based on the burst time.
- Set the current time to 0.
- Initialize an empty ready queue to hold the processes.
- While there are processes in the list:
   - Check if any processes have arrived at the current time. If yes, move them from the list to the ready queue.
   - If the ready queue is empty, increment the current time by 1.
   - If the ready queue is not empty:
     - Select the process with the longest burst time from the ready queue.
     - Execute the process for its entire burst time.
     - Update the current time by adding the process's burst time.
     - Remove the executed process from the ready queue and the list.
- Repeat steps 5a to 5c until all processes have been executed.
- Calculate the average waiting time and turnaround time based on the execution sequence.
```

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/b5517aca-26ba-44e2-a15e-eb1955ba0d12)

**Comment by tarunvyshnav777** [comment]
@Kumar-laxmi please assign this. I can code in all 4 languages

**Comment by Anushka-gupta496** [comment]
@Kumar-laxmi kindly assign me assign this issue.

**Comment by Aarsh30** [comment]
can you assign me @Kumar-laxmi  I have done this all algorithm and already I have the codes just I  to make pr

**Comment by HadiaSamreen** [comment]
Kindly assign this issue to me. I am very good at CPU scheduling concepts @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Assigned!
@HadiaSamreen : C, C++, Python and Java

**Comment by shanvijha30** [comment]
@Kumar-laxmi I would like to work on this issue. Could you please assign this issue to me.
Thank you!

**Comment by shanvijha30** [comment]
@Kumar-laxmi Please could assign this issue to me. I would like to work on it.

**Comment by shanvijha30** [comment]
@Kumar-laxmi I would like to work on this issue it seems to be inactive.
Thank you!

**Comment by shanvijha30** [comment]
@Kumar-laxmi I would like to work on this issue. Could you please assign it to me as it seems to be inactive.
Thank you!

**Comment by Kumar-laxmi** [comment]
Assigned!
@shanvijha30 : C, C++, Python and Java
