### ISSUE TITLE
Priority Scheduling [CPU Scheduling] in C, C++, Python and Java

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1447]
**Is your feature request related to a problem? Please describe.**
Preemptive Priority CPU Scheduling Algorithm is a pre-emptive method of CPU scheduling algorithm that works based on the priority of a process. In this algorithm, the editor sets the functions to be as important, meaning that the most important process must be done first. In the case of any conflict, that is, where there are more than one processor with equal value, then the most important CPU planning algorithm works on the basis of the FCFS (First Come First Serve) algorithm.

**Describe the solution you'd like**
```
- Get the list of processes along with their priorities and burst times.
- Sort the list in ascending order based on the priority.
- Set the current time to 0.
- Initialize an empty ready queue to hold the processes.
- While there are processes in the list:
   - Check if any processes have arrived at the current time. If yes, move them from the list to the ready queue.
   - If the ready queue is empty, increment the current time by 1.
   - If the ready queue is not empty:
      - Select the process with the highest priority from the ready queue.
      - Execute the process for its entire burst time.
      - Update the current time by adding the process's burst time.
      - Remove the executed process from the ready queue and the list.
- Repeat steps 5a to 5c until all processes have been executed.
- Calculate the average waiting time and turnaround time based on the execution sequence.
```

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/4d20240b-d958-44b2-be06-6c14662c57b2)

**Comment by tarunvyshnav777** [comment]
@Kumar-laxmi please assign this. I can code in all languages

**Comment by ranjanmangla1** [comment]
please assign me, i have code ready

**Comment by HadiaSamreen** [comment]
I am beginner to thecontribution but i am good at OS concepts . Please assign this to me @Kumar-laxmi

**Comment by divyansh956** [comment]
Please assign me @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Assigned!
@divyansh956 : C, C++, Python and Java
