### ISSUE TITLE
Round robin [CPU Scheduling] in C, C++, Python and Java 

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1448]
**Is your feature request related to a problem? Please describe.**
Round Robin is a CPU scheduling algorithm where each process is cyclically assigned a fixed time slot. It is the preemptive version of First come First Serve CPU Scheduling algorithm. Round Robin CPU Algorithm generally focuses on Time Sharing technique.

**Describe the solution you'd like**
```
- Get the list of processes along with their burst times.
- Set the time quantum (also known as time slice) value.
- Initialize the current time to 0.
- Initialize an empty ready queue to hold the processes.
- While there are processes in the list or the ready queue is not empty:
   - Check if any processes have arrived at the current time. If yes, move them from the list to the ready queue.
   - If the ready queue is empty, increment the current time by 1.
   - If the ready queue is not empty:
     - Select the process at the front of the ready queue.
     - Execute the process for the time quantum or its remaining burst time, whichever is smaller.
     - Update the current time by the time the process was executed.
     - Reduce the burst time of the executed process by the amount of time it was executed.
     - If the process has completed (burst time becomes 0), remove it from the ready queue and the list.
     - If the process has not completed, move it to the back of the ready queue.
- Repeat steps 5a to 5c until all processes have been executed.
- Calculate the average waiting time and turnaround time based on the execution sequence.
```

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/8054ba85-c620-450a-8609-989910e5ecdf)

**Comment by palakag29** [comment]
Please assign it to me

**Comment by Inferno2211** [comment]
Hi @Kumar-laxmi , could you please assign this to me under SSOC'23?

This will be my first contribution in this repo

**Comment by ranjanmangla1** [comment]
please assign me, i have code ready

**Comment by HadiaSamreen** [comment]
This will be my first contribution , Could you please assign this to me @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Assigned!
@Inferno2211 : C, C++, Java and Python

**Comment by palakag29** [comment]
Please assign it to me @Kumar-laxmi

**Comment by shanvijha30** [comment]
@Kumar-laxmi Please assign this issue to me I would like to work on it .

**Comment by palakag29** [comment]
@palakag29 @Kumar-laxmi @shanvijha30

**Comment by shanvijha30** [comment]
@Kumar-laxmi I would like to work on this issue. Could you please assign it to me.

**Comment by shanvijha30** [comment]
@Kumar-laxmi I would like to work on it please assign it to me.
Thank you!

**Comment by derphalesh** [comment]
This issue has been assigned for to long can you reassign it to me

**Comment by Kumar-laxmi** [comment]
Assigned!
@palakag29 : C, C++, Java and Python

**Comment by derphalesh** [comment]
Can you assign this to me as this issue is not assigned to anyone

**Comment by chhavisharma30** [comment]
Can you assgn me this issue? I can work on this in all four languages.

**Comment by Shreyaprasad02** [comment]
Can you please assign this issue to me? I will work on it as a priority.
@Kumar-laxmi

**Comment by shivangi2002** [comment]
@Kumar-laxmi please assign it to me.

**Comment by Paritosh-J** [comment]
@Kumar-laxmi I request you to please assign me this issue.
The algorithm will be implemented in C++, Python and Java.
Thank You

**Comment by Kumar-laxmi** [comment]
Assigned!
@Paritosh-J : C, C++, Python and Java
