### ISSUE TITLE
Shortest Remaining Time First [CPU Scheduling] in C, C++, Python and Java

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1449]
**Is your feature request related to a problem? Please describe.**
Shortest remaining time first is the preemptive version of the Shortest job first which we have discussed earlier where the processor is allocated to the job closest to completion. In SRTF the process with the smallest amount of time remaining until completion is selected to execute.

**Describe the solution you'd like**
```
- Get the list of processes along with their burst times.
- Set the current time to 0.
- Initialize an empty ready queue to hold the processes.
- While there are processes in the list or the ready queue is not empty:
  - Check if any processes have arrived at the current time. If yes, move them from the list to the ready queue.
  - If the ready queue is empty, increment the current time by 1.
  - If the ready queue is not empty:
    - Select the process with the shortest remaining burst time from the ready queue.
    - Execute the process for a unit of time (preempting if necessary).
    - Update the current time by 1.
    - Reduce the burst time of the executed process by 1.
    - If the process has completed (burst time becomes 0), remove it from the ready queue and the list.
    - If the process has not completed, keep it in the ready queue and continue.
- Repeat steps 4a to 4c until all processes have been executed.
- Calculate the average waiting time and turnaround time based on the execution sequence.
```

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/56e2026a-c679-4d8d-afd6-dcca6f51fc0d)

**Comment by divyansh956** [comment]
I will do this please assign me

**Comment by ranjanmangla1** [comment]
please assign me, i have code ready

**Comment by Aarsh30** [comment]
can you assign me @Kumar-laxmi  I have done this all algorithm and already I have the codes just I  to make pr

**Comment by Devchawla2608** [comment]
@Kumar-laxmi kindly assign this to me under SSOC'23. I'm ready to contribute in all 4 languages

**Comment by Kumar-laxmi** [comment]
Assigned!
@Devchawla2608 : C, C++, Python and Java

**Comment by shanvijha30** [comment]
@Kumar-laxmi Would like to work on this issue could please assign it to me.

**Comment by shanvijha30** [comment]
@Kumar-laxmi Please assign it to me. I would like to work on it.

**Comment by Kumar-laxmi** [comment]
Assigned!
@SimranLahrani842 : C, C++, Python and Java
