### ISSUE TITLE
divide and conquer algorithm 

### ISSUE THREAD

**Issue by harshagr70** [Kumar-laxmi/Algorithms#145]
**Is your feature request related to a problem? Please describe.**
A divide and conquer algorithm is a strategy of solving a large problem by breaking the problem it into smaller sub-problems,

**Describe the solution you'd like**
i want to add the details about divide and conquer algorithm with code illustration in cpp.

**Additional context**
please assign me this issue

**Comment by Kumar-laxmi** [comment]
Please raise issue addressing specific algorithm
