### ISSUE TITLE
Dynamic Programming Algorithm to find largest Sub-Square matrix of all 1's in a binary matrix

### ISSUE THREAD

**Issue by AK3847** [Kumar-laxmi/Algorithms#1452]
**Is your feature request related to a problem? Please describe.**
--> This is a very great implementation of  dynamic programming  as there are many overlapping sub-parts and also this type of algorithm is often asked in interviews and competitions.

**Describe the solution you'd like:**
--> I would like to add this algorithm in Dynamic-Programming folder in C++,C,JAVA and Python

**Describe alternatives you've considered:**

**Additional context**
I have a great knowledge about this topic and the algorithm so I can implement very efficiently and will also comment it properly. @Kumar-laxmi Please assign me this issue under SSOC'23. Thanks for Consideration.

**Comment by Shobhitsingh-2503** [comment]
I have a nice grasp over Recursion and DP so I find myself efficient enough to implement it and will also comment it properly. 
@Kumar-laxmi Please assign me this issue I am interested.
P.S. it would my first contribution in open source so please give me the priveeledge to contribute.

**Comment by Kumar-laxmi** [comment]
This repo is not for competitive programming question
