### ISSUE TITLE
Memory Management Algorithms used in OS

### ISSUE THREAD

**Issue by ranjanmangla1** [Kumar-laxmi/Algorithms#1454]
**Is your feature request related to a problem? Please describe.**
There are no memory management algorithms like best fit, worst fit, first come first serve, buddy system in this repo. This algorithms are quite important and are used in modern operating systems. Can you assign me this issue, new to SSOC'23, I will contribute.

**Describe the solution you'd like**
I will add C++, C, Java and Python implementations of these algorithms

**Comment by Kumar-laxmi** [comment]
So you have the freedom to raise issue to solve any particular algorithm but you have mentioned all the algo. in one issue to solve. Kindly raise issue to solve one algo per issue
