### ISSUE TITLE
Kruskal's Algorithm in C, C++, Java & Python

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1459]
### Feature :
Kruskal's Algorithm is a greedy algorithm that is used to find the minimum spanning tree from a graph.
The idea is to sort all edges of given graph in increasing order, and then keep on adding new edges and nodes in the spanning tree if the added edge does not form a cycle. 

This will be added in C, C++, Java and Python.

### Description of solution :
- Will add Kruskal's Algorithm with adequate comments and proper documentation for readers to get a clear understanding.
- To be added in C, C++, Java and Python

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/9527e4e0-987a-4e06-a43d-5358a9fbe477)

**Comment by tarunvyshnav777** [comment]
@Kumar-laxmi kindly assign this to me under SSOC'23. I'm ready to contribute in all 4 languages

**Comment by Devchawla2608** [comment]
@Kumar-laxmi please assign this to me under SSOC'23. I'm ready to contribute in all 4 languages

**Comment by mitali-dxt** [comment]
@Kumar-laxmi please assign this to me. This will be my first pr under ssoc.

**Comment by Viveksati5143** [comment]
@Kumar-laxmi I'll work on this issue.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Viveksati5143 : C, C++, Python and Java

**Comment by Viveksati5143** [comment]
Closes: #1497 @Kumar-laxmi

**Comment by derphalesh** [comment]
@Kumar-laxmi please assign this issue to me will do it within 5 days
