### ISSUE TITLE
Mathematical programs related to geometrical shapes

### ISSUE THREAD

**Issue by ajruttam** [Kumar-laxmi/Algorithms#146]
This will contain programs to calculate

#### Area and Perimeter for 2D objects like:
+ square
+ rectangle
+ triangle
+ circle

#### Total surface area, Curved surface area and Volume for 3D objects like:
+ Cube
+ Cuboid
+ Cylinder
+ Cone
+ Sphere
+ Hemisphere

I will do this in Python, @Kumar-laxmi sir. Please assign this work to me.

**Comment by Sachittarway** [comment]
Please assign the task. I can perform the above task in c++.

**Comment by Kumar-laxmi** [comment]
Kindly raise issue pertaining to standard algorithms.
Even self made algorithms are welcomed!
