### ISSUE TITLE
Treap Algorithm

### ISSUE THREAD

**Issue by Devchawla2608** [Kumar-laxmi/Algorithms#1462]
**Is your feature request related to a problem? Please describe.**
The Treap algorithm, also known as the Randomized Binary Search Tree, combines properties of both binary search trees and heaps. It maintains the binary search tree property based on the keys of the nodes and the heap property based on the priorities assigned to the nodes.

**Describe the solution you'd like**
1.) Define a node structure with key and priority attributes.
2.) Implement methods for insertion, deletion, and rotation operations.
3.) For insertion, recursively find the appropriate position based on key values and priorities.
4.) Rotate nodes as necessary to maintain the heap property during insertion.
5.) For deletion, recursively find the node to be deleted based on key values.
6) Rotate nodes as necessary to maintain both the binary search tree property and the heap property during deletion.
7.) Perform in-order traversal to process the nodes in sorted order.
8.) Create an instance of the treap and use the methods to perform operations.
9.) Utilize the treap for efficient search, insert, delete, and traversal operations with expected logarithmic time complexity

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/92145696/b13162ec-82a5-4502-82a9-03d4dbcfd8ac)

**Comment by Devchawla2608** [comment]
@Kumar-laxmi please assign this to me under SSOC'23. I'm ready to contribute in all 4 languages

**Comment by Kumar-laxmi** [comment]
Assigned!
@Devchawla2608 : C, C++, Python and Java
