### ISSUE TITLE
Find S Algorithm in Python

### ISSUE THREAD

**Issue by Lakshita2** [Kumar-laxmi/Algorithms#1473]
**Is your feature request related to a problem? Please describe.**
 The find-S algorithm finds the most specific hypothesis that fits all the positive examples. 
The find-S algorithm starts with the most specific hypothesis and generalizes this hypothesis each time it fails to classify an observed positive training data. Hence, the Find-S algorithm moves from the most specific hypothesis to the most general hypothesis.

**Describe the solution you'd like**
Algorithm to solve this-
step1: Initialize h to most specific hypothesis in H i.e. h= h = {ϕ, ϕ, ϕ, ϕ, ϕ, ϕ}
step2: For each positive training example x 
            For each attribute constraint ai in h
                If constraint ai is satisfied by x
                      then do nothing
                Else
                      replace ai in h by next most general constraint that is satisfied by x

I can do this in python. Please assign it to me.

**Comment by Kumar-laxmi** [comment]
Since this is an intermediate level algorithm, could you choose one more language for implementation

**Comment by Lakshita2** [comment]
Yes I can also do this in C++

**Comment by Lakshita2** [comment]
This is my first PR. I will do this in C++ and Python. Please assign it to me.

**Comment by Lakshita2** [comment]
@Kumar-laxmi please assign it to me. I can do this in C++ and Python.

**Comment by Lakshita2** [comment]
@Kumar-laxmi Please assign it to me. This is my first issue.
