### ISSUE TITLE
Longest Common subsequence in python

### ISSUE THREAD

**Issue by SimranLahrani842** [Kumar-laxmi/Algorithms#1475]
**Is your feature request related to a problem? Please describe.**
I ll write in python as it is already given in Java,c,c++.
I ll write it by myself the entire program.
**Describe the solution you'd like**
LCS is used to find longest subsequence using dynamic programming.

**Comment by SimranLahrani842** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] I ll write in python as it is already given in Java,c,c++. I ll write it by myself the entire program. **Describe the solution you'd like** A clear and concise description of what you want to happen. LCS is used to find longest subsequence using dynamic programming.

Assign me this @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Assigned!
@SimranLahrani842 : Python
