### ISSUE TITLE
Playfair Cipher Implementation

### ISSUE THREAD

**Issue by tarunvyshnav777** [Kumar-laxmi/Algorithms#1477]
### Playfair Cipher

**Describe the solution you'd like**
I would like to implement it in all 4 languages. 

**Approach** 
1). Generate the key Square(5×5): The key square is a 5×5 grid of alphabets that acts as the key for encrypting the plaintext. Each of the 25 alphabets must be unique and one letter of the alphabet (usually J) is omitted from the table (as the table can hold only 25 alphabets). If the plaintext contains J, then it is replaced by I. 
The initial alphabets in the key square are the unique alphabets of the key in the order in which they appear followed by the remaining letters of the alphabet in order. 

2). Algorithm to encrypt the plain text: The plaintext is split into pairs of two letters (digraphs). If there is an odd number of letters, a Z is added to the last letter. 

**Additional context**
Playfair cipher is an encryption algorithm to encrypt or encode a message. It is the same as a traditional cipher. The only difference is that it encrypts a digraph (a pair of two letters) instead of a single letter.

![playfair-cipher-program-in-java7](https://github.com/Kumar-laxmi/Algorithms/assets/105963438/90252d8e-d869-4042-b9f7-7469dae16f70)

**Comment by tarunvyshnav777** [comment]
@Kumar-laxmi assign this to me under SSOC'23

**Comment by Kumar-laxmi** [comment]
Assigned!
@tarunvyshnav777 : C, C++, Python and Java

**Comment by Kumar-laxmi** [comment]
What is your status on this issue?

**Comment by tarunvyshnav777** [comment]
@Kumar-laxmi need one more day! Have others things to manage
