### ISSUE TITLE
Longest Remaining Time First [CPU Scheduling] in C, C++, Python and Java

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1478]
**Is your feature request related to a problem? Please describe.**
The longest remaining time first is a preemptive version of the longest job first scheduling algorithm. This scheduling algorithm is used by the operating system to program incoming processes for use in a systematic way. This algorithm schedules those processes first which have the longest processing time remaining for completion.

**Describe the solution you'd like**
```
- Get the list of processes along with their burst times.
- Set the current time to 0.
- Initialize an empty ready queue to hold the processes.
- While there are processes in the list or the ready queue is not empty:
   - Check if any processes have arrived at the current time. If yes, move them from the list to the ready queue.
   - If the ready queue is empty, increment the current time by 1.
   - If the ready queue is not empty:
      - Select the process with the longest remaining burst time from the ready queue.
      - Execute the process for a unit of time (preempting if necessary).
      - Update the current time by 1.
      - Reduce the burst time of the executed process by 1.
      - If the process has completed (burst time becomes 0), remove it from the ready queue and the list.
      - If the process has not completed, keep it in the ready queue and continue.
- Repeat steps 4a to 4c until all processes have been executed.
- Calculate the average waiting time and turnaround time based on the execution sequence.
```

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/de2926b4-c086-4be1-b320-ae3794e8da64)

**Comment by shanvijha30** [comment]
@Kumar-laxmi I would like to work on this issue. Could you please assign it to me under SSOC23.
Thank you!

**Comment by Kumar-laxmi** [comment]
Assigned!
@shanvijha30 : C, C++, Python and Java
