### ISSUE TITLE
Highest Response Ratio Next [CPU Scheduling] in C, C++, Python and Java

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1479]
**Is your feature request related to a problem? Please describe.**
Highest Response Ratio Next is a non-preemptive CPU Scheduling algorithm and it is considered as one of the most optimal scheduling algorithms. The name itself states that we need to find the response ratio of all available processes and select the one with the highest Response Ratio. A process once selected will run till completion. 

**Describe the solution you'd like**
```
- Get the list of processes along with their arrival times and burst times.
- Set the current time to 0.
- Initialize an empty ready queue to hold the processes.
- While there are processes in the list or the ready queue is not empty:
   - Check if any processes have arrived at the current time. If yes, move them from the list to the ready queue.
   - If the ready queue is empty, increment the current time by 1.
   - If the ready queue is not empty:
     - Calculate the response ratio for each process in the ready queue using the formula:
                      Response Ratio = (Waiting Time + Burst Time) / Burst Time
     - Select the process with the highest response ratio from the ready queue.
     - Execute the selected process for its entire burst time.
     - Update the waiting time for all other processes in the ready queue by adding the burst time of the executed process.
     - Update the current time by adding the burst time of the executed process.
     - Remove the executed process from the ready queue and the list.
- Repeat steps 4a to 4c until all processes have been executed.
- Calculate the average waiting time and turnaround time based on the execution sequence.
```

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/49fa6b50-a46b-4b81-a3c1-8a87ef6d57a2)

**Comment by shanvijha30** [comment]
@Kumar-laxmi I would like to work on this issue. Could you please assign it to me under SSOC 23.
Thank you!

**Comment by shanvijha30** [comment]
@Kumar-laxmi I would like to work on this issue as well.

**Comment by Ashutoshbind15** [comment]
@Kumar-laxmi would like to work on this issue as it'll be my first contribution in algorithms repo under the ssoc'23 program and I have also implemented similar algorithms in my OS classes. Thanks in advance!

**Comment by Kumar-laxmi** [comment]
Assigned!
@Ashutoshbind15 : C, C++, Python and Java

**Comment by shanvijha30** [comment]
@Kumar-laxmi I would like to work on this issue and create a PR. Could you please assign it to me as it seems to be inactive.
Thank you!

**Comment by Ashutoshbind15** [comment]
Completing it asap!
