### ISSUE TITLE
Dijkstra Algorithm 

### ISSUE THREAD

**Issue by Abhinavkar** [Kumar-laxmi/Algorithms#148]
**Is your feature request related to a problem? Please describe.**
Dijkstra Algorithm is one of the algorithm which asked in every interview or coding round of the jobs of SDE

**Describe the solution you'd like**
Will present a code with easy representation and using graphical ways 

**Additional context**
"Screenshots about the solution"

**Comment by Abhinavkar** [comment]
please assign me this @Kumar-laxmi

**Comment by samvid2020** [comment]
I would be happy to resolve this issue @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Please check the README.md regarding algorithms that have been contributed already
