### ISSUE TITLE
Binary Search Tree in Java and Python

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1480]
**Is your feature request related to a problem? Please describe.**
Binary Search Tree is a node-based binary tree data structure which has the following properties:
- The left subtree of a node contains only nodes with keys lesser than the node’s key.
- The right subtree of a node contains only nodes with keys greater than the node’s key.
- The left and right subtree each must also be a binary search tree.

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/4948c02e-631f-496f-a760-f9d53590b2ac)

**Comment by tarunvyshnav777** [comment]
@Kumar-laxmi I can do this!

**Comment by shanvijha30** [comment]
@Kumar-laxmi I would like to work on this issue could you please assign it to me.
Thank you!

**Comment by Shankhadweep** [comment]
@Kumar-laxmi I would like to work on this issue. Can you please assign it to me?

**Comment by Mrudula1205** [comment]
@Kumar-laxmi I would like to work on this issue. Please assign it to me under SSoC'23.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Shankhadweep : Java & Python

**Comment by AnuragSingh612** [comment]
@Kumar-laxmi Please assign to me as well.

**Comment by NupurHardiya** [comment]
Hello @Kumar-laxmi  
I would like to work on this issue could you please assign it to me under ssoc23.
Thank you!
