### ISSUE TITLE
Pancake sort

### ISSUE THREAD

**Issue by Abhinavcode13** [Kumar-laxmi/Algorithms#1482]
Pancake sort, also known as the "burnt pancake sort," is a sorting algorithm that aims to sort a list by continuously flipping adjacent elements. The name "pancake sort" comes from the analogy of sorting a stack of pancakes by flipping them with a spatula.

Here's an overview of how Pancake sort works:

1. Start with the unsorted list.
2. Identify the largest unsorted element in the list.
3. Flip the sublist from the beginning to the position of the largest element, thereby moving the largest element to the beginning of the list.
4. Flip the entire list, moving the largest element to the end of the list.
5. Repeat steps 2-4 with the remaining unsorted portion of the list (excluding the already sorted elements) until the entire list is sorted.

The main operation in Pancake sort is the flipping of the elements, which is done by reversing the order of elements in a sublist. The algorithm iteratively finds the largest unsorted element and brings it to the correct position by performing a sequence of flips.

Pancake sort has a worst-case time complexity of O(n^2), where n is the number of elements in the list. This is because for each element, it performs a sequence of flips that involves scanning the entire list. However, in practice, the algorithm is often faster than its worst-case time complexity suggests.

Pancake sort is primarily used as a teaching tool or for understanding the concept of sorting algorithms. It is not commonly used in practical scenarios due to its relatively high time complexity compared to more efficient sorting algorithms like merge sort or quicksort.

**Comment by Abhinavcode13** [comment]
@Kumar-laxmi please assign me this issue!!

**Comment by Kumar-laxmi** [comment]
refer #1299
