### ISSUE TITLE
Bogo sort

### ISSUE THREAD

**Issue by Abhinavcode13** [Kumar-laxmi/Algorithms#1483]
Bogo sort, also known as "stupid sort" or "random sort," is a highly inefficient and randomized sorting algorithm. It works by repeatedly shuffling the elements of a list randomly and checking if the list is sorted. If the list is not sorted, the process is repeated until the list happens to be sorted.

Here's an overview of how Bogo sort works:

1. Start with an unsorted list.
2. Shuffle the elements randomly to create a permutation of the list.
3. Check if the list is sorted.
4. If the list is sorted, the sorting process is complete. If not, go back to step 2 and repeat the shuffling process.
5. Repeat steps 2-4 until the list is sorted.

Bogo sort has an average-case and worst-case time complexity of O(n!), where n is the number of elements in the list. This means that the algorithm tries all possible permutations of the list, which grows exponentially as the number of elements increases. As a result, Bogo sort is highly inefficient and impractical for sorting large lists.

Due to its random nature, Bogo sort can take an extremely long time to complete, and there is no guarantee of its termination. It is primarily used as an example of an inefficient algorithm and is not suitable for practical sorting applications.

While Bogo sort is not a viable sorting algorithm in practice, it can be an interesting concept to explore and discuss when studying sorting algorithms and their efficiency.

**Comment by Abhinavcode13** [comment]
Please assign this issue to me @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
refer #1332
