### ISSUE TITLE
There is no go to top button in readme

### ISSUE THREAD

**Issue by ranjanmangla1** [Kumar-laxmi/Algorithms#1485]
**Is your feature request related to a problem? Please describe.**
Read me of this repo has become huge is gonna become big, so go back to top button is required at the bottom of readme

**Describe the solution you'd like**
i will add it. please assign this issue to me

**Comment by ranjanmangla1** [comment]
a button in the readme, when clicked on will take us to top of the read me, will add a demo soon if you want.

**Comment by Kumar-laxmi** [comment]
I think such feature is not required as of now
