### ISSUE TITLE
Sha-224 & Blake-2 Cryptographic hashing function

### ISSUE THREAD

**Issue by MANURAJ7** [Kumar-laxmi/Algorithms#1488]
Is your feature request related to a problem ?

--> I saw the Cryptography file and the hashing functions present in there. I would like to add some of the famous and fundamental hashing functions which I know about. These are Blake - 2 and SHA - 224.

Describe the solution you'd like

-->SHA - 224 is a hashing function its part of SHA - 2 family, widely used in security protocols such as SSL / TLS .
Blake-2 is a cryptographic hash function designed to be fast and secure. It is an improvement over the popular SHA - 3 algorithm.
I would be writing code for both the hashing functions in C++ while explaining every detail of the code. I'll also give brief intro about the algorithms and the process of hashing they use.
For implementing hashing functions I'll use "Openssl" library which will provide hashing function for SHA-224 and "Sodium" library for Blake-2 function.

**Comment by Kumar-laxmi** [comment]
So basically you want to implement two separate algorithms in one issue

**Comment by MANURAJ7** [comment]
Hy @Kumar-laxmi for your concern I will make a new branch where I can add these changes seperately in different commits.
Thank you.

**Comment by Kumar-laxmi** [comment]
Better close this issue and raise two separate issues for these two algos separately, it will be easy to score
