### ISSUE TITLE
Add Multi-source Shortest Path "MSSP" algorithm for undirected graphs in all C,C++ and Java

### ISSUE THREAD

**Issue by Ashutoshbind15** [Kumar-laxmi/Algorithms#1490]
**Describe the solution you'd like**
Would like to add Multi-source Shortest Path for undirected graphs algorithm in C,C++ and Java

**Approach**
Contain a queue having multiple start nodes for a bfs and keep finding greedily the shortest path to other nodes:
It will essentially be equal to the current level(of bfs) for any unexplored node else it'll also be colored, i.e. act as a source in the next level search

**Additional context**
The time complexity of this approach is : O(V+E) -> the same as that of a BFS algorithm.
The space complexity will be O(V) -> a queue to store the vertices of the level and a visited array.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Ashutoshbind15 : C, C++, Java & Python
