### ISSUE TITLE
Buddy memory allocation Algorithm Implementation in Java, C++, C and Python

### ISSUE THREAD

**Issue by ranjanmangla1** [Kumar-laxmi/Algorithms#1491]
**Is your feature request related to a problem? Please describe.**
The repo does not contain Buddy System Memory Allocation Algorithm, i want to work on this issue, kindly assign me this issue 

**Describe the solution you'd like**
I would add an implementation of the algorithm in C, C++, Java & Python.

**Comment by Kumar-laxmi** [comment]
Assigned!
@ranjanmangla1 : C, C++, Python and Java
