### ISSUE TITLE
First Fit Memory Allocation Algorithm in C, C++, Java & Python

### ISSUE THREAD

**Issue by ranjanmangla1** [Kumar-laxmi/Algorithms#1494]
Is your feature request related to a problem? Please describe.
Memory allocation techniques are an important part of the operating systems. FIrst fit is one of them. In worst fit memory allocation, each new request is allocated the first suitable block of memory found on traversing

Describe the solution you'd like
I would add C, C++, Java & Python Implementation of the algorithm

**Comment by Kumar-laxmi** [comment]
Assigned!
@ranjanmangla1 : C, C++, Python and Java
