### ISSUE TITLE
Next Fit Memory Allocation Algorithm in C, C++, Java & Python 

### ISSUE THREAD

**Issue by ranjanmangla1** [Kumar-laxmi/Algorithms#1495]
**Is your feature request related to a problem? Please describe.**
Memory allocation techniques are an important part of the operating systems. Next fit is one of them. It is just a modified version of first fit, where you are allocating the first suitable block of memory, but for next request, you start from the block that was previously alloted.

**Describe the solution you'd like**
I would add C, C++, Java & Python Implementation of the algorithm

Please assign me this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@ranjanmangla1 : C, C++, Python and Java
