### ISSUE TITLE
Adding folder for bit manipulation problems 

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [Kumar-laxmi/Algorithms#1496]
I would like to contribute to this repository by adding a new folder called "bit manipulation." This folder will contain various problems related to bit manipulation, including Sudoku and Josephus and many more

I believe that these problems can provide valuable learning opportunities for users interested in understanding and practicing bit manipulation techniques.

Please consider reviewing and merging this contribution under SSOC to enhance the repository's content and provide users with additional educational resources.

**Comment by Kumar-laxmi** [comment]
There is already a folder named ```Binary``` for that
