### ISSUE TITLE
Dinning Philosophers Problem 

### ISSUE THREAD

**Issue by Abhinavkar** [Kumar-laxmi/Algorithms#150]
**Is your feature request related to a problem? Please describe.**
A operating system problem in which philosopher spend time alternating thinking & eating  to solve deadlock issue

**Describe the solution you'd like**
i would like to propose a detailed solution regarding dining-philosophers problem 

**Describe alternatives you've considered**
i can also explain algo in presentation form 

**Additional context**
Details solution in form of png will be provided

**Comment by Abhinavkar** [comment]
@Kumar-laxmi assign me with this

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi assign me with this

Please mention the language you would like to work on

**Comment by Kumar-laxmi** [comment]
Assigned!
@Abhinavkar : C
