### ISSUE TITLE
BFS in python as it is not done

### ISSUE THREAD

**Issue by SimranLahrani842** [Kumar-laxmi/Algorithms#1502]
**Is your feature request related to a problem? Please describe.**
how bfs works and code written in python by myself will be explained.
Simple implementation in python.

**Describe the solution you'd like**
Bfs is breadth first search algorithm which always finds an optimal solution but takes time.

**Comment by SimranLahrani842** [comment]
@Kumar-laxmi assign me this

**Comment by Kumar-laxmi** [comment]
as of now do now work on BFS or DFS since there are minor confusion around it
