### ISSUE TITLE
[FR]: Add `RUNLENGTH Algorithm` for data compression in Java

### ISSUE THREAD

**Issue by imranaai** [Kumar-laxmi/Algorithms#1506]
**Is your feature request related to a problem? Please describe.**
Add some more algorithms for data compression in Java.

**Describe the solution you'd like**
`Run length compression` or `Run Length Encoding(RLE)` works by reducing the physical size of a repeating string of characters. This repeating string is called ‘run’ and the size is called ‘length’. This type of compression is mainly used for file formats such as `TIFF`, `BMP`, and `PCX`.

**Describe alternatives you've considered**
N/A

**Additional context**
Appreciate your contributions.

**Comment by Kumar-laxmi** [comment]
This is an easy algorithm so kindly implement it in all four languages

Assigned!
@imranaai : C, C++, Python and Java

**Comment by udc29h** [comment]
Could you please assign this to me

**Comment by imranaai** [comment]
I am working on it, it's likely to be completed by tomorrow.
