### ISSUE TITLE
Bankers Algorithm

### ISSUE THREAD

**Issue by Sachittarway** [Kumar-laxmi/Algorithms#151]
**Is your feature request related to a problem? Please describe.**
Bankers algorithm is one of the important algorithm in Operating systems which decides which task is to be executed first in os level. Also it is one of the most common problem asked in interviews

**Describe the solution you'd like**
I will code in c language where multiple request will be made by user and which request will be considered on prior basis will be decided by the algorithm and that same model is followed in os level.

**Describe alternatives you've considered**
I have considered a user input values which is the same model which is performed in os level for application

**Additional context**
I will provide the screenshots of the outputs and a detail explaination of it .Also I will provide code on resource request algorithm code which is one of the important part of bankers algorithm.

Please assign me this task @Kumar-laxmi

**Comment by samvid2020** [comment]
Can you assign this to me? @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
@samvid2020 @Sachittarway Please mention the language you would like to work on

**Comment by mvpamansingh** [comment]
@Kumar-laxmi I am ready to work on this issue, can you please assign this to me in c ++

**Comment by Sachittarway** [comment]
> @samvid2020 @Sachittarway Please mention the language you would like to work on

@Kumar-laxmi I will code in c language. Please assign me the task.

**Comment by samvid2020** [comment]
I am ready to work on java @Kumar-laxmi

**Comment by mvpamansingh** [comment]
@Kumar-laxmi where I have to create file for Banker's Algorithm in C++? in which folder?

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi where I have to create file for Banker's Algorithm in C++? in which folder?

Deadlock Avoidance

**Comment by stiwari-ds** [comment]
@Kumar-laxmi Please assign it to me for Python.

**Comment by zugzwang03** [comment]
Assigned!
@stiwari-ds : Python

**Comment by Kumar-laxmi** [comment]
@Sachittarway @samvid2020 What is your status on this issue?

**Comment by Sachittarway** [comment]
> @Sachittarway @samvid2020 What is your status on this issue?

Ya will be doing it. Actually my exams are going on and my last exam is on 20th jan. 
And i was also working in different issues in the algorithm part only. 
Will soon commit .

**Comment by samvid2020** [comment]
@Kumar-laxmi yup going to address this issue max by tomorrow morning!

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi yup going to address this issue max by tomorrow morning!

Status?

**Comment by 072arushi** [comment]
@Dharnish38 assigned
