### ISSUE TITLE
Ford-Fulkerson Algorithm

### ISSUE THREAD

**Issue by Devchawla2608** [Kumar-laxmi/Algorithms#1510]
**Is your feature request related to a problem? Please describe.**
  Ford-Fulkerson is a graph algorithm used to find the maximum flow in a flow network. It iteratively finds augmenting paths from the source to the sink and updates the flow along those paths until no more augmenting paths exist.

**Describe the solution you'd like**
1.) Start with an initial flow of 0.
2.) While there is a path from the source to the sink in the residual graph:
3.) Find an augmenting path in the residual graph. An augmenting path is a path from the source to the sink such that all edges in the path have residual capacity greater than 0.
4.) Determine the minimum residual capacity along the augmenting path. This is the maximum amount of flow that can be added to the current flow.
5.) Augment the flow along the augmenting path by the minimum residual capacity.
6.) Update the residual capacities of the edges in the augmenting path.
Return the maximum flow.

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/92145696/6a2dc2e5-c703-4f6c-9d53-af7bcf7ccbbd)

**Comment by Devchawla2608** [comment]
@Kumar-laxmi  please assign this to me under SSOC'23. I'm ready to contribute in all 4 languages

**Comment by Kumar-laxmi** [comment]
Assigned!
@Devchawla2608 : C & Java

**Comment by udc29h** [comment]
Please assign this to me under SSOC'23. I can easily implement it in all the languages.
