### ISSUE TITLE
Stoer-Wagner algorithm

### ISSUE THREAD

**Issue by Devchawla2608** [Kumar-laxmi/Algorithms#1511]
**Is your feature request related to a problem? Please describe.**
The Stoer-Wagner algorithm is an algorithm for finding the minimum cut in an undirected graph. The minimum cut in a graph is the cut with the smallest total weight or capacity, representing the minimum amount of flow that needs to be removed to disconnect the graph.

**Describe the solution you'd like**
1.) Start with the original graph.
2.) Initialize an empty set S to keep track of the vertices in the cut and an empty cut weight W.
3.) While there are more than 1 vertex in the graph:
4.) Choose an arbitrary vertex v not yet in S.
5.) Add v to S.
6.) Compute the minimum cut between S and the remaining vertices using a modified version of the Max Flow algorithm (such as the Ford-Fulkerson algorithm).
7.) Update W to be the maximum of the current W and the cut weight obtained from the minimum cut.
8.) Return the final cut weight W.

 

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/92145696/76cece45-3d70-480a-a80b-ea915fecf23c)

**Comment by Devchawla2608** [comment]
@Kumar-laxmi  please assign this to me under SSOC'23. I'm ready to contribute in all 4 languages

**Comment by Kumar-laxmi** [comment]
Assigned!
@Devchawla2608 : C, C++, Java & Python

**Comment by udc29h** [comment]
Please assign this to me  SSOC'23. I'm ready to contribute in all the languages .
