### ISSUE TITLE
SHA-224 Cryptographic Hashing Function

### ISSUE THREAD

**Issue by MANURAJ7** [Kumar-laxmi/Algorithms#1512]
*Is your feature request related to a problem ?

--> I saw the Cryptography file and the hashing functions present in there. I would like to add SHA - 224 hashing function in there.

*Describe the solution you'd like :-
-->I would be writing code for the hashing functions in C++ while explaining every detail of the code. I'll also give brief intro about the algorithm and the process of hashing it uses.
For implementing hashing function I'll use "Openssl" library which will provide hashing function for SHA-224 .

**Comment by Kumar-laxmi** [comment]
Could you implement this in all four languages since it is an easy issue?

**Comment by MANURAJ7** [comment]
Sure I'll implement it in all the given languages.
Please assign me the issue.
