### ISSUE TITLE
Blake-2 Hashing Function

### ISSUE THREAD

**Issue by MANURAJ7** [Kumar-laxmi/Algorithms#1513]
*Is your feature request related to a problem ?

--> I saw the Cryptography file and the hashing functions present in there. I would like to add Blake-2 hashing function in there.

*Describe the solution you'd like :-
-->I would be writing code for the hashing functions in C++ while explaining every detail of the code. I'll also give brief intro about the algorithm and the process of hashing it uses.
For implementing hashing function I'll use "Sodium" library which will provide hashing function for Blake-2 .

**Comment by Kumar-laxmi** [comment]
Can you implement this without library (using pure logic)
