### ISSUE TITLE
MD5 algorithm in Python 

### ISSUE THREAD

**Issue by SimranLahrani842** [Kumar-laxmi/Algorithms#1517]
**Is your feature request related to a problem? Please describe.**
MD5 or message digest algorithm will produce a 128-bit hash value. There are a couple of security issues with the md5 algorithm that is why we mainly used it to check data integrity.

**Describe the solution you'd like**
The Python standard library includes a module called hashlib, which contains most of the popular hashing algorithms. Most of the algorithms are implemented inside hashlib module.

**Comment by Kumar-laxmi** [comment]
Can you implement this without library (purely on logic)
