### ISSUE TITLE
Adding of Russian Peasant Algorithm 

### ISSUE THREAD

**Issue by Aarsh30** [Kumar-laxmi/Algorithms#1519]
The "Russian peasant algorithm" is a traditional method for performing multiplication that dates back to ancient times. It is also known as the "Russian peasant multiplication" or the "Egyptian multiplication" algorithm.

Here's how it works:

Start with two numbers, the multiplicand (the number you want to multiply) and the multiplier (the number by which you want to multiply).

Create two columns. In the left column, write down the multiplicand. In the right column, write down the multiplier.

Divide the number in the left column by 2 (ignore any remainder), and double the number in the right column. Continue this process until the number in the left column becomes 1.

Cross out any row where the number in the left column is even.

Add up all the numbers in the right column that are not crossed out. The sum of these numbers is the result of the multiplication.

I would be implementing this algo in 4 language so @Kumar-laxmi can you please assigned me.

Thank you

**Comment by Kumar-laxmi** [comment]
Assigned!
@Aarsh30 : C, C++, Python and Java

**Comment by keenpaul29** [comment]
@Kumar-laxmi @Aarsh30 I have already added the C++ code in my #1560 pull request.
Please see to it and reply.

**Comment by Aarsh30** [comment]
@keenpaul29  with out getting assigned of the issues why you are made pr 

there is one procedure of open source to be followed that create or look at issues message in it and get assign to you and then start working on what you have been assigned and once your work has been done make it pr and connect it with the issues what you had got it  and the reviewers would review your work and get it merge in the repo
