### ISSUE TITLE
Breadth First Search (BFS) in C, C++, Java and Python

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1526]
**Is your feature request related to a problem? Please describe.**
The Breadth First Search (BFS) algorithm is used to search a graph data structure for a node that meets a set of criteria. It starts at the root of the graph and visits all nodes at the current depth level before moving on to the nodes at the next depth level.

**Describe the solution you'd like**
Starting from the root, all the nodes at a particular level are visited first and then the nodes of the next level are traversed till all the nodes are visited.

To do this a queue is used. All the adjacent unvisited nodes of the current level are pushed into the queue and the nodes of the current level are marked visited and popped from the queue.

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/abe687f9-d793-47bf-a897-6f656759e0c5)

**Comment by OMKAR-KALEPU** [comment]
Please assign me

**Comment by mandliyarajendra11** [comment]
i want to work on this issue

**Comment by harshitaaa8** [comment]
i want to work on this issue

**Comment by trisharaj06** [comment]
Could you assign this to me

**Comment by Inferno2211** [comment]
Hi please assign me this issue under SSOC'23.
This will be my first contribution in this repo

**Comment by Vidip-Ghosh** [comment]
I would like to work on this issue. Can you please assign this to me under SSOC 2.0?

**Comment by marshadkhn** [comment]
Hey @Kumar-laxmi
I would like to work on this issue as I am doing open-source and data structure and algorithm since 5month
I can write this code in all the languages you mentioned with the optimized code and I have my new approach too

My branch name will be - marshadkhn
Assign me this @Kumar-laxmi

**Comment by ranjanmangla1** [comment]
@Kumar-laxmi Can you assign me this issue?

**Comment by Kumar-laxmi** [comment]
Assigned!
@OMKAR-KALEPU : C, C++, Python and Java

**Comment by Raksha703** [comment]
Hey, I am SSOC'23 contributor and would like to contribute to this issue. Please assign this issue to me!!
