### ISSUE TITLE
[FR]: Add the LZW algorithm in all Languages.

### ISSUE THREAD

**Issue by imranaai** [Kumar-laxmi/Algorithms#1533]
**Is your feature request related to a problem? Please describe.**
Adding more algorithms to the data compression section.

**Describe the solution you'd like**
The LZW algorithm stands for Lempel-Ziv-Welch. These three were the inventors of these algorithms. It is a compression algorithm that compresses a file into a smaller one using a table-based lookup. This algorithm is mainly used to compress GIF files and optionally to compress and PDF and TIFF files. The files compressed using this algorithm are saved with .lzw extension.

**Describe alternatives you've considered**
N/A

**Additional context**
All the contributions are appreciated.

**Comment by Kumar-laxmi** [comment]
Assigned!
@imranaai : C, C++, Python and Java

**Comment by imranaai** [comment]
> are you working on this issue. otherwise assign it to me.
> 

Yes
