### ISSUE TITLE
To find Bridges in a Graph using Tarjan's Algorithm

### ISSUE THREAD

**Issue by viveksingh912** [Kumar-laxmi/Algorithms#1535]
**Is your feature request related to a problem? Please describe.**
An edge in an undirected graph is said to be a bridge, if and only if by removing it, disconnects the graph, or make different components of the graph. 

**Describe the solution you'd like**
We'll perform DFS with a slight change . 
Suppose their are two nodes U and V, then this edge is said to be a bridge if it's  not possible to reach before U through V.
For this purpose I'll be maintaining arrays visited[],low[],and curr[] , where visited[] represents where whether a node is already visited or not  , low[] represents the minimum steps to reach to a node and curr[] represents actual steps to reach to a node.

**Comment by viveksingh912** [comment]
@Kumar-laxmi  Could you  please assign me this issue under SSOC23 ?

**Comment by Kumar-laxmi** [comment]
Sorry this algo has been implemented in all four languages
