### ISSUE TITLE
 [SSOC'23] Kaprekar Number Calculation 

### ISSUE THREAD

**Issue by pra9patil** [Kumar-laxmi/Algorithms#1541]
## Kaprekar Number Calculation

 * This code calculates the Kaprekar number, a special number that is obtained
 * by taking a non-negative integer, arranging its digits in ascending and
 * descending order, subtracting the smaller number from the larger number,
 * and repeating this process until the resulting number becomes zero or
 * reaches a constant value known as the Kaprekar constant.
 *
 * Supported languages: C, C++, Java, Python
 * 
 * Language-specific Implementations:
 * - C: kaprekar_number.c
 * - C++: kaprekar_number.cpp
 * - Java: KaprekarNumber.java
 * - Python: kaprekar_number.py
 * 
 * For more information about Kaprekar
 ```https://en.wikipedia.org/wiki/Kaprekar_number```

##  Example

```  Num = 45 ;
     Num^2=2025
     45=20+25 
```

**Comment by pra9patil** [comment]
@Kumar-laxmi will you please assign me this issue , I complete it today itself

**Comment by Kumar-laxmi** [comment]
Assigned!
@pra9patil : C, C++, Python and Java

**Comment by pra9patil** [comment]
@Kumar-laxmi Thanks sir
