### ISSUE TITLE
M Coloring Algorithm in C, C++, PYTHON, JAVA

### ISSUE THREAD

**Issue by anand-harsh** [Kumar-laxmi/Algorithms#1557]
Reopen #1192 

**Is your feature request related to a problem? Please describe.**
This algorithm is used to determine if the undirected graph can be colored with at most m colors such that no two adjacent vertices of the graph are colored with the same color.

**Comment by anand-harsh** [comment]
@Kumar-laxmi please assign me this issue

**Comment by Kumar-laxmi** [comment]
assigned!
@anand-harsh : C, C++, Python and Java
