### ISSUE TITLE
Kaprekar Number in C , C++, Python, JAVA

### ISSUE THREAD

**Issue by anand-harsh** [Kumar-laxmi/Algorithms#1559]
Reopen #1541 

**Is your feature request related to a problem? Please describe.**
Kaprekar Number Calculation
This code calculates the Kaprekar number, a special number that is obtained
by taking a non-negative integer, arranging its digits in ascending and
descending order, subtracting the smaller number from the larger number,
and repeating this process until the resulting number becomes zero or
reaches a constant value known as the Kaprekar constant.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anand-harsh** [comment]
@Kumar-laxmi please assign me this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@anand-harsh : C, C++, Python and Java

**Comment by anand-harsh** [comment]
> @Kumar-laxmi please assign me this issue

but its already assigned to me

**Comment by Kumar-laxmi** [comment]
@anand-harsh status on this issue?

**Comment by anand-harsh** [comment]
> @anand-harsh status on this issue?

I will make PR by tonight.
