### ISSUE TITLE
[SSOC'23] Implementation/Usage of PyCaret Regression Module(Library) for Machine Learning - Python

### ISSUE THREAD

**Issue by manishkumar00208** [Kumar-laxmi/Algorithms#1566]
PyCaret is an open-source, low-code machine learning library in Python that automates machine learning workflows. It is an end-to-end machine learning and model management tool that speeds up the experiment cycle exponentially and makes you more productive.
The PyCaret’s regression module has over 25 algorithms and 10 plots to analyze the performance of models. Be it hyper-parameter tuning, ensembling, or advanced techniques like stacking, PyCaret’s regression module has it all.
Here's the sample screenshot of usage of the models comparison:
![Models_compare](https://github.com/Kumar-laxmi/Algorithms/assets/76589863/796c6318-9433-46ec-bc8e-63bb9275577d)

**Comment by manishkumar00208** [comment]
@Kumar-laxmi @072arushi

**Comment by Kumar-laxmi** [comment]
So you just want to some library functions?

This repo is for algorithms implemented without any library function

**Comment by manishkumar00208** [comment]
But by using pycaret library, people can choose what algorithm to choose
and that algo can be directly implemented using pycaret....!!
