### ISSUE TITLE
NthRoot using Binary Search

### ISSUE THREAD

**Issue by ak-sh-at** [Kumar-laxmi/Algorithms#1567]
**Is your feature request related to a problem? Please describe.**
Finding Nth root of any positive integer.

**Describe the solution you'd like**
The problem can be solved using Binary Search as the problem has a monotonically increasing function.

**Describe alternatives you've considered**
Implementation of Binary Search

**Additional context**

Required inputs:
N-denotes the Nth root.
X-denotes the number of which nth root has to be calculated.

Required Output:
Return the Nth root correct upto five decimal places.

Example:
input: 
4  125
output:
3.34370

**Comment by ak-sh-at** [comment]
@Kumar-laxmi Please assign this issue to me under SSOC 2.0

**Comment by Kumar-laxmi** [comment]
Assigned!
@ak-sh-at : C, C++, Python and Java
