### ISSUE TITLE
Add Kosaraju algorithm in C,Java and Python

### ISSUE THREAD

**Issue by Ikshvaku24** [Kumar-laxmi/Algorithms#1568]
Kosaraju's algorithm is a popular algorithm used to find all strongly connected components in a directed graph. A strongly connected component is a subgraph in which there is a directed path between every pair of vertices.
I want to add this algorithm in C, Java and Python.
Please assign this issue under SSOC'23.

**Comment by Kumar-laxmi** [comment]
refer #1456
