### ISSUE TITLE
[SSOC'23] Random Forest Algorithm in python - Machine Learning

### ISSUE THREAD

**Issue by manishkumar00208** [Kumar-laxmi/Algorithms#1570]
**Is your feature request related to a problem? Please describe.**
There's no algorithm for Random Forest in Machine Learning Directory using python.

**Describe the solution you'd like**
Implemented Random Forest Algorithm in Python from Scratch.

**Comment by manishkumar00208** [comment]
@Kumar-laxmi Please Assign me with this issue!

**Comment by Kumar-laxmi** [comment]
Assigned!
@manishkumar00208 : Python
