### ISSUE TITLE
Lasso Regression - Machine Learning Algorithm in Python

### ISSUE THREAD

**Issue by brahmamyv** [Kumar-laxmi/Algorithms#1575]
**Is your feature request related to a problem? Please describe.**
Yes. There is no Lasso regression implementation . And I want to do it from scratch in python.

**Describe the solution you'd like**
Lasso regression, also known as L1 regularization, is a linear regression technique that adds a penalty term to the cost function in order to shrink or eliminate the coefficients of less important features. 

**Additional context**

![image](https://github.com/Kumar-laxmi/Algorithms/assets/130195097/134f42f5-7184-485b-9307-0bf26c1f79f7)

**Comment by brahmamyv** [comment]
@Kumar-laxmi Please assign me this lasso regression algorithm

**Comment by Kumar-laxmi** [comment]
Assigned!
@brahmamyv : Python and Java 

Kindly do not use any ML Library
