### ISSUE TITLE
Add Cycle Detection & deleting a node in linkedlist

### ISSUE THREAD

**Issue by prashanth772** [Kumar-laxmi/Algorithms#1577]
Wanted to add cycle detection and Deleting a node in linkedList (java)  section

**Comment by jahnvisahni31** [comment]
Hey, I am SSOC'23 contributor and would like to contribute to this issue. Please assign this issue to me!!

**Comment by prashanth772** [comment]
@jahnvisahni31 I see you spamming comments and asking issues from everyone, instead find an issue and raise it.

**Comment by jahnvisahni31** [comment]
I Can do this issue as i am know how to add cycle detection in linkedlist

**Comment by prashanth772** [comment]
Then raise an issue, instead commenting and asking someone's issues.

**Comment by prashanth772** [comment]
Assign me this @Kumar-laxmi

**Comment by prashanth772** [comment]
I'm a GSSOC contributor and would like to contribute to this, I will write code in all 3 languages, please assign me this issue @Kumar-laxmi

**Comment by chhavisharma30** [comment]
I can do this. Kindly assign me this issue.

**Comment by shivangi2002** [comment]
@Kumar-laxmi  please assign me with this issue.
