### ISSUE TITLE
Interquartile Range (IQR)

### ISSUE THREAD

**Issue by pra9patil** [Kumar-laxmi/Algorithms#1580]
**Is your feature request related to a problem? Please describe.**
The interquartile range defines the difference between the third and the first quartile. Quartiles are the partitioned values that divide the whole series into 4 equal parts. So, there are 3 quartiles. First Quartile is denoted by Q1 known as the lower quartile, the second Quartile is denoted by Q2 and the third Quartile is denoted by Q3 known as the upper quartile. Therefore, the interquartile range is equal to the upper quartile minus lower quartile.

**Describe the solution you'd like**
Interquartile range IQR tells us the range 
where the bulk of the values lie. The interquartile 
range is calculated by subtracting the first quartile
from the third quartile. 
IQR = Q3 - Q1

**Additional context**
For more understanding refer below example
``` Input :   1 , 2 , 3, 4 , 5 , 6 ,7 , 8 ,9 10 , 11 ```
 ``` output:  3 ```

Explain : As first we have to calculate Q2 which is median of the series so 
     Q2 = 6 

   Now , we have to calculate Q1 basically Q1 is median of series which start from first element of series till the Q2 
    In our example Q1 = 3
   and , Q3 is median of range start after Q2 to till the last element of series 
   In our case Q3 = 9 
   and therefor the IQR for our series is 3

**Comment by pra9patil** [comment]
@Kumar-laxmi sir will you please assign me this issue please.

**Comment by Kumar-laxmi** [comment]
Assigned!
@pra9patil : C, C++, Python and Java

**Comment by pra9patil** [comment]
@Kumar-laxmi Thank you sir 
I will code it and make PR before 9 PM
