### ISSUE TITLE
implementation of queues using stack in C++, Java and python

### ISSUE THREAD

**Issue by pratham-srivastava-07** [Kumar-laxmi/Algorithms#1581]
this is an issue under SSOC'23 to implement queues using stack in respective programming languages

**Comment by Craniace** [comment]
@Kumar-laxmi please assign me this in all languages.

**Comment by chhavisharma30** [comment]
I can solve this issue. Kindly assign this to me.

**Comment by shivangi2002** [comment]
@Kumar-laxmi  it would be my first issue. I would be really happy to solve this issue.
