### ISSUE TITLE
Array to BST

### ISSUE THREAD

**Issue by noobcoder007-exe** [Kumar-laxmi/Algorithms#1582]
Given a sorted array. Write a function that creates a Balanced Binary Search Tree using array elements.
This is an issue under SSOC'23
please assign this to me..

**Comment by jahnvisahni31** [comment]
Hey, I am SSOC'23 contributor and would like to contribute to this issue. Please assign this issue to me!!

g

**Comment by pratyushsahu0308** [comment]
Hey, I am SSOC'23 contributer and want to work on this issue using c++ or java. Kindly assign it to me.

**Comment by Kumar-laxmi** [comment]
This program is already there
