### ISSUE TITLE
Job Scheduling Algorithms

### ISSUE THREAD

**Issue by Rohith1816** [Kumar-laxmi/Algorithms#1583]
**Job Scheduling Algorithms in C++,Python,C,Java**
Job Schedulings Algorithms FCFS,SJF,Robin Round

**Solution Description**
A Clear implementation of FCFS,SJF,Robin Round Algorithms in all the languauges 

Please assign issue to me I Promise you that I will accomplish my task in a perfect way and I haven't started my Contribution in SSOC yet.

**Comment by jahnvisahni31** [comment]
Hey, I am SSOC'23 contributor and would like to contribute to this issue. Please assign this issue to me!!

**Comment by Kumar-laxmi** [comment]
These algo's issues are already open
