### ISSUE TITLE
Add Quickhull Algorithm in C,C++,Java and Python

### ISSUE THREAD

**Issue by Ikshvaku24** [Kumar-laxmi/Algorithms#1584]
Quickhull is a convex hull algorithm that is used to find the convex hull of a set of points in a two-dimensional space. The convex hull of a set of points is the smallest convex polygon that encloses all the points.
This algorithm recursively divides the points into two sets, one above and one below an edge. It then finds the points farthest from the edge on each side and uses them to create new edges. This process continues until no more points are left inside the hull.
Time Complexity: O(n log n) in the average case, O(n^2) in the worst case.
Please assign this issue under SSOC'23

**Comment by jahnvisahni31** [comment]
Hey, I am SSOC'23 contributor and would like to contribute to this issue. Please assign this issue to me!!

**Comment by Kumar-laxmi** [comment]
Assigned!
@Ikshvaku24 : C, C++, Python and Java
