### ISSUE TITLE
Pancake sort in C, C++, Java and Python

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1589]
**Is your feature request related to a problem? Please describe.**
Given an unsorted array, the task is to sort the given array. You are allowed to do only following operation on array. 
- flip(arr, i): Reverse array from 0 to i 

**Describe the solution you'd like**
__Approach__: Unlike a traditional sorting algorithm, which attempts to sort with the fewest comparisons possible, the goal is to sort the sequence in as few reversals as possible.

Following are the detailed steps. Let given array be arr[] and size of array be n. 
- Start from current size equal to n and reduce current size by one while it’s greater than 1. Let the current size be curr_size. 
- Do following for every curr_size
   - Find index of the maximum element in arr[0 to curr_szie-1]. Let the index be ‘mi’
   - Call flip(arr, mi)
   - Call flip(arr, curr_size – 1) 

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/d0750334-8d94-41dd-82f0-20fe7e2ad3e9)

**Comment by firoz3130** [comment]
Can I get this issue  assigned on me?

**Comment by Pranjal-Kri** [comment]
@Kumar-laxmi  can you assign this issue to me.

**Comment by Kumar-laxmi** [comment]
Assigned!
@firoz3130 : C, C++, Python and Java
