### ISSUE TITLE
Scanline Algorithm in java,c

### ISSUE THREAD

**Issue by jahnvisahni31** [Kumar-laxmi/Algorithms#1591]
The Scanline Algorithm efficiently fills polygons with arbitrary shapes, including convex and concave polygons. It avoids the need for complex calculations or explicit boundary tracking and works well for relatively simple 2D shapes. However, it may encounter challenges with overlapping or self-intersecting polygons, which require additional techniques for handling those cases.
** We want a code with commented quotes and also that is easily understandable by the beginner**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/121384173/7d74eeb3-0d52-4308-9542-02f419f33387)

**Comment by Pranjal-Kri** [comment]
@Kumar-laxmi can you assign this to me. I can write code for this algorithm in java , c and python.

**Comment by Kumar-laxmi** [comment]
Assigned!
@jahnvisahni31 : C & Java

**Comment by jahnvisahni31** [comment]
![image](https://github.com/Kumar-laxmi/Algorithms/assets/121384173/bd871e99-6768-4e22-b927-62e935e48098)
![image](https://github.com/Kumar-laxmi/Algorithms/assets/121384173/a5ca171d-8b3b-48e8-84aa-94ff791d50fc)
java
![image](https://github.com/Kumar-laxmi/Algorithms/assets/121384173/63bd557b-c0ec-4a20-a96e-115404d92d02)
![image](https://github.com/Kumar-laxmi/Algorithms/assets/121384173/30d0abc5-0255-4be1-ae15-0c11ad8e8495)

**Comment by jahnvisahni31** [comment]
c++
Done this issue

**Comment by jahnvisahni31** [comment]
@Kumar-laxmi  please check
