### ISSUE TITLE
LCS for 3 strings

### ISSUE THREAD

**Issue by AK3847** [Kumar-laxmi/Algorithms#1604]
**Is your feature request related to a problem? Please describe.**
I would like to contribute the Dynamic Approach to find the length of longest common Sub-Sequence in 3 Strings

**Describe the solution you'd like**
I will implement this algorithm in all 4 languages as required.

**Describe alternatives you've considered**

**Additional context**
@Kumar-laxmi  please assign me this issue under SSOC'23.

**Comment by Kumar-laxmi** [comment]
I think there is already an issue on LCS
