### ISSUE TITLE
Smith Waterman Algorithm

### ISSUE THREAD

**Issue by Mayureshd-18** [Kumar-laxmi/Algorithms#1605]
The Smith-Waterman algorithm is a dynamic programming algorithm used to perform sequence alignment, particularly in bioinformatics. It is an improvement over the Needleman-Wunsch algorithm, as it allows for local sequence alignments and can handle sequences with different lengths.

The algorithm takes two sequences as input and calculates a score that represents their similarity or dissimilarity.

![image](https://github.com/Kumar-laxmi/Algorithms/assets/98738585/7364e622-2bfc-4934-ba2c-25053cbab53b)

Step1. Performance matrix
Step2. Backtracking
Step3. Finding out the start and the end index
Step4 Testing

@Kumar-laxmi Pls assign me this issue.

**Comment by Mayureshd-18** [comment]
@Kumar-laxmi Pls assign this to me.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Mayureshd-18 : C, C++, Python and Java
