### ISSUE TITLE
Morse Code in C, C++, Java & Python

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1607]
**Is your feature request related to a problem? Please describe.**
Morse code is a method of transmitting text information as a series of on-off tones, lights, or clicks that can be directly understood by a skilled listener or observer without special equipment. It is named for Samuel F. B. Morse, an inventor of the telegraph.

The algorithm is very simple. Every character in the English language is substituted by a series of ‘dots’ and ‘dashes’ or sometimes just singular ‘dot’ or ‘dash’ and vice versa.

Every text string is converted into the series of dots and dashes. For this every character is converted into its Morse code and appended in encoded message. Here we have copied space as it is. We have considered both numbers and alphabets.

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/8be1448c-a991-49fe-9660-03969881e1af)

**Comment by prashanth772** [comment]
I am a GSSOC contributor and would like to contribute to this issue, please assign me this issue @Kumar-laxmi

**Comment by divyansh956** [comment]
I would like to work on this issue @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
> I am a GSSOC contributor and would like to contribute to this issue, please assign me this issue @Kumar-laxmi

This repo is under SSOC, not GSSoC

**Comment by prashanth772** [comment]
Okay it's my first contribution, I'll do it under SSOC only

**Comment by Kumar-laxmi** [comment]
Assigned!
@prashanth772 : C, C++, Python and Java
