### ISSUE TITLE
Flattening a Linked List

### ISSUE THREAD

**Issue by Devchawla2608** [Kumar-laxmi/Algorithms#1612]
**Is your feature request related to a problem? Please describe.**
Flattening a Linked List

**Describe the solution you'd like**
1) Start with the head of the linked list.
2.) Iterate through the linked list until the current node is not NULL.
3.) Create two pointer which will point to two down list
4.) If the current node has a down pointer, follow it and reach the last node of the down list and merge both down linkedlist.
5.) Continue this process until all nodes are traversed.
6.) Return the modified linked list.

![image](https://github.com/Kumar-laxmi/Algorithms/assets/92145696/acdcacfc-e25c-4e4f-a33d-926ed8febfb1)

**Comment by Kumar-laxmi** [comment]
Assigned!
@Devchawla2608 : C, C++, Python and Java
