### ISSUE TITLE
Convolutional Neural Network

### ISSUE THREAD

**Issue by Craniace** [Kumar-laxmi/Algorithms#1616]
Description:
A Convolutional Neural Network (CNN) is a type of deep learning algorithm specifically designed for processing structured grid-like data, such as images. It is widely used in computer vision tasks, including image classification, object detection, and image segmentation.

CNNs are inspired by the organization of the visual cortex in animals, where neurons are arranged in receptive fields to detect local patterns and gradually build up a hierarchical representation of visual information.

![image](https://github.com/Kumar-laxmi/Algorithms/assets/100042684/d279533f-0fbf-4681-921e-cd5774d6861c)

@Kumar-laxmi please assign me this issue in Python, JAVA AND C++.

**Comment by Craniace** [comment]
please assign me this under ssoc'23

**Comment by Kumar-laxmi** [comment]
This should be implemented without any library functions

Assigned!
@Craniace : C, C++, Java & Python
