### ISSUE TITLE
Detect loop in linked list java

### ISSUE THREAD

**Issue by SimranLahrani842** [Kumar-laxmi/Algorithms#1618]
**Is your feature request related to a problem? Please describe.**
This is done in c++ but I ll add in Java.
I ll add the code along with op and comments.

**Describe the solution you'd like**
Will do this using slow and fast pointers.

**Describe alternatives you've considered**

**Additional context**

**Comment by SimranLahrani842** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] This is done in c++ but I ll add in Java. I ll add the code along with op and comments.
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen. Will do this using slow and fast pointers.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

Assign me this @Kumar-laxmi

**Comment by chhavisharma30** [comment]
I can solve this issue. Kindly assign it to me.
