### ISSUE TITLE
heap sort

### ISSUE THREAD

**Issue by NiharikaSharma18** [Kumar-laxmi/Algorithms#162]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NiharikaSharma18** [comment]
@Kumar-laxmi  please this to me.

**Comment by samvid2020** [comment]
Can I get this Issue? @Kumar-laxmi @NiharikaSharma18

**Comment by Kumar-laxmi** [comment]
This algorithm has been implemented already
