### ISSUE TITLE
Ant Bee Colony (ABC) Optimization code in Python and C++

### ISSUE THREAD

**Issue by rayarka26** [Kumar-laxmi/Algorithms#1622]
**Is your feature request related to a problem? Please describe.**
I will add Python and C++ codes for Ant Bee Colony (ABC) Optimization.

**Describe the solution you'd like**
The Artificial Bee Colony (ABC) algorithm is a population-based optimization algorithm inspired by the foraging behavior of honeybees. It was proposed by Dervis Karaboga in 2005.

**Describe alternatives you've considered**

**Additional context**
The algorithm simulates the foraging behavior of bees, such as employed bees, onlooker bees, and scout bees, to search for an optimal solution in a given search space.

**Comment by Kumar-laxmi** [comment]
Assigned!
@rayarka26 : C++ & Python
