### ISSUE TITLE
Bentley-Ottmann Algorithm

### ISSUE THREAD

**Issue by hlw-aryan** [Kumar-laxmi/Algorithms#1624]
**Is your feature request related to a problem? Please describe.**
The basic approach for solving the line segment intersection problem lacks efficiency and can be time inefficient. This poses challenges for users who require quick and accurate solutions in scenarios where line segments intersect.

**Describe the solution you'd like**
I propose implementing the Bentley-Ottmann algorithm to address this problem effectively. The Bentley-Ottmann algorithm offers an efficient solution for determining line segment intersections. By adopting this algorithm, we can significantly optimize the computation process and enhance the overall performance of line segment intersection detection.

**Describe alternatives you've considered**
Alternative approaches have been explored, but they often involve complex and lengthy code, resulting in decreased performance. The **Bentley-Ottmann algorithm**, on the other hand, provides an optimal solution with a time complexity of O((n + k) * log n), where n is the number of line segments and k is the number of intersections. This makes it the preferred choice for efficiently solving the line segment intersection problem.

**Additional context**
Accurate detection of line segment intersections is crucial in various fields, including computational geometry, computer graphics, and geographic information systems. By implementing the Bentley-Ottmann algorithm, we can improve the efficiency of this calculation, reducing the computational time and effort required. This enhancement will benefit applications that deal with line segments and require fast and accurate intersection detection, enabling better decision-making and analysis.

**Comment by Kumar-laxmi** [comment]
Assigned!
@hlw-aryan : C, C++, Java & Python
