### ISSUE TITLE
Boruvka's Algorithm in C, C++, Java & Python

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1625]
**Is your feature request related to a problem? Please describe.**
It is one of the oldest minimum spanning tree algorithms. On record, Boruvka came up in 1926. It was published as a method of constructing an efficient electricity network.

**Describe the solution you'd like**
```
1) Input is a connected, weighted and un-directed graph.
2) Initialize all vertices as individual components (or sets).
3) Initialize MST as empty.
4) While there are more than one components, do following
   for each component.
      a)  Find the closest weight edge that connects this 
          component to any other component.
      b)  Add this closest edge to MST if not already added.  
5) Return MST.
```

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/060d4aff-372d-4705-944f-adfc3bbe6d3e)

**Comment by harshitaaa8** [comment]
I can work on this issue please assign it to me.

**Comment by hlw-aryan** [comment]
@Kumar-laxmi please assign it to me

**Comment by Kumar-laxmi** [comment]
Assigned!
@harshitaaa8 : C, C++, Java & Python

**Comment by shivam0277** [comment]
i would like to work on this issue , please assign it to me .
