### ISSUE TITLE
Quick select algorith in C, C++, Python, Java

### ISSUE THREAD

**Issue by harshitaaa8** [Kumar-laxmi/Algorithms#1626]
Reopen #1368 

**Is your feature request related to a problem? Please describe.**
Quick Select is a selection algorithm to find the k-th smallest element in an unordered list.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by harshitaaa8** [comment]
@Kumar-laxmi please assign me this issue.

**Comment by Kumar-laxmi** [comment]
You have already attempted it once, you can focus on other issues
