### ISSUE TITLE
Binary Search in 2D Array 

### ISSUE THREAD

**Issue by samvid2020** [Kumar-laxmi/Algorithms#163]
**Is your feature request related to a problem? Please describe.**
This algorithm operation getting performed using the Java Programming Language on 2D Array 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by samvid2020** [comment]
Do assign this Issue to me @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Duplicate issue
refer #135
