### ISSUE TITLE
[Bug]: README- youtube link not visible

### ISSUE THREAD

**Issue by maitri-vv** [Kumar-laxmi/Algorithms#1633]
### Contact Details

maitrivaghasiya99@gmail.com

### What happened?

A bug happened!
In README, youtube link is not visible at the bottom

![image](https://github.com/Kumar-laxmi/Algorithms/assets/87691594/ab507623-5c32-4d51-a463-f4afea198373)
here

### Version

1.0.2 (Default)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kumar-laxmi** [comment]
Assigned!
@maitri-vv : Documentation
