### ISSUE TITLE
Solve Largest Square Problem in java

### ISSUE THREAD

**Issue by avantikachauhann** [Kumar-laxmi/Algorithms#1637]
**Is your feature request related to a problem? Please describe.**
Given an m x n binary matrix filled with 0's and 1's, find the largest square containing only 1's and return its area.

**Describe the solution you'd like**
dynamic programming array 

**Describe alternatives you've considered**
dynamic programming array and then Traverse through the matrix

**Additional context**
Assign my contribution under SSOC'23

**Comment by Kumar-laxmi** [comment]
Don't raise issues for leetcode problems
