### ISSUE TITLE
Remove loop in Linked List

### ISSUE THREAD

**Issue by Devchawla2608** [Kumar-laxmi/Algorithms#1640]
**Is your feature request related to a problem? Please describe.**
Remove loop in Linked List

**Describe the solution you'd like**
1.)This method is also dependent on Floyd’s Cycle detection algorithm.
2.)Detect Loop using Floyd’s Cycle detection algorithm and get the pointer to a loop node.
3.)Count the number of nodes in the loop. Let the count be k.
4.)Fix one pointer to the head and another to a kth node from the head.
5.)Move both pointers at the same pace, they will meet at the loop starting node.
6.)Get a pointer to the last node of the loop and make the next of it NULL.

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/92145696/c0b671e5-b4b2-4214-b66b-4dc31800222d)

**Comment by Devchawla2608** [comment]
@Kumar-laxmi  please assign this to me under SSOC'23. I'm ready to contribute in all 4 languages

**Comment by Kumar-laxmi** [comment]
refer #759
