### ISSUE TITLE
Segregate even and odd nodes in a Linked List

### ISSUE THREAD

**Issue by Devchawla2608** [Kumar-laxmi/Algorithms#1641]
**Is your feature request related to a problem? Please describe.**
Segregate even and odd nodes in a Linked List

**Describe the solution you'd like**
1.) Create Two nodes even and odd
2.) Traverse the linked list
3.) If node's data is even attach the node after even tail  otherwise after odd tail
4.) Add Odd pointer after Even pointer
5.) Return Even's head

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/92145696/5ddd50fc-8e72-4137-86ae-0cc8519a462b)

**Comment by Devchawla2608** [comment]
@Kumar-laxmi  please assign this to me under SSOC'23. I'm ready to contribute in all 4 languages

**Comment by Devchawla2608** [comment]
@Kumar-laxmi please assign this to me under SSOC'23. I'm ready to contribute in all 4 languages

**Comment by chhavisharma30** [comment]
I have experience with linked list and I have already solved this question. Kindly assign me this issue.
