### ISSUE TITLE
Longest Subarray with sum K

### ISSUE THREAD

**Issue by Saloni020** [Kumar-laxmi/Algorithms#1646]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I'm a contributor with SSOC'23 and would really like to contribute the solution to this probelm.

**Comment by Saloni020** [comment]
@Kumar-laxmi please assign me this

**Comment by khushboo-9876** [comment]
hey ,is this issue availabe please assign me

**Comment by chhavisharma30** [comment]
I can solve this issue. Assign it to me please.

**Comment by shivangi2002** [comment]
@Kumar-laxmi please assign it to me...
