### ISSUE TITLE
Vertical Order Tree traversal

### ISSUE THREAD

**Issue by Saloni020** [Kumar-laxmi/Algorithms#1647]
**Is your feature request related to a problem? Please describe.**
A traversal in which we divide the binary tree in verticals from left to right, and in every vertical, we print the nodes from top to bottom.

**Describe the solution you'd like**
Assigning verticals and levels to nodes.

**Additional context**
![vertical-order-lines](https://github.com/Kumar-laxmi/Algorithms/assets/92468986/fde319d3-afd0-4542-8c5f-864f1d276d5c)

**Comment by Saloni020** [comment]
I'm contributing to SSOC'23. Please assign me this problem. @Kumar-laxmi

**Comment by PrakarshSingh5** [comment]
please assign to me
