### ISSUE TITLE
FLOYDS ALGORITHM for Cycle Detection in Java, C, C++, Python (LinkedList)

### ISSUE THREAD

**Issue by prashanth772** [Kumar-laxmi/Algorithms#1652]
**Is your feature request related to a problem? Please describe.**
Cycle Detection
There is a cycle in a linked list if there is some node in the list that can be reached again by continuously following the next pointer.

**Describe the solution you'd like**

FLOYDS ALGORITHM
- This approach uses a two-pointer a fast pointer and a slow pointer to determine if there exists a cycle in the loop. 
- The slow pointer moves one node ahead at a time, while the fast pointer moves two nodes ahead at a time.
- If a loop exists in the linked list, the fast and slow pointers are bound to meet at some point.

![image](https://github.com/Kumar-laxmi/Algorithms/assets/124067333/b16aec21-30fb-4003-bb20-b93bbe2f9082)

**Comment by prashanth772** [comment]
I would also like to add some other problems like:

- Deleting a node in linkedlist
- Odd Even LinkedList (group all the nodes with odd indices together followed by the nodes with even indices)
- Remove duplicates from linkedlist

I am an SSOC'23 contributor.
Please assign me this issue.

**Comment by PrakarshSingh5** [comment]
Please assign me

**Comment by Tanyamodi** [comment]
I would like to work on this issue, kindly assign this to me.
