### ISSUE TITLE
Image Processing Using OpenCV in Python

### ISSUE THREAD

**Issue by prashanth772** [Kumar-laxmi/Algorithms#1654]
Title: Adding Image Processing Techniques to the Repository

Description:
I would like to contribute to the repository by adding various image processing techniques. Here is a summary of the techniques I plan to add:

1. Gray Scaling: Implementing gray scaling functionality to convert color images to grayscale.

2. Cropping an Image: Adding a feature to crop images, allowing users to extract a specific region of interest.

3. RGB Color Channels: Providing functionality to separate and manipulate individual RGB color channels in an image.

4. Resizing an Image: Implementing image resizing functionality to allow users to adjust the dimensions of an image.

5. Shapes and Text: Adding support for drawing basic shapes (e.g., rectangles, circles) and overlaying text on images.

6. Flipping an Image: Implementing image flipping capabilities, allowing users to flip images vertically, horizontally, or both.

7. Drawing on Image: Enabling users to draw freehand lines or shapes on an image using the mouse.

I will work on these features, please assign me this issue @Kumar-laxmi

**Comment by jimmycool** [comment]
Sir, I would like to work on this please assign this to me I am an expert in image procesding

**Comment by Kumar-laxmi** [comment]
@prashanth772 This repo is for algorithms and not for implementing library functions, instead you can raise issues to implement image processing algorithms

**Comment by jimmycool** [comment]
I would like to implement image processing algorithms using opencv
