### ISSUE TITLE
[Bug]: Incorrect Output Strings Camel Case

### ISSUE THREAD

**Issue by SportingDot1024** [Kumar-laxmi/Algorithms#1656]
### Contact Details

shriram_kannuri@outlook.com

### What happened?

A bug happened!
![image](https://github.com/Kumar-laxmi/Algorithms/assets/86733057/632f78e9-7104-4cad-b394-be8ba073d604)
The objective of the code is to convert a given string to CamelCase format, which is not resolved in this code, as you can see in the output.

**Input**: hii this is camel case
**Output**: HiiThisIsCamelCase
**Expected Output**: hiiThisIsCamelCase 

_Please send me this issue so I can work on it as soon as possible._

### Version

1.0.2 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kumar-laxmi** [comment]
So is this error in all languages?

**Comment by SportingDot1024** [comment]
In C++, the output matches with the expected output.

in Python, C and Java the output doesn't match the expected output.

Java
[cid:8b7fe4fe-1a4f-4698-ad7f-59707385288a]


C
[cid:886d2235-06ee-41f7-92d9-7d0af482f2e7]


AND the Python I have already given that on the issue.

I would be installing JDK and MSYS2 for Java and C/C++ for doing my work completely on VS Code.
I have intermediate level experience in all 4 languages so I can do this.
________________________________

**Comment by Kumar-laxmi** [comment]
Assigned!
@SportingDot1024 : Bug
