### ISSUE TITLE
[SSoC 2.0] Min Indexed D-Heap Algorithm

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Kumar-laxmi/Algorithms#1658]
**Is your feature request related to a problem? Please describe.**
- The min d-indexed heap uses a d-ary tree structure to represent the heap, where d is the degree of the tree.
- It supports insertion, extraction of the minimum element, and decreasing the key of a specific element.
- To insert an element, it is added to the end of the array and then swapped upwards until the heap property is restored.

**Describe the solution you'd like**
- The min d-indexed heap reduces the number of comparisons required during operations compared to a binary heap, especially when d is greater than 2, resulting in potential performance improvements.

**Describe alternatives you've considered**
- Binary heap may be a alternative of this algorithm but for some cases, it's time complexity is very high.

**Additional context**

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi please assign this algorithm to me

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi @zugzwang03 @Arun9739 @072arushi sir, please assign this algorithm to me
i have also ready with the code and want to create a pr under SSoC 2.0
i can solve it in C, C++, JAVA, and PYTHON

**Comment by Kumar-laxmi** [comment]
Assigned!
@Avdhesh-Varshney : C, C++, Java & Python
