### ISSUE TITLE
[SSoC 2.0] Matrix Inverse Algorithm

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Kumar-laxmi/Algorithms#1659]
**Is your feature request related to a problem? Please describe.**
-  It is a request for information about matrix inverse algorithm.

**Describe the solution you'd like**
- Clear and concise explanation of the matrix inverse algorithm.
- Steps or mathematical formula to compute the inverse of a matrix.
- Details on any specific techniques or algorithms used for matrix inversion.

**Describe alternatives you've considered**
- No alternatives.

**Additional context**

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi Sir, please assign this project to me

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi @zugzwang03 @Arun9739 @072arushi sir, please assign this algorithm to me
i have also ready with the code and want to create a pr under SSoC 2.0
i can solve it in C, C++, JAVA, and PYTHON

**Comment by Kumar-laxmi** [comment]
Matrix Inverse is just a concept, kindly raise issue related to a specific algorithm
