### ISSUE TITLE
Add  New  Sorting Algorithm - Bogo Sort

### ISSUE THREAD

**Issue by Gaurang1602** [Kumar-laxmi/Algorithms#1661]
### **Bogo sort : -**

Bogo sort is an algorithm used to sort the elements of an array by randomly generating different permutations of an array and then checking whether it is sorted or not. It’s based on the generate-and-test paradigm. Other names for bogo sort include permutation sort, stupid sort, slow sort, shotgun sort, or monkey sort.

**Feature : -**
Add Bogo sort in C++ , C , java , python.

### Description of solution :

- Will add Bogo sort with adequate comments and proper documentation for readers to get a clear understanding.
- To be added in C, C++, Java and Python.

Alternatives Considered :

Can you please assign me this issue under SSoC'23  @Kumar-laxmi

**Comment by Gaurang1602** [comment]
@Kumar-laxmi Sir please assign this isssue to me.

**Comment by Kumar-laxmi** [comment]
This issue has been implemented in all four languages
