### ISSUE TITLE
 Implement Canny Edge Detection Algorithm for Image Processing

### ISSUE THREAD

**Issue by prashanth772** [Kumar-laxmi/Algorithms#1663]
**Is your feature request related to a problem? Please describe.**
The Canny edge detection algorithm is a widely used technique for detecting edges in digital images, known for its effectiveness in accurately detecting edges while suppressing noise.

**Describe the solution you'd like**
I would like to implement the Canny edge detection algorithm in Python, following the standard steps involved:

1. **Noise Reduction:** Apply a Gaussian blur to reduce noise in the image.
2. **Gradient Calculation:** Compute the gradients using Sobel operators to determine the magnitude and direction of edges.
3. **Non-maximum Suppression:** Suppress non-maximum gradient values to thin out the edges.
4. **Double Thresholding:** Apply double thresholds to classify edges as strong, weak, or non-edges.
5. **Hysteresis:** Connect weak edges to strong edges using hysteresis to form continuous edge contours.

I would like to work on this issue and contribute to the project under SSOC'23. Please assign it to me @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Assigned!
@prashanth772 : C, C++, Python and Java
