### ISSUE TITLE
Kadane's Algorithm to find SubArray with Maximum Sum

### ISSUE THREAD

**Issue by eknathmali** [Kumar-laxmi/Algorithms#1667]
**Is your feature request related to a problem? Please describe.**
Yes, I saw the array folder in the repo doesn't have many algorithms so Kadane's algorithm is also one of them used to solve the problem of finding subarray with a maximum sum in O(n) Time Complexity. 

**Describe the solution you'd like**
Standard Algorithm

**Additional context**
Adding this algo can help others to learn more algorithms related to array.

**Comment by Kumar-laxmi** [comment]
REFER #1328
