### ISSUE TITLE
Merge sort in Linked List in c++

### ISSUE THREAD

**Issue by Vidip-Ghosh** [Kumar-laxmi/Algorithms#1668]
**Is your feature request related to a problem? Please describe.**
2 Linked lists are given, we want combined linked list in sorted order.
TC -> O(N*log(N))

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Please assign me this issue under SSOC 2.0

**Comment by Kumar-laxmi** [comment]
Since it is an easy issue, kindly implement the algorithm in all four languages

Assigned!
@Vidip-Ghosh : C, C++, Java & Python

**Comment by Tanyamodi** [comment]
I would like to work on this issue, kindly assign this to me.
