### ISSUE TITLE
Adding Bidirectional Selection Sort algorithms in C, C++, Python and Java.

### ISSUE THREAD

**Issue by rahulmalakar42** [Kumar-laxmi/Algorithms#1671]
**Is your feature request related to a problem? Please describe.**
I request to add a new algorithm which is an improvised version of selection sort.

**Describe the solution you'd like**
Instead of the general selection sort where we continuously select the smallest element from unsorted part and put it in its position, in bidirectional selection sort, there are two pointers which handles the positions of the smallest and largest element and sort them accordingly.

**Describe alternatives you've considered**
I have implemented the solution using while loop. Whereas, it can also be done using recursion.

**Additional context**
There are 2 lines of user input :
The first line of input requires the number of elements in an array to be sorted.
The second line requires the elements itself.

**Comment by Kumar-laxmi** [comment]
Assigned!
@rahulmalakar42 : C, C++, Java & Python
