### ISSUE TITLE
Long Short-Term Memory (LSTM) Networks 

### ISSUE THREAD

**Issue by Craniace** [Kumar-laxmi/Algorithms#1675]
**Description:**
Long Short-Term Memory (LSTM) is a type of recurrent neural network (RNN) architecture designed to capture long-term dependencies in sequential data. Standard RNNs suffer from the "vanishing gradient" problem, which makes it challenging for the network to learn and propagate information over long sequences.

![image](https://github.com/Kumar-laxmi/Algorithms/assets/100042684/235f6820-8a10-48ff-8501-a3f15965c411)

@Kumar-laxmi please assign me this issue under SSOC '23 in python and c++.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Craniace : C++ & Python
