### ISSUE TITLE
[Bug]: In Read.me file of the Repo 

### ISSUE THREAD

**Issue by Prachurya-Ray** [Kumar-laxmi/Algorithms#1680]
### Contact Details

prachuryaray@gmail.com

### What happened?

A bug happened! In Read.me file of the Repo the cloning steps has been mentioned twice. Most importantly the first time the steps has been written (before inclusion of images), it states to clone the main repo instead of forked repo.

First:
<img width="479" alt="image" src="https://github.com/Kumar-laxmi/Algorithms/assets/70370699/68fc8c17-942a-4b44-a26d-cd5a17e86831">

Second:
<img width="428" alt="image" src="https://github.com/Kumar-laxmi/Algorithms/assets/70370699/4b290a11-62b9-4370-b890-5e7969d76361">

### Version

1.0.2 (Default)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kumar-laxmi** [comment]
Please include pictures to explain the issue better

**Comment by Prachurya-Ray** [comment]
Thanks. Pictures updated on the issue.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Prachurya-Ray : Documentation
