### ISSUE TITLE
Remove Cycle in Linked-List in C, C++, Java & Python

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1683]
**Is your feature request related to a problem? Please describe.**
Given a linked list. If the linked list contains a loop, return True and remove the loop.
A linked list contains a cycle if it consists of a node that can be reached again by continuously following the next pointer.

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/a922a694-184c-46b2-9d63-70d5b9e42979)

**Comment by shanvijha30** [comment]
@Kumar-laxmi I would like to work on this issue. Could you please assign it to me.
Thank you!

**Comment by Devchawla2608** [comment]
@Kumar-laxmi please assign this to me under SSOC'23. I'm ready to contribute in all 4 languages

**Comment by Kumar-laxmi** [comment]
Assigned!
@shanvijha30 : C, C++, Java & Python

**Comment by Tanyamodi** [comment]
I would like to work on this issue, kindly assign this to me.

**Comment by shivangi2002** [comment]
@Kumar-laxmi .It would be a great opportunity to work on it in cpp. Please assign me this.

**Comment by ngm76** [comment]
Hi, I would like to contribute for this issue, in Java. Can you please assign it to me.
