### ISSUE TITLE
Prim's Algorithm in C 

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1685]
### Feature :
Prim's Algorithm is a greedy algorithm that is used to find the minimum spanning tree from a graph.
This algorithm is present in C++, Java and Python but is missing in C. 

### Description of solution :
- Will add Prim's algorithms with adequate comments and proper documentation for readers to get a clear understanding.
- To be added in C language. 

### Alternatives Considered :
- Online Resources and Tutorials
- External Libraries or Frameworks

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/da242ee7-66d6-4712-ad27-134b41074b12)

**Comment by brandonszeto** [comment]
@Kumar-laxmi I would like to work on this issue. Could you please assign it to me. Thank!

**Comment by shanvijha30** [comment]
@Kumar-laxmi Please assign this issue to me. I would like to work on it.

**Comment by Devchawla2608** [comment]
@Kumar-laxmi  please assign this to me under SSOC'23. I'm ready to contribute in all 4 languages

**Comment by Kumar-laxmi** [comment]
Assigned!
@brandonszeto : C

**Comment by khushboo-9876** [comment]
hey ,is this issue availabe please assign me
