### ISSUE TITLE
Bron–Kerbosch Algorithm in C, C++, Python and Java

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1687]
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to a problem. I would like to implement Bron–Kerbosch algorithm using C, C++, Python and Java languages.

The Bron–Kerbosch algorithm is an enumeration algorithm for finding maximal cliques in an undirected graph. It lists all subsets of vertices with the two properties that each pair of vertices in one of the listed subsets is connected by an edge, and no listed subset can have any additional vertices added to it while preserving its complete connectivity.

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/5fb0c215-d8aa-4299-ad36-4acc1b7583d7)

**Comment by hlw-aryan** [comment]
@Kumar-laxmi plz assign it to me

**Comment by Abhinavcode13** [comment]
Please assign me @Kumar-laxmi

**Comment by tarunvyshnav777** [comment]
Kindly assign me @Kumar-laxmi

**Comment by kumawatvinit** [comment]
Please assign this issue to me

**Comment by derphalesh** [comment]
@Kumar-laxmi please assign the issue to me will complete it within 4-5 days

**Comment by Kumar-laxmi** [comment]
Assigned!
@kumawatvinit : C, C++, Java & Python

**Comment by Abhinavcode13** [comment]
Bro @Kumar-laxmi i mentioned it

**Comment by shivam0277** [comment]
i would like to work on this issue please it to me .

**Comment by Ashish1100** [comment]
Hi @kumar-laxmi, I will be happy to work on this algorithm in Python and this is an approach to solve the very algorithm:

Firstly, I will create a function called bron_kerbosch() that takes three arguments: the graph, the set of vertices in the clique so far, and the set of vertices that cannot be in the clique.

Secondly, iterate over the set of vertices that can be in the clique.

Fourth, for each vertex, generate a new clique by adding the vertex to the current clique and then recursively calling the bron_kerbosch() function on the new clique.

Fifth, the function then returns the list of all maximal cliques that it found.
Create a main function that creates a graph and then calls the bron_kerbosch() function on the graph.

Lastly, The bron_kerbosch() function then prints out all of the maximal cliques in the graph.

** I am also working on C, C++ and Java
Kindly, assign me the issue.
