### ISSUE TITLE
Guess The Number

### ISSUE THREAD

**Issue by Soumya6Tiwari** [Kumar-laxmi/Algorithms#1688]
**Is your feature request related to a problem? Please describe.**
Yes, the task is to guess a number in between 1 to 100 and to find out the total no.of trials  in which the user has correctly  guessed a randomly generated number. Below are the rules of the game:

If the guessed number is bigger than the actual number, the program will respond with the message that the guessed number is higher than the actual number.
If the guessed number is smaller than the actual number, the program will respond with the message that the guessed number is lower than the actual number.
If the guessed number is equal to the actual number , the program will end with a suitable message.

**Describe the solution you'd like**
The approach is to generate a random number .
Now using a loop, take input from the user and for each input print whether the number is smaller or larger than the actual number. and along with that also count the no.of trials using a counter variable.
If  the user guessed the number correctly, print that the user won. and also  print the total no.of trials done to guess the randomly generated number.

**Additional context**
The solution to this issue will be available in all the four languages C,C++,Java, Python.
Sir, Kindly assign me this issue under  SSOC 2023 as this will be my first PR and I have already started working on it.

**Comment by Kumar-laxmi** [comment]
Do not raise questions to solve interview questions
