### ISSUE TITLE
Find the missing number in an array

### ISSUE THREAD

**Issue by Soumya6Tiwari** [Kumar-laxmi/Algorithms#1689]
**Is your feature request related to a problem? Please describe.**
Find the missing number in an array.
**Describe the solution you'd like**
One common method is to sum up all the numbers in the array and then compare it with the expected sum of the numbers in the given range. The difference between the expected sum and the actual sum will be the missing number.
**Describe alternatives you've considered**

**Additional context**
The solution will be provided in all the four languages C, C++, Java ,Python. 
Sir,kindly assign me this issue under SSOC 2023 .I have already found out the solutions for above .
This will be my first PR.

**Comment by Kumar-laxmi** [comment]
Do not raise questions to solve interview questions
