### ISSUE TITLE
Left View of Binary Tree

### ISSUE THREAD

**Issue by Devchawla2608** [Kumar-laxmi/Algorithms#1690]
**Is your feature request related to a problem? Please describe.**
 Left view of a Binary Tree is set of nodes visible when tree is visited from Left side

**Describe the solution you'd like**
1.) Create an empty vector called result to store the level order traversal.
2.) If the root is NULL, return the empty result.
3.) Create a queue of Node* and enqueue the root node.
4.) While the queue is not empty
5.) Get the current size of the queue.
6.) Create an empty vector called temp to store the nodes at the current level.
7.) Iterate x times, where x is the current size of the queue:
8.) Dequeue the front element of the queue and store it in top.
9.) If top is NULL, continue to the next iteration.
10.) Add top->data to the temp vector.
11.) Enqueue the left and right children of top, if they exist.
12.) Push the temp vector into the result vector.
13.) Create an empty vector called leftView to store the left view nodes.
14.) Iterate over each vector in result and append the first element to leftView.
15.) Return the leftView vector.

![image](https://github.com/Kumar-laxmi/Algorithms/assets/92145696/80654831-ed0d-454b-823f-310357436297)

**Comment by Devchawla2608** [comment]
@Kumar-laxmi please assign this to me under SSOC'23. I'm ready to contribute in all 4 languages

**Comment by Kumar-laxmi** [comment]
This algo has been implemented
