### ISSUE TITLE
Trapping Rain Water

### ISSUE THREAD

**Issue by Devchawla2608** [Kumar-laxmi/Algorithms#1692]
**Is your feature request related to a problem? Please describe.**
The Trapping Rain Water problem is used to calculate the amount of water that can be trapped between bars in a histogram-like structure. The problem statement typically provides an array representing the heights of the bars. The task is to determine the total amount of water that can be trapped between the bars.

**Describe the solution you'd like**
1.) Initialize variables leftMax and rightMax to store the maximum heights of bars on the left and right sides
2.) Initialize variables left and right to point to the first and last elements of the array.
3.) Initialize a variable ans to store the total trapped water, initially set to 0.
4.) While left is less than or equal to right
5.) If the height of the bar at index left is less than or equal to the height of the bar at index right
6.) If the height of the bar at index left is greater than leftMax, update leftMax with the current height.
7.) Otherwise, calculate the trapped water at the left index by subtracting the height of the bar at left from leftMax, and add the result to ans.
8.) Increment left by 1.
9.) Otherwise, do the same steps as above but with right instead of left.
10.) Return the value of ans as the total amount of trapped water.

![image](https://github.com/Kumar-laxmi/Algorithms/assets/92145696/11b2aba9-63b0-421f-907c-e3eb330c60f2)

**Comment by Devchawla2608** [comment]
@Kumar-laxmi please assign this to me under SSOC'23. I'm ready to contribute in all 4 languages

**Comment by khushboo-9876** [comment]
hey ,is this issue availabe please assign me

**Comment by Kumar-laxmi** [comment]
Don't raise issues to solve the interview questions
