### ISSUE TITLE
Linear Search

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#17]
Implement Linear Search and Binary Search in the following four languages:
- C
- C++
- Python
- Java

**Comment by Kumar-laxmi** [comment]
@Rayyanranje You have to do both searching algorithm in:
- C
- C++
- Python
- Java

**Comment by Kumar-laxmi** [comment]
> @Rayyanranje You have to do both searching algorithm in:
> 
> * C
> * C++
> * Python
> * Java

8 Programs in total

**Comment by Rayyanranje** [comment]
ok got it

**Comment by Umang1103** [comment]
@Kumar-laxmi can I work on this issue?

**Comment by Kumar-laxmi** [comment]
Since this is a easy issue, you are required to write the code in all 4 languages

> @Kumar-laxmi can I work on this issue? I might not be able to write it in Java.

**Comment by Kumar-laxmi** [comment]
@Umang1103 @Rayyanranje  Implement Linear Search in the following four languages:

- C
- C++
- Python
- Java

**Comment by Umang1103** [comment]
Okay!

**Comment by Umang1103** [comment]
@Kumar-laxmi Done✌️
