### ISSUE TITLE
Add Selection Sort in C++ , Java & Python

### ISSUE THREAD

**Issue by Abhay3819** [Kumar-laxmi/Algorithms#1702]
**Description**
## Problem - Sort of Array using Selection Sort in C++ , Java & Python

Examples -

Inout : 9, 7, 78, 66, 45
Output : 7, 9, 45, 66, 78

Inout : 17, 15, 62, 56, 25
Output : 15, 17, 25, 56, 62

Time Complexity  : O(N2)
Space Complexity : O(1)

**Comment by Kumar-laxmi** [comment]
Sorry this algorithm has been implemented already
