### ISSUE TITLE
Shell Sort

### ISSUE THREAD

**Issue by Devchawla2608** [Kumar-laxmi/Algorithms#1705]
**Is your feature request related to a problem? Please describe.**
Shell sort is mainly a variation of Insertion Sort

**Describe the solution you'd like**
1.) Start with a gap value, typically half the length of the array.
2.) Repeat until the gap becomes 1
3.) Perform Insertion Sort on sub-arrays with the current gap.
4.) Reduce the gap by dividing it by 2.
5.) Perform a final Insertion Sort pass on the array with a gap of 1

![image](https://github.com/Kumar-laxmi/Algorithms/assets/92145696/8e3853a5-411e-42c2-8eaf-2f1efc80ee0e)

**Comment by Devchawla2608** [comment]
@Kumar-laxmi please assign this to me under SSOC'23. I'm ready to contribute in all 4 languages

**Comment by Kumar-laxmi** [comment]
This algo has been implemented in all four languages
