### ISSUE TITLE
Reverse Polish Notation

### ISSUE THREAD

**Issue by Devchawla2608** [Kumar-laxmi/Algorithms#1706]
**Is your feature request related to a problem? Please describe.**
Reverse Polish Notation also known as postfix notation

1.) Create an empty stack to hold operands.
2.) Read the expression from left to right.
3.) If the element is an operand, push it onto the stack.
4.) If the element is an operator, pop the required number of operands from the stack, perform the operation, and push the result back onto the stack.
5.) After reading the entire expression, the final result is left on the stack.

![image](https://github.com/Kumar-laxmi/Algorithms/assets/92145696/af7e12cc-0b52-492d-ac12-e82096e0e26a)

**Comment by Devchawla2608** [comment]
@Kumar-laxmi please assign this to me under SSOC'23. I'm ready to contribute in all 4 languages

**Comment by rajchaudhary99** [comment]
#include <iostream>
#include <stack>
#include <sstream>

using namespace std;

int evaluateRPN(const string& expression) {
    stack<int> operands;

    stringstream ss(expression);
    string token;

    while (getline(ss, token, ' ')) {
        if (isdigit(token[0])) {
            
            operands.push(stoi(token));
        } else {
            
            int operand2 = operands.top();
            operands.pop();
            int operand1 = operands.top();
            operands.pop();

            if (token == "+") {
                operands.push(operand1 + operand2);
            } else if (token == "-") {
                operands.push(operand1 - operand2);
            } else if (token == "*") {
                operands.push(operand1 * operand2);
            } else if (token == "/") {
                operands.push(operand1 / operand2);
            }
        }
    }

    return operands.top();
}

**Comment by rajchaudhary99** [comment]
Use this code 
#include <iostream>
#include <stack>
#include <sstream>
#include <string>
#include <cctype> // For isdigit

using namespace std;

int evaluateRPN(const string& expression) {
    stack<int> operands;
    stringstream ss(expression);
    string token;

    while (getline(ss, token, ' ')) {
        if (isdigit(token[0]) || (token.size() > 1 && token[0] == '-' && isdigit(token[1]))) {
            operands.push(stoi(token));
        } else {
            int operand2 = operands.top();
            operands.pop();
            int operand1 = operands.top();
            operands.pop();

            if (token == "+") {
                operands.push(operand1 + operand2);
            } else if (token == "-") {
                operands.push(operand1 - operand2);
            } else if (token == "*") {
                operands.push(operand1 * operand2);
            } else if (token == "/") {
                operands.push(operand1 / operand2);
            }
        }
    }

    return operands.top();
}

**Comment by rajchaudhary99** [comment]
Fix some bugs

**Comment by Kumar-laxmi** [comment]
@rajchaudhary99 If you would like to contribute to this issue, you can raise a new issue by mentioning the programming languages in which you would like to work in.
