### ISSUE TITLE
Shri Dharacharya Algorithm (SSOC'2)

### ISSUE THREAD

**Issue by swastik-akhil** [Kumar-laxmi/Algorithms#1721]
I want to add one of the famous algorithms of all time that is Shri Dharacharya Rule to find the roots of any quadratic whether it contains real or imaginary roots. Kindly assign this under SSOC 2.

**Comment by Manish12-verma** [comment]
hey please assign this issue to me under SSOC 2.0

**Comment by Kumar-laxmi** [comment]
Assigned!
@swastik-akhil : C, C++, Java & Python
