### ISSUE TITLE
Insert a New Element into a Sorted Singly Linked List

### ISSUE THREAD

**Issue by Prachurya-Ray** [Kumar-laxmi/Algorithms#1722]
**Is your feature request related to a problem? Please describe.**
Given a sorted singly linked list. we have to insert a new given element into it.

**Describe the solution you'd like**
We will use two pointers which will move to the desired location as it it sorted, then will store the address into the new node containing the new element.

**Comment by Kumar-laxmi** [comment]
This has been implemented
