### ISSUE TITLE
Sieve Eratosthenes Algorithm 

### ISSUE THREAD

**Issue by Vanraj8169** [Kumar-laxmi/Algorithms#173]
**Algorithm:**  _The sieve of Eratosthenes is one of the most efficient ways to find all primes smaller than n when n is smaller than 10 million or so_

Given a number n, print all primes smaller than or equal to n. It is also given that n is a small number. 

**Example:** 

**Input :** n =10
**Output :** 2 3 5 7 

**Input :** n = 20 
**Output:** 2 3 5 7 11 13 17 19

**Time Complexity:** O(n*log(log(n)))
**Auxiliary Space:** O(n)

@Kumar-laxmi  Please assign me this task to add this algorithm in java Maths directory

**Comment by Kumar-laxmi** [comment]
Assigned!
@Vanraj8169 : Java

**Comment by Shubh08am** [comment]
@Kumar-laxmi Please assign me this task  Using C++

**Comment by Sachittarway** [comment]
@Kumar-laxmi Please assign me this task using c language.

**Comment by vijay-kumar-yadav** [comment]
assign this problem in python to me.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Sachittarway : C
@vijay-kumar-yadav : Python

**Comment by vijay-kumar-yadav** [comment]
@Kumar-laxmi  you forgot to assign me check asignees section

**Comment by vijay-kumar-yadav** [comment]
> @Kumar-laxmi you forgot to assign me check asignees section

@Kumar-laxmi please assign

**Comment by vijay-kumar-yadav** [comment]
@Kumar-laxmi Its not plagiarism but wrong code submitted 

[Sieve of eratosthenes](https://github.com/vijay-kumar-yadav/Algorithms/blob/main/C%2B%2B/Maths/Sieve%20of%20Eratosthenes%20Algorithm.cpp)

[GFG Sieve of eratosthenes](https://www.geeksforgeeks.org/sieve-of-eratosthenes/)
in problem statement we have to find prime number till the given number

But In submitted code it showing first n number of prime number

![image](https://user-images.githubusercontent.com/83089894/211236212-af7fca4f-8ac3-4141-af24-c4f1954a3d11.png)

**Comment by Shubh08am** [comment]
> @Kumar-laxmi wrong code submission
> 
> [Sieve of eratosthenes](https://github.com/vijay-kumar-yadav/Algorithms/blob/main/C%2B%2B/Maths/Sieve%20of%20Eratosthenes%20Algorithm.cpp)
> 
> [GFG Sieve of eratosthenes](https://www.geeksforgeeks.org/sieve-of-eratosthenes/) in problem statement we have to find prime number till the given number
> 
> But In submitted code it showing first n prime number
> 
> ![image](https://user-images.githubusercontent.com/83089894/211236212-af7fca4f-8ac3-4141-af24-c4f1954a3d11.png)


@vijay-kumar-yadav that's not the wrong code I have explained about the algorithm now one can used it as they want weather to print first n , just smaller , just greater prime no.

**Comment by vijay-kumar-yadav** [comment]
> > @Kumar-laxmi wrong code submission
> > [Sieve of eratosthenes](https://github.com/vijay-kumar-yadav/Algorithms/blob/main/C%2B%2B/Maths/Sieve%20of%20Eratosthenes%20Algorithm.cpp)
> > [GFG Sieve of eratosthenes](https://www.geeksforgeeks.org/sieve-of-eratosthenes/) in problem statement we have to find prime number till the given number
> > But In submitted code it showing first n prime number
> > ![image](https://user-images.githubusercontent.com/83089894/211236212-af7fca4f-8ac3-4141-af24-c4f1954a3d11.png)
> 
> @vijay-kumar-yadav that's not the wrong code I have explained about the algorithm now one can used it as they want weather to print first n , just smaller , just greater prime no.

@Shubh08am  So here we are not talking about application its about algorithm

**Comment by Sachittarway** [comment]
This algorithm is to print prime numbers upto the given input in the efficient way. If we see the documents of it , it also states that only. @vijay-kumar-yadav @Shubh08am @Kumar-laxmi

**Comment by vijay-kumar-yadav** [comment]
> This algorithm is to print prime numbers upto the given input in the efficient way. If we see the documents of it , it also states that only. @vijay-kumar-yadav @Shubh08am @Kumar-laxmi

@Sachittarway Exactly

**Comment by Shubh08am** [comment]
> > > @Kumar-laxmi wrong code submission
> > > [Sieve of eratosthenes](https://github.com/vijay-kumar-yadav/Algorithms/blob/main/C%2B%2B/Maths/Sieve%20of%20Eratosthenes%20Algorithm.cpp)
> > > [GFG Sieve of eratosthenes](https://www.geeksforgeeks.org/sieve-of-eratosthenes/) in problem statement we have to find prime number till the given number
> > > But In submitted code it showing first n prime number basically it is an application of algorihm
> > > ![image](https://user-images.githubusercontent.com/83089894/211236212-af7fca4f-8ac3-4141-af24-c4f1954a3d11.png)
> > 
> > 
> > @vijay-kumar-yadav that's not the wrong code I have explained about the algorithm now one can used it as they want weather to print first n , just smaller , just greater prime no.
> 
> @Shubh08am So here we are not talking about application its about algorithm

If u want that u just need to find lower bound of the no. and see till that index in sieve where primes are stored... But, the sieve part of code is correct I have created the sieve globally, and I don't want it to be called again and again as if large value of n exist and passed with test cases of order 1e5 and you call sieve again and again it leads to TLE.

**Comment by vijay-kumar-yadav** [comment]
> @vijay-kumar-yadav @Shubh08am what's the issue? In the image the output is printed correctly.

please read the problem statement [Sieve of Eratosthenes](https://www.geeksforgeeks.org/sieve-of-eratosthenes/)

**Comment by Sachittarway** [comment]
> > @vijay-kumar-yadav @Shubh08am what's the issue? In the image the output is printed correctly.
> @Sachittarway  please read the problem statement [Sieve of Eratosthenes](https://www.geeksforgeeks.org/sieve-of-eratosthenes/) 
> Or you can read above 

Ya read the problem statement. According to it 
Input : n = 20 
Output: 2 3 5 7 11 13 17 19
Is correct. And in the image also it's same. Then were the issue arrises.

**Comment by vijay-kumar-yadav** [comment]
> > > @vijay-kumar-yadav @Shubh08am what's the issue? In the image the output is printed correctly.
> > > @Sachittarway  please read the problem statement [Sieve of Eratosthenes](https://www.geeksforgeeks.org/sieve-of-eratosthenes/)
> > > Or you can read above
> 
> Ya read the problem statement. According to it Input : n = 20  Output: 2 3 5 7 11 13 17 19 Is correct. And in the image also it's same. Then were the issue arrises.

in Image n = 10

**Comment by Sachittarway** [comment]
> > > > @vijay-kumar-yadav @Shubh08am what's the issue? In the image the output is printed correctly.
> > > > @Sachittarway  please read the problem statement [Sieve of Eratosthenes](https://www.geeksforgeeks.org/sieve-of-eratosthenes/)
> > > > Or you can read above
> > 
> > Ya read the problem statement. According to it Input : n = 20  Output: 2 3 5 7 11 13 17 19 Is correct. And in the image also it's same. Then were the issue arrises.
> 
> in Image n = 10

n is dynamic any value of n we can take. It's according to the user.

**Comment by Sachittarway** [comment]
> > > > @vijay-kumar-yadav @Shubh08am what's the issue? In the image the output is printed correctly.
> > > > @Sachittarway  please read the problem statement [Sieve of Eratosthenes](https://www.geeksforgeeks.org/sieve-of-eratosthenes/)
> > > > Or you can read above
> > 
> > Ya read the problem statement. According to it Input : n = 20  Output: 2 3 5 7 11 13 17 19 Is correct. And in the image also it's same. Then were the issue arrises.
> 
> in Image n = 10

Ok then the output is wrong . Beacuse we have to take prime numbers upto 10.
