### ISSUE TITLE
Fast and Slow approch in Linked list

### ISSUE THREAD

**Issue by dontwike** [Kumar-laxmi/Algorithms#1732]
**Is your feature request related to a problem? Please describe.**
Yes, I want to implement fast and slow approach in the linked list which helps in finding loop in a linked list

**Describe the solution you'd like**
We take 2 pointers in a linked list fast and slow, where fast moves two steps in every turn and slow moves a single step in every turn, both the pointer meets in the list if only there is a loop available otherwise the goes till null.

**Describe alternatives you've considered**

**Additional context**
Helps in finding a loop in Linked List and a node in a cycle.

Assign me this issue under SSOC

**Comment by Kumar-laxmi** [comment]
This has been implemented
