### ISSUE TITLE
Delete All The Nodes in a Doubly Linked List

### ISSUE THREAD

**Issue by Prachurya-Ray** [Kumar-laxmi/Algorithms#1734]
**Is your feature request related to a problem? Please describe.**
Given a doubly linked list. We have to write a function to delete all the nodes. 

**Describe the solution you'd like**
We have to traverse the head pointer till it reaches tail pointer and along the way delete its previous node, then delete the last node.

**Comment by Kumar-laxmi** [comment]
This operation has been implemented as a part of a program
