### ISSUE TITLE
Adding of Bitonic Sort algo

### ISSUE THREAD

**Issue by Aarsh30** [Kumar-laxmi/Algorithms#1735]
Bitonic Sort is a parallel sorting algorithm that was designed for implementation on parallel processors. It is also known as the "bitonic merge sort" or "bitonic merge-exchange sort." Bitonic Sort is an interesting algorithm because it is based on the concept of bitonic sequences.

Bitonic sequences are sequences that either monotonically increase and then monotonically decrease or vice versa. A bitonic sequence can be sorted using the Bitonic Sort algorithm.

Algorithm Steps:

Divide the array into two halves, creating two bitonic sequences.
Recursively sort each half in different directions (one in increasing order and the other in decreasing order).
Merge the two sorted bitonic sequences into one, maintaining the bitonic property.
Recursively merge the subsequences until the entire array is sorted.

Bitonic Sort is particularly useful in parallel computing environments, where it can be efficiently parallelized. 

@Kumar-laxmi  assign me so i can make pr

**Comment by Kumar-laxmi** [comment]
Assigned!
@Aarsh30 : C, C++, Python and Java
