### ISSUE TITLE
Adding the Smooth Sort Algorithm 

### ISSUE THREAD

**Issue by Aarsh30** [Kumar-laxmi/Algorithms#1737]
Smooth Sort is an adaptive sorting algorithm that is an improved version of Heap Sort. It was designed to take advantage of patterns in the input data and provide better performance in some cases. Like Heap Sort, Smooth Sort is based on binary heaps but uses a more sophisticated approach to maintain the heap property and achieve better time complexity.

Algorithm Steps:

1,Build the initial binary heap (max-heap) from the input array using sift-up operations (comparing the element with its parent and swapping if necessary).
2,Start with the root (maximum element) of the heap.
3,Swap the root with the last element of the heap (rightmost element in the array).
4,Remove the last element from the heap and consider the remaining elements as the heap.
5,Restore the heap property by performing sift-down operations (comparing the element with its children and swapping if necessary) on the new root (former last element) until the heap property is satisfied again.
6,Repeat steps 2-5 until the heap is empty (all elements have been extracted).
7,The elements extracted in step 2 are in reverse sorted order, forming the sorted output.

Smooth Sort differs from traditional Heap Sort in how it constructs and maintains the heap. It uses a variant of Leonardo Heap, which is a combination of heaps and balanced binary trees. This helps to reduce the number of comparisons and swaps, leading to improved performance.

The time complexity of Smooth Sort is O(n log n) in the worst-case scenario and O(n) in the best-case scenario for almost sorted arrays. It is also an adaptive sorting algorithm, meaning its performance improves when the input data is partially sorted or nearly sorted.

@Kumar-laxmi can you assign it to me for the contribution

**Comment by Kumar-laxmi** [comment]
Assigned!
@Aarsh30 : C, C++, Python and Java
