### ISSUE TITLE
Add Rod cutting problem and LIS problem in dynamic prog.(JAVA)

### ISSUE THREAD

**Issue by shivam0277** [Kumar-laxmi/Algorithms#1740]
Rod Cutting Problem: Given a rod of length n and a list of prices for different lengths, determine the maximum value that can be obtained by cutting the rod into pieces and selling them.

Longest Increasing Subsequence (LIS): Given an array of integers, find the length of the longest increasing subsequence.

**Comment by Kumar-laxmi** [comment]
refer #703 & #1475
