### ISSUE TITLE
[SSoC 2.0] Adding Links Cut Algorithm

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Kumar-laxmi/Algorithms#1742]
**Is your feature request related to a problem? Please describe.**
- "Link-Cut Tree" (LCT), which is a dynamic forest data structure designed to efficiently handle various tree-related operations like link, cut, and find root.

**Describe the solution you'd like**
- I would like to understand how the Link-Cut Tree data structure works, its main functions (link, cut, find root, access), and what benefits it offers. It should be explained in simple terms without requiring me to refer to the provided code snippet.

**Describe alternatives you've considered**
- I have thought about exploring other tree data structures like Binary Search Trees (BST), AVL Trees, and Red-Black Trees to see how they compare to the Link-Cut Tree in terms of efficiency and capabilities.

**Additional context**
- The Link-Cut Tree data structure is useful for solving various dynamic tree-related problems efficiently.

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi @zugzwang03 sir, please assign this task to me

**Comment by keenpaul29** [comment]
@Kumar-laxmi I would be highly obliged if you assign this task to me

**Comment by Kumar-laxmi** [comment]
Kindly include all operation in the code

Assigned!
@Avdhesh-Varshney : C, C++, Java & Python
