### ISSUE TITLE
Sliding Windows Algorithm

### ISSUE THREAD

**Issue by Shubh08am** [Kumar-laxmi/Algorithms#175]
**Is your feature request related to a problem? Please describe.**
I would like to add Sliding Windows Algorithm and questions related to it using C++.
Please Assign this task to me.

**Comment by Kumar-laxmi** [comment]
Please elaborate @Shubh08am

**Comment by Shubh08am** [comment]
> Please elaborate @Shubh08am

https://github.com/Shubh08am/Sliding-Windows
Can u go through this repo (it's made by me) once this contains the set of questions that can be solved using sliding windows algorithm. I would like to add them

**Comment by Kumar-laxmi** [comment]
Assigned!
@Shubh08am : C++

**Comment by Kumar-laxmi** [comment]
@Shubh08am Add the algorithms in **Sliding Window** folder

**Comment by Kumar-laxmi** [comment]
Assigned!
@mvpamansingh : Java

Please implement all problems in https://github.com/Shubh08am/Sliding-Windows

**Comment by mvpamansingh** [comment]
@Kumar-laxmi do I need to implement all the problems in that folder?

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi do I need to implement all the problems in that folder?

Yes

**Comment by mvpamansingh** [comment]
@Kumar-laxmi can you please provide problem statements

**Comment by mvpamansingh** [comment]
@Kumar-laxmi can I contribute later , I have exams now

**Comment by Dharnish38** [comment]
Can you assign this issue to me in the languages of java and python

**Comment by Dharnish38** [comment]
Can you assign this issue to me in the languages of java and python @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
@Dharnish38 You need to implement all the algorithms mentioned in https://github.com/Shubh08am/Sliding-Windows (and successfully implementing this ,I will award you 30points )

Assigned!
@Dharnish38 : Java & Python

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi Can I also work on those problem statements implementing in python?
