### ISSUE TITLE
Structurally identical tree

### ISSUE THREAD

**Issue by chhavisharma30** [Kumar-laxmi/Algorithms#1759]
**Is your feature request related to a problem? Please describe.**
Implement algorithm to find if two trees are structurally identical.

**Describe the solution you'd like**
A recursive function will be implemented to check whether data at each level of the tree is same at each node.

**Comment by chhavisharma30** [comment]
Kindly assign me this issue.

**Comment by shivangi2002** [comment]
please assign it to me.
