### ISSUE TITLE
Min and Max using Divide and Conquer

### ISSUE THREAD

**Issue by krutika-ladani** [Kumar-laxmi/Algorithms#1761]
**Approach**
In this approach, the array is divided into two halves. Then using recursive approach maximum and minimum numbers in each halves are found. Later, return the maximum of two maxima of each half and the minimum of two minima of each half.

**Divide and conquer approach for Max. Min problem works in three stages.**

- If a1 is the only element in the array, a1 is the maximum and minimum.
- If the array contains only two elements a1 and a2, then the single comparison between two elements can decide the minimum and maximum of them.
- If there are more than two elements, the algorithm divides the array from the middle and creates two subproblems. Both subproblems are treated as an independent problem and the same recursive process is applied to them. This division continues until subproblem size becomes one or two.

After solving two subproblems, their minimum and maximum numbers are compared to build the solution of the large problem. This process continues in a bottom-up fashion to build the solution of a parent problem.

![Screenshot (72)](https://github.com/Kumar-laxmi/Algorithms/assets/119760273/2edb7628-5816-4344-b942-908660421d5b)

**Comment by krutika-ladani** [comment]
@Kumar-laxmi can you please assign me this issue under SSOC 2.0

**Comment by shivangi2002** [comment]
> **Approach** In this approach, the array is divided into two halves. Then using recursive approach maximum and minimum numbers in each halves are found. Later, return the maximum of two maxima of each half and the minimum of two minima of each half.
> 
> **Divide and conquer approach for Max. Min problem works in three stages.**
> 
> * If a1 is the only element in the array, a1 is the maximum and minimum.
> * If the array contains only two elements a1 and a2, then the single comparison between two elements can decide the minimum and maximum of them.
> * If there are more than two elements, the algorithm divides the array from the middle and creates two subproblems. Both subproblems are treated as an independent problem and the same recursive process is applied to them. This division continues until subproblem size becomes one or two.
> 
> After solving two subproblems, their minimum and maximum numbers are compared to build the solution of the large problem. This process continues in a bottom-up fashion to build the solution of a parent problem.
> 
> ![Screenshot (72)](https://user-images.githubusercontent.com/119760273/255157167-2edb7628-5816-4344-b942-908660421d5b.png)

@Kumar-laxmi  Please assign me this issue.
