### ISSUE TITLE
FibonnaciNumber

### ISSUE THREAD

**Issue by shivangi2002** [Kumar-laxmi/Algorithms#1769]
**Is your feature request related to a problem? Please describe.**
Given a number n,  print its Fibonacci Number using recursion

**Comment by shivangi2002** [comment]
@Kumar-laxmi  Can you please assign it to me?

**Comment by Raj-Kedia** [comment]
Hello, can you assign me this issue

**Comment by Geeks-Arpan** [comment]
please assign me this issue
