### ISSUE TITLE
Tree Traversals ( Inorder | Preorder | Postorder )

### ISSUE THREAD

**Issue by Gaurav-8604** [Kumar-laxmi/Algorithms#177]
**Is your feature request related to a problem? Please describe.**
Trees are a very important data structure in any of the coding languages. Coders get confused when they come to the traveraal of trees, how to traverse trees how can we use tree to get real life solutions and many more.

**Describe the solution you'd like**
I will be providing detailed and pictorial solution of various traversals of trees such as inorder, preorder and postorder with the help of recursion.

**Describe alternatives you've considered**
Iteration was considered the best way of traversal of trees until recursion arose.
Now, each tree has to use recursion as it simple to represent and reusability of functions make the code short.

**Additional context**
Please assign me this issue @Kumar-laxmi in C++ and SWOC S3

**Comment by Kumar-laxmi** [comment]
Assigned!
@Gaurav-8604 : C++

**Comment by VishalS-HK** [comment]
Can I be assigned this in C?

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 

Can I do it in C as well as Java? Please assign this issue to me?
