### ISSUE TITLE
Rabin Karp

### ISSUE THREAD

**Issue by Abhinavkar** [Kumar-laxmi/Algorithms#178]
**Is your feature request related to a problem? Please describe.**
As mentioned in Readme Rabin Karp is Done in C++ it can be also implemented in C prog as well as  java 

**Describe the solution you'd like**
Will provide clear and proper documented solution of it 

**Describe alternatives you've considered**
Can be solved in java script 

**Additional context**
Screenshot will be added of solution with the time complexity and other stuff

**Comment by Abhinavkar** [comment]
@Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Assigned!
@Abhinavkar : C

**Comment by Kumar-laxmi** [comment]
Java would be assigned to some one else

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 

Can I do it in C++ and Java, I will be happy to work in this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@Abhinavkar : C
@Priyanshu-Singh-1 : Java

**Comment by Kumar-laxmi** [comment]
refer #96
