### ISSUE TITLE
Icons or Logos are missing from the Readme.md 

### ISSUE THREAD

**Issue by Rajeevjewar** [Kumar-laxmi/Algorithms#1780]
<img width="735" alt="Screenshot 2023-08-09 at 12 02 59 AM" src="https://github.com/Kumar-laxmi/Algorithms/assets/97542658/9f272afc-c5e6-4c2a-b511-621f2ba4347b">

**Comment by Kumar-laxmi** [comment]
How do you propose to solve it?

**Comment by Kumar-laxmi** [comment]
By the way it is visible on my end
