### ISSUE TITLE
Binary Search Tree  || Java 

### ISSUE THREAD

**Issue by Abhinavkar** [Kumar-laxmi/Algorithms#179]
**Is your feature request related to a problem? Please describe.**
Binary Search Hasnt been done in java 

**Describe the solution you'd like**
Will code it clear with a proper documented solution 

**Describe alternatives you've considered**
A clear and concise description of the solution will done in other languages 

**Additional context**
Other documentation will be added in the time of pr merge

**Comment by Kumar-laxmi** [comment]
Assigned!
@Abhinavkar : Java

**Comment by Kumar-laxmi** [comment]
Refer #92
