### ISSUE TITLE
Improve readme file of Backtracking 

### ISSUE THREAD

**Issue by ayan-joshi** [Kumar-laxmi/Algorithms#1793]
**Is your feature request related to a problem? Please describe.**
Backtracking is one of the major concept in algorithms , so the readme file of the backtracking folder should be explaining the backtracking concept.

**Additional context**
Please assign me the issue I'll work on it @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Assigned!
@ayan-joshi : Documentation
