### ISSUE TITLE
Doubly Linked List || C 

### ISSUE THREAD

**Issue by Abhinavkar** [Kumar-laxmi/Algorithms#180]
**Is your feature request related to a problem? Please describe.**
Doubly Linked List hasn't been programmed in c Language 
**Describe the solution you'd like**
Will code it in proper way with a proper documentation of it 

**Describe alternatives you've considered**
A clear and concise description of solution will be added 

**Additional context**
Time complexity ss and solution will attach at the time of pr

**Comment by Kumar-laxmi** [comment]
Assigned!
@Abhinavkar : C

**Comment by Kumar-laxmi** [comment]
refer #51
