### ISSUE TITLE
Backtracking Algorithm 

### ISSUE THREAD

**Issue by Abhinavkar** [Kumar-laxmi/Algorithms#181]
**Is your feature request related to a problem? Please describe.**
Standard Problems :

[Backtracking | prb 1 (The Knight’s tour problem)]
[Backtracking | prb 2 (Rat in a Maze)]
[Backtracking | prb 3 (N Queen Problem)]
[Backtracking | prb 4 (Subset Sum)]
[Backtracking | prb 5 (m Coloring Problem)]
[Backtracking | prb 6 (Hamiltonian Cycle)]
[Backtracking | prb 7 (Sudoku)]
[Backtracking | prb 8 (Solving Cryptarithmetic Puzzles)]
[Backtracking | prb 9 (Magnet Puzzle)]
[N Queen in O(n) space]

**Describe the solution you'd like**
Will code it in c , c++ , java

**Comment by Abhinavkar** [comment]
@Kumar-laxmi Assign me with this

**Comment by Abhinavkar** [comment]
@Kumar-laxmi  should i do it in folder or make a separate programs of each prb

**Comment by Kumar-laxmi** [comment]
Assigned!
@Abhinavkar : C

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 
Can I work in C++? I am willing to work in this issue

**Comment by Kumar-laxmi** [comment]
@Priyanshu-Singh-1 Are you ready to work on all mentioned problems in issue description?

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 

First I will work on problem number 1, 2, and 3. After this is completed I will work on later remaining. So for now you can assign me problems no 1, 2, 3.

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi
> 
> First I will work on problem number 1, 2, and 3. After this is completed I will work on later remaining. So for now you can assign me problems no 1, 2, 3.

But the PR will be merged when all problems are solved

**Comment by Kumar-laxmi** [comment]
Assigned!
@Abhinavkar : C
@Priyanshu-Singh-1 : C++

**Comment by Abhinavkar** [comment]
@Kumar-laxmi should do all programs in same issue 
will i get points for all of them

**Comment by Abhinavkar** [comment]
@Kumar-laxmi i am able to work for other problem i have already have  a pull request

**Comment by sumitkr2000** [comment]
is someone working on this?
if not please assign me this issue in c++.

**Comment by Priyanshu-Singh-1** [comment]
> m Coloring Problem

I am working on C++.

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi

Actually, my exams are going on, so I will not be able to contribute these days. So, I request you to not un-assign me this issue, and all the other issues that have been assigned to me.

I will again start contributing once my exams end!

Hope you consider this! Thank you!

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi Can you assign me the Rat in a Maze (prb 2)?

**Comment by Priyanshu-Singh-1** [comment]
@sitamgithub-MSIT I have already made the PR for all the above mentioned problems in cpp

**Comment by sitamgithub-MSIT** [comment]
> @sitamgithub-MSIT I have already made the PR for all the above mentioned problems in cpp

If anything left to implement in python, then I can work on that.

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi Can you confirm about the python codes of the above problems?
