### ISSUE TITLE
Morris Traversal Algorithm

### ISSUE THREAD

**Issue by Sachittarway** [Kumar-laxmi/Algorithms#183]
**Is your feature request related to a problem? Please describe.**
Morris traversal is an important algorithm in trees in O(n) time complexitiy.

**Describe the solution you'd like**
I will code it in c++ language in the efficient way.

**Additional context**
I will be providing screenshots of output as well as short notes on it.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Sachittarway : C++

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 

Can you assign this issue to C and Java? I will be happy to contribute in this issue.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Sachittarway : C++
@Priyanshu-Singh-1 : C

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 
In which folder under C, should I add this issue?

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi In which folder under C, should I add this issue?

Trees

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 

I have created PR #217 for this respective issue in C.

**Comment by PiXeL99-eng** [comment]
@Kumar-laxmi Please assign me this issue in Python

**Comment by Kumar-laxmi** [comment]
Assigned!
@PiXeL99-eng : Python

**Comment by Kumar-laxmi** [comment]
This issue is only left with implementation in Java

**Comment by maheshbanagar** [comment]
i will implement this in java. could you please assign to me?

**Comment by Kumar-laxmi** [comment]
Assigned!
@maheshbanagar : Java

**Comment by maheshbanagar** [comment]
i am not able to push the code to the branch i created 
![issue](https://user-images.githubusercontent.com/84569564/216517016-31fa61c4-5add-424b-ba0b-4381b6e1e0f7.png)
i am new to github ,pls help me with this
