### ISSUE TITLE
DFS and BFS

### ISSUE THREAD

**Issue by Gaurav8604** [Kumar-laxmi/Algorithms#186]
**Is your feature request related to a problem? Please describe.**
Depth first search and Breadth first search to traverse graphs.

**Describe the solution you'd like**
Use class and structure to design a tree and implement depth and breadth first search.

**Describe alternatives you've considered**
Recursion will be my main approach as it is the only efficient way to traverse graphs

**Additional context**
Please assign this to me in C++

**Comment by Kumar-laxmi** [comment]
Assigned!
@Gaurav-8604 : C++

Please make the PR under **Searching** folder

**Comment by Mridul-2003** [comment]
Please assign me this code in python

**Comment by Kumar-laxmi** [comment]
Assigned!
@Gaurav-8604 : C++
@Mridul-2003 : Python

**Comment by Mansiuniyal** [comment]
Please assign this code to me in C

**Comment by MansiBhayade** [comment]
Please assign this code to me in java

**Comment by Kumar-laxmi** [comment]
> Please assign this code to me in c++

Implementation in C++ done

**Comment by Abhilash1781** [comment]
@Kumar-laxmi Its been a month since you assigned , I would like to work on this issue in C . Please assign me

**Comment by Kumar-laxmi** [comment]
Assigned!
@sitamgithub-MSIT : Python
@Abhilash1781 : C
