### ISSUE TITLE
STL of C++

### ISSUE THREAD

**Issue by Gaurav-8604** [Kumar-laxmi/Algorithms#187]
**Is your feature request related to a problem? Please describe.**
Clearing each and every concept of Standard Template Library if the C++ language.

**Describe the solution you'd like**
Various functions describing the use of the various data structures in C++ implemented by STL.

**Describe alternatives you've considered**
vector, stack, queue, priority_queue, set, map, 
![image](https://user-images.githubusercontent.com/106819107/210560952-cab0d4b6-139b-4e96-8944-2b726b9b03fe.png)

**Additional context**
Please assign this to me in C++

**Comment by Kumar-laxmi** [comment]
@Gaurav-8604 What exactly do you want to implement?

**Comment by Gaurav-8604** [comment]
Demonstrating each and every function of STL

Eg. 
stack<int> stk;
stk.pop()
OR
unordered_map<int,int> umap;

**Comment by Anmol-Baranwal** [comment]
@Kumar-laxmi 
Please assign this to me.

I want to make some things clear, there are so many methods in STL so it is basically very tough to cover all of these in a single file. Still, I would cover most of them explaining the need with comments and detailed explanation with other necessary mentions.

**Comment by Kumar-laxmi** [comment]
This repository is for algorithms and not for implementation of library function
