### ISSUE TITLE
Matrix Chain Multiplication

### ISSUE THREAD

**Issue by NikitaGupta-17** [Kumar-laxmi/Algorithms#189]
Please assign it to me .I can code in C++.

**Comment by mvpamansingh** [comment]
@Kumar-laxmi please assign issue this in java

**Comment by Kumar-laxmi** [comment]
@NikitaGupta-17 What is you status on this issue?

**Comment by Kumar-laxmi** [comment]
Due to inactivity of @NikitaGupta-17, I am unassigning this issue in C++

**Comment by mvpamansingh** [comment]
where should I create file for matrixchain multiplication ? in dynamic programming? @Kumar-laxmi

**Comment by NikitaGupta-17** [comment]
Yes please assign it in dynamic programming

**Comment by NikitaGupta-17** [comment]
Please assign this issue in C to me.
