### ISSUE TITLE
Intersection of Two Linked List

### ISSUE THREAD

**Issue by NikitaGupta-17** [Kumar-laxmi/Algorithms#190]
Please assign it to me.I can code in c++.

**Comment by Kumar-laxmi** [comment]
Assigned!
@NikitaGupta-17 : C++

**Comment by trushee** [comment]
@Kumar-laxmi can you please assign it to me in java

**Comment by silentspectator20** [comment]
Please assign this to me in C language. @Kumar-laxmi

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi Please assign me this implementing in python
