### ISSUE TITLE
Dutch national Flag Algorithm

### ISSUE THREAD

**Issue by sumitkr2000** [Kumar-laxmi/Algorithms#193]
Please assign this issue to me. C++

**Comment by Kumar-laxmi** [comment]
Assigned!
@sumitkr2000 : C++

**Comment by Kumar-laxmi** [comment]
Assigned! 
@Vanraj8169 : Java

**Comment by Kumar-laxmi** [comment]
@sumitkr2000 What is your status on this issue?

**Comment by PiXeL99-eng** [comment]
@Kumar-laxmi please assign me this in Python

**Comment by Kumar-laxmi** [comment]
Assigned!
@PiXeL99-eng : Python

**Comment by Kumar-laxmi** [comment]
This algorithm is only available in ```C```

**Comment by Sowham-3098** [comment]
I can do it in C Language

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi If the C implementation is still not done, then can you assign me that?
