### ISSUE TITLE
Math Algorithm - Armstrong number

### ISSUE THREAD

**Issue by ajruttam** [Kumar-laxmi/Algorithms#194]
Armstrong number is a number that is equal to the sum of cubes of its digits
I will do this in Python. Please assign this to me @Kumar-laxmi sir.

**Comment by Kumar-laxmi** [comment]
Assigned!
@ajruttam : C, C++, Java, Python

since this is a easy problem you have to attempt in languages.

**Comment by ajruttam** [comment]
Sure sir. Thank you! Will do and submit it soon

**Comment by Kumar-laxmi** [comment]
This algorithm has been implemented in all four languages
