### ISSUE TITLE
 Math - Multiplication of two Matrices

### ISSUE THREAD

**Issue by dineshnalam** [Kumar-laxmi/Algorithms#200]
Please assign this issue to me in Java and C @Kumar-laxmi

**Comment by Durgesh4993** [comment]
i want to work on these please assign me

**Comment by aakanksha-thakar** [comment]
I am ready to work on this in Java please assign me this task.

**Comment by Kumar-laxmi** [comment]
Since this is a easy algorithm you have to code this algorithm in all four languages

Assigned!
@dineshnalam : C, C++, Java, Python

**Comment by RAJEEVKUMAR9598** [comment]
hii sir can you assign to me this task.so i make a project who operate all operation .so please assign me this issue

**Comment by dineshnalam** [comment]
@Kumar-laxmi kindly check PR #240 , I've submitted it 3 days ago itself
