### ISSUE TITLE
Add Some Sorting algorithm

### ISSUE THREAD

**Issue by Anuragwagh** [Kumar-laxmi/Algorithms#213]
Want to add Wave sort, DNF sort, count sort using CPP and python

**Comment by Kumar-laxmi** [comment]
Please open separate issues for separate algorithms so that other contributors can also contribute to those algorithms separately.

**Comment by Anuragwagh** [comment]
> Please open separate issues for separate algorithms so that other contributors can also contribute to those algorithms separately.

Actually, I intend to merge it; in fact, I have already done so.
