### ISSUE TITLE
Deadlock Avoidance

### ISSUE THREAD

**Issue by vijay-kumar-yadav** [Kumar-laxmi/Algorithms#215]
In deadlock avoidance, the operating system is provided with extra information related to all resources any process will require during its lifetime. Then at every request, the system can decide whether to grant that request or not. This decision depends upon

1. resources currently available
2. resources currently allocated to each process
3. future request and release of resources by each process

**Comment by vijay-kumar-yadav** [comment]
please assign this issue in c  to me.

**Comment by Kumar-laxmi** [comment]
Please open issue pertaining to specific algorithm and not a broad concept

**Comment by vijay-kumar-yadav** [comment]
> Please open issue pertaining to specific algorithm and not a broad concept

@Kumar-laxmi I know its a concept having algorithm like bankers algorithm. I am asking for this algo

**Comment by vijay-kumar-yadav** [comment]
> > Please open issue pertaining to specific algorithm and not a broad concept
> 
> @Kumar-laxmi I know its a concept having algorithm like bankers algorithm. I am asking for this algo

Okay 👌😅

**Comment by Kumar-laxmi** [comment]
> > > Please open issue pertaining to specific algorithm and not a broad concept
> > 
> > 
> > @Kumar-laxmi I know its a concept having algorithm like bankers algorithm. I am asking for this algo
> 
> Okay 👌😅

Already an issue is open on Bankers Algorithm
