### ISSUE TITLE
Wave sort in C++

### ISSUE THREAD

**Issue by atul1510** [Kumar-laxmi/Algorithms#225]
I want to add an algorithm of Wave sort.
@Kumar-laxmi sir please assign me this issue.

**Comment by Kumar-laxmi** [comment]
> I want to add an algorithm of Wave sort. @Kumar-laxmi sir please assign me this issue.

Which language would you like to work on?

**Comment by atul1510** [comment]
In C++ sir

**Comment by vijay-kumar-yadav** [comment]
@Kumar-laxmi  in C assign it to me

**Comment by Kumar-laxmi** [comment]
Assigned!
@atul1510 : C++
@vijay-kumar-yadav : C

**Comment by mvpamansingh** [comment]
@Kumar-laxm I am ready to work on this issue please assign this issue in java

**Comment by Kumar-laxmi** [comment]
@mvpamansingh What is your status on this algorithm?

**Comment by mvpamansingh** [comment]
@Kumar-laxmi can I please contribute later, I have exams now

**Comment by Abhinavcode13** [comment]
assign this issue to me in c @Kumar-laxmi
