### ISSUE TITLE
Tarjan Algorithm 

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Kumar-laxmi/Algorithms#234]
**Is your feature request related to a problem? Please describe.**
I wanted to add implementation of tarjan algorithm to solve problems related to bridges in graph.

**Describe the solution you'd like**
Using tin[], low[] arrays & a timer variable.

**Additional context**
We can also find strongly connected component & it is much faster than kosaraju.

@Kumar-laxmi 
Assign me this in c++

**Comment by Kumar-laxmi** [comment]
Assigned!
@Anmol-Baranwal : C++

**Comment by Aaditya1612** [comment]
@Kumar-laxmi Please assign this to me in C, Java and Python under SWoC'23
