### ISSUE TITLE
Boyer-Moore Majority Voting Algorithm

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Kumar-laxmi/Algorithms#235]
**Is your feature request related to a problem? Please describe.**
Implementation of Boyer-Moore algorithm to solve majority element.

**Describe the solution you'd like**
I will solve it for finding majority element 1 (occuring more than 2 times), and majority element 2 (occuring more than 3 times)

**Additional context**
In which section should I add this? under sub-arrays.

@Kumar-laxmi 
assign me this in c++

**Comment by Kumar-laxmi** [comment]
Assigned!
@Anmol-Baranwal : C++

**Comment by Sachittarway** [comment]
@Kumar-laxmi Please assign me in c.

**Comment by stiwari-ds** [comment]
@Kumar-laxmi Please assign it to me in Python.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Sachittarway : C
@stiwari-ds : Python

**Comment by Kumar-laxmi** [comment]
@Sachittarway What is your status on this issue

**Comment by Sachittarway** [comment]
> @Sachittarway What is your status on this issue

Ya actually working on one more algorithm. Will commit this by 20th.

**Comment by sumitkr2000** [comment]
Is anyone working on this issue in C++?

**Comment by Anmol-Baranwal** [comment]
> Is anyone working on this issue in C++?

I have already merged the solution through PR in c++.
