### ISSUE TITLE
Merge Intervals Algorithm in C++

### ISSUE THREAD

**Issue by atul1510** [Kumar-laxmi/Algorithms#238]
I want to add a Merge intervals algorithm and for this, I would like to code the solution for this problem in C++ language.

Problem Description: Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.

Input: intervals = [[1,3],[2,6],[8,10],[15,18]]
Output: [[1,6],[8,10],[15,18]]
@Kumar-laxmi sir please assign me this issue.

**Comment by Kumar-laxmi** [comment]
Do you mean **Merge Overlapping Intervals Algorithm** & under what category this algorithm comes

**Comment by zugzwang03** [comment]
> Do you mean **Merge Overlapping Intervals Algorithm** & under what category this algorithm comes

This kind of questions generally fall under the greedy algorithm, and yeah merge overlapping intervals algorithm and merge intervals algorithm is the same.

**Comment by Kumar-laxmi** [comment]
@atul1510 Please specify the language you would like to work on

**Comment by Kumar-laxmi** [comment]
@atul1510 Please specify the language you would like to work on

**Comment by atul1510** [comment]
> @atul1510 Please specify the language you would like to work on

I will like to work in C++ Language.

**Comment by atul1510** [comment]
@Kumar-laxmi @zugzwang03 assign me this issue.

**Comment by Kumar-laxmi** [comment]
@atul1510 Could you implement this algorithm in all four languages

**Comment by Kumar-laxmi** [comment]
Assigned!
@atul1510 : C, C++, Java, Python
