### ISSUE TITLE
Optimal Merge Pattern

### ISSUE THREAD

**Issue by NikitaGupta-17** [Kumar-laxmi/Algorithms#243]
Given n number of sorted files, the task is to find the minimum computations done to reach the Optimal Merge Pattern. 
When two or more sorted files are to be merged altogether to form a single file, the minimum computations are done to reach this file are known as Optimal Merge Pattern. I can code in c++.
Please assign it to me.

**Comment by Kumar-laxmi** [comment]
@NikitaGupta-17 Could you explain the problem with illustrations and diagrams

**Comment by NikitaGupta-17** [comment]
Optimal merge pattern
It is minimum no of moves req to merge files by Greedy Approach.
It is a process of merging 2 sorted files of different length into a single sorted file.
If length of sorted file is n and length of another sorted file is m then time complexity will be O(n+m).

Approach
1) sort files in ascending order of sizes.
2) Pick the files of smaller sizes and merge them.

For example
Q If there are 5 files apply optimal merge pattern.(20,30,10,5,30).
Ans
Step 1: Sort files in ascending order of their sizes.
x4 x3 x1 x2 x5
5  10 20 30 50
Step 2: Pick the files of smaller size and merge them
Merge x3 and x4 |z1|=5+10=15
Merge z1 and x1|z2|=35
Merge x2 and x5|z3|=60
Merge z3 and z2=60+35=95
Total no of moves= 205

205 is the minimum no of moves if we combine in different ways then moves will be greater than 205.

**Comment by NikitaGupta-17** [comment]
![Uploading 20230111_212050.jpg…]()

**Comment by NikitaGupta-17** [comment]
@Kumar-laxmi I have added the example please review now.

**Comment by Kumar-laxmi** [comment]
@NikitaGupta-17 Could you implement this in all four languages?

**Comment by NikitaGupta-17** [comment]
I can implement it in C++ and Python.

**Comment by NikitaGupta-17** [comment]
Yes I can. Please assign this issue to me.

**Comment by NikitaGupta-17** [comment]
@Kumar-laxmi  Pleae assign this issue to me I have coded in all 4 languages.
