### ISSUE TITLE
Cocktail sorting in C++

### ISSUE THREAD

**Issue by ArgyPorgy** [Kumar-laxmi/Algorithms#244]
**Is your feature request related to a problem? Please describe.**
Not a bug or a problem, i just want to add cocktail sorting in C++

**Describe the solution you'd like**
I will add the code of cocktail sorting

please assign this issue to me under swoc, @Kumar-laxmi thank you!

**Comment by Kumar-laxmi** [comment]
Assigned!
@ArgyPorgy : C++

**Comment by muskan467** [comment]
assign me i will do in python

**Comment by ArgyPorgy** [comment]
@Kumar-laxmi my semester exams are going on so I'm not able to do it yet. My exams are ending on 11th feb, I'll start working on it once I'm done with my exams. I'm really sorry that this is taking so much time, hope you will understand.

**Comment by Kumar-laxmi** [comment]
@muskan467 What is your status on this issue?

**Comment by muskan467** [comment]
@Kumar-laxmi I have created pull request #471, and that file is merged also.
