### ISSUE TITLE
Backtracking

### ISSUE THREAD

**Issue by viveksondhiya** [Kumar-laxmi/Algorithms#248]
**Is your feature request related to a problem? Please describe.**

Adding some content and the example of Backtracking

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![backtracking](https://user-images.githubusercontent.com/98210740/211171070-e9fa6c92-3728-41dd-a4a1-a83b0c956019.gif)

**Comment by viveksondhiya** [comment]
Some new way to understand the backtracking

**Comment by Kumar-laxmi** [comment]
refer #181
