### ISSUE TITLE
Permutation of string in C++

### ISSUE THREAD

**Issue by Garvit414** [Kumar-laxmi/Algorithms#249]
**Is your feature request related to a problem? Please describe.**
I want to add the code for possible permutations of string.

**Describe the solution you'd like**
This code can be done with help of recursion and backtracking.

**Describe alternatives you've considered**
In which section should I add this? under Backtracking.

@Kumar-laxmi assign it to me.

**Comment by Kumar-laxmi** [comment]
@Garvit414 Please elaborate

**Comment by Garvit414** [comment]
Given a string S, the task is to write a program to print all permutations of a given string. 
e.g.
Input: S = “ABC”
Output: “ABC”, “ACB”, “BAC”, “BCA”, “CBA”, “CAB”

**Comment by stiwari-ds** [comment]
@Kumar-laxmi Please assign it to me for Python.

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi Can you assign it to me for python?

**Comment by Abhinavcode13** [comment]
@Kumar-laxmi  Assign this issue to me in **C/C++** please.
