### ISSUE TITLE
Algorithm to convert Binary Tree into Binary Search Tree

### ISSUE THREAD

**Issue by Aaditya1612** [Kumar-laxmi/Algorithms#250]
Given a Binary Tree, convert it to a Binary Search Tree. The conversion must be done in such a way that keeps the original structure of Binary Tree. 
I can code it in Java, Python and C++.
@Kumar-laxmi Please assign this to me under SWoC'23

**Comment by dv8081** [comment]
1.Traverse the Binary Tree in-order (left, root, right) and store the node values in an array. This will give you the nodes of the tree in sorted order.
2.Traverse the Binary Tree again, this time replacing the value of each node with the next value in the sorted array.

**Comment by Kumar-laxmi** [comment]
> 1.Traverse the Binary Tree in-order (left, root, right) and store the node values in an array. This will give you the nodes of the tree in sorted order. 2.Traverse the Binary Tree again, this time replacing the value of each node with the next value in the sorted array.

Please mention the language you would like to work on

**Comment by Kumar-laxmi** [comment]
> Given a Binary Tree, convert it to a Binary Search Tree. The conversion must be done in such a way that keeps the original structure of Binary Tree. I can code it in Java, Python and C++. @Kumar-laxmi Please assign this to me under SWoC'23

Since this is a easy problem you have to implement this in all four languages, are you OK with it

**Comment by Aaditya1612** [comment]
Yes I can implement it in all four languages.
@Kumar-laxmi Please assign this to me.
Thank you

**Comment by Aaditya1612** [comment]
Yes I can code this in all four languages.
@Kumar-laxmi please assign this to me.
Thank you
