### ISSUE TITLE
Beautiful String Algorithm in C++

### ISSUE THREAD

**Issue by atul1510** [Kumar-laxmi/Algorithms#261]
I want to add a Beautiful String Algorithm. 
And for this, I would like to code the solution for this problem in C++ language.

Problem Statement : 
A binary string is called beautiful if it contains alternating 0s and 1s.
For Example:‘0101’, ‘1010’, ‘101’, and ‘010’ are beautiful strings.

@Kumar-laxmi sir, Please Assign me this issue.

**Comment by zugzwang03** [comment]
Yep, nice issue! Start working on it @atul1510

**Comment by Kumar-laxmi** [comment]
@atul1510 Since this is an easy algorithm please implement it in all four languages

**Comment by Kumar-laxmi** [comment]
> Yep, nice issue! Start working on it @atul1510

Assigned!
@atul1510 : C, C++. Java, Python
