### ISSUE TITLE
Shell Sort Algorithm

### ISSUE THREAD

**Issue by Kinshuk2003** [Kumar-laxmi/Algorithms#263]
**Is your feature request related to a problem? Please describe.**
shell sort is a sorting algorithm that is an extended version of insertion sort. Shell sort has improved the average time complexity of insertion sort.

**Describe the solution you'd like**
Algorithms in C, C++, Python

please assign this to me @Kumar-laxmi

**Comment by Mansiuniyal** [comment]
@Kumar-laxmi Can you assign this to me in C

**Comment by Kumar-laxmi** [comment]
Assigned!
@Kinshuk2003 : Python
@Mansiuniyal : C

**Comment by Kinshuk2003** [comment]
#299

**Comment by silentspectator20** [comment]
@Kumar-laxmi Please assign this to me in C++

**Comment by sumitkr2000** [comment]
Hey, @Kumar-laxmi is this issue available in C++? If not, please assign me this issue in C++.
