### ISSUE TITLE
Circular Linked List

### ISSUE THREAD

**Issue by Paritosh-J** [Kumar-laxmi/Algorithms#265]
### Definition
A Circular Linked List has the last node pointing to its first node.

### Implementation
Circular Linked List will be implemented in **C++**.

### Request Statement
**I hereby request you to please assign me this Algorithm.**

**Comment by Kumar-laxmi** [comment]
Assigned!
@Paritosh-J : C++

**Comment by Mansiuniyal** [comment]
Can you please assign me this issue in C

**Comment by stiwari-ds** [comment]
@Kumar-laxmi Please assign it to me in Python.

**Comment by iianuragii** [comment]
Please assign this to me in java

**Comment by iianuragii** [comment]
Thank you for assigning it to me

**Comment by Kumar-laxmi** [comment]
@iianuragii What is your status??

**Comment by Kumar-laxmi** [comment]
Unassigned @iianuragii due to inactivity

**Comment by Kumar-laxmi** [comment]
This issue is available in ```Java```

**Comment by Abhinavcode13** [comment]
Can you assign me this issue in java under SSOC 2.0?
