### ISSUE TITLE
Algorithm for converting an Binary number to a Decimal number and Decimal number to Binary number

### ISSUE THREAD

**Issue by viveksondhiya** [Kumar-laxmi/Algorithms#270]
**Is your feature request related to a problem? Please describe.**
It is not associated with a problem. Actually, your repository doesn't contain this type of Algorithm So I want to add this Algorithm 

**Describe the solution you'd like**
I am providing the easy algorithm to convert a binary number to an Integer and an integer to a binary number using java or CPP language 

**Describe alternatives you've considered**

**Additional context**
![example of Binary to decimal number](https://user-images.githubusercontent.com/98210740/211328020-75d29815-e0f3-4eaa-a898-11f0dfc5a072.jpg)

**Comment by PK284** [comment]
@Kumar-laxmi Please assign me to this
 I'll write clear codes in Java/Cpp as you have mentioned and will follow your instructions

**Comment by zugzwang03** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

Proper explanation of algorithm and your approach towards solving it must be explained first, otherwise issues can not be assigned.

**Comment by viveksondhiya** [comment]
Is it clear now @zugzwang03

**Comment by zugzwang03** [comment]
you are writing it in both java and c++ ?

**Comment by zugzwang03** [comment]
Well, start working then, assigned to you @viveksondhiya

**Comment by Abhilash1781** [comment]
@zugzwang03 Can I work on this issue in C

**Comment by zugzwang03** [comment]
Assigned 
@Abhilash1781 : C

**Comment by viveksondhiya** [comment]
I am done my task why it is not added to your repository  @zugzwang03

**Comment by zugzwang03** [comment]
> I am done my task why it is not added to your repository @zugzwang03

I did not update it that's why :)

**Comment by Abhilash1781** [comment]
@viveksondhiya bro did u updated the README.md file

**Comment by viveksondhiya** [comment]
> @viveksondhiya bro did u updated the README.md file

No I only submitted the solution of the problem

**Comment by Abhilash1781** [comment]
You have to update readme file

**Comment by viveksondhiya** [comment]
> You have to update readme file
what I have to update... in read me file

**Comment by Kumar-laxmi** [comment]
@Abhilash1781 Is it possible for you to implement this in Python too

**Comment by Abhilash1781** [comment]
yes sir

**Comment by viveksondhiya** [comment]
I am done my task why it is not added to your repository @Kumar-laxmi

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi If the python one is still not implemented then can you assign me that?

**Comment by Abhinavcode13** [comment]
@Kumar-laxmi can u assign me this issue in python if It's still not done.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Abhinavcode13 : C++

**Comment by mrenigmatic19** [comment]
can you assign this to me in c++ @Kumar-laxmi @zugzwang03 if no one is working on it

**Comment by Kumar-laxmi** [comment]
> can you assign this to me in c++ @Kumar-laxmi @zugzwang03 if no one is working on it

@mrenigmatic19 Do you wish to work in Java

**Comment by mrenigmatic19** [comment]
@Kumar-laxmi well I am proficient in C++.....if possible may i work on sorting algorithms (insertion sort , selection sort and merge sort) on linkedlist?? under social summer of code?

**Comment by Kumar-laxmi** [comment]
@mrenigmatic19 refer: https://github.com/Kumar-laxmi/Algorithms/issues/664

**Comment by Abhinavcode13** [comment]
> @Kumar-laxmi well I am proficient in C++.....if possible may i work on sorting algorithms (insertion sort , selection sort and merge sort) on linkedlist?? under social summer of code?

It's not started yet

**Comment by mrenigmatic19** [comment]
@Abhinavcode13 no prob.....I m new to Github and open source contribution. I will be happy to work on this algorithms as practice and to get comfortable using github.

**Comment by Kumar-laxmi** [comment]
> @Abhinavcode13 no prob.....I m new to Github and open source contribution. I will be happy to work on this algorithms as practice and to get comfortable using github.

Kindly start your contribution after 1st June 2023

**Comment by nithinkatta** [comment]
Actually we make it more optimized using bit manipulation

**Comment by DevBhojani116** [comment]
> > can you assign this to me in c++ @Kumar-laxmi @zugzwang03 if no one is working on it
> 
> @mrenigmatic19 Do you wish to work in Java

I can do it in java.... I can do it under SSOC'23 but it is not mentioned on quine...

**Comment by Coding-whiz** [comment]
> Assigned! @Abhinavcode13 : C++

can you pls assign me the one to be done in python
