### ISSUE TITLE
tower of hanoi

### ISSUE THREAD

**Issue by ADITYA0714** [Kumar-laxmi/Algorithms#272]
Tower of Hanoi is a mathematical puzzle where we have three rods and n disks. 1) Only one disk can be moved at a time. 2) Each move consists of taking the upper disk from one of the stacks and placing it on top of another stack i.e. a disk can only be moved if it is the uppermost disk on a stack.

I will write the code for this and i request you to kindly issue me this algorithm.

**Comment by dineshnalam** [comment]
Assign this to me in C @Kumar-laxmi

**Comment by Durgesh4993** [comment]
Assign this to me in C++ @Kumar-laxmi

**Comment by zugzwang03** [comment]
Issues would be assigned on a first come, first serve basis. Assigning the issue to @ADITYA0714 as per that. Start working on it!

**Comment by zugzwang03** [comment]
Also it would be better if you could specify in which language you want to write the Tower of Hanoi problem, so that I can assign the other language task to others @ADITYA0714

**Comment by ADITYA0714** [comment]
ASSIGN This to me in c language

**Comment by zugzwang03** [comment]
Assigned! 
@ADITYA0714 : C

**Comment by zugzwang03** [comment]
> Assign this to me in C++ @Kumar-laxmi

Assigned @Durgesh4993 in C++

**Comment by Kumar-laxmi** [comment]
Due to inactivity I am unassigning @ADITYA0714 @Durgesh4993
