### ISSUE TITLE
DNF Sort

### ISSUE THREAD

**Issue by Anuragwagh** [Kumar-laxmi/Algorithms#280]
DNF sort (also known as "Do Not Follow" sort) is an algorithm for sorting elements in an array. It has been shown to be faster than other sorting algorithms such as quicksort, and is often used in memory-constrained environments where other sorting algorithms may not be viable.
Want to add DNF Sort in CPP and Python,Assign me

**Comment by Kumar-laxmi** [comment]
refer #193
