### ISSUE TITLE
Job Sequencing

### ISSUE THREAD

**Issue by Lakshita2** [Kumar-laxmi/Algorithms#282]
**Is your feature request related to a problem? Please describe.**
Given n jobs with deadlines and profits, our task is to find the optimal sequence to schedule the jobs in order to maximize profit and the maximum profit. Note- If the job is completed within its deadline then only its profit is added.

**Describe the solution**
 I will solve it using greedy approach. I first sort the jobs in decreasing order of their profit. One by one we take a job and check if a slot is available before the deadline. If it is then we allocate the last slot available and add the job's profit to the total profit and add that job at that slot in the schedule
array, otherwise, the job is not scheduled.

**Additional context**
We can add this in the greedy folder.
I will solve it in C++. Please assign it to me.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Lakshita2 : C++

**Comment by stiwari-ds** [comment]
@Kumar-laxmi Please assign it to me for Python.

**Comment by sumitkr2000** [comment]
is anyone working on this issue?
If not please assign me this issue.

**Comment by MrKoshens** [comment]
Please assign me this issue in python

**Comment by Kumar-laxmi** [comment]
Assigned!
@stiwari-ds : Python

**Comment by stiwari-ds** [comment]
> Assigned! @stiwari-ds : Python

Could you please check if I am actually assigned this issue? I cannot see it in my assigned issues. Thanks.

**Comment by Kumar-laxmi** [comment]
Assigned!
@sumitkr2000 : C

**Comment by sumitkr2000** [comment]
@Kumar-laxmi I have been already assigned this issue in C++. I have also created a pr. Why are you assigning me now?

**Comment by Kumar-laxmi** [comment]
> Assigned! @Lakshita2 : C++

@sumitkr2000 Because this issue using C++ has been implemented already

**Comment by sumitkr2000** [comment]
ok @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
> ok @Kumar-laxmi . I don't know C. So please unassign me.

Ok

**Comment by papri24majumder** [comment]
@Kumar-laxmi Please assign it to me for Java.

**Comment by zugzwang03** [comment]
!Assigned : @papri24majumder in Java

**Comment by Kumar-laxmi** [comment]
This issue is only left in ```C```

**Comment by Lakshita2** [comment]
I can solve this in C. Please assign it to me

**Comment by zugzwang03** [comment]
@Lakshita2 assigned for C language
