### ISSUE TITLE
N Queens Problem

### ISSUE THREAD

**Issue by Lakshita2** [Kumar-laxmi/Algorithms#283]
**Is your feature request related to a problem? Please describe.**
The N Queens is the problem of placing N chess queens on an N×N chessboard such that no two queens attack each other. We have to find the placement of the queens.

**Describe the solution you'd like**
I have a simple solution to this. We first consider that each row contains only a single queen. Then, we take an array that will store the column no. of each queen's place. We check whether we can place a queen at column i by checking the previous queens placements. If we cannot find such a column then we backtrack and change the previous queens placements.

**Additional context**
We can add this in Backtracking folder.
I will solve it in C++. Please assign it to me.

**Comment by Kumar-laxmi** [comment]
refer #181
