### ISSUE TITLE
Longest Common Subsequence

### ISSUE THREAD

**Issue by Lakshita2** [Kumar-laxmi/Algorithms#286]
**Is your feature request related to a problem? Please describe.**
Problem Statement- Given two sequences A and B, sequence C is a common subsequence of A and B if C is subsequence of both A and B.  Our task is to find the maximum length common subsequence between two given sequences. A subsequence is a sequence that appears in the same relative order need not to be continuous.

**Describe the solution you'd like**
I can solve this using Dynamic Programming. 

**Additional context**
We can add this in Dynamic-Programming folder.
I will solve it in C++. Please assign it to me.

**Comment by viveksondhiya** [comment]
assign me i will do in java

**Comment by diyagoyal98** [comment]
I can Implement this in c language.
Please assign this to me

**Comment by NikitaGupta-17** [comment]
Please assign this issue in C++ to me.

**Comment by stiwari-ds** [comment]
@Kumar-laxmi Please assign this issue to me for Python.

**Comment by Kumar-laxmi** [comment]
@stiwari-ds What is your status??

**Comment by stiwari-ds** [comment]
> @stiwari-ds What is your status??

Sorry about the late reply, should be making the PR by tomorrow morning.
