### ISSUE TITLE
Moore's Voting Algorithm

### ISSUE THREAD

**Issue by sumitkr2000** [Kumar-laxmi/Algorithms#291]
**Is your feature request related to a problem? Please describe.**
This algorithm finds the majority element in an array. The majority element is the element that appears more than ⌊n / 2⌋ times. 
Please assign me this issue in C++.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Kumar-laxmi** [comment]
refer #235
