### ISSUE TITLE
EDIT DISTANCE

### ISSUE THREAD

**Issue by sumitkr2000** [Kumar-laxmi/Algorithms#293]
**Is your feature request related to a problem? Please describe.**
I would like to add edit distance, a famous dynamic programming problem. Please assign me this issue in C++.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Kumar-laxmi** [comment]
Assigned!
@sumitkr2000 : C++

**Comment by muskan467** [comment]
Please assign this issue to me in Python.

**Comment by muskan467** [comment]
Assign me I will do it in Python

**Comment by Kumar-laxmi** [comment]
Assigned!
@muskan467 : Python

**Comment by stiwari-ds** [comment]
@Kumar-laxmi Is this issue still being worked on? Else I would like to implement in Python.

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi Is the issue in python still to be implemented? Then can you assign me that?

**Comment by stiwari-ds** [comment]
> @Kumar-laxmi Is the issue in python still to be implemented? Then can you assign me that?

I am already implementing it.

**Comment by sitamgithub-MSIT** [comment]
> > @Kumar-laxmi Is the issue in python still to be implemented? Then can you assign me that?
> 
> I am already implementing it.

Ok. If Java has not been done yet then please assign me that @Kumar-laxmi
