### ISSUE TITLE
LRU Cache Design

### ISSUE THREAD

**Issue by siddarth-ba-72** [Kumar-laxmi/Algorithms#302]
**Is your feature request related to a problem? Please describe.**
Cache is the memory very close to CPU and has less access time. Cache is fast but also has less Space compared to RAM. Since it is small we need to have efficient utilization of small size memory. LRU(Least Recently Used) is one of the techniques for this purpose.

**Describe the solution you'd like**
In LRU Cache we keep the recently accessed item least recently used item. This can be implemented using Linked List
I want to implement this in Java and C++. Please assign this task to me.

**Comment by Kumar-laxmi** [comment]
@siddarth-ba-72 Could you implement this in all four languages

**Comment by siddarth-ba-72** [comment]
Ok fine i will implement in all 4 languages

**Comment by siddarth-ba-72** [comment]
@Kumar-laxmi i am ready to implement this in all 4 languages. Please can you assign this task to me?

**Comment by kapil4457** [comment]
Please assign me this issue...

**Comment by Kumar-laxmi** [comment]
@siddarth-ba-72 Kindly implement this within one week or else this issue would be assigned to @kapil4457

**Comment by siddarth-ba-72** [comment]
Thank you for assigning @Kumar-laxmi
