### ISSUE TITLE
Merge Sort

### ISSUE THREAD

**Issue by khushigarg1** [Kumar-laxmi/Algorithms#307]
Merge sort is a divide-and-conquer algorithm that sorts an array (or list) by recursively breaking the array down into smaller sub-arrays, sorting those sub-arrays, and then merging the sorted sub-arrays back together to form the final, sorted array.

Here is the basic approach of merge sort algorithm:
1-Divide the array into two equal-sized subarrays.
2-Recursively sort each subarray.
3-Merge the two sorted subarrays back into the original array in sorted order.

I will do it in C++ Please assign it to me.

**Comment by shauryabaijal** [comment]
Merge sort is a divide-and-conquer algorithm that sorts an array (or list) by recursively breaking it down into smaller sub-arrays, sorting them, and then merging the sorted sub-arrays back together to form the final, sorted array.

The basic approach of the merge sort algorithm is as follows:
1. Separate the array into two equal-sized subarrays.
2-Sort each subarray recursively.
3-In sorted order, merge the two sorted subarrays back into the original array.

I'll write it in Python. Please delegate it to me.

**Comment by Kumar-laxmi** [comment]
Sorry this algorithm has been implemented
