### ISSUE TITLE
merge two sorted linked list

### ISSUE THREAD

**Issue by khushigarg1** [Kumar-laxmi/Algorithms#309]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

1-Initialize two pointers, one for each list, to the head of each list.
2-Compare the data at the current pointer of each list.
3-Take the smaller value and append it to the merged list.
4-Move the pointer of the list that the value came from to the next element.
5-Repeat steps 2-4 until one of the pointers reaches the end of its list.
6-Append the remaining elements of the list that is not yet at the end to the merged list.
7-Return the merged list.
The time complexity of this algorithm is O(n), where n is the total number of elements in both linked lists.

**Describe alternatives you've considered**

**Additional context**

**Comment by Kumar-laxmi** [comment]
Since this is a easy algorithm kindly implement this problem in all four languages

Assigned!
@khushigarg1 : C, C++, Python, Java

**Comment by RAJEEVKUMAR9598** [comment]
@Kumar-laxmi please assign task me in c++ language
