### ISSUE TITLE
Adding Algorithm for Camelcase

### ISSUE THREAD

**Issue by atul1510** [Kumar-laxmi/Algorithms#315]
I want to add an algorithm for converting a text-based sentence into camelCase format 
and I will provide the solution code for this problem in C++ language.

Problem Description :
Program to convert text sentences in CamelCase format.

Examples:
1] INPUT: "this is camel case"
    OUTPUT "thisIsCamelCase"

2] INPUT: "Hi Atul here"
    OUTPUT: "HiAtulHere"

@Kumar-laxmi sir, please assign me this issue.

**Comment by atul1510** [comment]
@zugzwang03 , @Arun9739 Please assign me this issue.

**Comment by Kumar-laxmi** [comment]
@atul1510 Could you implement this algorithm in all four languages

**Comment by Kumar-laxmi** [comment]
Assigned!
@atul1510 : C, C++, Java, Python
