### ISSUE TITLE
Algorithm to solve Rain Water Problem using Stack

### ISSUE THREAD

**Issue by atul1510** [Kumar-laxmi/Algorithms#316]
I want to add an algorithm and for rain water problem using stack
and for this, I would like to code the solution for this problem in C++ language.

Problem Description : 
Input[] = {1, 1, 5, 2, 1, 8 , 1, 0, 2, 1, 2, 6};
Output = 31
It return the maximum water that can be stored.

@Kumar-laxmi sir , please assign me this issue.

**Comment by atul1510** [comment]
@zugzwang03 , @Arun9739 please assign me this issue.

**Comment by Kumar-laxmi** [comment]
@atul1510 Could you implement this algorithm in all four languages

**Comment by Kumar-laxmi** [comment]
Assigned!
@atul1510 : C, C++, Java, Python
