### ISSUE TITLE
Detect loop in Linked list

### ISSUE THREAD

**Issue by Lakshita2** [Kumar-laxmi/Algorithms#319]
**Is your feature request related to a problem? Please describe.**
Given the head of a linked list, check if the linked list has a loop or not.

**Describe the solution you'd like**
I will solve this using two pointer technique (fast and slow pointer).

**Additional context**
This can be added in Linked list folder. 
I will solve this in C++. Please assign it to me.

**Comment by Kumar-laxmi** [comment]
refer #122
