### ISSUE TITLE
inorder, preorder, postorder traversal 

### ISSUE THREAD

**Issue by khushigarg1** [Kumar-laxmi/Algorithms#324]
Preorder traversal visits the root node first, then recursively traverses the left subtree, followed by the right subtree.

Inorder traversal visits the left subtree first, then the root node, followed by the right subtree.

Postorder traversal visits the left subtree first, then the right subtree, followed by the root node.

I would like to solve all traversal in c++. Please assign this to me.

**Comment by Kumar-laxmi** [comment]
refer #177
