### ISSUE TITLE
Create/Update README.md of all folder and sub-folders

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#328]
This is a bonus issue where the contributor is expected to create/update the ```README.md``` of all folder and subfolder explaining what is there in folder with the help of image, diagram and table (if algorithms have to be listed like the repo's README.md).

To get assigned, first please explain your approach to it.

**Comment by dicode04** [comment]
Considering that algorithms are core foundation of computer sciences, it is important to categorize and understand them in a proper flow. Considering that these algorithms are solved using C++, C, Java and Python, we will generally follow a template and provide a structure which data structure is used & it's complexity as well. 

Categories includes linear and non-linear data structures and we can label the algorithms into those sub-categories. Likewise for e.g., TREES is a given folder and we want to merge sub-folder of AVL TREES, BINARY SEARCH TREE, etc., we will label them in TREES folder. And to provide better visualization we will make use of diagrams, images which will help others to understand properly.
