### ISSUE TITLE
Activity Selection 

### ISSUE THREAD

**Issue by shailja2727** [Kumar-laxmi/Algorithms#330]
**Is your feature request related to a problem? Please describe.**
It is classic Greedy Problem .In activity selection problem we always pick the next activity whose finish time is the least among the remaining activities and the start time is more than or equal to the finish time of the previously selected activity. We can sort the activities according to their finishing time so that we always consider the next activity as the minimum finishing time activity

**Describe the solution you'd like**
i)Sort the activities according to their finishing time 
ii)Select the first activity from the sorted array and print it 
ii)Do the following for the remaining activities in the sorted array
If the start time of this activity is greater than or equal to the finish time of the previously selected activity then select this activity and print it

**Additional context**
It can be added in the Greedy-Algorithms folder of C++ directory. I will solve it in C++ ,Please assign it to me

**Comment by Kumar-laxmi** [comment]
@shailja2727 Please implement this in all four languages

**Comment by Kumar-laxmi** [comment]
Assigned!
@shailja2727 : C, C++, Python, Java

**Comment by shailja2727** [comment]
> Assigned! @shailja2727 : C, C++, Python, Java

@Kumar-laxmi I've implemented in all the four languages .Please Check
