### ISSUE TITLE
Painting fence Algorithm

### ISSUE THREAD

**Issue by Sachittarway** [Kumar-laxmi/Algorithms#332]
**Is your feature request related to a problem? Please describe.**
The “Painting Fence Algorithm” states that you are given a fence having some posts (some wooden pieces or some other pieces) and some colors. Find out the number of ways to paint the fence.

**Additional context**
I will be using DP to solve this algorithm.

**Comment by Sachittarway** [comment]
@Kumar-laxmi Please assign me in C++.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Sachittarway : C++
@Vanraj8169 : Java

**Comment by Kumar-laxmi** [comment]
@Sachittarway Is it possible for you to implement in C and @Vanraj8169 is it possible for you to implement in Python
