### ISSUE TITLE
Kadane's Algorithm

### ISSUE THREAD

**Issue by GouravDutta-01** [Kumar-laxmi/Algorithms#335]
**Is your feature request related to a problem? Please describe.**
I want to add Kadane's Algorithm which is used to find the maximum sum of  subarray.

**Programming Language**
Java

**Describe the solution you'd like**
Kadane's algorithm is based on iterative dynamic programming approach.

**Describe alternatives you've considered**
Generally Kadane's Algorithm returns max subarray sum as 0 when all elements in array is negative. But I implemented the Algorithm by considering this case so that it returns the  maximum negative number in this case.

**Additional context**
This issue is raised as a part of my SWOC-S3 contribution.

**Comment by Kumar-laxmi** [comment]
refer #95
