### ISSUE TITLE
Hamiltonian Path

### ISSUE THREAD

**Issue by iianuragii** [Kumar-laxmi/Algorithms#339]
**Is your feature request related to a problem? Please describe.**
A Hamiltonian path (or traceable path) is a path in an undirected or directed graph that visits each vertex exactly once.
It can be considered as a part of Graph in your repo.

**Describe the solution you'd like**
I would like to do this algorithm using Hashmap in java.

**Describe alternatives you've considered**
I can also solve this problem using Dynamic Programming.

**Additional context**
![image](https://user-images.githubusercontent.com/99462598/212459512-67255ba5-c4b9-49cd-bbd4-4f049de4b3c8.png)

**Comment by Kumar-laxmi** [comment]
Please implement this algorithm in all four languages

Assigned!
@iianuragii : C, C++, Java, Python

**Comment by iianuragii** [comment]
while Merging my code it's showing "fatal: unable to access 'https://github.com/Kumar-laxmi/Algorithms.git/': The requested URL returned error: 403".

![image](https://user-images.githubusercontent.com/99462598/213278896-6a23871e-712a-43fc-bd2b-1e7bdf18413b.png)

What should I do?

**Comment by Kumar-laxmi** [comment]
> while Merging my code it's showing "fatal: unable to access 'https://github.com/Kumar-laxmi/Algorithms.git/': The requested URL returned error: 403".
> 
> ![image](https://user-images.githubusercontent.com/99462598/213278896-6a23871e-712a-43fc-bd2b-1e7bdf18413b.png)
> 
> What should I do?

Have you forked the repo?

**Comment by Abhinavcode13** [comment]
Can I address this issue in C/C++ under SS0C 2023?
