### ISSUE TITLE
Reverse a singly linked list in python

### ISSUE THREAD

**Issue by papri24majumder** [Kumar-laxmi/Algorithms#340]
**Is your feature request related to a problem? Please describe.**
No, it is not a problem. I want to write an algorithm to reverse a singly linked list in python

**Describe the solution you'd like**
I will create a linked list first and then reverse it using the iterative approach.

**Describe alternatives you've considered**
No.

**Additional context**

**Comment by Kumar-laxmi** [comment]
Please implement this algorithm in all four languages

**Comment by Kumar-laxmi** [comment]
Assigned!
@papri24majumder : C, C++, Java, Python

And please don't update the README.md

**Comment by trushee** [comment]
@Kumar-laxmi pls assign me this issue. Thanks
