### ISSUE TITLE
Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by VaibhavArora314** [Kumar-laxmi/Algorithms#346]
**Is your feature request related to a problem? Please describe.**
I want to add a solution to the problem of searching in a rotated sorted array in O(log n).

*What is a rotated sorted array?*
There is an integer array (say nums) sorted in ascending order (with distinct values). Suppose nums = [0,1,2,4,5,6,7], now we rotated nums 4 times then it will become  [4,5,6,7,0,1,2]. This is an example of a rotated sorted array.

*Problem example*
Input: nums = [4,5,6,7,0,1,2], search = 1
Output: 5 (index of element 1)

**Describe the solution you'd like**
I want to use a modified version of the binary search. First, I will find the min element in the array then I will search on the side on which the element should be present.

Please assign me this issue in C++, I am willing to work on it.

**Comment by Ultimateutkarsh11** [comment]
@Kumar-laxmi please assign this issue to me in C language.

**Comment by goyalh4164** [comment]
Please assign this to me in java

**Comment by Kumar-laxmi** [comment]
Kindly don't open issue pertaining to LeetCode problems

**Comment by VaibhavArora314** [comment]
> Kindly don't open issue pertaining to LeetCode problems

I was unaware of this rule, could you please remove the spam label. I will rewrite the issue following the guidelines of the project.
