### ISSUE TITLE
Peak Index in a Mountain

### ISSUE THREAD

**Issue by Ultimateutkarsh11** [Kumar-laxmi/Algorithms#347]
**Is your feature request related to a problem? Please describe.**
I want to add a solution to the problem "Peak index in a mountain".

*What is a mountain array?*
A mountain array is an array which is increasing in the first part and then decreasing in the second part.
The peak element is that which is the largest element in the array. Suppose i is the the index of peak element, then:
arr[0] < arr[1] < ... < arr[i - 1] < arr[i] > arr[i + 1] > ... > arr[arr.length - 1]

*Example:*
Input: arr = [0,3,5,7,10,8,4,3,2]
Output: 4 (index of 10)

**Describe the solution you'd like**
I would like to solve this problem by using a modified version of Binary Search.
Please assign this issue to me in C++, I am willing to work on it!

**Comment by VaibhavArora314** [comment]
@Kumar-laxmi please assign me this issue in C.

**Comment by GouravDutta-01** [comment]
@Kumar-laxmi Please assign me this issue in java
