### ISSUE TITLE
Adding Reverse LinkList Algorithm in C++

### ISSUE THREAD

**Issue by atul1510** [Kumar-laxmi/Algorithms#349]
I want to add an algorithm for reversing a LinkedList 
and for this, I will provide the solution code in C++ language.

Problem Description :
Program to implement reverse a linked list in C++

Examples:
1] INPUT: 
Entered linked list
89 35 16 7

OUTPUT: 
Reversed the given Linked list
7 16 35 89

@Kumar-laxmi @zugzwang03  @Arun9739 please assign me this issue.

**Comment by Kumar-laxmi** [comment]
refer #340
