### ISSUE TITLE
Index sequential search

### ISSUE THREAD

**Issue by Aaditya1612** [Kumar-laxmi/Algorithms#352]
**Is your feature request related to a problem? Please describe.**
This issue is to request for adding index sequential search which has not yet been included in this project.

**Describe the solution you'd like**
I would like to add code for Index Sequential Search in Java, C, C++ and Python

**Issue Request*
@Kumar-laxmi , I hereby request you to please assign this to me under SWoC'23

**Comment by Aaditya1612** [comment]
@Kumar-laxmi please review this issue.

**Comment by Kumar-laxmi** [comment]
@Aaditya1612 Could you implement this in all four languages

**Comment by Aaditya1612** [comment]
@Kumar-laxmi Yes I can implement this in all four languages.

**Comment by Aaditya1612** [comment]
@Kumar-laxmi Why you have added **question** label? It's a searching algorithm.
Correct me if I am wrong.

**Comment by Nikhil743** [comment]
hello @Kumar-laxmi please assigned me , I can code in all four language
