### ISSUE TITLE
Median of 2 sorted arrays in  O(log (m+n))

### ISSUE THREAD

**Issue by CS50X-RGB** [Kumar-laxmi/Algorithms#356]
**Is your feature request related to a problem? Please describe.**
Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.
The overall run time complexity should be O(log (m+n)).

**Describe the solution you'd like**
We would use concept of cutting an array and then comparing and finding the array which would not only decrease the space complexity and but also the time complexity from O(n²) to  O(log (m+n)).

**Comment by Kumar-laxmi** [comment]
Could you give an elaborate description of the problem

**Comment by CS50X-RGB** [comment]
@Kumar-laxmi Updated the problem

**Comment by CS50X-RGB** [comment]
@Kumar-laxmi any update??

**Comment by Kumar-laxmi** [comment]
Could explain with the help of examples and diagrams

**Comment by CS50X-RGB** [comment]
Yeah i can

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi I can take up this issue. Also can explain the issue in way you want.
