### ISSUE TITLE
Catalan numbers

### ISSUE THREAD

**Issue by ashadmuneer** [Kumar-laxmi/Algorithms#358]
Catalan numbers algorithm is Dynamic Programming algorithm. In combinatorial mathematics, the Catalan numbers form a sequence of natural numbers that occur in various counting problems, often involving recursively-defined objects.

**Describe the solution you'd like**

Catalan numbers are defined as a mathematical sequence that consists of positive integers, which can be used to find the number of possibilities of various combinations.
I will write the code in C++ for this and I request you to kindly assign me this algorithm.

**Comment by ashadmuneer** [comment]
@Kumar-laxmi pls assign this issue to me

**Comment by MrKoshens** [comment]
Please assign this issue to me in C and python

**Comment by Kumar-laxmi** [comment]
@ashadmuneer Could you implement this algorithm in all four languages

**Comment by ashadmuneer** [comment]
@Kumar-laxmi Ok I will do in all four languages

**Comment by ashadmuneer** [comment]
@Kumar-laxmi pls assign to me

**Comment by Kumar-laxmi** [comment]
Assigned!
@ashadmuneer : C, C++, Python, Java
