### ISSUE TITLE
Coin Change Problem in Dynamic Programming

### ISSUE THREAD

**Issue by sshiwangi** [Kumar-laxmi/Algorithms#359]
**Is your feature request related to a problem? Please describe.**
Coin change problem is a very famous problem of dynamic programming and it is not present in the folder.

**Describe the solution you'd like**
I would like to add coin change problem along with its code, proper comments, and will also add a readme file describing the problem for better understanding.

**Describe alternatives you've considered**

**Additional context**

**Comment by sshiwangi** [comment]
@Kumar-laxmi please assign me this issue under swoc.

**Comment by Kumar-laxmi** [comment]
@sshiwangi Could you implement this in all four languages

**Comment by sshiwangi** [comment]
> @sshiwangi Could you implement this in all four languages

Yes I will implement it in all four languages but can you tell me should I put the same problem in all 4 languages folder?

**Comment by Kumar-laxmi** [comment]
> > @sshiwangi Could you implement this in all four languages
> 
> Yes I will implement it in all four languages but can you tell me should I put the same problem in all 4 languages folder?

Yeah in ```Dynamic Programming```

**Comment by Kumar-laxmi** [comment]
Assigned!
@sshiwangi : C, C++, Python, Java
