### ISSUE TITLE
Unique Path 2

### ISSUE THREAD

**Issue by Kaushan-Dutta** [Kumar-laxmi/Algorithms#360]
**Is your feature request related to a problem? Please describe.**
It is a backtracking problem where the a robot is at (x,y) position and we have to check whether the robot can reach at (x1,y1) position , also there are a number of walls where the robot cannot walk.

**Describe the solution you'd like**
I would adopt the reccursive based approach to solve this problem and use backtracking method.

**Describe alternatives you've considered**
I could use loop structure but it would take a long time and then also the problem will be solved is not clear

**Comment by Kumar-laxmi** [comment]
Could you give an elaborate description of the problem you would like to solve

**Comment by Kumar-laxmi** [comment]
Please don't raise issue to implement LeetCode questions
