### ISSUE TITLE
Binary Tree Traversal using one traversal

### ISSUE THREAD

**Issue by sumitkr2000** [Kumar-laxmi/Algorithms#364]
**Is your feature request related to a problem? Please describe.**
Hey, @Kumar-laxmi I want to add an algorithm to Tree in C++ by which we can find the inorder, preorder, and postorder traversals just by using gone traversal iteratively. Please assign me this issue. Thank you!

**Describe the solution you'd like**
Using stack.

**Describe alternatives you've considered**

**Additional context**

**Comment by Kumar-laxmi** [comment]
refer #177
