### ISSUE TITLE
[Bug]: In Bubble Sort CPP inner loop does redundant comparison upto last index of array

### ISSUE THREAD

**Issue by Hunking9797** [Kumar-laxmi/Algorithms#367]
### What happened?

The earlier inner loop of bubble sort is used to compare until the last index of the array which is redundant, we can compare only up to 1 less index than the outer loop.

### Version

1.0.2 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kumar-laxmi** [comment]
Please elaborate your approach to make this algorithm more efficient

**Comment by Hunking9797** [comment]
The earlier inner loop of the bubble sort was used to compare up to array_size-1 index, I'm improving the algorithm by only allowing comparison up to array_size - outer_loop_iterator - 1.

**Comment by Kumar-laxmi** [comment]
@Hunking9797 Assigned!
