### ISSUE TITLE
Bankers Deadlock Avoidance Algorithm in C

### ISSUE THREAD

**Issue by Harikaraja** [Kumar-laxmi/Algorithms#371]
The banker’s algorithm is a resource allocation and deadlock avoidance algorithm that tests for safety .

There will be some processes and resources and the processes will be requesting some resources . Resource allocation will be done to the processes such that no process will be deadlocked . 

![image](https://user-images.githubusercontent.com/80022302/212550092-b0bd17c0-c1a1-4407-a677-71dbedd69d5b.png)

If any process is deadlocked then the resources are reclaimed from the process to prevent the deadlock.

This Algorithm consists of Safety algorithm and Resource request algorithm.

safety algorithm is used to check whether the system  is in safe state or not and resource request algorithm is used to assign requested resources to the processes.

## Steps in Safety Algorithm are:

1. Work = Available
   Finish[i] = false , where i=0,1,2,3,....n

2. Need[i]<Work[i]
   Finish[i]=false , i=0,1,2,3...n

3 .  Work[i]=Work[i]+Allocated[i]
       Finish[i]=true

4. If finish[i]=true for all i=0,1,2,3..n then the syatem is considered to be in safe state.

## Steps in Resource request algorithm :

Available[i,j]=Available[i,j]-Request[i,j]
Allocation[i,j]=Allocation[i,j]+Request[i,j]
Need[i,j]=Need[i,j]-Request[i,j]

## Example

![image](https://user-images.githubusercontent.com/80022302/212549754-31a25396-2590-42cc-9311-0b4161293ebf.png)

Calculating Need 

![image](https://user-images.githubusercontent.com/80022302/212549788-5a6beccf-e53b-4c0b-bd81-fdfa011dccd7.png)

### For Process P1:

Need <= Available

7, 4, 3 <= 3, 3, 2 condition is false.

So, we examine another process, P2.

### For Process P2:

Need <= Available

1, 2, 2 <= 3, 3, 2 condition true

New available = available + Allocation

(3, 3, 2) + (2, 0, 0) => 5, 3, 2

Similarly, we examine another process P3.

### For Process P3:

P3 Need <= Available

6, 0, 0 < = 5, 3, 2 condition is false.

Similarly, we examine another process, P4.

### For Process P4:

P4 Need <= Available

0, 1, 1 <= 5, 3, 2 condition is true

New Available resource = Available + Allocation

5, 3, 2 + 2, 1, 1 => 7, 4, 3

Similarly, we examine another process P5.

### For Process P5:

P5 Need <= Available

4, 3, 1 <= 7, 4, 3 condition is true

New available resource = Available + Allocation

7, 4, 3 + 0, 0, 2 => 7, 4, 5

Now, we again examine each type of resource request for processes P1 and P3.

### For Process P1:

P1 Need <= Available

7, 4, 3 <= 7, 4, 5 condition is true

New Available Resource = Available + Allocation

7, 4, 5 + 0, 1, 0 => 7, 5, 5

So, we examine another process P2.

### For Process P3:

P3 Need <= Available

6, 0, 0 <= 7, 5, 5 condition is true

New Available Resource = Available + Allocation

7, 5, 5 + 3, 0, 2 => 10, 5, 7

##  Hence, we execute the banker's algorithm to find the safe state and the safe sequence like P2, P4, P5, P1 and P3.

**Comment by Kumar-laxmi** [comment]
refer #151
