### ISSUE TITLE
N Queens Problem 

### ISSUE THREAD

**Issue by khushigarg1** [Kumar-laxmi/Algorithms#373]
The basic steps of the backtracking algorithm for the n queens problem are as follows:

Place a queen in the first column of the first row.
Move to the next column.
If a conflict is found, backtrack and try a different position for the queen.
If a solution is found, stop.
Repeat steps 2-4 for each column until a solution is found or all columns have been checked.

I would like to solve this problem in C++ please assign it to me.

**Comment by Kumar-laxmi** [comment]
refer #181
