### ISSUE TITLE
Algorithm that uses stack to determine the largest area in given histogram

### ISSUE THREAD

**Issue by atul1510** [Kumar-laxmi/Algorithms#374]
I want to add an algorithm that uses "stack" to determine the largest area in a given histogram.
and I will provide the solution code for this problem in C++ language.

Problem Description :
Find the largest rectangular area possible in a given histogram

Examples:
1] INPUT: 
    h.push_back(5);
    h.push_back(4);
    h.push_back(1);
    h.push_back(6);
    h.push_back(3);
    h.push_back(2);
    h.push_back(2);

OUTPUT: 8

@Kumar-laxmi @zugzwang03 @Rishikavishnoi @072arushi @Sanjanabharadwaj25  please assign me this issue.

**Comment by 072arushi** [comment]
@atul1510 you have been assigned this issue. All the best.

**Comment by Kumar-laxmi** [comment]
@atul1510 Could you implement this in all four languages

**Comment by atul1510** [comment]
> @atul1510 Could you implement this in all four languages

Sure, I can implement this in all four languages.
C++,C,Java,Python
