### ISSUE TITLE
Next greater element using stack

### ISSUE THREAD

**Issue by sumitkr2000** [Kumar-laxmi/Algorithms#376]
**Is your feature request related to a problem? Please describe.**
Hey, @Kumar-laxmi I want to add a famous algorithm used to find the next greater element using stack. Please assign me this issue in C++. Thank you!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sumitkr2000** [comment]
Please assign me this issue @Kumar-laxmi

**Comment by sumitkr2000** [comment]
Please assign me this issue @Kumar-laxmi

**Comment by sumitkr2000** [comment]
Please assign me this issue @Kumar-laxmi

**Comment by sumitkr2000** [comment]
Please assign me this issue @Kumar-laxmi

**Comment by Volcano-Dragon** [comment]
I can do this in python also.

**Comment by sumitkr2000** [comment]
Please assign me this issue @Kumar-laxmi

**Comment by sumitkr2000** [comment]
Please assign me this issue @Kumar-laxmi

**Comment by viveksondhiya** [comment]
@Kumar-laxmi  please assign me i will do in java

**Comment by Kumar-laxmi** [comment]
@viveksondhiya Could you implement this algo in C and Java

**Comment by viveksondhiya** [comment]
> @viveksondhiya Could you implement this algo in C and Java
Ok I will do in both languages
