### ISSUE TITLE
Compare Two Linked Lists

### ISSUE THREAD

**Issue by NikitaGupta-17** [Kumar-laxmi/Algorithms#377]
**Is your feature request related to a problem? Please describe.**
We are given 2 linked list and we have to identify whether the two linked are identical or not(value and the position of nodes coating value must be same)

**Describe the solution you'd like**

First of all I take 2 linked list input from user. 
Then I create a compare function which traverse both linked list from starting and compare each node value if the values are same then we check for next node else we return from the function and print "Not Identical" otherwise print "Identical".

EX :
Let the user input 1st linked list:
1->2->4->3
And 2nd linked list:
1->2->3->4

Starting from first node of 1st and 2nd linked list both value same so we go to next node.
The value in 2nd node is also same so we go to 3rd node.
The value of 3rd node is not same so we print Not identical.

**Comment by Kumar-laxmi** [comment]
Please don't raise issues pertaining to general operations
