### ISSUE TITLE
Counting Sort In C++

### ISSUE THREAD

**Issue by NikitaGupta-17** [Kumar-laxmi/Algorithms#378]
**Is your feature request related to a problem? Please describe.**
Counting sort is an sorting algorithm for sorting an array.
It works by counting the number of objects having distinct key values (a kind of hashing). Then some arithmetic operation is performed to find the position of each element.

**Describe the solution you'd like**
I solved this by creating 3 arrays - C,A,B 
A contains initially unsorted array
B will contain the sorted array
Initially C array stores the count of each variable.
Then running loop and setting 
C[i]=C[i]+C[i-1]
Then c[i] will contain the count of numbers less than or equal to i
Then we run the loop from 0 till length of A
And add the I th element at correct position using C array in Array B.
Array B is the final output.

**Comment by Sanjanabharadwaj25** [comment]
@NikitaGupta-17 Counting Sort algorithm already exists. Please take up another problem.

**Comment by Kumar-laxmi** [comment]
refer #121
