### ISSUE TITLE
Stack Using Priority Queue in C

### ISSUE THREAD

**Issue by NikitaGupta-17** [Kumar-laxmi/Algorithms#379]
**Is your feature request related to a problem? Please describe.**
In priority queue, we assign priority to the elements that are being pushed. A stack requires elements to be processed in Last in First Out manner. 
So we have to create Stack using priority queue.

I can code in C .Please assign it to me.

**Comment by silentspectator20** [comment]
Please assign me this issue in C++. @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
@NikitaGupta-17 Could you implement the algorithm in all four languages

**Comment by Kumar-laxmi** [comment]
Assigned!
@NikitaGupta-17 : C, C++, Java, Python
