### ISSUE TITLE
STL Sorting in String 

### ISSUE THREAD

**Issue by RAJEEVKUMAR9598** [Kumar-laxmi/Algorithms#387]
Is your feature request related to a problem? Please describe.
Here a shortcut method with less time complexity given which is using STL ( Standard template library).
We can sort the activities according to their finishing time so that we always consider the next activity as the minimum finishing time complexity.

Describe the solution you'd like
1. Use a specific header file.
2. add a loop.
3. Use sort function.

Additional context

It can be added in Sorting -Algorithms folder of C++ directory. I will solve it in C++ ,Please assign it to me @Kumar-laxmi @Arun9739 

![STL](https://user-images.githubusercontent.com/99285150/212841048-7cd357cf-8102-4b26-9dc8-f70642fc4a54.PNG)

**Comment by Kumar-laxmi** [comment]
Kindly raise issues pertaining to algorithm and not for working of library functions
