### ISSUE TITLE
KMP(Knuth-Morris-Pratt) ALGO in C++

### ISSUE THREAD

**Issue by khushigarg1** [Kumar-laxmi/Algorithms#388]
The KMP (Knuth-Morris-Pratt) algorithm is a string matching algorithm that is used to find patterns in text.
     
Algorithm for KMP:- 
-> Initialize a variable 'j' to 0 and an empty array 'lps' of size equal to the length of the pattern.
-> Iterate through the pattern and for each character at index 'i':
     a. Compare the current character with the next character in the pattern.
     b. If they match, increment 'j' and set the value of lps[i] to 'j'.
     c. If they don't match, check if 'j' is not 0. If it is not, set 'j' to the value of lps[j-1]. Repeat step 2a and 2b until a match is found or j 
     becomes 0.
-> Initialize variables 'i' and 'j' to 0, to keep track of the current position in the text and pattern respectively.
-> Iterate through the text and for each character at index 'i':
     a. Compare the current character in the text with the character at the same position in the pattern.
     b. If they match, increment both 'i' and 'j'.
     c. If they don't match, check if 'j' is not 0. If it is not, set 'j' to the value of lps[j-1]. Repeat step 4a and 4b until a match is found or j 
     becomes 0.
     d. If j is equal to the length of the pattern, a match has been found, and the index of the match in the text is i-j.
-> If a match is not found, return -1.

Time Complexity:- O(n+m)
I can code in C++. Please assign it to me.

**Comment by Kumar-laxmi** [comment]
refer #138
