### ISSUE TITLE
Rabin Karp in C++

### ISSUE THREAD

**Issue by khushigarg1** [Kumar-laxmi/Algorithms#389]
**Is your feature request related to a problem? Please describe.**
The Rabin-Karp algorithm is a string matching algorithm that uses a rolling hash function to quickly compare patterns in text.

The algorithm starts by pre-computing the hash value of the pattern.
It then iterates through the text, computing the hash value of each substring of length equal to the length of the pattern.
The algorithm then compares the computed hash value with the pre-computed hash value of the pattern.
If the two hash values match, the algorithm performs a character-by-character comparison of the substring to the pattern to confirm the match.
If a match is found, the algorithm returns the starting index of the match in the text.
If a match is not found, the algorithm returns -1.

average time complexity:-  O(n+m)
I can code in C++, Please assign it to me

**Comment by Kumar-laxmi** [comment]
refer #96
