### ISSUE TITLE
Bisection Algorithm in C++

### ISSUE THREAD

**Issue by programmingninjas** [Kumar-laxmi/Algorithms#390]
Bisection method to find roots of an equation.
Category: Maths

**Comment by Kumar-laxmi** [comment]
@programmingninjas Could you implement this in all four languages

**Comment by programmingninjas** [comment]
@Kumar-laxmi Yes why not

**Comment by Kumar-laxmi** [comment]
Assigned!
@programmingninjas : C, C++, Java, Python
