### ISSUE TITLE
Lowest Common Ancestors in a binary tree

### ISSUE THREAD

**Issue by khushigarg1** [Kumar-laxmi/Algorithms#392]
**Is your feature request related to a problem? Please describe.**
LCA is the lowest node in the tree that has both n1 and n2 as descendants, where n1 and n2 are the nodes for which we wish to find the LCA. It is the lowest level parent shared by two nodes within a tree.
              1
         2        3
    4      5 6      7
then LCA for (4,5) = 2
 LCA for (4,2) = 2
I can do it in c++. please assign it to me.

**Comment by viveksondhiya** [comment]
@Kumar-laxmi  please assign me i will do in java
