### ISSUE TITLE
Binary Tree from preorder and inorder

### ISSUE THREAD

**Issue by khushigarg1** [Kumar-laxmi/Algorithms#393]
**Is your feature request related to a problem? Please describe.**

As we know in preorder, leftmost elemnt is the root of tree. we will search that node in inorder sequence and will find out all elements on the left side of that node will be in the left substree and elements on right will be in the right subtree. so we can contrust bianry tree by recursion.

I can code in C++. Please assign it to me.

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi Can the label 'stand by' be removed now? I can contribute in python for this specific issue.
