### ISSUE TITLE
An algorithm that contain details of the book present in the library using OOPS

### ISSUE THREAD

**Issue by atul1510** [Kumar-laxmi/Algorithms#396]
An algorithm that contains all details of the book present in a library using OOPS
I want to add an algorithm that contains all details of the book present in a library using OOPS
and for this, I will provide the solution code for this problem in C++ language.

Problem Description :
A book that contains the attribute BookID, book name, and price. It also contains member functions to input and show its attributes.

Examples:
1] INPUT: 
Enter the writer's name:
Atul Kumar
Enter the details of the book:
Enter the Book ID:
4567
Enter the Book Name:
Algorithms
Enter the Price 
500
OUTPUT :

========================= DETAILS ===================================
==================================================================

Writer's name: Atul Kumar
The details of the book are:
Book ID: 4567
Book Name: Algorithms
Price: 500

@Kumar-laxmi  @072arushi @zugzwang03 @Sanjanabharadwaj25 @Rishikavishnoi @Arun9739  please assign me this issue.

**Comment by Kumar-laxmi** [comment]
This looks more like some Capstone Project
