### ISSUE TITLE
Jump searching in cpp

### ISSUE THREAD

**Issue by ADITYA0714** [Kumar-laxmi/Algorithms#408]
kindly issue me the code of jump searching in C++ language.

Description:-
A jump search or block search refers to a search algorithm for ordered lists. It works by first checking all items Lₖₘ, where k\in \mathbb {N} and m is the block size, until an item is found that is larger than the search key.

**Comment by Kumar-laxmi** [comment]
could you explain with the help of some diagram

**Comment by Kumar-laxmi** [comment]
And would you like to implement this algorithm in all four languages

**Comment by ADITYA0714** [comment]
Yes, surely I can do this in java and c language too

**Comment by ADITYA0714** [comment]
![WhatsApp Image 2023-01-20 at 9 34 51 AM](https://user-images.githubusercontent.com/95866052/213615357-a191956d-b1a6-4a20-8aae-1b01a0e3f679.jpeg)


This is the diagram representation of the jump search.

**Comment by Kumar-laxmi** [comment]
Assigned!
@ADITYA0714 : C, C++, Java, Python

**Comment by ADITYA0714** [comment]
I Have made the code :
what all should i include before pull request.
it would be grt if  you tell in simplier manner as i'm  new to these things

**Comment by sumitkr2000** [comment]
Hey, @Kumar-laxmi is this issue available in C++? If not, please assign me this issue in C++.

**Comment by Kumar-laxmi** [comment]
> Hey, @Kumar-laxmi is this issue available in C++? If not, please assign me this issue in C++.

Could you implement this in all languages

**Comment by sumitkr2000** [comment]
I only know c++. But if you want me to implement ot in all languages I will have to take help of Google. Are you open to it?

**Comment by Kumar-laxmi** [comment]
> I only know c++. But if you want me to implement ot in all languages I will have to take help of Google. Are you open to it?
It would be Ok for me until it is directly not plagiarised from Google

**Comment by Kumar-laxmi** [comment]
Assigned!
@sumitkr2000 : C, C++, Python, Java

**Comment by sumitkr2000** [comment]
Ok!
