### ISSUE TITLE
Fibbonacci series 

### ISSUE THREAD

**Issue by ADITYA0714** [Kumar-laxmi/Algorithms#409]
Kindly issue me the fibbonacci series code in C language. 

Description:-
The Fibonacci numbers, commonly denoted Fₙ, form a sequence, the Fibonacci sequence, in which each number is the sum of the two preceding ones. The sequence commonly starts from 0 and 1, although some authors start the sequence from 1 and 1 or sometimes from 1 and 2

**Comment by Kumar-laxmi** [comment]
give proper description

**Comment by ADITYA0714** [comment]
the Fibonacci numbers, commonly denoted Fₙ, form a sequence, the Fibonacci sequence, in which each number is the sum of the two preceding ones. The sequence commonly starts from 0 and 1, although some authors start the sequence from 1 and 1 or sometimes from 1 and 2

**Comment by Kumar-laxmi** [comment]
Can you implement this in all 4 languages using recursion and Dynamic Programming

**Comment by ADITYA0714** [comment]
yes, I can do in all four language.

**Comment by ADITYA0714** [comment]
kindly assign me in all 4 language

**Comment by MrKoshens** [comment]
kindly assign me this issue in all 4 languages

**Comment by abhishekbhonde** [comment]
kindly assign me this i can do it in 4 languages.

**Comment by Kumar-laxmi** [comment]
Assigned!
@ADITYA0714 : C, C++, Java, Python

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi Is the work still on? If it is can you assign me that?

**Comment by sumitkr2000** [comment]
Hey, @Kumar-laxmi is this issue available in C++? If not, please assign me this issue in C++.

**Comment by Kumar-laxmi** [comment]
Assigned!
@sitamgithub-MSIT : C, C++, Java, Python

**Comment by Abhinavcode13** [comment]
Can I work on this issue if not done?

**Comment by shubhamjaiswar43** [comment]
Assign this to me (C, C++, Java, Python, Dp in C)

**Comment by shubhamjaiswar43** [comment]
Assign this to me (C, C++, Java, Python, Dp in C++)

**Comment by shubhamjaiswar43** [comment]
Assign this to me (C, C++, Java, Python, Dp)

**Comment by Kumar-laxmi** [comment]
Assigned!
@shubhamjaiswar43 : C, C++, Java, Python

**Comment by shubhamjaiswar43** [comment]
> Assigned! @shubhamjaiswar43 : C, C++, Java, Python

In Which File it should be added ???

**Comment by shubhamjaiswar43** [comment]
> Assigned! @shubhamjaiswar43 : C, C++, Java, Python

In the code, I have to print the whole series till nth term or only the nth term of the series ??

**Comment by Kumar-laxmi** [comment]
> > Assigned! @shubhamjaiswar43 : C, C++, Java, Python
> 
> In the code, I have to print the whole series till nth term or only the nth term of the series ??

@shubhamjaiswar43 You need to print the whole series till nth term

**Comment by Nikhil743** [comment]
Assign this to me (C, C++, Java, Python, Dp)
