### ISSUE TITLE
An Algorithm to find shortest unsorted continuous subarray

### ISSUE THREAD

**Issue by atul1510** [Kumar-laxmi/Algorithms#417]
I want to add an algorithm that finds the shortest unsorted continuous subarray.

I will provide the solution code for this problem in  C++ / C / Java / Python

Problem Description :

Given an unsorted array of size n, find the minimum length subarray 
 such that sorting this subarray makes the whole array sorted. 

Example: 

1] INPUT:  int arr[] = {12, 15, 17, 23, 31, 38, 34, 36, 37, 55, 62};

OUTPUT: The unsorted subarray which makes the given array
sorted lies between indices 5 and 8.

@Kumar-laxmi @072arushi @zugzwang03 @Arun9739 @Rishikavishnoi @Sanjanabharadwaj25 Please assign me this issue.

**Comment by 072arushi** [comment]
@atul1510 assigned

**Comment by Kumar-laxmi** [comment]
@atul1510 Please implement this algorithm in all four languages

**Comment by atul1510** [comment]
> @atul1510 Please implement this algorithm in all four languages

Sure sir.
