### ISSUE TITLE
 Linked List Palindrome or not

### ISSUE THREAD

**Issue by Lakshita2** [Kumar-laxmi/Algorithms#426]
**Is your feature request related to a problem? Please describe.**
Given the head of a singly linked list, we have to check whether it is palindrome or not.

**Describe the solution you'd like**
I will first reverse the second half of linked list, then compare the first half with the second half node by node. 

**Additional context**
We can add this in Linked List folder.
I will solve this in C++. Please assign it to me.

**Comment by Raj-Kedia** [comment]
Please assign me this issue. I will do this in python.

**Comment by Kumar-laxmi** [comment]
@Lakshita2 Could you implement this in all four languages

**Comment by Lakshita2** [comment]
Yes I can, please assign it to me.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Lakshita2 : C, C++, Java, Python
