### ISSUE TITLE
Gnome Sort in C

### ISSUE THREAD

**Issue by Abhilash1781** [Kumar-laxmi/Algorithms#427]
**Is your feature request related to a problem? Please describe.**
I will work on Gnome sort in  C . Gnome sort is a sorting algorithm based on the concept of a Garden Gnome sorting his flower pots. A garden gnome sorts the flower pots like first he checks a flower pot next to him and previous one , if they are in correct order , he moves one step forward . If not he swaps the pot until it suits in right order . 

**Describe the solution you'd like**
Gnome sort is similar to Insertion sort but not exactly the same . 

**Describe alternatives you've considered**
 -NIL-

**Additional context**
-NIL-

**Comment by Kumar-laxmi** [comment]
Could you explain this with the help of Diagrams

**Comment by Abhilash1781** [comment]
So , there is an array of elements , let's say 5 3 2 4. 
1) You are at zeroth position , now move one step forward to your right .
2) Check whether this element is greater than or equal to previous element . If yes move right . 
3) If the current element is smaller than previous element , then swap the elements . 
4) Repeat these steps till the end of an array . If it reaches the array is sorted . 

![Gnome sort - Wikipedia - Google Chrome 22-01-2023 18_44_40](https://user-images.githubusercontent.com/72621930/213917741-20ebac2e-8ba9-4d7f-92df-8dbcc093cee4.png)

I found this example in -  https://en.wikipedia.org/wiki/Gnome_sort
If you want to visually see how gnome sorting works , then checkout this link - https://www.sortvisualizer.com/gnomesort/

**Comment by Dharnish38** [comment]
Can you assign this issue to me in C++, Java and Python  @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Assigned!
@Abhilash1781 : C
@Dharnish38 : C++, Java, Python

**Comment by Kumar-laxmi** [comment]
@Abhilash1781 What is your status on this issue

**Comment by Abhilash1781** [comment]
Sorry , I will contribute by today night
