### ISSUE TITLE
REDUCED ROW ECHELON FORM (RREF)

### ISSUE THREAD

**Issue by Volcano-Dragon** [Kumar-laxmi/Algorithms#428]
**Is your feature request related to a problem? Please describe.**
It is related to the mathematical algorithm to convert the augmented matrix to the ROW ECHELON FORM. It is very useful in calculating linear algebra calculations.

**Describe the solution you'd like**
The user will enter the augmented matrix after that step-wise step we will calculate its row-echelon form by displaying each row's operations.

**Additional context**
I can do this in Python and C++. Plz assign this to me.

**Comment by Kumar-laxmi** [comment]
Since this is an easy issue, it has to be implemented in all four languages

Assigned!
@Volcano-Dragon : C, C++, Java, Python

**Comment by Volcano-Dragon** [comment]
Sorry, due to timing issues, I'm unable to complete this algorithm before March 15 (i.e., the last date for the SWOC S3 project submission).
I will submit it later on (as a normal contribution).
Thank you :)
