### ISSUE TITLE
To remove duplicates from a sorted array in C++

### ISSUE THREAD

**Issue by Vyshnavi21504** [Kumar-laxmi/Algorithms#429]
Hello, I am Vyshnavi Madhusudhan a contributor from SWOC3.0. Please assign me this in cpp

**Comment by kapil4457** [comment]
Hello @Kumar-laxmi  please assign me this issue...I can do this in c++ using O(n) time complexity;

**Comment by Raj-Kedia** [comment]
Hello @Kumar-laxmi. Please assign me this. I can do this in C++ or python, which will be perfect for you.

**Comment by Kumar-laxmi** [comment]
@Vyshnavi21504 Could you implement this algorithm in all four languages

**Comment by Vyshnavi21504** [comment]
can u please mention the four language you want me to do.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Vyshnavi21504 : C, C++, Java, Python

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi Is the work still on? If it is can you assign me that?

**Comment by sumitkr2000** [comment]
Hey, @Kumar-laxmi is this issue available in C++? If not, please assign me this issue in C++.

**Comment by Kumar-laxmi** [comment]
Assigned!
@sitamgithub-MSIT : C, C++, Java, Python

**Comment by shubhamjaiswar43** [comment]
Hello , please asssign this issue to me

**Comment by Nikhil743** [comment]
Hello @Kumar-laxmi. Please assign me this. I can do this in C++ or python, which will be perfect for you.
