### ISSUE TITLE
Cocktail Sort Algorithm

### ISSUE THREAD

**Issue by Ayatisonkar** [Kumar-laxmi/Algorithms#433]
Cocktail Sort is a bidirectional bubble sort.It is both a stable sorting algorithm and a comparison sort.The algorithm differs from a bubble sort in that it sorts both directions on each pass through the list and solves the problem of turtles in bubble sort.
[cocktail.zip](https://github.com/Kumar-laxmi/Algorithms/files/10475159/cocktail.zip)
[cocktail shaker screenshots.odt](https://github.com/Kumar-laxmi/Algorithms/files/10475188/cocktail.shaker.screenshots.odt)

**Comment by Kumar-laxmi** [comment]
Please follow the template for PR

**Comment by Ayatisonkar** [comment]
Respected sir,
Can you please tell me the meaning of authored the thread because i am new
to github.
