### ISSUE TITLE
Cocktail Shaker Sort

### ISSUE THREAD

**Issue by Ayatisonkar** [Kumar-laxmi/Algorithms#436]
Not a bug or problem. I want to add the Cocktail Shaker Sort algorithm which is often used as educational tool and solving turtles in bubble sort.

Cocktail shaker sort is a slight variation of bubble sort. It differs in that instead of repeatedly passing through the list from bottom to top, it passes alternately from bottom to top and then from top to bottom. It can achieve slightly better performance than a standard bubble sort.
Problem Description :

Given an unsorted array of size n, print the array in sorted form using Cocktail Shaker Short.

Example:

1] INPUT: int arr[] = {12, 15, 17, 31,20, 38, 34};

OUTPUT: 12,15,17,20,31,34,38

Cocktail sort passes through the list both from left to right and from right to left. However, bubble sort just passes through in one direction in each iteration. Another advantage of the cocktail sort is that since it checks the list in both directions, the range of possible swaps will reduce per pass

please assign this issue to me.
I will provide Cocktail Shaker Algorithm in python.

**Comment by Dharnish38** [comment]
@Kumar-laxmi  Can you assign this issue to me in C++ and Java.

**Comment by Abhilash1781** [comment]
Can you assign this in C @Kumar-laxmi

**Comment by Vyshnavi21504** [comment]
please assign me this issue.I can do this in c++

**Comment by Kumar-laxmi** [comment]
@Ayatisonkar Could you implement this in all four languages

**Comment by Ayatisonkar** [comment]
Yes sir I can @Kumar-laxmi

**Comment by Abhilash1781** [comment]
@Kumar-laxmi sir I just checked that there's same issue in #244 . 
U assigned him for C++ .

**Comment by Kumar-laxmi** [comment]
refer #244
