### ISSUE TITLE
Perceptron Learning AND,OR Boolean Function in Python

### ISSUE THREAD

**Issue by Harikaraja** [Kumar-laxmi/Algorithms#441]
Perceptron is the smallest neural network possible . Making perceptron learn Boolean functions that are linearly seperable from scratch without any libraries using python.

Here STEP Function is used as a activation function for perceptron.

**Comment by Kumar-laxmi** [comment]
@Harikaraja Could you implement this in all four languages

**Comment by Harikaraja** [comment]
Sir actually i don't have knowledge on Java and in c I think implementing
it is a tough task since it doesn't have oops .

**Comment by Kumar-laxmi** [comment]
@Harikaraja So could you implement this in C++ & Python

**Comment by Harikaraja** [comment]
Sir I don't know java

**Comment by Harikaraja** [comment]
Yes sir I can implement in CPP and python

**Comment by Kumar-laxmi** [comment]
Assigned!
@Harikaraja : C++ & Python

**Comment by Harikaraja** [comment]
Sir an in python i can show the perceptron learning using some graphs with
matplotlib but in CPP it's not possible .Then is it fine sir ?

**Comment by Kumar-laxmi** [comment]
It is ok

**Comment by Harikaraja** [comment]
Sir an in python i can show the perceptron learning using some graphs with
matplotlib but in CPP it's not possible .Then is it fine sir ?

**Comment by Harikaraja** [comment]
Ok sir thank you

**Comment by Harikaraja** [comment]
Sir I am unable to complete it in c++ can i make a pr only with python.... please Sir.

**Comment by Kumar-laxmi** [comment]
> Sir I am unable to complete it in c++ can i make a pr only with python.... please Sir.

Ok, but your PR won't be marked as ```Intermediate```

**Comment by Harikaraja** [comment]
Ok sir

**Comment by Kumar-laxmi** [comment]
Assigned!
@Harikaraja : Python

**Comment by Kumar-laxmi** [comment]
@Harikaraja What is your status on this issue??

**Comment by Harikaraja** [comment]
Today I will make a pr sir , sorry for the delay.I am having my semester
exams that is why I am inactive on this issue .

**Comment by Kumar-laxmi** [comment]
@Harikaraja Kindly work on this issue before 15th March
