### ISSUE TITLE
K-Nearest Neighbor Algorithm

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [Kumar-laxmi/Algorithms#444]
**Is your feature request related to a problem? Please describe.**
K-Nearest Neighbor Algorithm in Python

**Comment by Srishtihere** [comment]
hey, can you please elaborate the problem, I would like to solve it in c++

**Comment by dicode04** [comment]
Please assign me this algorithm. I'll go with a different approach using python.

**Comment by Abhilash1781** [comment]
@Kumar-laxmi @072arushi please assign this to me in C .

**Comment by Abhilash1781** [comment]
@Kumar-laxmi please re-open this issue so that I can contribute

**Comment by Kumar-laxmi** [comment]
@Soumya-Kushwaha What is your status on this issue?
