### ISSUE TITLE
Possible combinations of string

### ISSUE THREAD

**Issue by Garvit414** [Kumar-laxmi/Algorithms#448]
A program which tells about the possible combinations or permutations of a string.
I will implement it in C++.
Problem Description:
Given a string S, the task is to write a program to print all permutations of a given string. 
e.g. Input: S = “ABC”
Output: “ABC”, “ACB”, “BAC”, “BCA”, “CBA”, “CAB”

@Kumar-laxmi please assign it to me.

**Comment by Dharnish38** [comment]
@Kumar-laxmi  Can you assign this issue to me in Java and Python.

**Comment by Ayatisonkar** [comment]
@Kumar-laxmi can you please assign this issue to me in C

**Comment by Kumar-laxmi** [comment]
Could you raise issues pertaining to standard algorithms
