### ISSUE TITLE
Extended Euclidean Algorithm

### ISSUE THREAD

**Issue by Dharnish38** [Kumar-laxmi/Algorithms#451]
**Is your feature request related to a problem? Please describe.**
Extended Euclidean Algorithm is used to find modular multiplicative inverse of a number which is used in cryptography and network security.

**Describing the problem**
We know that,

Inverse of a number (A) will be = A^-1  or we can say that A * A^-1 will be equal to 1

but incase of modular multiplicative inverse of a number (A) is when the expression below is true

 (A*A^-1) mod (C) is equal to 1

from the expression we can say that A^-1 will be the inverse of A.
 
On top of that we have an important point that modular multiplicative inverse exists when A and C are **coprime**  to eachother or we can also say the gcd of A and C should be equal to **1**

**Additional context**
I will solve this issue in Java, C++, Python and C

**Comment by Vyshnavi21504** [comment]
Hello @Kumar-laxmi please assign me this issue...I can do this in c++

**Comment by Kumar-laxmi** [comment]
@Dharnish38 Could you implement this algorithm in all four languages

**Comment by Dharnish38** [comment]
Yes I can implement this algorithm in all four languages of Java, Python, C++ and C too.  @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Assigned!
@Dharnish38 : C, C++, Java, Python
