### ISSUE TITLE
Splay Trees

### ISSUE THREAD

**Issue by khushigarg1** [Kumar-laxmi/Algorithms#452]
**Is your feature request related to a problem? Please describe.**
Splay trees are a type of self-balancing binary search tree. They are designed to improve the average time complexity of basic operations, such as search, insert, and delete, by rearranging the tree after each operation to move the recently accessed elements closer to the root. This makes subsequent operations on those elements faster. Splay trees are particularly useful in situations where the elements being accessed are not distributed uniformly, or where the access pattern changes over time.
I can do it in C++, Please assign it to me!

**Comment by Kumar-laxmi** [comment]
Assigned!
@khushigarg1 : C++

**Comment by mvpamansingh** [comment]
@Kumar-laxmi can you assign this issue in c and java

**Comment by Kumar-laxmi** [comment]
@khushigarg1 What is your status on this issue

**Comment by mvpamansingh** [comment]
@Kumar-laxmi can I put the files in tree folder?

**Comment by mvpamansingh** [comment]
@Kumar-laxmi I have contributed, please check it once

**Comment by Kumar-laxmi** [comment]
@khushigarg1 What is your status?

**Comment by khushigarg1** [comment]
> @khushigarg1 What is your status?

Sorry, my semester exam was going on now it got completed so I will do it surely within 1-2 day.

**Comment by Kumar-laxmi** [comment]
This issue is left in ```Python```
