### ISSUE TITLE
K Means Clustering

### ISSUE THREAD

**Issue by Shashank1130** [Kumar-laxmi/Algorithms#463]
**Is your feature request related to a problem? Please describe.**
K-Means Clustering in Python

**Comment by Kumar-laxmi** [comment]
@Shashank1130 What is your status on this issue?

**Comment by Kumar-laxmi** [comment]
I am unassigning @Shashank1130 due to inactivity

**Comment by Paritosh-J** [comment]
@Kumar-laxmi I request you to **kindly assign me in C++**.
Thank You

**Comment by Kumar-laxmi** [comment]
Assigned!
@Paritosh-J : C++

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi Can you assign me the same in python?

**Comment by Kumar-laxmi** [comment]
@sitamgithub-MSIT What is your status on this issue?

**Comment by sitamgithub-MSIT** [comment]
> @sitamgithub-MSIT What is your status on this issue?

Working on that
