### ISSUE TITLE
Algorithm to find minimum jumps in C/C++/Java/Python using DP

### ISSUE THREAD

**Issue by atul1510** [Kumar-laxmi/Algorithms#464]
I want to add an algorithm that finds the minimum number of jumps to reach the other end of the array. 
and for this, I will provide the solution code for this problem in C/C++/Java/Python languages.

Problem Description :

You have given an array arr[ ] where each element represents the maximum number of steps that can be made forward from that index. The task is to find the minimum number of jumps to reach the other end of the array starting from the 0th index. 
And if the end isn’t reachable, return -1 as the output.

Examples:
1] INPUT:  arr[ ] = { 1, 9, 4, 7, 3, 7, 2, 1, 8, 9, 5 }
OUTPUT:  Minimum number of jumps to reach the other end is 2

2] INPUT:  arr[ ] = { 1, 8, 2, 7, 3, 7, 2, 1, 8, 9, 4 }
OUTPUT:  Minimum number of jumps to reach the other end is 3

@Kumar-laxmi @072arushi @zugzwang03 @Arun9739 @Rishikavishnoi . Please assign me this issue.

**Comment by Kumar-laxmi** [comment]
@atul1510 What is the name of the algorithm and could you tell more about your approach

**Comment by atul1510** [comment]
> @atul1510 What is the name of the algorithm and could you tell more about your approach

Sir, it basically finds the minimum number of jumps needed to reach arr[ i ] from arr[ 0 ].

**Comment by zugzwang03** [comment]
So it is a question on jumpGame, and the algorithm is dp, and you can do it in all 4 languages: C, C++, Python, Java, right? @atul1510

**Comment by atul1510** [comment]
> So it is a question on jump game, and the algorithm is dp, and you can do it in all 4 languages: C, C++, Python, and Java, right? @atul1510

Yes
