### ISSUE TITLE
Spiral Print Algorithm in 2D arrays 

### ISSUE THREAD

**Issue by Ultimateutkarsh11** [Kumar-laxmi/Algorithms#466]
**Is your feature request related to a problem? Please describe.**
I want to add an algorithm for spiral traversal on 2D arrays

**Describe the solution you'd like**
- First, four variables containing the indices for the corner points of the array are initialized.
The algorithm starts from the top left corner of the array, and traverses the first row from left to right. Once it traverses the whole row it does not need to revisit it, thus, it increments the top corner index.

- Once complete, it traverses the rightmost column top to bottom. Again, once this completes, there is no need to revisit the rightmost column, thus, it decrements the right corner index.

- Next, the algorithm traverses the bottommost row and decrements the bottom corner index afterward.

- Lastly, the algorithm traverses the leftmost column, incrementing the left corner index once it’s done.

**Additional context**
@Kumar-laxmi Please assign me this issue in C++.

**Comment by Dharnish38** [comment]
Can you assign this issue to me in Java and Python @Kumar-laxmi

**Comment by VaibhavArora314** [comment]
Please assign this to me in C.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Vanraj8169 : Java
@VaibhavArora314 : C
@Dharnish38 : Python
@Ultimateutkarsh11 : C++

**Comment by Kumar-laxmi** [comment]
@Vanraj8169 @Ultimateutkarsh11 What is your status on this issue?

**Comment by Ultimateutkarsh11** [comment]
> @Vanraj8169 @Ultimateutkarsh11 What is your status on this issue?

My exams just finished yesterday, will raise a PR by today itself.

**Comment by mahendraDew** [comment]
@Vanraj8169 are you still working on this issue if not then please @Kumar-laxmi  sir assign this to me in java.

**Comment by Kumar-laxmi** [comment]
Assigned!
@mahendraDew : Java
