### ISSUE TITLE
Linear Sieve

### ISSUE THREAD

**Issue by kapil4457** [Kumar-laxmi/Algorithms#473]
**Is your feature request related to a problem? Please describe.**
I will be implementing an algorithm called "linear sieve" using which we can find all prime numbers between 2 and n . 
**Describe the solution you'd like**
A general way to solve this type of problem is to use a sieve of Eratosthenes. But the problem with that is the time complexity is O(n log log n). But using this solution we can do the same in O(n) time complexity
**Describe alternatives you've considered**
None.

**Additional context**

I don't have any diagram to explain it except just the code.

**Comment by Kumar-laxmi** [comment]
Sorry this algorithm has been implemented
