### ISSUE TITLE
Algorithm to find a triplet who's sum is equal to a given value in C/C++/Java/Python using Sorting

### ISSUE THREAD

**Issue by atul1510** [Kumar-laxmi/Algorithms#482]
I want to add an algorithm that finds a triplet whose sum is equal to a given value
and for this, I will provide the solution code in all four languages C/C++/Java/Python.

Problem Description :
Given an array and a value, find if there is a triplet in the array whose sum is equal to the given value. If there is such a triplet present in the array, then print the triplet and return true. Else return false.

EXAMPLES:
1] Input: array = { 7, 10, 6, 14, 4, 9 }, sum = 25; 
   Output: Triplet is 4, 7, 14

@Kumar-laxmi @072arushi @zugzwang03 @Rishikavishnoi @Sanjanabharadwaj25 @Arun9739  , please assign me this issue.

**Comment by zugzwang03** [comment]
you mean 3 sum problem? @atul1510

**Comment by atul1510** [comment]
> you mean 3 sum problem? @atul1510

Yes kind of, it basically finds the group of triplets whose sum is equal to the given number

**Comment by zugzwang03** [comment]
!Assigned 
@atul1510 : C, C++, Java, Python

**Comment by RitikaRathore05** [comment]
I want to work on this issue under SWOC S3. please assign it to me.
