### ISSUE TITLE
Add Ternary Search Code | Assign this issue to me | For C++ code

### ISSUE THREAD

**Issue by sinhasaurabh079** [Kumar-laxmi/Algorithms#484]
**Title:** Add Ternary Search Code

**Description:**
I am requesting the addition of ternary search code to this project. Ternary search is a technique for finding the minimum or maximum value of a unimodal function and it can be useful in optimization problems.

**Implementation details:**
- I suggest adding a new class/file called "TernarySearch" to the project, with a function called "ternary_search" that takes in the left and right interval of the search and returns the minimum/maximum value found.
- I also suggest including appropriate comments in the code to explain the implementation of the algorithm.

**Benefits:**
- Ternary search can be more efficient than other optimization techniques like gradient descent or Newton's method in certain cases.
- It can be useful for solving problems in competitive programming where the function is uni-modal and the domain and range of the function is known.

**References:**
- [Wikipedia article on Ternary Search](https://en.wikipedia.org/wiki/Ternary_search)
- [Example implementation of Ternary Search](https://www.geeksforgeeks.org/ternary-search/)

**Comment by sinhasaurabh079** [comment]
@Kumar-laxmi Look into this, if found contributable then assign this to me

**Comment by Kumar-laxmi** [comment]
Could you implement this in all four languages

**Comment by sinhasaurabh079** [comment]
Ohk i will add the in four language can you please name it - I think you are saying about c,c++,Java & Python
