### ISSUE TITLE
Bennett's Formula to find  Fibonacci sequence in C++

### ISSUE THREAD

**Issue by sinhasaurabh079** [Kumar-laxmi/Algorithms#485]
**Description**
I have written a C++ code for calculating Fibonacci numbers using three different methods:
1. Golden ratio, (the recurrence relation)
2. Simple iterative method
3. Recursion. I would like to contribute this code to the repository to make it available for other developers to use.

`` The code uses boost multiprecision library to handle large integers and well commented. ``

**Application:**

    Fibonacci series calculation
    Large integers handling

Please let me know if there are any issues with the template or if you need any additional information.

**Please assign me this issue**

**Comment by sinhasaurabh079** [comment]
@Kumar-laxmi  Look into this, if found contributable then assign this to me

**Comment by Kumar-laxmi** [comment]
Assigned!
@sinhasaurabh079 : C++

**Comment by Kumar-laxmi** [comment]
Could you implement this in all four languages

**Comment by sinhasaurabh079** [comment]
Yes

**Comment by Kumar-laxmi** [comment]
Assigned!
@sinhasaurabh079 : C, C++, Python, Java
