### ISSUE TITLE
Dinic's Algorithm

### ISSUE THREAD

**Issue by kapil4457** [Kumar-laxmi/Algorithms#486]
**Is your feature request related to a problem? Please describe.**
It is a graph algorithm for finding the maximum flow or that given graph. I can submit this algorithm in c++ , java and python
**Describe the solution you'd like**
Steps for the algorithm : 
1) Initialize residual graph G as given graph.
2) Do BFS of G to construct a level graph (or assign levels to vertices) and also check if more flow is possible.
         - If more flow is not possible, then return
         - Send multiple flows in G using level graph until blocking flow is reached. 

**Describe alternatives you've considered**
None.

**Additional context**
None

**Comment by Kumar-laxmi** [comment]
@kapil4457 Could you implement this algo in all four languages

**Comment by kapil4457** [comment]
> @kapil4457 Could you implement this algo in all four languages

I can do it in three....C++ , java and python

**Comment by Kumar-laxmi** [comment]
ok

**Comment by Kumar-laxmi** [comment]
Assigned!
@kapil4457 : C++, Java, Python

**Comment by Kumar-laxmi** [comment]
Assigned!
@Sachittarway : C

**Comment by Kumar-laxmi** [comment]
@Sachittarway What is your status on this issue
