### ISSUE TITLE
DES Algorithm

### ISSUE THREAD

**Issue by aradhya-10** [Kumar-laxmi/Algorithms#493]
Not a bug or problem. I want to add the DES algorithm which is a popular algorithm used in cryptography.

DES (Data Encryption Standard) is a symmetric cipher algorithm and uses the block cipher method for encryption and decryption. DES is a landmark in cryptographic algorithms. It works based on Fiesta Cipher Structure.
I want to add the code in C++.

**Comment by Kumar-laxmi** [comment]
Assigned!
@aradhya-10 : C++

**Comment by Dharnish38** [comment]
@Kumar-laxmi  assign this to me in java

**Comment by MrKoshens** [comment]
@Kumar-laxmi please assign me this issue in python

**Comment by MrKoshens** [comment]
@Kumar-laxmi If possible please assign this issue to me in python.

**Comment by MrKoshens** [comment]
@Kumar-laxmi please assign me this issue if there is no work going on. I can complete it in C,C++,Python and java

**Comment by Kumar-laxmi** [comment]
@aradhya-10 has been unassigned due to inactivity

**Comment by Kumar-laxmi** [comment]
Assigned!
@MrKoshens : C, C++, Java, Python

**Comment by Kumar-laxmi** [comment]
But it should include everything:
- encryption
- decryption
- round key generation

**Comment by MrKoshens** [comment]
> But it should include everything:
> - encryption
> - decryption
> - round key generation

Yes sir
