### ISSUE TITLE
Caeser Cipher

### ISSUE THREAD

**Issue by Paritosh-J** [Kumar-laxmi/Algorithms#497]
### Definition

In cryptography, the Caesar Cipher is one of the simplest and best known encryption techniques. It is a type of substitution cipher where each letter in the plaintext is replaced with a letter pointing to a specified number of digits in the alphabet.

### Implementation

Caeser Cipher will be implemented in **C, C++, Java and Python**.

### Request Statement

I hereby request you to **please assign me this issue**.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Paritosh-J : C, C++, Python, Java

**Comment by MrKoshens** [comment]
please assign me this issue in python

**Comment by Kumar-laxmi** [comment]
@MrKoshens Is it possible for you to implement this algo in ```C```

**Comment by Harikaraja** [comment]
please assign me this issue in c

**Comment by MrKoshens** [comment]
> please assign me this issue in c

I am already assigned this issue in C. In fact i have also already completed it. I'm just waiting for the PR to be merged so i can open a new PR

**Comment by Harikaraja** [comment]
Ok fine
