### ISSUE TITLE
Closures of relations

### ISSUE THREAD

**Issue by VaibhavArora314** [Kumar-laxmi/Algorithms#498]
Hey, I want to add a program to find reflexive, symmetric, and transitive closure(using both the traditional approach and warshall algorithm) of a relation.

The closure of a relation is the smallest relation containing the original relation and following the required properties.
This is a popular problem in the field of discrete mathematics.

Ex: A = {0,1,2,3,4}, R: A->A 
R = {(0,0),(1,2),(2,2),(2,3),(2,4)}
Reflexive closure of R = {(0,0),(1,1),(1,2),(2,2),(2,3),(2,4),(3,3),(4,4)}
Symmetric closure of R = {(0,0),(1,2),(2,1),(2,2),(2,3),(3,2),(2,4),(4,2)}
Transitive closure of R = {(0,0),(1,2),(2,2),(2,3),(2,4),(1,3),(1,4)}

![image](https://user-images.githubusercontent.com/84830429/215344581-57777687-505b-42a4-8812-2366d9f8b98c.png)

This can be implemented using C, C++, Java, and Python.

@Kumar-laxmi @zugzwang03 @Arun9739 @Sanjanabharadwaj25 @072arushi  please assign me this issue.

**Comment by Kumar-laxmi** [comment]
Assigned!
@VaibhavArora314 : C, C++, Java, Python
