### ISSUE TITLE
Add Perfect Number Algo in Maths section

### ISSUE THREAD

**Issue by palaksinghania05** [Kumar-laxmi/Algorithms#501]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add Algorithm for Perfect Numbers in Java 

**Describe alternatives you've considered**

**Additional context**

**Comment by Kumar-laxmi** [comment]
@palaksinghania05 Could you implement this in all four languages

**Comment by palaksinghania05** [comment]
@Kumar-laxmi  I am more confident in java and python, but I can implement it in C and C++ too after taking help from the internet if that's okay.

**Comment by MrKoshens** [comment]
please assign me this issue in python

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi I am more confident in java and python, but I can implement it in C and C++ too after taking help from the internet if that's okay.

You can take help but please don't copy paste the codes

**Comment by Kumar-laxmi** [comment]
Assigned!
@palaksinghania05 : C, C++, Java, Python
