### ISSUE TITLE
Double linked list

### ISSUE THREAD

**Issue by sushmita-2002** [Kumar-laxmi/Algorithms#51]
Can I implement double linked list in C++ in your project.

**Comment by Kumar-laxmi** [comment]
# **assigned** !😁

**Comment by Sowham-3098** [comment]
Can I implement this using C Language?

**Comment by harshraj9988** [comment]
please assign the implementation of doubly linked list in java to me.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Sowham-3098 : C
@harshraj9988 : Java

**Comment by goyalh4164** [comment]
Hello Sir Please assign this to me.
I will make some valuable contributions to this in c and c++ both languages

**Comment by Kumar-laxmi** [comment]
> Hello Sir Please assign this to me. I will make some valuable contributions to this in c and c++ both languages

You can work on C++

**Comment by Kumar-laxmi** [comment]
Assigned!
@goyalh4164 : C++

**Comment by goyalh4164** [comment]
Thanks for Assigning!!
I will Work on it.

**Comment by Paritosh-J** [comment]
@Kumar-laxmi I would like to bring this under your kind attention that **C++ implementation assigned to @goyalh4164 has passed the minimum threshold of raising a PR for same**. Therefore I request you to **please assign the C++ implementation to me**.
Thank You

**Comment by goyalh4164** [comment]
> @Kumar-laxmi I would like to bring this under your kind attention that **C++ implementation assigned to @goyalh4164 has passed the minimum threshold of raising a PR for same**. Therefore I request you to **please assign the C++ implementation to me**.
> Thank You

@Paritosh-J I have already implemented it.@Kumar-laxmi Haven't approved it till now.It was implemented within one after assignment.

**Comment by stiwari-ds** [comment]
@Kumar-laxmi Please assign it to me for Python.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Sowham-3098 : C
@harshraj9988 : Java
@stiwari-ds : Python

**Comment by Kumar-laxmi** [comment]
@harshraj9988 What is your status on this issue?

**Comment by Kumar-laxmi** [comment]
> It's in progress. Will create a PR by sunday

Now what is your status??

**Comment by harshraj9988** [comment]
> 

So apparently, my code for double linked list (java) is already submitted and merged, here is the link [https://github.com/Kumar-laxmi/Algorithms/blob/main/Java/Linked-List/DoubleLinkedList.java](link)

**Comment by harshraj9988** [comment]
So apparently, my code for double linked list (java) is already merged (#76 )
