### ISSUE TITLE
 queue data structure in c 

### ISSUE THREAD

**Issue by Neha00011** [Kumar-laxmi/Algorithms#531]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I want to add a file containing all queue operations (ex: enqueue ,dequeue using linked list) under c folder.
kindly add this issue under swoc3 and assign it to me.

**Describe alternatives you've considered**

**Additional context**

**Comment by Kumar-laxmi** [comment]
Since it is an easy issue, this problem should be implemented in all four languages.
@Neha00011 Can you implement this problem in all four languages?

**Comment by Neha00011** [comment]
Yes, I can do that.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Neha00011 : C, C++, Java, Python

**Comment by Kumar-laxmi** [comment]
Place the program files in ```Linked List``` folder

**Comment by Abhinavcode13** [comment]
Is this issue resolved or Can I work on it?

**Comment by Abhinavcode13** [comment]
@Kumar-laxmi ??

**Comment by Kumar-laxmi** [comment]
> Is this issue resolved or Can I work on it?

Yeah this issue is resolved
