### ISSUE TITLE
Maths problem - Factorial of a number

### ISSUE THREAD

**Issue by muskan467** [Kumar-laxmi/Algorithms#540]
**Is your feature request related to a problem? Please describe.**
Factorial of a number is the product of natural numbers upto that number.
n! = 1*2*3...*n

**Describe the solution you'd like**
I will use loops for it and the final answer would be the multiplication of natural nos till that no.

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by Kumar-laxmi** [comment]
Since this is a easy issue, kindly implement it in all four languages

Assigned!
@muskan467 : C, C++, Python, Java
