### ISSUE TITLE
Diffie-Hellman Algorithm 

### ISSUE THREAD

**Issue by Harikaraja** [Kumar-laxmi/Algorithms#552]
**Is your feature request related to a problem? Please describe.**
Elliptic Curve Cryptography (ECC) is an approach to public-key cryptography, based on the algebraic structure of elliptic curves over finite fields. 
**Describe the solution you'd like**
Diffie-Hellman Algorithm is a solution for Elliptic curve cryptography. An elliptic curve is a planar algebraic curve defined by an equation of the form

y^2 = x^3 + ax + b           
 
Where ‘a’ is the co-efficient of x and ‘b’ is the constant of the equation  

The curve is non-singular; that is, its graph has no self-intersections 

# Diffie-Hellman algorithm

The Diffie-Hellman algorithm is being used to establish a shared secret that can be used for secret communications while exchanging data over a public network using the elliptic curve to generate points and get the secret key using the parameters.  

For the sake of simplicity and practical implementation of the algorithm, we will consider only 4 variables, one prime P and G (a primitive root of P) and two private values a and b.
P and G are both publicly available numbers. Users (say Alice and Bob) pick private values a and b and they generate a key and exchange it publicly. The opposite person receives the key and that generates a secret key, after which they have the same secret key to encrypt

# Example:

Step 1: Alice and Bob get public numbers P = 23, G = 9

Step 2: Alice selected a private key a = 4 and
        Bob selected a private key b = 3

Step 3: Alice and Bob compute public values
Alice:    x =(9^4 mod 23) = (6561 mod 23) = 6
        Bob:    y = (9^3 mod 23) = (729 mod 23)  = 16

Step 4: Alice and Bob exchange public numbers

Step 5: Alice receives public key y =16 and
        Bob receives public key x = 6

Step 6: Alice and Bob compute symmetric keys
        Alice:  ka = y^a mod p = 65536 mod 23 = 9
        Bob:    kb = x^b mod p = 216 mod 23 = 9

Step 7: 9 is the shared secret.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Harikaraja : C, C++

**Comment by Abhilash1781** [comment]
Please assign me in Python

**Comment by Ananta-Vaishnavi** [comment]
P
lease assign me in Java

**Comment by Ananta-Vaishnavi** [comment]
Can you add a swoc label to this?
