### ISSUE TITLE
Secure Hash Algorithm(SHA-256)

### ISSUE THREAD

**Issue by MrKoshens** [Kumar-laxmi/Algorithms#563]
Secure Hash Algorithm:
SHA-256 is a secure hash algorithm that belongs to the SHA-2 family of hash functions. The algorithm takes an input (or "message") and returns a fixed-size string of bytes, which is a "digest" that represents the message. The size of the digest is 256 bits (32 bytes). SHA-256 is a one-way function, which means that it is impossible to reverse the process and obtain the original message from the digest. However, any change to the input message will produce a completely different digest, so the algorithm is commonly used to verify the integrity of data, for example, to check that a downloaded file has not been altered during transmission. SHA-256 is widely used in cryptography and is considered to be secure for many applications. However, there have been some theoretical attacks on the algorithm that suggest it may not be suitable for long-term use.

**Describe alternatives you've considered**
I want to add code for SHA-256 algorithm in the cryptography section. I can provide the code in python, C and C++

**Comment by Kumar-laxmi** [comment]
Assigned!
@MrKoshens : C, C++, Java, Python
