### ISSUE TITLE
To reverse a given linklist from the user in all four languages C/C++/Java/Python

### ISSUE THREAD

**Issue by atul1510** [Kumar-laxmi/Algorithms#565]
PROBLEM STATEMENT : 
To reverse a linked list in place. The code should take a linked list as input and reverse the order of the nodes in the list. The result should be a linked list with the nodes in reverse order. The solution should use in-place reversal, meaning that it should modify the linked list without creating a new data structure to store the reversed list. The code should be written in the programming language specified 
(C, C++, Java, or Python).

EXAMPLE :
Original Linked List: 1 -> 2 -> 3 -> 4 -> 5 -> NULL

Reversed Linked List: 5 -> 4 -> 3 -> 2 -> 1 -> NULL

@Kumar-laxmi , @072arushi , @Rishikavishnoi Please assign me this issue.

**Comment by Kumar-laxmi** [comment]
This algorithm has been implemented in all four languages

**Comment by atul1510** [comment]
Ok
