### ISSUE TITLE
Algorithm to convert Roman numeral into its Decimal equivalent using string in C/C++/Java/Python

### ISSUE THREAD

**Issue by atul1510** [Kumar-laxmi/Algorithms#566]
Problem Statement
Given a Roman numeral, the task is to convert it into its decimal equivalent.

Approach
The approach used to solve this problem is to iterate over each character in the input Roman numeral string in reverse order. If the value of the current symbol is greater than or equal to the value of the previous symbol, it is added to the result. If the value of the current symbol is less than the value of the previous symbol, it is subtracted from the result.

To obtain the value of each Roman numeral, we can create a function value that takes a character as input and returns its decimal equivalent. This function checks the character against all valid Roman numerals and returns the corresponding decimal value.

Example
1)
Input:  "XXI"
Output: 21
2)
Input:  "MCMXCIV"
Output: 1994

In the first example, the Roman numeral "XXI" is converted to its decimal equivalent 21. In the second example, the Roman numeral "MCMXCIV" is converted to its decimal equivalent 1994.

I will present the solution to the problem of converting Roman numerals to decimals in C/C++/Java/Python.

@Kumar-laxmi , @072arushi , @Rishikavishnoi please assign me this issue.

**Comment by Kumar-laxmi** [comment]
The menu should have two option:
- Integer to Roman
- Roman to Integer

**Comment by atul1510** [comment]
@Kumar-laxmi  sir, I am capable of implementing each one separately, and I prefer to work on them individually rather than integrating them into a menu-driven system.

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi sir, I am capable of implementing each one separately, and I prefer to work on them individually rather than integrating them into a menu-driven system.

Work on them separately and call those modules based on if-else condition

**Comment by Kumar-laxmi** [comment]
Assigned!
@atul1510 : C, C++, Java, Python
