### ISSUE TITLE
Modular exponentiation

### ISSUE THREAD

**Issue by sumitkr2000** [Kumar-laxmi/Algorithms#568]
**Is your feature request related to a problem? Please describe.**
Hey, @Kumar-laxmi I want to add the code of modular exponentiation in C++ to your repo. Please assign me this issue. Thank you!

**Describe the solution you'd like**
Modular Exponentiation in C++.

**Describe alternatives you've considered**

**Additional context**

**Comment by Kumar-laxmi** [comment]
Assigned!
@sumitkr2000 : C++

**Comment by Dharnish38** [comment]
@Kumar-laxmi , Please assign this issue to me in C, Java, Python.
