### ISSUE TITLE
Vernam Cipher

### ISSUE THREAD

**Issue by Paritosh-J** [Kumar-laxmi/Algorithms#577]
### Definition

👉 In cryptography, the Vernam Cipher encypts the alphabetic text. It's a substitution technique to convert the plain text into cipher text.

👉 It's also called ONE TIME PAD Cipher Algorithm.

### Implementation

Vernam Cipher will be implemented in **C++ and Python**.

### Request Statement

I hereby request you to **please assign me this issue**.

**Comment by Dharnish38** [comment]
@Kumar-laxmi , Please assign this issue to me in Java.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Paritosh-J : C++, Python
@Dharnish38 : C, Java

**Comment by MrKoshens** [comment]
@Kumar-laxmi Please assign me this issue in C, C++, Python

**Comment by Paritosh-J** [comment]
> @Kumar-laxmi Please assign me this issue in C, C++, Python

Kindly note that this issue is already assigned to me in C++ and Python.

**Comment by Kumar-laxmi** [comment]
@Dharnish38 What is your status?

**Comment by Dharnish38** [comment]
@Kumar-laxmi , Within today evening this issue will be solved.
