### ISSUE TITLE
Diagonal Print Algorithm in 2D arrays

### ISSUE THREAD

**Issue by Dharnish38** [Kumar-laxmi/Algorithms#578]
**Is your feature request related to a problem? Please describe.**
I want to add an algorithm for diagonal traversal on 2D arrays

**Describe the solution you'd like**
1) Create variables i=0, j=0 to store the current indices of row and column
2) Run a loop from 0 to n*n, where n is the side of the matrix.
3) Use a flag "isUp" to decide whether the direction is upwards or downwards. Set isUp = true initially the direction is going upward.
4) If isUp = 1 then start printing elements by incrementing column index and decrementing the row index.
5) Similarly if isUp = 0, then decrement the column index and increment the row index.
6) Move to the next column or row (next starting row and column
7) Do this till all the elements get traversed.

**Additional context**
@Kumar-laxmi , Assign this issue to me in all four languages of C ,C++, Java and Python.

**Comment by Dharnish38** [comment]
@Kumar-laxmi , I hope this picture explains about it.
![Diagnol](https://user-images.githubusercontent.com/122768878/219842544-8bf54cc1-1ff2-42be-ae72-a0f395104f02.png)

**Comment by Kumar-laxmi** [comment]
Since it is an easy issue, please implement this algorithm in all four languages

Assigned!
@Dharnish38 : C, C++, Python, Java

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi if the work is still left can you assign me the work?

**Comment by sumitkr2000** [comment]
Hey, @Kumar-laxmi is this issue available in C++? If not, please assign me this issue in C++.
