### ISSUE TITLE
Hill Cipher

### ISSUE THREAD

**Issue by Paritosh-J** [Kumar-laxmi/Algorithms#580]
### Definition

👉 In Classical Cryptography, the Hill cipher is a polygraphic substitution cipher based on linear algebra. 

👉 Invented by Lester S. Hill in 1929, it was the first polygraphic cipher in which it was practical to operate on more than three symbols at once.

### Implementation

Hill Cipher will be implemented in **C++ and Python**.

### Request Statement

I hereby request you to **kindly assign me this issue**.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Paritosh-J : C++, Python

**Comment by Dharnish38** [comment]
@Kumar-laxmi , Please assign this task to me in Java.

**Comment by samvid2020** [comment]
can you assign this to me for java @Kumar-laxmi

**Comment by samvid2020** [comment]
Should i do this in C ?

**Comment by Kumar-laxmi** [comment]
> Should I do this in C or Java ? @Kumar-laxmi

```C```
