### ISSUE TITLE
Job Sequencing in Java

### ISSUE THREAD

**Issue by papri24majumder** [Kumar-laxmi/Algorithms#581]
**Is your feature request related to a problem? Please describe.**
No, my feature request is not related to a problem.

**Describe the solution you'd like**
In the job sequencing problem, the objective is to find a sequence of jobs, which is completed within their deadlines and gives maximum profit. I will code job sequencing in java.

**Describe alternatives you've considered**
No alternatives

**Additional context**
Nil

**Comment by Kumar-laxmi** [comment]
refer #282
