### ISSUE TITLE
Algorithm to find the length of given linked list in C/C++/Java/python

### ISSUE THREAD

**Issue by atul1510** [Kumar-laxmi/Algorithms#584]
Problem Statement:

Given a singly linked list, write a function to find the length of the linked list.

Approach:

To find the length of a singly linked list, we need to iterate through the list and count the number of nodes in the list. We can start with the head of the linked list and traverse through each node until we reach the end of the list. We increment a counter variable for each node we visit until we reach the end of the list. Once we reach the end of the list, the counter variable will contain the length of the linked list.

Examples:
1 -> 2 -> 3 -> 4 -> 5 -> null
We can find the length of this list using the following steps:

Start with the head of the list, the node with the value 1.
Traverse through each node, incrementing a counter variable for each node we visit.
Once we reach the end of the list, the counter variable will contain the length of the linked list, which in this case is 5.
So the length of the above-linked list is 5.

@Kumar-laxmi , @072arushi , @Rishikavishnoi . Please assign me this issue.

**Comment by MrKoshens** [comment]
i can code this in C, C++ and python. please assign me @Kumar-laxmi

**Comment by atul1510** [comment]
@Kumar-laxmi, @072arushi  I already raised this issue before.

**Comment by Kumar-laxmi** [comment]
Assigned!
@MrKoshens : C, C++, Python, Java

**Comment by atul1510** [comment]
@Kumar-laxmi sir, this issue is raised by me. And you assign another person to it.

**Comment by atul1510** [comment]
@Kumar-laxmi, @072arushi Please assign me this issue.

**Comment by 072arushi** [comment]
@atul1510 assigned

**Comment by sumitkr2000** [comment]
Hey, @Kumar-laxmi is this issue available in C++? If not, please assign me this issue in C++.
