### ISSUE TITLE
Algorithm to check if two given Strings are Isomorphic to each other in C/C++/Java/python

### ISSUE THREAD

**Issue by atul1510** [Kumar-laxmi/Algorithms#585]
Problem Statement:

 Given two strings s and t, determine if they are isomorphic. Two strings are isomorphic if the characters in s can be replaced to get t.

Approach: To solve this problem, we need to compare the mapping of each character in string s to its corresponding character in string t. To do this, we can create two hash maps - one to store the mapping from s to t and another to store the mapping from t to s. Then we can iterate through each character in the strings and compare their corresponding mappings. If we find a mismatch, we can return False, indicating that the strings are not isomorphic. If we reach the end of the strings without finding a mismatch, we can return True.

Example: Let's say we are given two strings s = "egg" and t = "add". To check if they are isomorphic, we can create two hash maps:

s_to_t = {'e': 'a', 'g': 'd'}
t_to_s = {'a': 'e', 'd': 'g'}

Then we can iterate through each character in the strings and compare their corresponding mappings:

s[0] = 'e' -> t[0] = 'a' (s_to_t)
s[1] = 'g' -> t[1] = 'd' (s_to_t)
s[2] = 'g' -> t[2] = 'd' (s_to_t)

Since we did not find a mismatch, we can return True, indicating that the strings are isomorphic.

@Kumar-laxmi , @072arushi , @Rishikavishnoi . Please assign me this issue.

**Comment by atul1510** [comment]
@Kumar-laxmi sir, should I close this issue or proceed with it?

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi sir, should I close this issue or proceed with it?

Close it

**Comment by atul1510** [comment]
> > @Kumar-laxmi sir, should I close this issue or proceed with it?
> 
> Close it

ok, sir.
