### ISSUE TITLE
Homophonic substitution

### ISSUE THREAD

**Issue by MrKoshens** [Kumar-laxmi/Algorithms#592]
Homophonic substitution is a type of encryption where each plaintext letter is replaced by one or more ciphertext symbols (usually numbers or letters) selected at random from a pool of possible symbols. The objective of using multiple symbols is to increase the complexity of the ciphertext and make it more resistant to frequency analysis attacks.

**Describe the solution you'd like**
Not a bug but I want to add codes in C, C++, python, and java.

**Comment by Kumar-laxmi** [comment]
Assigned!
@MrKoshens : C, C++, Python, Java
