### ISSUE TITLE
Algorithm for Topological sorting in Graph in CPP

### ISSUE THREAD

**Issue by Kshitij321** [Kumar-laxmi/Algorithms#603]
I want to add topological sorting algorithm in CPP

**Problem Statement:**

Given a directed graph, find a topological ordering of its nodes. A topological ordering is an ordering of the nodes such that for every directed edge (u, v), node u comes before node v in the ordering.

**Input Format:**

The first line of input contains two space-separated integers n and m (1 ≤ n ≤ 10^5, 1 ≤ m ≤ 10^6), where n is the number of nodes in the graph and m is the number of edges. The nodes are numbered from 0 to n-1.

The next m lines contain two space-separated integers u and v (0 ≤ u, v ≤ n-1) that represent a directed edge from node u to node v in the graph.

**Output Format:**

If the input graph is acyclic, the output should contain a single line with the topologically sorted nodes of the graph separated by a space.

If the input graph contains cycles, the output should contain a single line with the text "Error: Graph contains cycle".

**INPUT----**
6 6
0 1
1 2
2 3
3 4
4 5
5 2
**OUTPUT---**
Error: Graph contains cycle

**INPUT---**
6 7
0 1
1 2
2 3
3 4
4 5
5 2
3 5
**OUTPUT---**
Topologically sorted nodes: 0 1 2 3 4 5

**Comment by Kumar-laxmi** [comment]
refer #113
