### ISSUE TITLE
Prim's Algorithm

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#61]
Implement Prim's Algorithm in the following languages:
- C
- C++
- Java
- Python

**Comment by ManavLohia945** [comment]
This is the code for Prim's Algorithm in Java
// Prim's Algorithm in Java

import java.util.Arrays;

class PGraph {

  public void Prim(int G[][], int V) {

    int INF = 9999999;

    int no_edge; // number of edge

    // create a array to track selected vertex
    // selected will become true otherwise false
    boolean[] selected = new boolean[V];

    // set selected false initially
    Arrays.fill(selected, false);

    // set number of edge to 0
    no_edge = 0;

    // the number of egde in minimum spanning tree will be
    // always less than (V -1), where V is number of vertices in
    // graph

    // choose 0th vertex and make it true
    selected[0] = true;

    // print for edge and weight
    System.out.println("Edge : Weight");

    while (no_edge < V - 1) {
      // For every vertex in the set S, find the all adjacent vertices
      // , calculate the distance from the vertex selected at step 1.
      // if the vertex is already in the set S, discard it otherwise
      // choose another vertex nearest to selected vertex at step 1.

      int min = INF;
      int x = 0; // row number
      int y = 0; // col number

      for (int i = 0; i < V; i++) {
        if (selected[i] == true) {
          for (int j = 0; j < V; j++) {
            // not in selected and there is an edge
            if (!selected[j] && G[i][j] != 0) {
              if (min > G[i][j]) {
                min = G[i][j];
                x = i;
                y = j;
              }
            }
          }
        }
      }
      System.out.println(x + " - " + y + " :  " + G[x][y]);
      selected[y] = true;
      no_edge++;
    }
  }

  public static void main(String[] args) {
    PGraph g = new PGraph();

    // number of vertices in grapj
    int V = 5;

    // create a 2d array of size 5x5
    // for adjacency matrix to represent graph
    int[][] G = { { 0, 9, 75, 0, 0 }, { 9, 0, 95, 19, 42 }, { 75, 95, 0, 51, 66 }, { 0, 19, 51, 0, 31 },
        { 0, 42, 66, 31, 0 } };

    g.Prim(G, V);
  }
}

**Comment by MaYaNkKashyap681** [comment]
I can add C++ code for it, Please assign this to me.

**Comment by Kumar-laxmi** [comment]
**@contributors** Any issue would be assigned after the coding period starts

**Comment by muskaanrajput14** [comment]
I want to contribute in c++, please it too me

**Comment by harshraj9988** [comment]
please assign this task to me for java language

**Comment by Kpallavi5** [comment]
Please assign this task to me for python

**Comment by Kumar-laxmi** [comment]
Assigned: 
@ManavLohia945 : Java
@MaYaNkKashyap681 : C++
@Kpallavi5 : Python

**Comment by MaYaNkKashyap681** [comment]
Do you want Code with comments or just code is fine.

**Comment by Kumar-laxmi** [comment]
> Do you want Code with comments or just code is fine.

Code with comment is a must

**Comment by MaYaNkKashyap681** [comment]
ok

**Comment by Kumar-laxmi** [comment]
Implement Prim's Algorithm in the following languages:
- Java
- Python

**Comment by Kumar-laxmi** [comment]
This algorithm is also available in C

**Comment by aradhya-10** [comment]
Hey, @Kumar-laxmi can you assign it to me for the C code?

**Comment by MaYaNkKashyap681** [comment]
> This algorithm is also available in C

ok.

**Comment by Abhilash1781** [comment]
Hi , I am a SWOC (Social Winter of Code ) contributor . Can you please assign me for Prim's Algorithm in C @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Assigned!
@aradhya-10 : C

**Comment by ayushete02** [comment]
As i see no code, 
Assign me this issue i will do it in Python

**Comment by Kumar-laxmi** [comment]
Assigned!
@aradhya-10 : C
@ayushete02 : C++

**Comment by Kumar-laxmi** [comment]
I am unassigning @Kpallavi5 due to inactivity

**Comment by Kumar-laxmi** [comment]
@ayushete02 @aradhya-10 What is your status on this issue?

**Comment by ayushete02** [comment]
@Kumar-laxmi 
Check : https://github.com/Kumar-laxmi/Algorithms/pull/567

**Comment by khushigarg1** [comment]
Please assign me this issue in C?

**Comment by Kumar-laxmi** [comment]
Unassigning @aradhya-10 due to inactivity

**Comment by Abhinavcode13** [comment]
Assign this issue to me in C++/C or python will do it.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Abhinavcode13 : C
