### ISSUE TITLE
Optimal Merge Pattern in all languages

### ISSUE THREAD

**Issue by NikitaGupta-17** [Kumar-laxmi/Algorithms#610]
Given n number of sorted files, the task is to find the minimum computations done to reach the Optimal Merge Pattern.
When two or more sorted files are to be merged altogether to form a single file, the minimum computations are done to reach this file are known as Optimal Merge Pattern. 
Optimal merge pattern
It is minimum no of moves req to merge files by Greedy Approach.
It is a process of merging 2 sorted files of different length into a single sorted file.
If length of sorted file is n and length of another sorted file is m then time complexity will be O(n+m).

Approach

sort files in ascending order of sizes.
Pick the files of smaller sizes and merge them.
For example
Q If there are 5 files apply optimal merge pattern.(20,30,10,5,30).
Ans
Step 1: Sort files in ascending order of their sizes.
x4 x3 x1 x2 x5
5 10 20 30 50
Step 2: Pick the files of smaller size and merge them
Merge x3 and x4 |z1|=5+10=15
Merge z1 and x1|z2|=35
Merge x2 and x5|z3|=60
Merge z3 and z2=60+35=95
Total no of moves= 205

205 is the minimum no of moves if we combine in different ways then moves will be greater than 205.
![s](https://user-images.githubusercontent.com/75840623/221919032-ec5b61c7-2ab5-444a-a5f5-930f95eb9081.jpg)

I can code in all languages. Please assign it to me.

**Comment by Kumar-laxmi** [comment]
Assigned!
@NikitaGupta-17 : C, C++, Java, Python

Kindly place the file in ```Greedy Algorithms```
