### ISSUE TITLE
Contributors who are added to the Private channel can only contribute under SWOC

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#62]
Welcome contributors to this repository !!!
**_Do star this repository and follow me for more more wonderful repositories_**

**Comment by ManavLohia945** [comment]
hey bro!! I came across this repository through Social winter of code and I want to make contributions to this issue if you could guide me so that i can start my open-source journey it would be great

**Comment by Kumar-laxmi** [comment]
# To raise an issue kindly follow these steps:

STEP 1: Go to the issues section
<img width="1440" alt="Screenshot 2023-01-01 at 7 38 36 AM" src="https://user-images.githubusercontent.com/76027425/210159341-2e7f91f0-6d92-4111-94b7-f1436d4619cc.png">

STEP 2: Click on the new issues button
<img width="1440" alt="Screenshot 2023-01-01 at 7 38 44 AM" src="https://user-images.githubusercontent.com/76027425/210159347-dad52d1b-1abb-43d6-8f43-20385129de94.png">

STEP 3: Enter the details of the issue and submit
<img width="1440" alt="Screenshot 2023-01-01 at 7 38 57 AM" src="https://user-images.githubusercontent.com/76027425/210159350-91212bdf-1c29-4ec0-a1a9-0ab42d472e53.png">

Kindly follow these steps and do comment if you have any doubts!!

**Comment by Kumar-laxmi** [comment]
@ ManavLohia945 please refer above

**Comment by ManavLohia945** [comment]
ok so to contribute the code for Prim's algo i have to create a new issue right?
and also I have practiced cyclic sort yesterday so I can also add the code for that in the sorting folder

**Comment by Kumar-laxmi** [comment]
> ok so to contribute the code for Prim's algo i have to create a new issue right? and also I have practiced cyclic sort yesterday so I can also add the code for that in the sorting folder

Yes, you may raise the issue in **issue section**

**Comment by ManavLohia945** [comment]
Ok sure will do that

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 

I am not been added to the private discord channel. Can you add me in since I am participating in SWOC S3 ?

**Comment by Arbtrage** [comment]
@Kumar-laxmi 
Same issue, I am also not added in the private discord channel .

**Comment by Kumar-laxmi** [comment]
@Priyanshu-Singh-1 @Arbtrage Your name and discord id?

**Comment by Arbtrage** [comment]
Name : Sayantan Naskar
Discord Id: Arbitrage#0868
@Kumar-laxmi

**Comment by Priyanshu-Singh-1** [comment]
> @Priyanshu-Singh-1 @Arbtrage Your name and discord id?

Name- Priyanshu Singh 
Discord ID - Priyanshu_48#8917

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 
I am still not added to your discord channels. Can you please add me in the discord

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi I am still not added to your discord channels. Can you please add me in the discord

Could you text me on discord, your name and discord id

**Comment by Priyanshu-Singh-1** [comment]
> > @Kumar-laxmi I am still not added to your discord channels. Can you please add me in the discord
> 
> Could you text me on discord, your name and discord id

Done! Kindly Check

**Comment by Neha00011** [comment]
@Kumar-laxmi I want to contribute in this project under swoc.can you please add me to your discord channel.
Name:Neha Panda
Discord Id:Neha00001#2570

**Comment by Ujwal19k** [comment]
@Kumar-laxmi I want to contribute in this project under SWOC. Can you please add me to your discord channel.
Name: Ujwal Katariya
Username: Ujwal.19#3835
ID: 865591683693543464
