### ISSUE TITLE
Feed Forward Neural Network

### ISSUE THREAD

**Issue by Paritosh-J** [Kumar-laxmi/Algorithms#620]
### Definition

A Feed Forward Neural Network is an artificial neural network in which the connections between nodes does not form a cycle. The feed forward model is the simplest form of neural network as information is only processed in one direction.
![image](https://user-images.githubusercontent.com/85030129/222732903-e273be5a-a59f-4683-9585-686720c7ee47.png)

### Implementation

Feed Forward Neural Network will be **implemented in C++**.

### Request Statement

I hereby request you to **please assign me this issue**.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Paritosh-J : C++

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi I can implement this in tensorflow, keras with the help of MNSIT dataset. Can you assign me this?

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi I can implement this in tensorflow, keras with the help of MNSIT dataset. Can you assign me this?

Can you implement it from scratch with any library or tool like ```Tensorflow```, ```keras``` or ```Pytorch```

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi No right now.
