### ISSUE TITLE
Tim Sort

### ISSUE THREAD

**Issue by Dharnish38** [Kumar-laxmi/Algorithms#629]
**Is your feature request related to a problem? Please describe.**
Tim sort is an sorting algorithm which is a combination of merge sort and insertion sort.
       1) Used in Java’s Arrays.sort() as well as Python’s sorted() and sort() inbuilt methods.
       2) First sort small pieces using Insertion Sort, then merges the pieces using a merge of merge sort.

**Describe the solution you'd like**
1) We divide the Array into blocks known as Run. 
2) We sort those runs using insertion sort one by one and then merge those runs using the combine function used in merge sort. 
3) If the size of the Array is less than run, then Array gets sorted just by using Insertion Sort.
4) The size of the run may vary from 32 to 64 depending upon the size of the array. 
5) Note that the merge function performs well when size subarrays are powers of 2. 
6) The idea is based on the fact that insertion sort performs well for small arrays.

**Pictorial Representation**
![TimSort](https://user-images.githubusercontent.com/122768878/223336824-a7a9fb7f-923b-4c2d-9982-69e21567752c.png)

**Additional context**
@Kumar-laxmi Please assign this issue to me in all four languages of **C, C++, Java and Python**

**Comment by Kumar-laxmi** [comment]
Assigned!
@Dharnish38 : C, C++, Java, Python
