### ISSUE TITLE
Report Plagiarism here

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#63]
**@contributors**, please report plagarism is found

**Comment by AnkitMajee** [comment]
> From When should we raise new issue for SWOC S3

**Comment by Durgesh4993** [comment]
Hello sir, Please assign this work to me

**Comment by Upendradwivedi** [comment]
Hello sir, i want to contribute in this project.

**Comment by PK284** [comment]
Hello Sir Please assign this to me.
I think I can make some valuable contributions.

**Comment by RAJEEVKUMAR9598** [comment]
hey sir!!
Can i upload a project based on matrix operations..
this project helps us to solve many operations in given matrix.
so can you assign me this project this is based on c++.

**Comment by Kumar-laxmi** [comment]
> hey sir @Kumar-laxmi !! Can i upload a project based on matrix operations.. this project helps us to solve many operations in given matrix. so can you assign me this project this is based on c++.

Raise an issue first with full description of your approach

**Comment by Kumar-laxmi** [comment]
@Durgesh4993 @Upendradwivedi @PK284 
### ! Please a specific issue in _issue section_ only

**Comment by Kumar-laxmi** [comment]
**@contributors** I will be pausing merging PR for 1-3 days, till then you can raise your issue and work on it

**Comment by Durgesh4993** [comment]
Ok sir
