### ISSUE TITLE
Announcement regarding SSOC'23

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#664]
This is to inform all the contributors that the coding period of SSOC'23 starts by 1st June 2023 and all the pull requests will be reviewed and merged after 1st June 2023.

**Comment by Kumar-laxmi** [comment]
All Issues and PRs made before 1st June 2023 will be closed

**Comment by ankit-0369** [comment]
I am new to github. Can anyone please help me in this. 
I had forked this repo and updated in the file which is reflected in my repo page. How can I make changes to this repo? I am not abled to to pull requests.

**Comment by Kumar-laxmi** [comment]
> I am new to github. Can anyone please help me in this. I had forked this repo and updated in the file which is reflected in my repo page. How can I make changes to this repo? I am not abled to to pull requests.

There would be a hands-on session on what is Open Source, Git and GitHub

**Comment by Coding-whiz** [comment]
> Hello @Kumar-laxmi I am interested in contributing to this project. Do we simply contribute algorithms related to the open issues or we can contribute some of our own algorithms which may not be present in this repo?

When it comes to solving issues you can only fork and pull request stating the solution but if you have another issue that is related to a repository you can click on new issue and add the issue. Once the repository owner likes your issue and merges it you can provide the solution too😌

**Comment by RougherO** [comment]
I saw that many of the C++ code has been written using plain C syntax instead of leveraging C++'s powerful tools. I wish to contribute to the C++ codes and refactor them. Could please guide me in this aspect.

**Comment by Kumar-laxmi** [comment]
> I saw that many of the C++ code has been written using plain C syntax instead of leveraging C++'s powerful tools. I wish to contribute to the C++ codes and refactor them. Could please guide me in this aspect.

Are you contributing under SSOC'23 ?

**Comment by RougherO** [comment]
> > I saw that many of the C++ code has been written using plain C syntax instead of leveraging C++'s powerful tools. I wish to contribute to the C++ codes and refactor them. Could please guide me in this aspect.
> 
> Are you contributing under SSOC'23 ?

Yes I am

**Comment by Kumar-laxmi** [comment]
> I saw that many of the C++ code has been written using plain C syntax instead of leveraging C++'s powerful tools. I wish to contribute to the C++ codes and refactor them. Could please guide me in this aspect.

Then on 1st June 2023 you can raise an issue solving this problem but with proper documentation & screen shots

**Comment by aasthak108** [comment]
Hello @Kumar-laxmi I am Aastha, and contributing under SSOC'23. 

I have experience in DSA for 3 years, I have observed thoroughly this repository and got to know that Hashing algorithms are less and also arrays one. I want to add some algorithms based on these data structures with optimization. Like, union/intersection of two arrays(hashing --less time complexity than using arrays). So, I request you to please assign this work to me.

**Union/Intersection of two arrays-**

Given two sorted arrays, find their union and intersection.
Example:

Input: arr1[] = {1, 3, 4, 5, 7}
        arr2[] = {2, 3, 5, 6} 
Output: Union : {1, 2, 3, 4, 5, 6, 7} 
         Intersection : {3, 5}

Input: arr1[] = {2, 5, 6}
        arr2[] = {4, 6, 8, 10} 
Output: Union : {2, 4, 5, 6, 8, 10} 
         Intersection : {6}

**Comment by aasthak108** [comment]
> Hello @Kumar-laxmi I am Aastha, I have experience in DSA for 3 years, and contributing under SSOC'23.
> 
> I am interested in contributing to the project. I have observed thoroughly this repository and got to know that Hashing algorithms are less and also arrays one. I want to add some algorithms based on these data structures with optimization. Like, union/intersection of two arrays(hashing --less time complexity than using arrays). So, I request you to please assign this work to me.
> 
> **Union/Intersection of two arrays-**
> 
> Given two sorted arrays, find their union and intersection. Example:
> 
> Input: arr1[] = {1, 3, 4, 5, 7} arr2[] = {2, 3, 5, 6} Output: Union : {1, 2, 3, 4, 5, 6, 7} Intersection : {3, 5}
> 
> Input: arr1[] = {2, 5, 6} arr2[] = {4, 6, 8, 10} Output: Union : {2, 4, 5, 6, 8, 10} Intersection : {6}

Hello can you please look into this. Thank you

**Comment by aasthak108** [comment]
> Hello @Kumar-laxmi I am Aastha, I have experience in DSA for 3 years, and contributing under SSOC'23.
> 
> I am interested in contributing to the project. I have observed thoroughly this repository and got to know that Hashing algorithms are less and also arrays one. I want to add some algorithms based on these data structures with optimization. Like, union/intersection of two arrays(hashing --less time complexity than using arrays). So, I request you to please assign this work to me.
> 
> **Union/Intersection of two arrays-**
> 
> Given two sorted arrays, find their union and intersection. Example:
> 
> Input: arr1[] = {1, 3, 4, 5, 7} arr2[] = {2, 3, 5, 6} Output: Union : {1, 2, 3, 4, 5, 6, 7} Intersection : {3, 5}
> 
> Input: arr1[] = {2, 5, 6} arr2[] = {4, 6, 8, 10} Output: Union : {2, 4, 5, 6, 8, 10} Intersection : {6}

Hello @Kumar-laxmi please look into this.

**Comment by Kumar-laxmi** [comment]
@aasthak108 If so then you can raise the issue

**Comment by aasthak108** [comment]
> @aasthak108 If so then you can raise the issue
Hello @Kumar-laxmi I raised an issue #1227 so please assign me this issue. Thank you!

**Comment by keenpaul29** [comment]
Hello @Kumar-laxmi sir, I am also participating in SSOC 23' and I have contributed in an issue. Will this contribution be applicable for SSOC?
