### ISSUE TITLE
Sorting Algorithms On Linked List.

### ISSUE THREAD

**Issue by mrenigmatic19** [Kumar-laxmi/Algorithms#665]
**Is your feature request related to a problem? Please describe.**
While sorting LinkedList we students face lots of confusion with LinkedList pointers.

**Describe the solution you'd like**
I will add few algorithms which helps to sort LinkedList.
Algorithm I will be working on:-
* Merge Sort
* Insertion Sort

**Additional context**
I am proficient in C++. I will implement this in C++,

**Comment by Praveen0090** [comment]
[sortlinkedlist.txt](https://github.com/Kumar-laxmi/Algorithms/files/11470041/sortlinkedlist.txtsort 
sort the linkedlist with the help of merge sort
C++ code
