### ISSUE TITLE
Bucket Sort in C & Python

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#674]
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to a problem. I would like to implement BucketSort algorithm using C and Python languages. BucketSort is a sorting algorithm that divides the input into a set of buckets and then sorts each bucket individually, typically using another sorting algorithm or recursively applying the same bucket sort algorithm. By implementing this algorithm, we can efficiently sort a collection of elements based on their distribution within a specific range. This will allow for faster sorting in scenarios where the input data has a known distribution or falls within a specific range.

**Describe the solution you'd like**
I would like a solution that provides an implementation of the BucketSort algorithm using both C and Python languages.

**Describe alternatives you've considered**
While considering the implementation of BucketSort using C and Python, I have explored a few alternative options as well. These alternatives include:
- Existing Sorting Libraries
- Hybrid Algorithms
- External Libraries
- Parallelization

**Additional context**
Here is the working of Bucket Sort:
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/281b52fa-a109-41b6-8317-33efc91c7714)

**Comment by Paritosh-J** [comment]
I request you to please assign me this issue.
Thank You

**Comment by shanvijha30** [comment]
@Kumar-laxmi Could you please assign this issue to me.
Thank you!

**Comment by Kumar-laxmi** [comment]
Assigned!
@shanvijha30 : C & Python

You can work on this issue but kindly make your PR after 1st June

**Comment by aditya0929** [comment]
@Kumar-laxmi Hi , can you assign me this issue I will make a PR request when the program starts .

**Comment by nilay2207** [comment]
@Kumar-laxmi I would like to contribute to this. Can you please assign me the issue. I will do it in both C and Python, I have deep understanding of them both so if later on you want some changes I can work on that as well. Thank you
