### ISSUE TITLE
Strassen's Matrix Multiplication in C++ & Java

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#675]
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to a problem. The problem I am facing involves implementing Strassen's Matrix Multiplication algorithm in C++ and Java.

Strassen's Matrix Multiplication is an efficient algorithm for multiplying two matrices using divide and conquer technique. It aims to reduce the number of multiplications required compared to the conventional matrix multiplication algorithm. The algorithm divides the matrices into smaller submatrices recursively until reaching a base case, and then performs matrix operations to combine the submatrices and obtain the final result.

**Describe the solution you'd like**
The solution I would like is assistance in resolving the issues I'm facing with implementing Strassen's Matrix Multiplication algorithm in C++ and Java.

**Describe alternatives you've considered**
In my pursuit of implementing Strassen's Matrix Multiplication algorithm in C++ and Java, I have considered a few alternatives to address the challenges and issues I am facing. Here are some of the alternatives I have explored:
- Conventional Matrix Multiplication
- External Libraries or Frameworks
- Code Review or Collaboration
- Online Resources and Tutorials

**Additional context**
Here is the working of algorithm:
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/5fd60e07-94e2-4f0b-a924-e9a91aca8380)

**Comment by Paritosh-J** [comment]
I request you to please assign me this issue.
Thank You

**Comment by dhruvmillu** [comment]
Please assign me this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@dhruvmillu : C++ & Java

**Comment by Abhishantpadam** [comment]
Hello man Can i also contribute in this issue i can also write the this code in c++

**Comment by SKSADIRUDDIN** [comment]
hello pls assign me this issue

**Comment by Jahnvisahni** [comment]
Please assign me this issue @Kumar-laxmi
