### ISSUE TITLE
K-Means Clustering using Python

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#676]
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to a problem. I would like to address an issue I encountered while using the K-Means Clustering algorithm in Python.

The K-Means Clustering algorithm is a popular unsupervised machine learning technique used for clustering data points into distinct groups based on their similarities. However, I have observed that the algorithm sometimes struggles with effectively handling datasets that contain outliers or have unevenly distributed clusters.

**Describe the solution you'd like**
The solution I would like involves incorporating additional functionality into the K-Means Clustering implementation in Python. Here are the specific features or improvements I would suggest:
- Robust outlier detection and removal
- Adaptive cluster initialization
- Density-based clustering extension
- Visualization tools
- Performance optimizations

**Describe alternatives you've considered**
When addressing the challenges in K-Means Clustering and considering alternatives, there are a few approaches that can be considered:
- Alternative clustering algorithms
- Preprocessing techniques
- Hybrid approaches
- Feature engineering

**Additional context**
Here is the desired result the algorithm will yield:
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/68131fbd-d519-49e7-a041-6304d95850d0)

**Comment by Paritosh-J** [comment]
I request you to please assign me this issue.
Thank You

**Comment by Kumar-laxmi** [comment]
Assigned!
@Paritosh-J : Python

You can start working on this issue, but PR would be accepted after 1st June 2023
