### ISSUE TITLE
Add Hill Climbing optimization algorithm technique

### ISSUE THREAD

**Issue by sha0urya** [Kumar-laxmi/Algorithms#680]
**Is your feature request related to a problem? Please describe.**

**Hill climbing** is a simple optimization algorithm used to find the best solution in a search space. It is inspired by the metaphor of climbing a hill to reach the highest point. 

**Describe the solution you'd like**

The algorithm starts with an initial solution and iteratively makes small incremental changes to it, always moving in the direction of improvement.

Will add Hill climbing optimization algorithm with adequate comments for readers to get a clear understanding.
To add in **C**, **C++**, **Java** and **Python**.

**Alternatives Considered :**
Can you please assign me this issue under SSoC'23 so that I can send in a PR on 1st June ?

Thank you..

**Comment by Kumar-laxmi** [comment]
Assigned!
@sha0urya : C, C++, Python & Java

**Comment by sha0urya** [comment]
Thank you..!!

**Comment by SKSADIRUDDIN** [comment]
assign me pls
