### ISSUE TITLE
Linear Regression in Java

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#681]
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to a problem. Currently, when implementing linear regression in Java, there is no standardized library or built-in functionality specifically dedicated to linear regression. While there are general-purpose libraries for machine learning in Java, they often require a significant amount of setup and configuration, which can be time-consuming and complex for beginners or developers who want a simple and straightforward solution.

**Describe the solution you'd like**
The solution I would like is the addition of a dedicated linear regression module or functionality in Java that provides a straightforward and standardized way to perform linear regression analysis.

Ideally, this solution should include the following key features:
- Simple API
- Training and Prediction Methods
- Support for Multiple Variables
- Performance Optimization
- Flexibility and Extensibility
- Documentation and Examples

**Describe alternatives you've considered**
While seeking a solution for linear regression in Java, I have considered a few alternatives to address the problem:
- External Libraries
- Manual Implementation
- Using General-Purpose Machine Learning Libraries

**Additional context**
Here is the diagram/figure to support my approach:
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/8719cf3a-d129-47bd-99c4-9fca0b239161)

**Comment by sha0urya** [comment]
@Kumar-laxmi Could you please assign this issue to me?
Thank you!

**Comment by Kumar-laxmi** [comment]
Assigned!
@sha0urya : Java

**Comment by Kumar-laxmi** [comment]
@sha0urya What is your update on this issue?

**Comment by sha0urya** [comment]
I will try to create the PR before  tommorow.
