### ISSUE TITLE
Prims in C

### ISSUE THREAD

**Issue by harshita-kaushik2** [Kumar-laxmi/Algorithms#682]
### Feature :
Prim's Algorithm is a greedy algorithm that is used to find the minimum spanning tree from a graph.
This algorithm is present in C++, Java and Python but is missing in C. 

### Description of solution :
- Will add Prim's algorithms with adequate comments and proper documentation for readers to get a clear understanding.
- To be added in C language. 

### Alternatives Considered :
- Online Resources and Tutorials
- External Libraries or Frameworks

I would like to work on this issue. Can you assign it to me under SSoC '23 ?
Thank you :)

**Comment by SPARSH1608** [comment]
am capable of implementing the Prims's algorithm in C++ and python languages. Therefore, I kindly request @Kumar-laxmi to assign me this issue.

**Comment by Jahnvisahni** [comment]
I am capable of implementing the Prims's algorithm in C .
Therefore, I kindly request @Kumar-laxmi to assign me this issue.

**Comment by Rahul-Talari** [comment]
Hi, I have optimised code for your problem, and I know it in C, C++, Java. I think I can provide justification for your problem. It would be very helpful for you if you assigned me this issue for SSOC-23 . I kindly request @Kumar-laxmi to assign me this issue.

**Comment by Kumar-laxmi** [comment]
Assigned!
@harshita-kaushik2 : C

I think by mistake you have mentioned ```Bellman Ford algorithm``` in the description, kindly update that too

**Comment by Rahul-Talari** [comment]
Sir, Once go through the comment again I haven't mention  about bellman ford algorithm

**Comment by Kumar-laxmi** [comment]
@harshita-kaushik2  What is your update on this?

**Comment by harshita-kaushik2** [comment]
Hey @Kumar-laxmi 
Due to a pending previous PR, I am unable to create a new PR for any other issue. All the changes I have made are getting pushed in the 1st PR on issue number #771 

I have made the contribution on issue #682 and am attaching the images for reference :

<img width="960" alt="code1" src="https://github.com/Kumar-laxmi/Algorithms/assets/112249538/35de205b-af12-44bb-801c-f97965507fd5">

<img width="960" alt="code3" src="https://github.com/Kumar-laxmi/Algorithms/assets/112249538/29c623d2-0712-4292-9c0d-73f84fac0944">

<img width="960" alt="code2" src="https://github.com/Kumar-laxmi/Algorithms/assets/112249538/7093edf2-80c4-4d3b-a4be-ce4825ade969">

And here is a screenshot of a sample input and the obtained output : 

<img width="959" alt="prims" src="https://github.com/Kumar-laxmi/Algorithms/assets/112249538/f59155d0-d7e1-4465-9310-f7c027220916">

Let me know if I have to make any changes for the same...

**Comment by Kumar-laxmi** [comment]
@harshita-kaushik2 What is your status on this issue?

**Comment by harshita-kaushik2** [comment]
Hey @Kumar-laxmi I've already showed you my progress on the issue. 
Can you please look into PR #771 so that I can create new PRs now...
