### ISSUE TITLE
Kruskal's Algorithm

### ISSUE THREAD

**Issue by harshita-kaushik2** [Kumar-laxmi/Algorithms#683]
### Feature :
Kruskal's Algorithm is a greedy algorithm that is used to find the minimum spanning tree from a graph.
The idea is to sort all edges of given graph in increasing order, and then keep on adding new edges and nodes in the spanning tree if the added edge does not form a cycle. 

This will be added in C, C++, Java and Python.

### Description of solution :
- Will add Kruskal's Algorithm with adequate comments and proper documentation for readers to get a clear understanding.
- To be added in C, C++, Java and Python

I would like to work on this issue. Can you assign it to me under SSoC '23 ?

**Comment by anirudh-negi** [comment]
I can work on Java for this algorithm. Please assign me under ssoc23

**Comment by Kumar-laxmi** [comment]
@harshita-kaushik2 What is your status on this issue?

**Comment by Monishparameswaran** [comment]
@Kumar-laxmi I have prior experience working with graphs in Java and I am well-versed in this particular algorithm. I am confident that I can complete this task efficiently. Kindly assign this issue to me.

**Comment by SPARSH1608** [comment]
@Kumar-laxmi Can i work on it?
