### ISSUE TITLE
Disjoint Set Union

### ISSUE THREAD

**Issue by SPARSH1608** [Kumar-laxmi/Algorithms#684]
**### Feature :**
Add Finding Components in graph using Disjoint Set Union in C,  C++ and  Python.

**### Description of solution :**
Will add Disjoint Set Union algorithm with adequate comments for readers to get a clear understanding.
To add in C, C++ and python .

**### Alternatives Considered :**
Online Resources and Tutorials

Can you assign me this issue under SSoC '23 so that I can send in a PR on 1st June ?

**Comment by Rahul-Talari** [comment]
Hi,I know it in C, C++, Java, and Python. I think I can provide  justification for your problem. It would be very helpful for you if you assigned me this issue for SSOC-23.

**Comment by Kumar-laxmi** [comment]
@SPARSH1608 Could you also implement this in Java?

**Comment by Rahul-Talari** [comment]
Yeah, I am familiar with java language

**Comment by SPARSH1608** [comment]
@Kumar-laxmi Yes I Can

**Comment by Kumar-laxmi** [comment]
Assigned!
@SPARSH1608 : C, C++, Java and Python

**Comment by Rahul-Talari** [comment]
I have done this problem and I am having the solution code in c,c++,java,python

**Comment by Kumar-laxmi** [comment]
> I have done this problem and I am having the solution code in c,c++,java,python

@Rahul-Talari If this issue is not solved within 1 week, then this issue would be assigned to you

**Comment by Rahul-Talari** [comment]
ok
