### ISSUE TITLE
Matrix Chain Multiplication in C, Java and Python

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#685]
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to a problem. Currently, when implementing matrix chain multiplication in Java and Python, there is no standardized library or built-in functionality specifically dedicated to efficiently solving this problem.

Matrix chain multiplication is a fundamental algorithmic problem that arises in various domains such as computer graphics, optimization, and numerical analysis. It involves finding the most efficient way to multiply a sequence of matrices, minimizing the total number of scalar multiplications required. However, implementing this algorithm efficiently can be complex and time-consuming, especially for developers who are not familiar with the intricacies of dynamic programming or algorithm design.

**Describe the solution you'd like**
The solution I would like is the addition of a dedicated matrix chain multiplication module or functionality in both Java and Python that provides a standardized and efficient way to solve this problem.

The ideal solution should include the following key features:
- Simple API
- Efficient Algorithms
- Support for Matrix Operations
- Performance Optimization
- Documentation and Examples

**Describe alternatives you've considered**
While seeking a solution for matrix chain multiplication in Java and Python, I have considered a few alternatives to address the problem:
- Manual Implementation
- Using General-Purpose Matrix Libraries
- Existing Algorithm Libraries

**Additional context**
Here is the reference image:
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/25f20fc6-a64b-43af-9aa5-e5245d22ee1c)

**Comment by rishabh1402** [comment]
Kindly, assign me this issue.

**Comment by Kumar-laxmi** [comment]
Assigned!
@rishabh1402 : Java & Python

**Comment by nilay2207** [comment]
I would like to work on this issue. Please assign me this issue.

**Comment by Kumar-laxmi** [comment]
Assigned!
@nilay2207 : C

**Comment by nilay2207** [comment]
Hey I had a doubt regarding this issue. Should I implement the solution
only in c or as well as java and python

**Comment by SimranLahrani842** [comment]
Assign me this issue 
My single pr is not merged yet..
@Kumar-laxmi

**Comment by Vikash0122** [comment]
Assign me this issue

**Comment by MeghanaReddyyy** [comment]
@Kumar-laxmi  please assign me this issue

**Comment by meghanareddy1808** [comment]
@Kumar-laxmi  please assign me this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@meghanareddy1808 : C, Java & Python

**Comment by Vikash0122** [comment]
@Kumar-laxmi i asked first🥲, but didn't tagged u🤧. And I have already opened the pull request in the respective folders.🥹

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi i asked first🥲, but didn't tagged u🤧. And I have already opened the pull request in the respective folders.🥹

Why did you open PR when you are only supposed to do it until you are not assigned and why did you spam PR section by creating multiple PRs that too for single issue

**Comment by Kumar-laxmi** [comment]
@meghanareddy1808 What is your status on this issue?

**Comment by meghanareddy1808** [comment]
@Kumar-laxmi I'm working on the issue. Will submit PR soon.
