### ISSUE TITLE
Binary Search Tree in Java and Python

### ISSUE THREAD

**Issue by rishabh1402** [Kumar-laxmi/Algorithms#686]
**Feature**
Binary search tree is a data structure that quickly allows us to maintain a sorted list of numbers. It is called a binary tree because each tree node has a maximum of two children.

This has already bee implemented in C, C++.

I would like to work on this issue and implement it in Java and Python. Can you assign it to me under SSoC '23 ?

**Comment by devender15** [comment]
Hey there, if no one is yet assigned to work on this issue then I want to solve this issue. Please assign this to me.

**Comment by anirudh-negi** [comment]
Hello, I can implement binary search in java. Please assign me this under ssoc 23

**Comment by Kumar-laxmi** [comment]
Assigned!
@rishabh1402 : Java & Python
