### ISSUE TITLE
Implement Hash Table Data Structure in C++

### ISSUE THREAD

**Issue by manu31shukla** [Kumar-laxmi/Algorithms#689]
**Is your feature request related to a problem? Please describe.**
I propose adding an implementation of a hash table data structure in C++ to the repository. Hash tables are widely used for efficient key-value storage and retrieval, making them an essential data structure in computer science.

**Describe the solution you'd like**
The implementation will provide the fundamental functionalities of a hash table, including insertion, deletion, and retrieval operations. It will handle collisions using a suitable collision resolution technique, such as separate chaining or open addressing.

**Describe alternatives you've considered**
The hash table will be designed to support generic key-value pairs, allowing users to store and retrieve values associated with any data type. It will provide a flexible and reusable solution that can be easily integrated into various projects.

The implementation will also include performance optimizations, such as load factor management and dynamic resizing, to ensure efficient operation even with a large number of elements.

**Additional context**
To facilitate usability and code readability, the implementation will be well-documented, with clear explanations of the data structure, its operations, and any underlying algorithms or techniques used. Additionally, proper unit tests will be provided to ensure correctness and robustness.

By adding this hash table implementation to the repository, it will serve as a valuable resource for anyone working on projects requiring efficient key-value storage and retrieval. It can be utilized as a reference or directly integrated into applications.

Please let me know if there are any specific guidelines or preferences regarding the implementation or any additional requirements for contributing to the repository. I am eager to contribute this important data structure to the repository and enhance its functionality.

**Comment by nilay2207** [comment]
I would love to work on this can you please assign me this issue.

**Comment by manu31shukla** [comment]
Hey @nilay2207 , I actually initiated this issue to work on it further after getting permission from @Kumar-laxmi
.

**Comment by nilay2207** [comment]
Oh my bad

**Comment by Rahul-Talari** [comment]
Hi, I have optimised code for your problem, and I know it in C, C++, Java, and Python. I think I can provide 100% justification for your problem. It would be very helpful for you if you assigned me this issue for SSOC-23.

**Comment by Kumar-laxmi** [comment]
@manu31shukla Could you choose one more language to work on?

**Comment by Rahul-Talari** [comment]
Are you asking to choose one more language or to choose 1 language from above languages.

**Comment by Rahul-Talari** [comment]
I can implement in javascript also
