### ISSUE TITLE
Add Fibonacci Search

### ISSUE THREAD

**Issue by ANI2707** [Kumar-laxmi/Algorithms#690]
**Fibonacci search** is an _efficient_ search algorithm that can quickly locate a target element in a sorted array. It achieves this by dividing the search space into Fibonacci numbers and narrowing down the search range based on the comparison of the target element with the middle element of the subarray.

**Feature :**
Add Fibonacci Search in C++ , C ,  Python , Java

**Description of solution :**

- Will add Fibonacci Search with adequate comments and proper documentation for readers to get a clear understanding.
- To be added in C, C++, Java and Python

**Alternatives Considered :**
Can you please assign me this issue under SSoC'23 so that I can send in a PR on 1st June ?

**Comment by VatsalHShah** [comment]
Hello! Can you please assign me this issue for SSOC-23. I have knowledge about fibonacci series and would like to implement that in a searching technique.

**Comment by anshikachamoli18** [comment]
Hello! Can you please assign me this issue under SSOC'23 ..I have knowledge of fibonacci algorithm in C and java ..so I can implement it in C and java..Please assign it to me..

**Comment by esha-26** [comment]
Hi, I know C, C++and Java. I also know the detailed working of fibonacci algorithm. Kindly assign this to me.

**Comment by gungunyadav02** [comment]
Hello! I have knowledge of fibonacci algorithm in C,C++ and java .Please assign this issue to me under SSOC'23.

**Comment by Kumar-laxmi** [comment]
Assigned!
@ANI2707 : C, C++, Java and Python
