### ISSUE TITLE
wanted to add Breadth-First Search code using java

### ISSUE THREAD

**Issue by GOPAL181** [Kumar-laxmi/Algorithms#691]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GOPAL181** [comment]
Breadth-First Search is a node method for obtaining the graph's shortest path.

**Comment by GOPAL181** [comment]
I would like to work on this issue and implement it in Java and Python. Can you assign it to me under SSoC '23 ?

**Comment by AggarwalNeelesh** [comment]
Assign me the task

**Comment by Rahul-Talari** [comment]
Hi, I have optimised code for your problem, and I know it in C, C++, Java, and Python. I think I can provide 100% justification for your problem. It would be very helpful for you if you assigned me this issue for SSOC-23.

**Comment by Aditya-Lawate-codez** [comment]
Hi there, I am experienced with java OOPS, I can contribute to this project very efficiently.
kindly assign me this project under SSOC 2023

**Comment by Siya8een** [comment]
i will resolve the issue please assign this to me

**Comment by anasadh** [comment]
I would like a clear and concise explanation of how the Breadth-First Search algorithm should be implemented in Java. It would be helpful if there's a step-by-step guide or sample code that I can follow to ensure the correct implementation.
