### ISSUE TITLE
Adding Reverse Integer code in Java

### ISSUE THREAD

**Issue by swastik-akhil** [Kumar-laxmi/Algorithms#693]
### Adding Code 
As Java is a widely used and highly preferred programming language, it is surprising that the code for reversing an integer is not readily available in Java. In light of this, I would be delighted to assist you by assigning the task of implementing the code for reversing an integer in Java under SSOC'2.
Admin - @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
@swastik-akhil Since this is an easy issue, kindly implement this algorithm in C and Java

**Comment by Kumar-laxmi** [comment]
Assigned!
@swastik-akhil : C & Java

**Comment by HARSHSUHANE17** [comment]
@Kumar-laxmi can i do this in C++?

**Comment by Mahendra-Lohar** [comment]
@Kumar-laxmi  I will do it C and java both please  assign me this issue.
