### ISSUE TITLE
Adding Cocktail Sort code in Java

### ISSUE THREAD

**Issue by swastik-akhil** [Kumar-laxmi/Algorithms#694]
I am enthusiastic about taking on the task of writing the Cocktail Sort code in Java as part of SSOC'2, in order to provide a valuable addition to the Algorithm repository.
Admin - @Kumar-laxmi

**Comment by Jahnvisahni** [comment]
Please assign me this issue @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
@swastik-akhil Since this is an easy issue, it has to be implemented in all four languages. But it has been implemented in ```C++``` so could you implement this in ```C```, ```Python``` and ```Java```.

**Comment by swastik-akhil** [comment]
I'll do that @Kumar-laxmi

**Comment by SivaHarshith1303** [comment]
Please assign me this issue @Kumar-laxmi . I can do it in Java , C and Python . With Proper Comments

**Comment by rafiya2003** [comment]
I would like to work on this, frankly I don't know much but I will learn and do. I am a newbie(first year UG student). I want to learn and grow. please give me the opportunity to learn and experience

**Comment by Rohith1816** [comment]
Cocktail sort is a variation of bubble sort that is both a stable sorting algorithm and a comparison sort. The algorithm differs from a bubble sort in that it sorts in both directions on each pass through the list. 
@Kumar-laxmi Please assign this to me  and I will do it in all the four languauges (c,c++,java,python) with a proper documnetation

**Comment by Panda-Abhisek** [comment]
Hey, can I get this project under SSOC 23 as a beginner?

**Comment by harshit7045** [comment]
Hello,@Kumar-laxmi

My name is Harshit Mishra, and I am a student at IIIT Una. I possess a strong understanding of data structures and algorithms and have the ability to write optimized code with explanatory comments. I kindly request to be assigned this issue.
Thank you.

**Comment by Mahendra-Lohar** [comment]
@Kumar-laxmi please assign me this issue I will do it . I am also a contributor in SSOC23
