### ISSUE TITLE
Add Longest Arithmetic Subsequence of Given Difference using Dynamic Programming in Java, Python and C++

### ISSUE THREAD

**Issue by shanvijha30** [Kumar-laxmi/Algorithms#695]
Feature : 

Given an integer array and an integer difference, return the length of the longest subsequence in array which is an arithmetic sequence such that the difference between adjacent elements in the subsequence equals difference.

A subsequence is a sequence that can be derived from array by deleting some or no elements without changing the order of the remaining elements.

![longest subsequence](https://github.com/Kumar-laxmi/Algorithms/assets/76652184/fbd556ff-237b-4d82-a573-d4267ed94ae2)

Solution:

Will provide the solution for the Longest Arithmetic Subsequence of Given Difference in Java, Python and C++ will proper comments and documentation.

I would like to work on this issue.
Could you please assign this issue to me under SSoC ' 23.

**Comment by shanvijha30** [comment]
@Kumar-laxmi Could you please assign this issue to me. I would like to work on it.
Thank you!

**Comment by shanvijha30** [comment]
@Kumar-laxmi I would like to work on this issue.
Could you please assign this to me.

**Comment by shanvijha30** [comment]
@Kumar-laxmi I would like to work on this issue.
Could you please assign it to me.

**Comment by Veena4512** [comment]
@Kumar-laxmi I can implement in java, c++, python.  I participate in various coding competitions. So can you please assign it to me?

**Comment by samroy-1** [comment]
@Kumar-laxmi ,I have coded similar pattern such as this and believe to have the correct expertise to work on it. Could you please assign this work to me?

**Comment by ishitagithub** [comment]
Greetings Sir, Please assign me this issue under SSOC' 23. I have a solid grasp of data structures and algorithms, enabling me to write efficient code with detailed explanations. I can write both naive and effective approach( using Dynamic Programming) to this problem. I can provide algorithm as well as code in any of these languages- C, C++, Java, Python.

**Comment by vivekpal24** [comment]
Sir kindly this assign to this me i can easily solve this issue in C,Cpp and Python language
