### ISSUE TITLE
Add Recursion Folder for Java Algorithms

### ISSUE THREAD

**Issue by Jiggy9** [Kumar-laxmi/Algorithms#696]
**Is your feature request related to a problem? Please describe.**
The problem at hand is the absence of a recursion algorithm in the repository, which is crucial for DSA interview preparation. Users currently lack a comprehensive resource for studying and practicing recursion concepts and problem-solving techniques.

**Describe the solution you'd like**
I suggest creating a new folder called "Recursion" within the existing Java folder of the repository. In this folder, I will add important recursion questions, such as Permutation of a String, Subsequences, Counting Zeroes in a Number, Palindrome, Digit Product, and Digit Sum. By incorporating these questions, the repository will offer a comprehensive selection of recursion problems for users to practice and learn from.

**Describe alternatives you've considered**
An alternative solution would involve creating a separate repository dedicated exclusively to recursion algorithms. However, integrating the recursion folder within the existing repository would provide users with a more streamlined and convenient experience, as it consolidates different algorithm topics in one place.

**Additional context**
As an open-source contributor for SSOC'23 with a strong understanding of DSA interview preparation, I believe that adding the recursion folder and including essential recursion questions will greatly enhance the educational value of the repository. This comprehensive resource will serve as a valuable asset for the community, facilitating effective learning and preparation for recursion algorithms.

**Comment by Kumar-laxmi** [comment]
@Jiggy9 Recursion folder has been added

**Comment by Jiggy9** [comment]
Thank you for creating recursion folder.. I would like to contribute important algorithm questions that I mentioned before to that folder in java.. can you assign to me?

**Comment by Kumar-laxmi** [comment]
You can create separate issue for that
