### ISSUE TITLE
Add Badges to Readme

### ISSUE THREAD

**Issue by Thrillseekr** [Kumar-laxmi/Algorithms#698]
**Is your feature request related to a problem? Please describe.**
I think there should be badges related to the Techstack this repository is based on.

**Describe the solution you'd like**
I'll add Badges of Techstack used along with data of fork, starred, watch, PRs etc

**Describe alternatives you've considered**

**Additional context**

**Comment by Kumar-laxmi** [comment]
Could you exactly provide a sample or demo of what you want to implement

**Comment by Thrillseekr** [comment]
I'll  be adding interactive badges and related to Tech Stacks used in this project as shown in below screenshot.

![Screenshot_20230531-113546_Chrome](https://github.com/Kumar-laxmi/Algorithms/assets/118781875/bc77fa72-d6dc-4325-a5d3-01365472efe9)

**Comment by Kumar-laxmi** [comment]
Sounds great!

Assigned!
@Thrillseekr
