### ISSUE TITLE
Implementing "Interpolation Search" in java, c++, c, python.

### ISSUE THREAD

**Issue by nilay2207** [Kumar-laxmi/Algorithms#699]
**Is your feature request related to a problem? Please describe.**
This feature is not directly related to any issue, but I just wanted to add a new algorithm which was not present in the repository.

**Describe the solution you'd like**
I would like to add the Interpolation Search algo with source code written in java, python, c++, c.

**Describe alternatives you've considered**
As it is a algorithm I don't find any alternatives

**Additional context**
The Interpolation Search has a time complexity of  O(log log n).

**Comment by Kumar-laxmi** [comment]
Assigned!
@nilay2207 : C, C++, Python, Java

**Comment by Kumar-laxmi** [comment]
What is your status on this issue?
