### ISSUE TITLE
To add 3sum problem in arrays in C++

### ISSUE THREAD

**Issue by ayan-joshi** [Kumar-laxmi/Algorithms#702]
**Is your feature request related to a problem? Please describe.**
Yes it's one of the most important problem and algorithm in arrays data structure

**Describe the solution you'd like**
I will add the cpp code of solving the 3sum problem.

**Describe alternatives you've considered**
Also with the solution I will add a readme file to explain the solution as well..

**Additional context**
Please @Kumar-laxmi  assign me this issue I'm a SSOC contributor.

**Comment by Kumar-laxmi** [comment]
Sorry it has been implemented in all four languages, refer algorithm no. 82

**Comment by ayan-joshi** [comment]
Can you please assign me any other algorithm from your side please @Kumar-laxmi

**Comment by ayan-joshi** [comment]
I can do the same for 4 sum problem please assign for 4sum problem @Kumar-laxmi
