### ISSUE TITLE
Add Partition Problem using Dynamic Programming in java and c++ .

### ISSUE THREAD

**Issue by Aishjahan** [Kumar-laxmi/Algorithms#704]
I want to add Partition Problem using Dynamic Programming in java and c++.

![Screenshot 2023-05-30 234922](https://github.com/Kumar-laxmi/Algorithms/assets/105747510/cd53c996-7c8f-4c68-a4a6-8606fbca4efc)

Please assign me this issue.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Aishjahan : C++ & Java
