### ISSUE TITLE
Add Shortest Common Supersequence Problem using Dynamic Programming in java .

### ISSUE THREAD

**Issue by Aishjahan** [Kumar-laxmi/Algorithms#705]
I want to add Shortest Common Supersequence Problem using Dynamic Programming in java .

![Screenshot 2023-05-30 235150](https://github.com/Kumar-laxmi/Algorithms/assets/105747510/d4ab7769-65f6-47cc-840b-ae96ede208a5)

Please assign me this issue.

**Comment by Kumar-laxmi** [comment]
Could you choose one more language to work on?

**Comment by Aishjahan** [comment]
yeah sure, I can do it in Java, C++, and python.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Aishjahan : C, C++, Java & Python

**Comment by ishitagithub** [comment]
Greetings Sir, Please assign me this issue under SSOC' 23. I have a solid grasp of data structures and algorithms, enabling me to write efficient code with detailed explanations. I can write both naive and effective approach( using Dynamic Programming) to this problem. I can provide algorithm as well as code in any of these languages- C, C++, Java, Python.

**Comment by Mahendra-Lohar** [comment]
@Kumar-laxmi Please assign me this issue. I will do it in C, C++, Java , Python . I am also a contributor in SSOC23'.
