### ISSUE TITLE
Add The Levenshtein distance (Edit distance) Problem using Dynamic Programming in java.

### ISSUE THREAD

**Issue by Aishjahan** [Kumar-laxmi/Algorithms#706]
I want to add The Levenshtein distance (Edit distance) Problem using Dynamic Programming in java.

![Screenshot 2023-05-31 000111](https://github.com/Kumar-laxmi/Algorithms/assets/105747510/7287aa58-6bb8-45ce-a060-e85bcf26e48c)

Please assign me this issue.

**Comment by Kumar-laxmi** [comment]
Issue description is incomplete

**Comment by Aishjahan** [comment]
![Screenshot 2023-05-31 101300](https://github.com/Kumar-laxmi/Algorithms/assets/105747510/26ce9c98-5d35-4a05-9bc5-4f846a649fa5)
![Screenshot 2023-05-31 101323](https://github.com/Kumar-laxmi/Algorithms/assets/105747510/5cc1dd3e-9592-4023-8613-53169f537958)
![Screenshot 2023-05-31 101343](https://github.com/Kumar-laxmi/Algorithms/assets/105747510/d804695f-4b4e-4b7e-b44e-5fb44a788ad6)


Here is an elaborative detail of the question.

**Comment by Kumar-laxmi** [comment]
Could you implement this in ```C```, ```Java``` and ```Python```

**Comment by Aishjahan** [comment]
yeah sure, I can do it in Java, C, and python.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Aishjahan : C, Java & Python

**Comment by Aarsh30** [comment]
i would like to contribute this and i can implement this

**Comment by rafiya2003** [comment]
I would like to work on this, frankly I don't know much but I will learn and do. I am a newbie(first year UG student). I want to learn and grow. please give me the opportunity to learn and experience

**Comment by Aishjahan** [comment]
> Assigned! @Aishjahan : C, Java & Python

Hey, you have assigned me the issue but it still shows on the issue that no one is assigned, will you please once look into it so that I can make a PR.
