### ISSUE TITLE
Add Depth First Search (DFS) in Graph – Iterative and Recursive Implementation

### ISSUE THREAD

**Issue by Aishjahan** [Kumar-laxmi/Algorithms#707]
I want to add dfs of graph in java,C++ and python.
Please assign me this issue.

**Comment by SANKOJUKEERTHI** [comment]
I WANT TO ADD THIS ALGORITHM USING JAVA AND CAN ASSURE OPTIMISED SOLUTION

**Comment by Aarsh30** [comment]
I would like to work on this and would like to contribute so could you please assigned me and i would provide different approaches

**Comment by P766-spec** [comment]
I would like to work on this issue under SSOC'23, could you please assign this to me @Kumar-laxmi

**Comment by SANKOJUKEERTHI** [comment]
I saw that the topological sort is not added for Java. I know the optimised solution for topo sort in Java. Can you create an issue for that and assign it to me. (SSOC'23)
