### ISSUE TITLE
To add C Implementation of Order Agnostic Binary Search ( No. 79)

### ISSUE THREAD

**Issue by git-leo-here** [Kumar-laxmi/Algorithms#708]
**Problem Statement :**
We are given an array which may be either sorted in ascending or descending order . Our task is to search for whether an element is present in the array . If yes , then at which position .

This problem corresponds to the Algorithm no. 79 .

**Approach :**
1. First determine whether the given array is sorted in Ascending or Descending order .
2. a) If array is sorted in Ascending order : run the corresponding code to sort the array .
2. b)  If array is sorted in Ascending order : run the corresponding code to sort the array .

**Additional context**
I would try to add modular code so that it is easier for the users to understand the working of the algorithm.

@Kumar-laxmi , @Rishikavishnoi , @072arushi . Please assign me this issue under SSOC'23.

**Comment by Kumar-laxmi** [comment]
@git-leo-here Could you implement this in Java also, so that problem is 100% completed

**Comment by git-leo-here** [comment]
Yes , would love to contribute the C and Java Implementations

**Comment by Kumar-laxmi** [comment]
Assigned!
@git-leo-here : C & Java

**Comment by git-leo-here** [comment]
Thanks !
