### ISSUE TITLE
Add Topological Sort Algorithm for DAG .

### ISSUE THREAD

**Issue by Aishjahan** [Kumar-laxmi/Algorithms#709]
I want to add Topological Sort Algorithm for DAG in java,C++ and python.
Please assign me this issue.

**Comment by Kumar-laxmi** [comment]
@Aishjahan Issue description is incomplete

**Comment by Aishjahan** [comment]
Here is the description of the problem.

![Screenshot 2023-05-31 103355](https://github.com/Kumar-laxmi/Algorithms/assets/105747510/67fabde3-e784-4b10-ae14-41de2a9631d4)
![Screenshot 2023-05-31 103412](https://github.com/Kumar-laxmi/Algorithms/assets/105747510/f4f058a0-91d9-4592-b354-b564657f0f85)

**Comment by Kumar-laxmi** [comment]
Assigned!
@Aishjahan : C, Python and Java
