### ISSUE TITLE
Add Breadth-First Search (BFS) – Iterative and Recursive Implementation.

### ISSUE THREAD

**Issue by Aishjahan** [Kumar-laxmi/Algorithms#711]
I want to add Breadth-First Search (BFS) – Iterative and Recursive Implementation in java, C++ and python.

Please assign me this isuue.

**Comment by Kumar-laxmi** [comment]
@Aishjahan This algorithm has not been implemented in ```C``` and ```Python```, so would you like to work on these two languages?

**Comment by Aishjahan** [comment]
Yeah sure, I'll be happy to work on it.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Aishjahan : C & Python
