### ISSUE TITLE
Reverse Linked List in group of K

### ISSUE THREAD

**Issue by pearlrathour** [Kumar-laxmi/Algorithms#712]
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to a problem. I would like to write a sorting algorithm for sorting a linked list in group of k using Cpp.

Original Linked List-
![image](https://github.com/Kumar-laxmi/Algorithms/assets/99817664/f03abecd-b5ed-4cf0-87a7-02c6ffea4faf)

Reverse Linked List (k=3)-
![image](https://github.com/Kumar-laxmi/Algorithms/assets/99817664/db92e3ee-72fa-4a80-9783-1317bd5bc92f)

I Will provide the solution for Reverse linked list in group of k problem with proper comments and documentation.

I would like to work on this issue.
Could you please assign this issue to me under SSoC ' 23.

**Comment by Kumar-laxmi** [comment]
@pearlrathour Could you implement this in all four languages?

**Comment by pearlrathour** [comment]
Yes, I will provide code in all 4 languages.

**Comment by Kumar-laxmi** [comment]
Assigned!
@pearlrathour : C, C++, Python and Java
