### ISSUE TITLE
Binary Tree View- Top, Bottom, Right, Left

### ISSUE THREAD

**Issue by pearlrathour** [Kumar-laxmi/Algorithms#715]
Given a binary tree, the task is to give output as top, bottom, rigt, left view of binary tree.

Example-

![image](https://github.com/Kumar-laxmi/Algorithms/assets/99817664/be1e7d89-66ee-4851-848c-eea69a870ae6)

Expexted output-

Top View : 3 1 0 2 5 8
Bottom View : 3 6 4 7 5 8
Left View :  0 1 3 6
Right View :  0 2 5 8

I Will provide the solution for Binary Tree problem in with proper comments and documentation.

I would like to work on this issue.
Could you please assign this issue to me under SSoC ' 23.

**Comment by Kumar-laxmi** [comment]
@pearlrathour Since it is an easy issue, could you implement this in all four languages: ```C```, ```C++```, ```Java``` and ```Python```

**Comment by pearlrathour** [comment]
Yes, I will provide code in all 4 languages.

**Comment by Rahul-Talari** [comment]
I have done this and i have solution in all the 4 languages.

**Comment by Kumar-laxmi** [comment]
Assigned!
@pearlrathour : C, C++, Python and Java
