### ISSUE TITLE
Add recursion question: String Permutation in Java

### ISSUE THREAD

**Issue by Jiggy9** [Kumar-laxmi/Algorithms#716]
Hey @Kumar-laxmi  I would like to add Java recursion important questions. Can you assign me as SSOC'23 contributor? Thank you.

**Comment by Kumar-laxmi** [comment]
@Jiggy9 Kindly open issue very specific to an algorithm you would like to work on

**Comment by Kumar-laxmi** [comment]
Kindly change the issue title and description ASAP

**Comment by Jiggy9** [comment]
I will add important recursion questions, such as Permutation of a String, Subsequences, Counting Zeroes in a Number, Palindrome, Digit Product, and Digit Sum. Sorry for inconvenience but I already mentioned everything in detail #696 which you closed.

**Comment by Kumar-laxmi** [comment]
> I will add important recursion questions, such as Permutation of a String, Subsequences, Counting Zeroes in a Number, Palindrome, Digit Product, and Digit Sum. Sorry for inconvenience but I already mentioned everything in detail #696 which you closed.

@Jiggy9 Kindly work on one algorithm at a time (It would be easy for other contributors to work on these algorithms)

**Comment by Kumar-laxmi** [comment]
Kindly choose one algo. and update title & description

**Comment by Jiggy9** [comment]
Sure, I understand.

**Comment by Jiggy9** [comment]
I will add String Permutation algo in java.

**Comment by Kumar-laxmi** [comment]
> I will add String Permutation algo in java.

Kindly mention a proper description about this issue

**Comment by Kumar-laxmi** [comment]
Along with screen shots, sample input and output

**Comment by Jiggy9** [comment]
<img width="538" alt="C1" src="https://github.com/Kumar-laxmi/Algorithms/assets/112299754/c6ee8f0b-3426-46ba-bfb0-7d2b3859c45d">
<img width="749" alt="C2" src="https://github.com/Kumar-laxmi/Algorithms/assets/112299754/2cc0deda-2e21-4cc5-869b-fcf634de31be">

Here I can take any String input for example input: "abc" and this approach generates all permutations of a given string using a recursive algorithm. It iterates through each character and inserts it at all possible positions within the current permutation. The time complexity is O(n!), where n is the length of the input string, and the space complexity is O(n^2).

**Comment by Kumar-laxmi** [comment]
Since this is an easy issue, you need to implement this in all four languages

Assigned!
@Jiggy9 : C, C++, Java & Python

**Comment by Jiggy9** [comment]
Sure, I will add it in C, C++, Java, and Python as well and will send a pull request on June 1st when SSOC starts!
