### ISSUE TITLE
0/1 Knapsack - Dynamic Programming approach

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#72]
0/1 Knapsack is available in the following languages:
- C
- C++
- Java
- Python

### Kindly include this project in **Dynamic Programming** folder

**Comment by Priyanshu-Singh-1** [comment]
Can you assign this issue to me as well? I have also solved this approach in my last week. So I am pretty confident in solving it once again.

So, I request you to please assign this issue to me

**Comment by Kumar-laxmi** [comment]
> Can you assign this issue to me as well? I have also solved this approach in my last week. So I am pretty confident in solving it once again.
> 
> So, I request you to please assign this issue to me

@Priyanshu-Singh-1 Kindly mention the languages you want to work on

**Comment by Priyanshu-Singh-1** [comment]
I would like to work with C++.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Priyanshu-Singh-1 : C++

**Comment by Priyanshu-Singh-1** [comment]
Thanks!
I will complete my task!

**Comment by harshraj9988** [comment]
please assign this task to me for java

**Comment by Kumar-laxmi** [comment]
Assigned!
@Priyanshu-Singh-1 : C++
@harshraj9988 : Java

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi, I have created PR for the C++ approach.

I request you to have a look, and if there is any issue feel free to tell me.

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi, Since, I have completed the work with C++, can you assign this issue to C language as well?

I would be happy to work on this issue as well

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi, Since, I have completed the work with C++, can you assign this issue to C language as well?
> 
> I would be happy to work on this issue as well

@Priyanshu-Singh-1 Please update the C File in the same PR

**Comment by Kumar-laxmi** [comment]
Assigned!
@Priyanshu-Singh-1 : C
@Priyanshu-Singh-1 : C++
@harshraj9988 : Java

**Comment by Priyanshu-Singh-1** [comment]
Sure, for now, I have closed my PR and will make a new one for both,  after completing for C

**Comment by Priyanshu-Singh-1** [comment]
I have made the PR containing the contribution for both issues that you have mentioned.

**Comment by harshraj9988** [comment]
@Priyanshu-Singh-1  Can I please use your problem statement for solving this issue in Java?

**Comment by PiXeL99-eng** [comment]
@Kumar-laxmi Please assign me this issue for Python code.

**Comment by Kumar-laxmi** [comment]
Assigned!
@harshraj9988 : Java
@PiXeL99-eng : Python

**Comment by Kumar-laxmi** [comment]
This algorithm has been implemented in all languages
