### ISSUE TITLE
To add Greedy Algorithm 

### ISSUE THREAD

**Issue by ayan-joshi** [Kumar-laxmi/Algorithms#725]
**Is your feature request related to a problem? Please describe.**
Yes , Greedy algorithm is used to solve problems to find anything in minimum attempt.

**Describe the solution you'd like**
I would like to add proper description and solution of greedy algorithm with a solve example of it 

**Describe alternatives you've considered**
I can do it for all three languages java ,c++ and python.

**Additional context**
@Kumar-laxmi  Please assign me this issue I'm a SSOC contributor

**Comment by Kumar-laxmi** [comment]
@ayan-joshi Greedy algorithm is a vast concept, kindly raise issue pertaining to specific algorithm
