### ISSUE TITLE
To add 4sum problem 

### ISSUE THREAD

**Issue by ayan-joshi** [Kumar-laxmi/Algorithms#726]
**Is your feature request related to a problem? Please describe.**
4sum problem is one of the important topic or the question in array data structure.

**Describe the solution you'd like**
It includes two or three solutions with different time and space complexity.

**Describe alternatives you've considered**
I can do it for three of the languages.

**Additional context**
@Kumar-laxmi Please assign me this issue I'm a SSOC contributor

**Comment by nazeer-18** [comment]
@Kumar-laxmi  
I'm good at solving this issue and i already solved this problem on GFG can you please assign this task to me?
https://practice.geeksforgeeks.org/problems/find-all-four-sum-numbers1732/1
This is my sol i got ac .

**Comment by Kumar-laxmi** [comment]
Assigned!
@ayan-joshi : C, C++, Python and Java

**Comment by Kumar-laxmi** [comment]
@ayan-joshi Could you provide a sample input-output, related screen-shots and under which category does this algorithm falls under

**Comment by Kumar-laxmi** [comment]
@nazeer-18 You can look into other unassigned issues or create a new issue

**Comment by nazeer-18** [comment]
ok sure thanks for responding
________________________________

**Comment by ayan-joshi** [comment]
@Kumar-laxmi okay I will add sample input and output as well , you need that in  as screenshots only or can be in written format also ?

**Comment by ayan-joshi** [comment]
@Kumar-laxmi I have answered the question I will add sample inputs and output please assign me

**Comment by Courage003** [comment]
I can provide with the most efficient and easy to understand C++ code....Please assign this task to me....

**Comment by Vaishu03** [comment]
@Kumar-laxmi I would like to work on this issue under SSOC'23, could you please assign this task to me

**Comment by ashif88** [comment]
can you please assign me this task I would love to contribute.
I have solved 4 sum problem in Leetcode.
I have solved 900+ DSA Problems in various Coding Platforms.
Some of my achievement includes:

Knight badge on [Leetcode](https://leetcode.com/ashifakhtar/)
4 Star on [Codechef](https://www.codechef.com/users/ashif_29dec)
Specialist on [Codeforces](https://codeforces.com/profile/ash88)

**Comment by Kumar-laxmi** [comment]
Kindly don't raise issues to solve DSA questions from LeetCode, HackerRank, etc
