### ISSUE TITLE
Add Bogo Sort 

### ISSUE THREAD

**Issue by Gaurang1602** [Kumar-laxmi/Algorithms#729]
### Bogo sort : -
Bogo sort is an algorithm used to sort the elements of an array by randomly generating different permutations of an array and then checking whether it is sorted or not. It’s based on the generate-and-test paradigm. Other names for bogo sort include permutation sort, stupid sort, slow sort, shotgun sort, or monkey sort. 

**Feature : -**
Add Bogo sort in C++ , C , java , python.

**Description of solution :**

-  Will add Bogo sort with adequate comments and proper documentation for readers to get a clear understanding.
-  To be added in C, C++, Java and Python.

 **Alternatives Considered :**
  Can you please assign me this issue under SSoC'23 so that I can send in a PR on 1st June ?

**Comment by Kumar-laxmi** [comment]
Assigned!
@Gaurang1602 : C, C++, Python and Java

**Comment by Kumar-laxmi** [comment]
@Gaurang1602 What is your status on this issue?

**Comment by Gaurang1602** [comment]
@Kumar-laxmi 
Actually sir , I am sick so that's why I am not able to do any PR , but from today I will start working on it , so please give me sometime .

**Comment by Kumar-laxmi** [comment]
Sorry @Gaurang1602 I have to unassign you due inactivity
