### ISSUE TITLE
Fractional Knapsack - Greedy approach

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#73]
Fractional Knapsack is available in the following languages:
- C
- C++
- Java
- Python

### Kindly include this project in **Greedy Programming** folder

**Comment by Priyanshu-Singh-1** [comment]
Can you assign this issue to me?
I will be happy to solve this issue

**Comment by Kumar-laxmi** [comment]
> Can you assign this issue to me? I will be happy to solve this issue

@Priyanshu-Singh-1 Please mention the language you would like to work on

**Comment by Priyanshu-Singh-1** [comment]
Can I mention two or more languages?
If its not possible then I could work on C++.

**Comment by Kumar-laxmi** [comment]
> Can I mention two or more languages? If its not possible then I could work on C++.

@Priyanshu-Singh-1 You can take any two language

**Comment by mayyyur** [comment]
I want to contribute fractional knapsack program in C language can you assign it to me ?

**Comment by Priyanshu-Singh-1** [comment]
Okay, thanks. I will first work with C++, after successful completion, I will work with the second language.
 I will work with C++

**Comment by Kumar-laxmi** [comment]
@mayyyur : C
@Priyanshu-Singh-1 : C++

**Comment by stiwari-ds** [comment]
I would like to work on this algorithm in **Python**, for SWOC S3.

Github: https://github.com/stiwari-ds
Devfolio: https://devfolio.co/@s_tiwari

**Comment by Soham-Chakraborty-8455** [comment]
I want to work on the C++ program. Please assign me

**Comment by Soham-Chakraborty-8455** [comment]
Yes, but I would prefer C++

**Comment by stiwari-ds** [comment]
@Kumar-laxmi I would prefer to work in Python since I have not worked with C/C++ for a long time. If Python version for Fractional Knapsack is already assigned, I can choose from other algorithms. Looking forward to contribute.

**Comment by Kumar-laxmi** [comment]
Assigned!
@stiwari-ds : Python
@Soham-Chakraborty-8455 : C

**Comment by khushigarg1** [comment]
> Fractional Knapsack is available in the following languages:
> 
> * C
> * C++
> * Java
> * Python
> 
> ### Kindly include this project in **Greedy Programming** folder

I would like to code in C. Can you assign this issue to me?

**Comment by Kumar-laxmi** [comment]
@Soham-Chakraborty-8455 Due to your inactivity I have unassigned this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@khushigarg1 : C

**Comment by Kumar-laxmi** [comment]
This algorithm is only available in:
- Java

**Comment by khushigarg1** [comment]
> This algorithm is only available in:
> 
> * Java

Can you assign this issue to me?

**Comment by Kumar-laxmi** [comment]
Assigned!
@khushigarg1 : Java
