### ISSUE TITLE
bogo sort

### ISSUE THREAD

**Issue by subhamsubham6063** [Kumar-laxmi/Algorithms#730]
**Is your feature request related to a problem? Please describe.**
I want to add bogo sort in  C and C++ language.

**Comment by Gaurang1602** [comment]
@subhamsubham6063 this Algorithm is not present in sorting algorithms so I opened this issue also this issue is opened by me first so please it is a humble request , to let me work on it.

**Comment by Kumar-laxmi** [comment]
refer #729
