### ISSUE TITLE
Add Comb sort  Algorithm 

### ISSUE THREAD

**Issue by Gaurang1602** [Kumar-laxmi/Algorithms#731]
### Comb sort : -
It is a comparison-based sorting algorithm that is mainly an improvement in bubble sort. In bubble sort, there is a comparison between the adjacent elements to sort the given array. So, in bubble sort, the gap size between the elements that are compared is 1. Comb sort improves the bubble sort by using a gap of size more than 1. The gap in the comb sort starts with the larger value and then shrinks by a factor of 1.3. It means that after the completion of each phase, the gap is divided by the shrink factor 1.3. The iteration continues until the gap is 1.

**Feature : -**

Add Comb sort in C++ , C , java , python.

**Description of solution :-**

- Will add comb sort with adequate comments and proper documentation for readers to get a clear understanding.
- To be added in C, C++, Java and Python.

**Alternatives Considered :**
Can you please assign me (@Kumar-laxmi ) this issue under SSoC'23 so that I can send in a PR on 1st June ?

**Comment by Kumar-laxmi** [comment]
Assigned!
@Gaurang1602 : C, C++, Python and Java

**Comment by Kumar-laxmi** [comment]
@Gaurang1602 What is your status on this issue?

**Comment by anand-harsh** [comment]
@Kumar-laxmi can you assign me this issue please

**Comment by Gaurang1602** [comment]
> @Gaurang1602 What is your status on this issue?

@Kumar-laxmi  
Actually sir , I am sick so that's why I am not able to do any PR , but from today I will start working on it , so please give me sometime .

**Comment by Kumar-laxmi** [comment]
Sorry @Gaurang1602 I have to unassign you since your have already taken so much time and other contributors are waiting for this issue
