### ISSUE TITLE
Add  Two pointer Algorithm

### ISSUE THREAD

**Issue by Gaurang1602** [Kumar-laxmi/Algorithms#732]
### Two pointer : -
The two-pointer technique is a search algorithm used to solve problems involving collections such as arrays and lists by comparing elements pointed by two pointers and updating them accordingly.

**Feature : -**

Add 2 Pointer Algorithm  in C++ , C , java , python.

**Description of solution :-**

- Will add 2 pointer with adequate comments  for readers to get a clear understanding.
- To be added in C, C++, Java and Python.

**Alternatives Considered :**

@Kumar-laxmi 
Can you please assign me this issue under SSoC'23 so that I can send in a PR on 1st June ?

**Comment by Kumar-laxmi** [comment]
Could you please provide and sample input-output and related screen shots

**Comment by SKSADIRUDDIN** [comment]
Hey,  I have good knowledge about 2 pointers. Can you assign me it?

**Comment by SKSADIRUDDIN** [comment]
@Kumar-laxmi  Hey, I have good knowledge about 2 pointers. Can you assign me it?

**Comment by Vaishu03** [comment]
@Kumar-laxmi I would love to work on this issue under SSOC'23, as I had good knowledge about this algorithm, can you assign this task to me?

**Comment by chandrakethan27** [comment]
@Kumar-laxmi Can you please assign me this issue i have good knowledge of algorithms

**Comment by KingpinDk** [comment]
Two Pointer Approach can be applied to a variety of problems involving arrays and linked list data structures.
Some most common problems are,
* Finding pairs with specific sum
* Finding subarrays with specific properties
* Detecting cycles in linked lists (fast and slow pointers)
here's my solution for finding pairs with specific sum in c++.
`bool pairSum(vector<int> A, int Size, int targetSum)
{
   int i = 0;//first pointer
    int j = size - 1;//second pointer
 
    while (i < j) {
        if (A[i] + A[j] == targetSum)
            return 1;
        else if (A[i] + A[j] < targetSum)
            i++;
        else
            j--;
    }
    return 0;
}`

the above case works only for sorted array
Time Complexity: O(n)
Space Complexity: O(1)

alternately we can explicitly sort the array which would cause
Time Complexity: O(n log n) //sort function
Space Complexity: O(1)

"IF YOU WANT TO ME TO MAKE SOLUTIONS FOR ALL THE PROBLEMS THAT COME UNDER TWO POINTER APPROACH , I CAN MAKE IT AS WELL IN ALL THESE LANGUAGES(JAVA, PYTHON, C, C++). MY SOLUTIONS WILL BE EFFICIENT AND READABLE. GRANT ME THIS ISSUES AND GET A PACKAGE OF EFFICIENT SOLUTIONS FOR PROBLEMS THAT COMES UNDER TWO POINTER APPROACH"
![Screenshot (81)](https://github.com/Kumar-laxmi/Algorithms/assets/118034679/8e76e563-31a4-4407-bc31-3ae96a0d3913)

**Comment by ashif88** [comment]
Can you please assign me this issue i have good knowledge of algorithms.
I have solved 900+ DSA Problems in various Coding Platforms.
I have solved many problems of two pointer algorithms.
1. Knight badge on [Leetcode](https://leetcode.com/ashifakhtar/)
2. 4 Star on [Codechef](https://www.codechef.com/users/ashif_29dec)
3. Specialist on [Codeforces](https://codeforces.com/profile/ash88)

**Comment by AK3847** [comment]
@Kumar-laxmi   I have a good knowledge around this topic as I am doing Competitive coding for quite some time now and have solved many question based on this algorithm so can you kindly assign me this issue?

1.  4 Star on [Codechef](https://www.codechef.com/users/abdulk_69)
2.  Specialist on [Codeforces](https://codeforces.com/profile/AbdulK_69)

Thanks for consideration!

**Comment by Veena4512** [comment]
@Kumar-laxmi I can implement in python. I'm proficient in python and I participate in various coding competitions. So can you please assign it to me?

**Comment by swastik-akhil** [comment]
### I can do it in Java @Kumar-laxmi

**Comment by shravanii2308** [comment]
Can you assign this issue to me @Kumar-laxmi  i can do it in C,C++ and python

**Comment by Kumar-laxmi** [comment]
Please don't raise LeetCode, GFG or HackerRank, etc
