### ISSUE TITLE
Add Sublist Search 

### ISSUE THREAD

**Issue by Gaurang1602** [Kumar-laxmi/Algorithms#733]
### Sublist search :-
Sublist search is used to detect a presence of one list in another list. Suppose we have a single-node list (let's say the first list), and we want to ensure that the list is present in another list (let's say the second list), then we can perform the sublist search to find it.

**Feature : -**
Add Sublist search in C++ , C , java , python.

**Description of solution : -**

- Will add Sublist search with adequate comments  for readers to get a clear understanding.
- To be added in C, C++, Java and Python.

**Alternatives Considered :-**

@Kumar-laxmi 
Can you please assign me this issue under SSoC'23 so that I can send in a PR on 1st June ?

**Comment by Kumar-laxmi** [comment]
Assigned!
@Gaurang1602 : C, C++, Python and Java

**Comment by Kumar-laxmi** [comment]
What is your status on this issue?

**Comment by Gaurang1602** [comment]
> Assigned! @Gaurang1602 : C, C++, Python and Java

Sir, I told you that I'm sick , but sir you closed all my issues , atleast  please leave my 1 issue , so that I can work on it , I will definitely contribute on Sublist search today

**Comment by Gaurang1602** [comment]
> > Assigned! @Gaurang1602 : C, C++, Python and Java
> 
> Sir, I told you that I'm sick , but sir you closed all my issues , atleast please leave my 1 issue , so that I can work on it , I will definitely contribute on Sublist search today

Please sir, it is a humble request .

**Comment by Kumar-laxmi** [comment]
Sorry but this issue is assigned to someone else, you can look into other issues only after you are well. Get Well Soon!

**Comment by Kumar-laxmi** [comment]
More than 1000 contributors are working on this repo and it is very difficult to review issues and PR at such a volume. Inactive issues open for such a long time just clutter the repo
