### ISSUE TITLE
Add Fibonacci Search Algorithm

### ISSUE THREAD

**Issue by Gaurang1602** [Kumar-laxmi/Algorithms#734]
### Fibonacci Search :-
As the name suggests, the Fibonacci Search Algorithm uses Fibonacci numbers to search for an element in a sorted input array.
Fibonacci Search is a comparison-based technique that uses Fibonacci numbers to search an element in a sorted array.

**Feature : -**
Add Fibonacci search Algorithm in C++ , C , java , python.

**Description of solution :-**

- Will add Fibonacci search Algorithm with adequate comments for readers to get a clear understanding.
- To be added in C, C++, Java and Python.

**Alternatives Considered :-**

@Kumar-laxmi
Can you please assign me this issue under SSoC'23 so that I can send in a PR on 1st June ?

**Comment by Kumar-laxmi** [comment]
Assigned!
@Gaurang1602 : C, C++, Python and Java

**Comment by Kumar-laxmi** [comment]
@Gaurang1602 What is your status on this issue?

**Comment by Gaurang1602** [comment]
@Kumar-laxmi 
Actually sir , I am sick so that's why I am not able to do any PR , but from today I will start working on it , so please give me sometime .

**Comment by harshitaaa8** [comment]
I can help to add the algorithm in c and python language.

**Comment by Kumar-laxmi** [comment]
Sorry @Gaurang1602 I have unassign you due to inactivity
