### ISSUE TITLE
Add Zeller's Algorithm 

### ISSUE THREAD

**Issue by RashakDude** [Kumar-laxmi/Algorithms#737]
**Is your feature request related to a problem? Please describe.**
Zeller's algorithm is used to find the day from a date

**Describe the solution you'd like**
I wanted to add the solution in C, C++, Java and Python. This will go under Maths section.
You can find about it more [here](https://www.tutorialspoint.com/Find-Weekday-using-Zeller-s-Algorithm)

**Comment by Kumar-laxmi** [comment]
Assigned!
@RashakDude : C, C++, Java and Python
