### ISSUE TITLE
Add RomulusT Algorithm

### ISSUE THREAD

**Issue by RashakDude** [Kumar-laxmi/Algorithms#738]
**Is your feature request related to a problem? Please describe.**
I wanted to add a cryptography algorithm names as RomulusT

**Describe the solution you'd like**
I wanted to add it in Python and Java.
You can find more about it [here](https://csrc.nist.gov/CSRC/media/Projects/Lightweight-Cryptography/documents/round-1/spec-doc/Romulus-spec.pdf)

**Comment by Kumar-laxmi** [comment]
Please provide sample input-output and related screen shot as reference instead of research paper

**Comment by RashakDude** [comment]
Here is a sample of what I coded - 

Key = 000102030405060708090A0B0C0D0E0F
Nonce = 000102030405060708090A0B0C0D0E0F
PT = 000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F303132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F606162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E8F909192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBEBFC0C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECEDEEEFF0F1F2
AD = 000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F303132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F606162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E8F909192
CT = 14431457C1B573058A16B8A10880FE96EF6ACAE8259E14586009309D7816B6E80BAE7041173B8F10C0244D470BF4D428EEDD31528DE95353448081D13513F24AA38CEEA10D07DD7E9CF1DC27A3EE92228D7D1BB15F3D3349D9791742664AC1CDDCE75780A0BA10CE24E1FF1A46EA62E4165D435C82BF9330B33B4AF7375465D89A4B8083940328BA33ABB16B1D181F8BFB979280702C7E0300D2687C1AD98D1A0F79FABDDDDD6A49CFBA4C7EB80AAEBE7C6B04A638834D38190901FFD5869E958E88FD2A3FF3149102C0F3FADB3B706CE8BC18EB61B737BB8EAC65A159768DA6B42408900B48857A4A0F6995950FA50373C98CDFF5C1B9124DDECEDDE1DF1F3FFE28B6

Here, PT is the plain-text and CT is the cipher text. I have verified that the cipher text is converting back to plain-text after decryption. FYI @Kumar-laxmi
