### ISSUE TITLE
Spiral Matrix code in Java

### ISSUE THREAD

**Issue by swastik-akhil** [Kumar-laxmi/Algorithms#742]
### Spiral Matrix
The code of spiral matrices is not available in Java In The Algorithm's repository. I would like to look forward to the issue and would like to contribute to it under SSOC'2.
@Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Could you provide a sample input-output as well as related screen shots to explain your approach

**Comment by swastik-akhil** [comment]
![Spiral Matrix](https://github.com/Kumar-laxmi/Algorithms/assets/126651810/8345e37c-b301-4ba8-a74c-69c1f65d92da)

**Comment by swastik-akhil** [comment]
This has already been implemented in C, C++ & Python in the Algorithm's repo, but this missing of Java file make it less prettier.
Assign this to me under SSOC'2 and let's make this repo more beautiful😍✨.
Admin- @Kumar-laxmi

**Comment by Swapnendu003** [comment]
Yes I have raised the same issue it can be solved in C also

**Comment by swastik-akhil** [comment]
@Swapnendu003 It's already present in C.
