### ISSUE TITLE
Boyer-Moore Majority Voting	

### ISSUE THREAD

**Issue by swastik-akhil** [Kumar-laxmi/Algorithms#745]
### Boyer-Moore Majority Voting
While exploring the repository, I noticed that the Boyer-Moore Majority Voting algorithm code in Java is currently missing. With your permission, I would like to take up the challenge of implementing the Boyer-Moore Majority Voting algorithm in Java. 
Admin- @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Assigned!
@swastik-akhil : Java

**Comment by avsnr** [comment]
Good

**Comment by swastik-akhil** [comment]
@Kumar-laxmi I'll complete it before 20

**Comment by Kumar-laxmi** [comment]
@swastik-akhil status?

**Comment by swastik-akhil** [comment]
I've completed the code but my pr #1354 is under process and that's why I cannot make any new one.
@Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Just create a new pull request from a new branch, that is how other contributors are creating multiple PRs at once

**Comment by swastik-akhil** [comment]
Thanks for that @Kumar-laxmi. I'll do that.

**Comment by swastik-akhil** [comment]
Hello @Kumar-laxmi , I'm currently stuck in some very urgent work that's why I'm not able to do it. Please allow me some time. It's an urgency for me. I ensure you that I'll do it as soon I get some time. I hope you'll understand my concern. I have made 2 PR earlier also and I promise I'll be delivering this one also.

**Comment by Kumar-laxmi** [comment]
Kindly complete this issue ASAP
