### ISSUE TITLE
To add level order traversal in c++

### ISSUE THREAD

**Issue by nazeer-18** [Kumar-laxmi/Algorithms#746]
I have the algorithm for level order traversal can you please assign this issue to me?
![image](https://github.com/Kumar-laxmi/Algorithms/assets/99654015/b1299de2-03a3-46d0-939a-b10464d84574)

**Comment by RohithBoppey** [comment]
What was the question about? Can you brief it to me? @nazeer-18

**Comment by nazeer-18** [comment]
Given a binary tree we need to output the level order traversal of iit
if given tree is
        1
   2        3
4   5   6   7

The output is : 1 2 3 4 5 6 7

**Comment by sripesh** [comment]
Using C++, I can write a program for level-order traverse in the given tree.

So, Please assign this issue to me for SSoC

**Comment by ashif88** [comment]
Can you please assign me this task I would love to contribute.
I have great knowledge of traversal techniques.
I have solved 900+ DSA Problems in various Coding Platforms.
Some of my achievement includes:
Knight badge on [Leetcode](https://leetcode.com/ashifakhtar/)
max 4 Star on [Codechef](https://www.codechef.com/users/ashif_29dec)
max Specialist on [Codeforces](https://codeforces.com/profile/ash88)

**Comment by Yash493** [comment]
Can you please assign this task to me , I am pretty good in Data structures and algorithms in c++

**Comment by Aryaman3007** [comment]
Could you please assign this issue to me under SSoC, I have recently completed trees recently and have my repo made on DSA. I will provide the approach and solution with the complexity analysis in C++.

**Comment by RohithBoppey** [comment]
> Can you please assign me this task I would love to contribute. I have great knowledge of traversal techniques. I have solved 900+ DSA Problems in various Coding Platforms. Some of my achievement includes: Knight badge on [Leetcode](https://leetcode.com/ashifakhtar/) max 4 Star on [Codechef](https://www.codechef.com/users/ashif_29dec) max Specialist on [Codeforces](https://codeforces.com/profile/ash88)

You have an amazing profile in Leetcode! Keep up the good work. Would like to be in contact with you, so feel free to follow me on my Linkedin or other socials! Great work, keep it up.

**Comment by TusharGagal** [comment]
can you please assign me this task, I am really good in these traversals. I have solved 300+ question on leetcode.

**Comment by Khushi-74** [comment]
I can explain code and demonstrate level order traversal in c++ very efficiently please assign me this issue under ssoc'23

**Comment by ishitagithub** [comment]
Greetings , Please assign me this issue under SSOC' 23. I have a solid grasp of data structures and algorithms, enabling me to write efficient code with detailed explanations. I can write both naive and effective approach( using Dynamic Programming) to this problem. I can provide algorithm as well as code in any of these languages- C, C++, Java, Python.
