### ISSUE TITLE
Edit Readme file for Greedy Algorithm branch

### ISSUE THREAD

**Issue by ayan-joshi** [Kumar-laxmi/Algorithms#747]
I want to edit the readme file of greedy algorithm which only describes the name of the branch .
I will add conecpt of greedy algorithm so that the user can understand about the 
greedy algorithm with the help of readme file itself.
@Kumar-laxmi please assign me this issue I'm a SSOC contributor.

**Comment by Kumar-laxmi** [comment]
Could you work on **README.md** of ```Greedy Algorithm``` present inside the folder of all four languages

**Comment by ayan-joshi** [comment]
Yes I will do for all folders

**Comment by ayan-joshi** [comment]
@Kumar-laxmi please assign me this I am ready to complete your requirements

**Comment by Courage003** [comment]
I have worked as code editorial for my college coding club. Here I want to enrich that experience and contribute towards your readme requirements. Please assign this task to me under SSOC'2023

**Comment by PadmeshSharma** [comment]
Please assign this issue to me under SSOC'23. @Kumar-laxmi
