### ISSUE TITLE
Linear Regression in Java

### ISSUE THREAD

**Issue by mochiron-desu** [Kumar-laxmi/Algorithms#749]
# Linear Regression 
In statistics, linear regression is a linear approach for modelling the relationship between a scalar response and one or more explanatory variables. 

![image](https://github.com/Kumar-laxmi/Algorithms/assets/72451747/7475aedd-013b-4762-b342-f6238ab7bad4)

I want to solve this problem using Java.

**Comment by Kumar-laxmi** [comment]
refer #681
