### ISSUE TITLE
To add sum at kth level in a binary tree in c++

### ISSUE THREAD

**Issue by nazeer-18** [Kumar-laxmi/Algorithms#750]
I have the algorithm for sum of nodes at level k in a binary tree 
could you please assign this issue for me?
sample output for input
    1 
 2     3
4 5  6  7
is
at levels 0,1,2
![image](https://github.com/Kumar-laxmi/Algorithms/assets/99654015/c82e1ecf-5436-4290-9bb6-d5fe6c29cc04)

**Comment by nazeer-18** [comment]
can I work on this?

**Comment by ashif88** [comment]
Can you please assign me this task I would love to contribute.
I have great knowledge of traversal techniques. And with the help of bfs this problem can be solved very easily.
I have solved 900+ DSA Problems in various Coding Platforms.
Some of my achievement includes:
Knight badge on [Leetcode](https://leetcode.com/ashifakhtar/)
max 4 Star on [Codechef](https://www.codechef.com/users/ashif_29dec)
max Specialist on [Codeforces](https://codeforces.com/profile/ash88)

**Comment by nazeer-18** [comment]
can i contribute this algo as this is missing in your repo?

**Comment by harshit7045** [comment]
Hello,

My name is Harshit Mishra, and I am a student at IIIT Una. I possess a strong understanding of data structures and algorithms and have the ability to write optimized code with explanatory comments. I kindly request to be assigned this issue.

**Comment by ishitagithub** [comment]
Greetings Sir, Please assign this issue to me. I have a strong understanding on the topic binary tree in dsa as well as c++ language. So, I can easily code this question in c++ .
