### ISSUE TITLE
To detect and remove loop in linked list in c++

### ISSUE THREAD

**Issue by nazeer-18** [Kumar-laxmi/Algorithms#751]
I have an algorithm to detect and remove loop in a linked list using hare and tortoise algorithm
can you please assign this issue to me?
![image](https://github.com/Kumar-laxmi/Algorithms/assets/99654015/2945983d-88e3-4223-b9e9-e1f5bc5608dc)
This is the corresponding algo for it.

**Comment by Aryankr-24** [comment]
I have intermediate level of experience in dsa. Kindly assign this project to me. Thank You.

**Comment by Venerablevivek** [comment]
I have an Best approach ... Kindly assign this project to me

**Comment by Kumar-laxmi** [comment]
refer #759 & #761

**Comment by nazeer-18** [comment]
> refer #759 & #761
Ive raised this issue 3 days back but u assigned this to someone who came 2 days back and u asked me to refer #759 #761 but they raised after me..
