### ISSUE TITLE
Johnson's Algorithm in C, C++, Java and Python

### ISSUE THREAD

**Issue by harshita-kaushik2** [Kumar-laxmi/Algorithms#758]
### Feature = Johnson's Algorithm
- Johnson's algorithm is capable of finding the shortest paths between all pairs of vertices, even in the presence of negative edge weights.
- It uses the Bellman-Ford algorithm to handle negative edge weights and identify negative cycles
- By transforming the graph and modifying the edge weights, it ensures that Dijkstra's algorithm can be applied effectively.

### Appraoch : 
1.Graph Transformation:
- Add a new vertex to the graph and connect it to all existing vertices with zero-weight edges.
- Assign zero weights to these new edges.

2. Bellman-Ford Algorithm:
- Use the Bellman-Ford algorithm to calculate the shortest distances from the newly added vertex to all other vertices in the graph.
- If a negative cycle is detected during this step, terminate the algorithm as it indicates that the graph contains no shortest paths.

3. Graph Modification:
- Modify the weights of the original graph based on the results of the Bellman-Ford algorithm.
- For each edge (u, v) in the graph, update its weight as the sum of its original weight and the distance from the newly added vertex to u minus the distance from the newly added vertex to v.

4. Dijkstra's Algorithm (Multiple Times):
- Apply Dijkstra's algorithm to each vertex in the modified graph to find the shortest paths from that vertex to all other vertices.
- This step is performed multiple times, once for each vertex in the graph.

### Attribute:
- To be added in C, C++, Java and Python.
- Added comments to explain the flow and logic of code to the reader.

I would like to work on this issue. Can you assign it to me under SSoC '23 ?
Thank You :)

**Comment by ayushi-ras** [comment]
Can I contribute in this

**Comment by Kumar-laxmi** [comment]
Assigned!
@harshita-kaushik2 : C, C++, Java and Python

**Comment by Kumar-laxmi** [comment]
@harshita-kaushik2 What is your status on this issue?

**Comment by Aarsh30** [comment]
@harshita-kaushik2  if you don't want to contribute then @Kumar-laxmi  can you assigned me i would like to do this algorithm
