### ISSUE TITLE
Remove a cycle in Linked List C++

### ISSUE THREAD

**Issue by singhapeksha** [Kumar-laxmi/Algorithms#759]
**Is your feature request related to a problem? Please describe.**
Yes, function for removal of linked list cycle is not there

**Describe the solution you'd like**

To remove a cycle in a linked list, you can use the Floyd's Cycle-Finding Algorithm, also known as the "Hare and Tortoise" algorithm. This algorithm detects the cycle in a linked list and identifies the node where the cycle starts. Once the starting node of the cycle is found, you can break the cycle by modifying the pointers accordingly.

I have the code for the same please assign this issue to me

**Comment by singhapeksha** [comment]
Please assign this issue to me

**Comment by Courage003** [comment]
We can do it using Floyd's Cycle Finding Algorithm...please assign this atsk to me...

**Comment by Monishka8303** [comment]
I can solve this problem in Java. Can I raise an issue for the same? @Kumar-laxmi

**Comment by ashif88** [comment]
Can you please assign me this task I would love to contribute.
I have great knowledge of Linked List.
I have solved 900+ DSA Problems in various Coding Platforms.
Some of my achievement includes:
Knight badge on [Leetcode](https://leetcode.com/ashifakhtar/)
max 4 Star on [Codechef](https://www.codechef.com/users/ashif_29dec)
max Specialist on [Codeforces](https://codeforces.com/profile/ash88)

**Comment by Kumar-laxmi** [comment]
Assigned!
@singhapeksha : C, C++, Java and Python
