### ISSUE TITLE
N-Queens Problem in c ,c++, JAVA and python

### ISSUE THREAD

**Issue by ShubhaSwarup** [Kumar-laxmi/Algorithms#760]
The N-Queens problem can also be approached using a feature-based method. In this approach, we define a set of features or criteria that determine the validity of a queen's placement on the chessboard. By iteratively evaluating these features, we can find valid solutions to the N-Queens problem.

Here are some common features used in the feature-based approach:

No Row or Column Attacks: Each queen must be placed in a unique row and column. This ensures that no two queens are in the same row or column, as queens can attack each other vertically and horizontally.

No Diagonal Attacks: Queens can attack each other diagonally as well. Therefore, no two queens should lie on the same diagonal line. This can be checked by comparing the differences between the row and column indices of each queen.

Incremental Placement: In the feature-based approach, queens are incrementally placed on the chessboard one by one, ensuring that each new placement adheres to the defined features. If a queen's placement violates any of the features, it is backtracked, and another valid position is sought.

Backtracking: Backtracking is a crucial component of the feature-based approach. When a queen's placement violates the features, the algorithm backtracks to the previous queen and explores a different position for it. This process continues until a valid solution is found or all possible configurations have been exhausted.

By using these features and the backtracking mechanism, the feature-based approach incrementally explores the search space, discarding invalid configurations and focusing on valid ones. This allows for an efficient and systematic way to find all possible solutions to the N-Queens problem.

It's worth noting that the feature-based approach can be implemented using various algorithms, such as recursive backtracking, constraint satisfaction algorithms, or even genetic algorithms. The specific implementation may vary based on the requirements and constraints of the problem at hand.

Please assign this issue to me

**Comment by ShubhaSwarup** [comment]
Please assign this issue to me

**Comment by Kumar-laxmi** [comment]
Assigned!
@ShubhaSwarup : C, C++, Java & Python

**Comment by RohithBoppey** [comment]
Can I also work on this? I have solved N-Queens question recently. This would be an opportunity to jog my memory.

**Comment by HARSHSUHANE17** [comment]
@Kumar-laxmi please assign this issue to me , I'll add code in C for N-queens problem.

**Comment by Mahendra-Lohar** [comment]
@Kumar-laxmi Please assign this issue to me , I'll add cod ein C , Python , C++ , Java using back tracking

**Comment by SubiditaB** [comment]
Please assign me this issue. I want to contribute to this repo.

**Comment by AKACHI-4** [comment]
Hey @ShubhaSwarup are u on it ... If not can I work on this issue ??
