### ISSUE TITLE
Detection of cycle in linked list 

### ISSUE THREAD

**Issue by singhapeksha** [Kumar-laxmi/Algorithms#761]
**Is your feature request related to a problem? Please describe.**
Code for removal of cycle in linked list is missing in python
**Describe the solution you'd like**
To remove a cycle in a linked list in Python, you can use Floyd's Cycle-Finding Algorithm. This algorithm helps detect the presence of a cycle and find the node where the cycle begins. Once the cycle is detected, you can break it by modifying the appropriate pointers. 

**Additional context**
I have a code for the same, so please assign me this issue.

**Comment by singhapeksha** [comment]
Please assign this to me!!

**Comment by Kumar-laxmi** [comment]
@singhapeksha Since this is an easy algorithm and has been done in ```C++```, would you like to implement this in ```C```, ```Python``` and ```Java```

**Comment by singhapeksha** [comment]
@Kumar-laxmi Yes i can implement it in C, Python and java. Please assign me this issue.

**Comment by VatsalHShah** [comment]
Can you plz assign this issuw to me under ssoc-23

**Comment by Kumar-laxmi** [comment]
Assigned!
@singhapeksha : C, Python & Java

**Comment by Kumar-laxmi** [comment]
@singhapeksha What is your status on this issue?
