### ISSUE TITLE
Caching Algorithm in c++

### ISSUE THREAD

**Issue by ShubhaSwarup** [Kumar-laxmi/Algorithms#762]
Caching algorithms are used to improve the performance of systems by storing frequently accessed data in a cache, which is a faster but smaller memory closer to the processor. The goal is to reduce the latency of accessing data by serving requests from the cache instead of the slower primary storage.

The caching approach involves three key operations: retrieving data, storing data, and evicting data when the cache becomes full. Different caching algorithms employ various strategies for these operations to maximize cache hit rates and minimize cache misses. Here are descriptions of commonly used caching algorithms and their approaches:

Least Recently Used (LRU):

Approach: The LRU caching algorithm keeps track of the usage history of cache items. It maintains a list or a queue where the most recently used items are moved to the front. When a new item is accessed, it is added to the front or moved to the front if it already exists.
Eviction: When the cache becomes full and a new item needs to be stored, the least recently used item (i.e., the one at the back of the list) is evicted.
Key idea: Items that have been recently used are more likely to be used again soon.
First-In-First-Out (FIFO):

Approach: The FIFO caching algorithm maintains the order in which items are added to the cache. When a new item is accessed, it is added to the cache. If the cache is full, the oldest item (i.e., the one at the front of the list) is evicted.
Eviction: The oldest item is evicted when the cache becomes full.
Key idea: Items that have been in the cache for a longer time are considered less likely to be used again soon.
Least Frequently Used (LFU):

Approach: The LFU caching algorithm keeps track of the frequency of cache item usage. Each item has a usage counter that is incremented whenever it is accessed. The item with the lowest usage counter is considered the least frequently used.
Eviction: When the cache becomes full and a new item needs to be stored, the item with the lowest usage counter is evicted.
Key idea: Items that have been accessed less frequently are considered less likely to be accessed in the future.
Random Replacement:

Approach: The random replacement caching algorithm randomly selects items to evict from the cache when it becomes full. Each item in the cache has an equal probability of being evicted.
Eviction: Items are evicted randomly when the cache becomes full.
Key idea: This algorithm does not consider usage history or frequency and relies solely on random selection.
The choice of caching algorithm depends on factors such as the access patterns, data characteristics, and the specific performance requirements of the system. Different caching algorithms have different trade-offs in terms of implementation complexity, cache hit rates, and eviction overhead. It is crucial to analyze the workload and tailor the caching strategy accordingly to achieve optimal performance.
Please assign this issue to me.

**Comment by parthpishte** [comment]
please assign this to me i can do this in c,c++ as well as python

**Comment by Kumar-laxmi** [comment]
You have mentioned multiple algorithms in one issue, please open one issue per algorithm
