### ISSUE TITLE
Kosaraju Algorithm in C, Java and Python

### ISSUE THREAD

**Issue by harshita-kaushik2** [Kumar-laxmi/Algorithms#763]
### Feature = Kosaraju Algorithm
Kosaraju's algorithm is a graph algorithm used to find strongly connected components (SCCs) in a directed graph. A strongly connected component is a subset of vertices in a graph where there is a path between any two vertices within the subset. The algorithm addresses the problem of identifying these strongly connected components.

- Kosaraju's algorithm is based on the concept of reversing edges and utilizing two DFS passes.
- The first pass is used to obtain the finish times of vertices in the original graph.
- The second pass performs DFS on the transposed graph using the order of finish times obtained in the first pass

### Approach : 
Kosaraju's algorithm utilizes depth-first search (DFS) and a two-pass approach to find strongly connected components in a directed graph. It performs the following steps:

1 First Pass (DFS):
- Perform a depth-first search (DFS) on the original graph, exploring vertices in any order.
- During the DFS traversal, record the order in which vertices finish their recursive DFS calls (i.e., finish times) in a stack or list.

2. Graph Transposition:
- Transpose the original graph by reversing the direction of all edges.
- This creates a new graph with the same vertices but with reversed edges.

3. Second Pass (DFS on Transposed Graph):

### Attributes : 
- This algorithm is present in C++, however missing in C, Java and Python
- Improved documentation
- Added comments to the code that explains its flow & logic.

I would like to work on this issue. Can you please assign it to me under SSoC '23 ?
Thank You :)

**Comment by Kumar-laxmi** [comment]
Assigned!
@harshita-kaushik2 : C, Java & Python

**Comment by Kumar-laxmi** [comment]
@harshita-kaushik2 What is your status on this issue?
