### ISSUE TITLE
Huffman Code Algorithm - C++

### ISSUE THREAD

**Issue by singhapeksha** [Kumar-laxmi/Algorithms#765]
**Is your feature request related to a problem? Please describe.**
Huffman Code Algorithm is a type of Greedy algorithm which is not there in the C++ folder.

**Describe the solution you'd like**
The Huffman coding algorithm is a widely used compression technique that assigns variable-length codes to different symbols in a given input based on their frequency of occurrence. It achieves efficient compression by assigning shorter codes to more frequent symbols and longer codes to less frequent symbols. Here's an overview of the Huffman coding algorithm:

Frequency Analysis: The first step is to analyze the input data and determine the frequency of occurrence of each symbol. Symbols can be individual characters, bytes, or any other unit of data.

Building the Huffman Tree: Based on the frequency analysis, a Huffman tree is constructed. The tree is built in a bottom-up manner, starting with individual symbols as leaf nodes and gradually merging them into higher-level nodes until a single root node is formed.

Assigning Codewords: During the construction of the Huffman tree, each symbol is associated with a binary codeword based on its position in the tree. The codeword is determined by traversing the tree from the root to the symbol's leaf node, assigning '0' for each left branch and '1' for each right branch.

Generating Huffman Codes: Once the codewords are assigned to each symbol, they form the Huffman codes. The Huffman codes are variable-length codes, where no code is a prefix of another code. This property ensures that the codes can be uniquely decoded during decompression.

Encoding: To encode the input data using Huffman coding, each symbol is replaced by its corresponding Huffman code. The resulting sequence of codes is the compressed representation of the input data. The compressed data is typically represented as a bitstream.

Decoding: During decompression, the encoded bitstream is processed by starting at the root of the Huffman tree. For each bit encountered, a traversal is made in the tree by following the left branch for '0' and the right branch for '1'. When a leaf node is reached, the corresponding symbol is outputted, and the process continues until the entire bitstream is decoded.

**Comment by singhapeksha** [comment]
Please assign me this issue!!

**Comment by Kumar-laxmi** [comment]
This algorithm is already present in C++, refer: https://github.com/Kumar-laxmi/Algorithms/blob/main/C%2B%2B/Data%20Compression/huffmanCoding.cpp
