### ISSUE TITLE
Dinic's Algorithn in C

### ISSUE THREAD

**Issue by harshita-kaushik2** [Kumar-laxmi/Algorithms#766]
### Feature = Dinic's Algorithm in C
- It has been **already implemented in C++, Java and Python but is missing in C.**

Dinic's algorithm is a graph algorithm used to find the maximum flow in a flow network. Given a directed graph with a source vertex, a sink vertex, and capacities assigned to the edges, the algorithm determines the maximum amount of flow that can be sent from the source to the sink.

It can handle large flow networks efficiently and is considered one of the fastest maximum flow algorithms.

### Approach : 
1. Initialization:
- Assign initial flow of zero to all edges in the graph.
- Create a level graph by performing a Breadth-First Search (BFS) from the source vertex. The level graph indicates the shortest distance from the source to each vertex in terms of the number of edges.

2. Blocking Flow:
- While there exists a blocking flow (a path from the source to the sink in the level graph):
- Use Depth-First Search (DFS) to find an augmenting path from the source to the sink in the level graph.
- Determine the maximum possible flow that can be sent through the augmenting path.
Update the flow values of the edges along the augmenting path.

3. Update Level Graph:
- After each blocking flow is found, update the level graph by performing another BFS from the source.
- The new level graph reflects the shortest distances from the source considering the updated flow values.

4. Termination and Maximum Flow:
- When there are no more blocking flows in the level graph, the algorithm terminates.
- The maximum flow in the network is the sum of the flows leaving the source vertex.

### Attributes : 
- Will add it in C language
- Improved documentation
- Plenty commented code that explain the flow and logic of the code

I would like to work on this issue. Can you assign it to me under SSoC '23 ?
Thank You :)

**Comment by Kumar-laxmi** [comment]
Assigned!
@harshita-kaushik2 : C

**Comment by Kumar-laxmi** [comment]
@harshita-kaushik2 What is your status on this issue?
