### ISSUE TITLE
Karger's Algorithm (Min Cut)

### ISSUE THREAD

**Issue by thakurdiwakar** [Kumar-laxmi/Algorithms#767]
**Is your feature request related to a problem? Please describe.**
Karger's Algorithm (Min Cut) :

Karger's algorithm is a randomized algorithm used to find the minimum cut in a graph. The minimum cut of a graph is defined as the smallest number of edges that, if removed, would divide the graph into two disconnected components. Karger's algorithm is based on the concept of contraction, where two randomly chosen vertices are merged into a single vertex, reducing the size of the graph. The algorithm repeats this contraction step until only two vertices (representing the two sides of the cut) remain.

**Describe the solution you'd like**

I wanted to add the solution in C++ and Python. 
You can find about it more [here](https://www.scaler.com/topics/data-structures/kargers-algorithm-for-minimum-cut/)

**Approach**-
Initialize the graph G.
Repeat until there are two vertices left:
Choose a random edge e in G.
Contract e, merging the two endpoints of e into a single vertex.
The cut formed by the two remaining vertices is a minimum cut.
The algorithm works by iteratively contracting randomly chosen edges until only two vertices remain. The cut formed by the two remaining vertices is then a minimum cut.

**Comment by thakurdiwakar** [comment]
Please Assign me this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@thakurdiwakar : C++ & Python

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir kindly assign me this issue under ssoc 23.I can code it using c++ and Java, please assign it to me as this would be my first PR.
