### ISSUE TITLE
Complete Implementation of Preorder, Inorder and Postorder Traversal in Tree in C++ and C

### ISSUE THREAD

**Issue by AnubhaSharma2709** [Kumar-laxmi/Algorithms#768]
I really didn't find the implementation of Preorder, Inorder and Postorder traversal in tree .
Please assign this to me
Under SSOC'23

**Comment by Kumar-laxmi** [comment]
@AnubhaSharma2709 Since it is an easy issue, kindly implement this in all four languages

**Comment by Kumar-laxmi** [comment]
Assigned!
@AnubhaSharma2709 : C, C++, Python and Java

**Comment by AnubhaSharma2709** [comment]
> @AnubhaSharma2709 Since it is an easy issue, kindly implement this in all four languages

Okay. Thankyou so much

**Comment by Khushi-74** [comment]
I am well versed with order traversal in binary tree and it is one of my favourite topic in dsa 
please assign me this issue I would like to work upon this under ssoc'23
