### ISSUE TITLE
Add Breadth First Search (BFS) algorithm in java.

### ISSUE THREAD

**Issue by GOPAL181** [Kumar-laxmi/Algorithms#772]
Breadth-first search is a graph traversal algorithm that starts traversing the graph from the root node and explores all the neighboring nodes. Then, it selects the nearest node and explores all the unexplored nodes. While using BFS for traversal, any node in the graph can be considered as the root node.

please assign me this issue

**Comment by Yash493** [comment]
Breadth-First Search (BFS) is a graph traversal algorithm that explores all vertices of a graph in breadth-first order, i.e., it visits all the vertices at the same level before moving to the next level. It starts at a given source vertex and explores all the vertices adjacent to the source vertex before moving to the next level of vertices.

Please Assign this issue to me I will make readme file for explanation of code

**Comment by ishitagithub** [comment]
Greetings , Please assign me this issue under SSOC'23? BFS is a graph traversal algorithm. I can provide algorithm as well as code in these languages:- Python, C, C++ and Java as well.
