### ISSUE TITLE
Add README.md to Linked List in all languages

### ISSUE THREAD

**Issue by harshita-kaushik2** [Kumar-laxmi/Algorithms#773]
### Feature :
- Explain about Singly Linked List, Doubly Linked List, and Circularly Linked List 
- Use pictographic explanation
- Write in all 4 languages 

I would like to work on this issue. Can you assign this to me under SSoC '23 ?
Thank you :)

**Comment by Kumar-laxmi** [comment]
Assigned!
@harshita-kaushik2 : Documentation
