### ISSUE TITLE
Add LeetCode Valid Analog Problem Solution

### ISSUE THREAD

**Issue by shubhanshurav** [Kumar-laxmi/Algorithms#776]
### Problem Name: Valid Anagram

**Description**
- Given two strings s and t, return true if t is an anagram of s, and false otherwise.
- An Anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.

 

- Example 1:

Input: s = "anagram", t = "nagaram"
Output: true
Example 2:

- Input: s = "rat", t = "car"
Output: false 

**Hey @Kumar-laxmi , I want to add the solution of valid anagram problem, so please asign it to me under SSOC'23**

**Comment by Kumar-laxmi** [comment]
Please don't raise issue pertaining to LeetCode, HackerRank, GFG Practice problems
