### ISSUE TITLE
Implementation of Lee's Algorithm

### ISSUE THREAD

**Issue by VrajPatelGitHub** [Kumar-laxmi/Algorithms#778]
The **Lee algorithm,** also known Specialized algorithm, for a graph traversal and pathfinding algorithm used to find the shortest path between two points in a graph or grid.The **Lee's algorithm** starts at a given starting point and explores the neighboring nodes in a breadth-first manner. It continues to expand the search level by level until it reaches the target point or exhausts all possible paths. The **Lee's algorithm** guarantees that if a path exists between the starting and target points, it will find the shortest path.

**Feature:**
Add Lee's Algorithm in Java, Python and C++

**Description of Solution**
1. To add Lee's Algorithm with adequate comments, documentation for readers to get a clear understanding
2. To be added in Java, Python and C++

**Alternative Considered:**
Can you please assign me this issue under SSoC'23 so that I can send a PR to it.

**Comment by Kumar-laxmi** [comment]
Assigned!
@VrajPatelGitHub : C, C++, Python and Java

**Comment by VrajPatelGitHub** [comment]
Yes @Kumar-laxmi , working, I will execute and implement these in proper manner might take little time
