### ISSUE TITLE
Implementation of Random Forest Classifier Algorithm 

### ISSUE THREAD

**Issue by VrajPatelGitHub** [Kumar-laxmi/Algorithms#780]
**Random Forest Classifier Algorithm** is a popular machine learning algorithm that is used for both classification and regression tasks. It is an ensemble learning method that combines multiple decision trees to make predictions. In the case of classification, it creates a forest of decision trees, and each tree in the forest independently predicts the class label. The final prediction is made by combining the predictions of all the trees through voting or averaging. **Random Forest Classifier Algorithm** is widely used in various applications, including image classification, text mining, fraud detection, and medical diagnosis. 

**Feature:**
Add Random Forest Classifier Algorithm in Java, Python and C++

**Description of Solution**
1. To add Random Forest Classifier Algorithm with adequate comments, documentation for readers to get a clear understanding.
2. To be added in Java, Python and C++

**Alternative Considered:**
Can you please assign me this issue under SSoC'23 so that I can send a PR to it.

**Comment by Kumar-laxmi** [comment]
Assigned!
@VrajPatelGitHub : C, C++, Java & Python

**Comment by Kumar-laxmi** [comment]
@VrajPatelGitHub What is your update on this?

**Comment by VrajPatelGitHub** [comment]
Yes @Kumar-laxmi , working, I will execute and implement these in proper manner might take little time

**Comment by Kumar-laxmi** [comment]
Kindly complete the implementation within next 1 week or else the issue will be closed
