### ISSUE TITLE
K Mean Clustering

### ISSUE THREAD

**Issue by VrajPatelGitHub** [Kumar-laxmi/Algorithms#781]
**K Means Clustering**
While going through the repository, I noticed that the K Means Clustering Algorithm code in Java and python is currently missing. With your permission, I would like to take up the challenge of implementing the **K Means Clustering Algorithm** in Java and Python.
Admin- **@Kumar-laxmi**

**Comment by Kumar-laxmi** [comment]
Since K-Means Clustering is already assigned in Python (refer #676 ), you can implement it in ```Java```

**Comment by Kumar-laxmi** [comment]
Assigned!
@VrajPatelGitHub : Java

**Comment by Kumar-laxmi** [comment]
@VrajPatelGitHub What is your update on this?

**Comment by VrajPatelGitHub** [comment]
Yes @Kumar-laxmi , working, I will execute and implement these in proper manner might take little time

**Comment by Kumar-laxmi** [comment]
Kindly complete the issue within next 1 week or else the issue would be closed
