### ISSUE TITLE
Implement Kosaraju's Algorithm in Java and Python

### ISSUE THREAD

**Issue by VrajPatelGitHub** [Kumar-laxmi/Algorithms#782]
**Kosaraju's Algorithm** is a graph algorithm used to find strongly connected components (SCCs) in a directed graph. A strongly connected component is a subgraph in which there is a path between any two vertices. The **Kosaraju's Algorithm** starts by traversing the graph using Depth-First Search (DFS). It visits each vertex in a depth-first manner and pushes the vertices onto a stack once all their adjacent vertices have been visited. After the initial traversal, the algorithm creates a transpose of the original graph by reversing the direction of each edge. In other words, if there is an edge from vertex u to vertex v in the original graph, there will be an edge from v to u in the transposed graph.

**Feature:**
Add Kosaraju's Algorithm in Java and Python 

**Description of Solution**
1. To add Kosaraju's Algorithm with adequate comments, documentation for readers to get a clear understanding
2. To be added in Java, Python 

**Alternative Considered:**
Can you please assign me this issue under SSoC'23 so that I can send a PR to it.

**Comment by Kumar-laxmi** [comment]
refer #763
