### ISSUE TITLE
Genetic Algorithm

### ISSUE THREAD

**Issue by thakurdiwakar** [Kumar-laxmi/Algorithms#786]
**Is your feature request related to a problem? Please describe.**
Genetic Algorithm:
A genetic algorithm (GA) is a search heuristic that is inspired by the process of natural evolution. This algorithm reflects the process of natural selection where the fittest individuals are selected for reproduction in order to produce offspring of the next generation.

The basic idea behind a GA is to start with a population of random solutions to a problem. These solutions are then evaluated and the fittest ones are selected to be parents. The parents then produce offspring by combining their genes in a random way. The offspring are then evaluated and the fittest ones are selected to be parents for the next generation. This process is repeated until a satisfactory solution is found.

**Describe the solution you'd like**
I wanted to add the solution in C++.
You can find about it more [here](https://www.geeksforgeeks.org/genetic-algorithms/)

**More About Genetic Algorithm**

Optimization problems: Genetic algorithms can be used to find the best solution to a problem, such as finding the shortest path between two points or finding the best combination of parameters for a machine learning model.
Search problems: Genetic algorithms can be used to find a solution to a problem, even if the problem is not well-defined. For example, genetic algorithms can be used to find a needle in a haystack or to find a pattern in a noisy dataset.
Machine learning: Genetic algorithms can be used to train machine learning models. For example, genetic algorithms can be used to find the best features for a machine learning model or to find the best parameters for a machine learning model.

**Comment by thakurdiwakar** [comment]
I would like to work on this issue. Could you please assign it to me under SSoC '23 ?

**Comment by Kumar-laxmi** [comment]
Assigned!
@thakurdiwakar : C++ & Python
