### ISSUE TITLE
Binary Tree Traversals

### ISSUE THREAD

**Issue by goyalh4164** [Kumar-laxmi/Algorithms#79]
Assign it to me. I will make Valuable contribution on all the types of traversals including zig-zag Traversal also

**Comment by Durgesh4993** [comment]
can i do this work also

**Comment by MaYaNkKashyap681** [comment]
Assign this to me, please.

**Comment by tejasri415** [comment]
I am a contributer from SWOC 3.0,Assign this to me I will make contribution on the traversal in all the ways possible

**Comment by muskaanrajput14** [comment]
Please assign it to me. I want to contribute in C++ Language

**Comment by goyalh4164** [comment]
Please Assign it to me I Have raised this Issue I can make a very valuable contribution and Neat Code

**Comment by Kumar-laxmi** [comment]
Kindly raise an issue that covers whole Binary Tree operation
