### ISSUE TITLE
Circular Linked List in JAVA

### ISSUE THREAD

**Issue by singhapeksha** [Kumar-laxmi/Algorithms#791]
**Is your feature request related to a problem? Please describe.**
the code for circular linked list is not available in java.

**Describe the solution you'd like**
A circular linked list is a type of linked list where the last node's next pointer points back to the first node, creating a circular structure. Unlike a regular linked list, which has a null or "tail" pointer at the end, a circular linked list does not have a distinct end. This circular arrangement allows for continuous traversal and enables efficient operations on the list.

Steps to create a circular linked list:

Define the Node class: Create a Node class that represents a single node in the circular linked list. Each node should have a data element and a next pointer to point to the next node.

Initialize the head pointer: Create a head pointer that initially points to null, indicating an empty list.

Insert nodes into the list:
a. Create a new node with the given data.
b. If the head is null, make the new node the head and set its next pointer to itself, forming a circular reference.
c. If the head is not null, traverse the list until the last node is reached (i.e., the node whose next pointer points to the head).
d. Set the next pointer of the last node to the new node.
e. Set the next pointer of the new node to the head, completing the circular reference.

Traverse the circular linked list:
a. Set a temporary node variable to the head.
b. Start a loop that continues until the temporary node variable becomes equal to the head again (indicating completion of a full traversal).
c. Within the loop, process the data of the current node.
d. Update the temporary node variable to its next pointer for the next iteration.

**Comment by Kumar-laxmi** [comment]
Assigned!
@singhapeksha : Java

**Comment by likhi-23** [comment]
please assign to me

**Comment by Kumar-laxmi** [comment]
@singhapeksha  What is your status on this issue?
