### ISSUE TITLE
Ant Colony Optimization Algorithm - Python

### ISSUE THREAD

**Issue by singhapeksha** [Kumar-laxmi/Algorithms#792]
**Is your feature request related to a problem? Please describe.**
Ant colony optimization is not there under optimization algorithms in Python.

**Describe the solution you'd like**

Ant Colony Optimization (ACO) is a metaheuristic optimization algorithm inspired by the foraging behavior of ants. It is commonly used to solve combinatorial optimization problems, such as the traveling salesman problem (TSP) and the vehicle routing problem (VRP). The algorithm mimics the behavior of ants as they search for food and communicate with each other through pheromone trails. Here's an explanation of the key components and steps of the Ant Colony Optimization algorithm:

Problem Definition: Define the optimization problem that needs to be solved, such as the TSP, VRP, or any other combinatorial problem.

Initialization:

Create a colony of artificial ants. Each ant represents a potential solution to the problem.
Assign random initial positions (or solutions) to the ants.
Solution Construction:

Each ant constructs a solution by iteratively building a feasible solution.
At each step, an ant selects the next component or decision based on a probabilistic rule that combines the pheromone trail information and a heuristic value.
The pheromone trail represents the accumulated knowledge of previously found good solutions.
The heuristic value captures problem-specific knowledge to guide the ant's decisions.
The selection probability of a particular component is typically proportional to the pheromone trail intensity and inversely proportional to the distance or cost associated with that component.
Local Update:

After each ant constructs a complete solution, a local update of the pheromone trail is performed.
The pheromone trail intensity is updated based on the quality of the solution constructed by the ant.
The update rule typically involves evaporation of the existing pheromone and deposition of new pheromone based on the quality of the solution.
Global Update:

After all ants have completed their solutions, a global update of the pheromone trail is performed.
The global update rule reinforces the pheromone trails of the best solutions found so far.
It ensures that good solutions have a higher probability of being selected by future ants.
Termination:

Determine a termination criterion, such as reaching a maximum number of iterations or achieving a satisfactory solution.
If the termination criterion is not met, go back to step 3.
Output:

Return the best solution found during the optimization process.
The key idea behind ACO is the positive feedback loop created by the pheromone trail. As ants repeatedly travel along good paths, they deposit pheromone, making those paths more attractive to other ants. Over time, the algorithm converges towards good solutions that are reinforced by the accumulated pheromone.

**Comment by singhapeksha** [comment]
Please assign this to me!!

**Comment by Kumar-laxmi** [comment]
Assigned!
@singhapeksha : Python
