### ISSUE TITLE
Hopcroft-Karp algorithm

### ISSUE THREAD

**Issue by Abhinavcode13** [Kumar-laxmi/Algorithms#794]
**Describe the solution you'd like**
Input: The algorithm takes as input a bipartite graph G, where the vertices are divided into two disjoint sets, often referred to as U and V.

Initialization: Initialize an empty matching M.

Breadth-First Search (BFS): The algorithm starts by performing a breadth-first search (BFS) on the graph G, considering only the unmatched vertices in set U. This BFS is used to find augmenting paths from unmatched vertices in U to unmatched vertices in V.

Layered Graph: The BFS creates layers in the graph, where the layers alternate between vertices in U and V. Each vertex is assigned a level indicating the shortest path length from an unmatched vertex in U. Vertices that are not reachable from unmatched vertices in U are not assigned any level.

Augmenting Paths: After the BFS, if there exists an augmenting path in the layered graph, it means we can increase the size of the matching M. An augmenting path is a path that starts at an unmatched vertex in U, ends at an unmatched vertex in V, and alternates between unmatched and matched edges.

Augmentation: To augment the matching, we start from an unmatched vertex in U and follow the augmenting path to an unmatched vertex in V. We update the matching by flipping the status of the edges along the path (matched edges become unmatched, and vice versa).

Repeat Steps 3-6: We repeat Steps 3-6 until there are no more augmenting paths in the layered graph. In each iteration, a new augmenting path is found and used to update the matching.

Output: The algorithm terminates when there are no more augmenting paths. The resulting matching M is the maximum cardinality matching in the bipartite graph G.

**Comment by Abhinavcode13** [comment]
Please assign me this issue under ssoc @Kumar-laxmi 

Thankyou

**Comment by Kumar-laxmi** [comment]
Assigned!
@Abhinavcode13 : C, C++, Python and Java
