### ISSUE TITLE
spiral matrix in java

### ISSUE THREAD

**Issue by nazeer-18** [Kumar-laxmi/Algorithms#797]
**Is your feature request related to a problem? Please describe.**
After going through your git hub I've found the spiral matrix algorithm is missing in java under arrays

**Describe the solution you'd like**
If you assign this issue to me I'll add the algorithm for spiral matrix under arrays section in java language

**Describe alternatives you've considered**
For sake of confirmation that this algo works properly I will ensure to submit it in GFG so that it will be error free

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/99654015/b302dc86-b2da-42ab-ba5e-e0e596ba2bfc)
A matrix of size 3x3 
with these values as entries now , the spiral order traversal is:
![image](https://github.com/Kumar-laxmi/Algorithms/assets/99654015/800ccf33-ff29-4f69-bdf9-0ce307cf3aed)

Could you please assign this issue to me?

**Comment by nazeer-18** [comment]
Can you assign this to me under SSOC?

**Comment by Venerablevivek** [comment]
@Kumar-laxmi I have successfully solved the same question on leetcode with 100% better solution... Assign this to me ... I know how to solve it very well ...

**Comment by Kumar-laxmi** [comment]
Assigned!
@nazeer-18 : Java

**Comment by nazeer-18** [comment]
Ive created a pull request , kindly check it @Kumar-laxmi 
refer #1036
