### ISSUE TITLE
[Regression Algorithms] : Implemtation of linear, logistic, lasso and ridge regression in Python

### ISSUE THREAD

**Issue by dishamodi0910** [Kumar-laxmi/Algorithms#798]
Implementation of all regression algorithms in Python using the fundamentals and SKLearn both.

**Comment by dishamodi0910** [comment]
I would like to work on this issue. 
Please assign it to me under SSOC 2023

**Comment by Kumar-laxmi** [comment]
Please raise separate issues pertaining to each algorithm
