### ISSUE TITLE
Add Search an element in a Linked List.

### ISSUE THREAD

**Issue by shanvijha30** [Kumar-laxmi/Algorithms#799]
Feature : 

Searching for an element in the list using a key element. Searching any element in the list needs traversing through the list and make the comparison of every element of the list with the key element. If the element is matched with any of the list element then the location of the element is returned from the function.

Solution : 

Will add with adequate comments and proper documentation for readers to get a clear understanding.
To be added in C, C++, Java and Python in Linked List folder.

@Kumar-laxmi Could you please assign this issue to me under SSoC'23
Thank you!

**Comment by SubiditaB** [comment]
Please assign me this issue. I want to contribute to this repo.

**Comment by Kumar-laxmi** [comment]
Sorry this operation has been implemented in Single LL algo
