### ISSUE TITLE
binary<->decimal in java

### ISSUE THREAD

**Issue by nazeer-18** [Kumar-laxmi/Algorithms#800]
**Is your feature request related to a problem? Please describe.**
I've found that algorithm for binary to decimal and decimal to binary is missing .

**Describe the solution you'd like**
So, I want to add a algorithm for the same which converts a decimal number to binary and a binary number into decimal.

**Describe alternatives you've considered**
If you assign this issue to me, I'll work on it.

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/99654015/86815b12-d51d-4ad0-a355-99a2699c01a1)
I've implemented in two ways I'll modify the algo if you assign it to me.

**Comment by nazeer-18** [comment]
Can you assign this to me under SSOc??

**Comment by Kumar-laxmi** [comment]
refer #740
