### ISSUE TITLE
Adding merge sort and bucket sort

### ISSUE THREAD

**Issue by kritika2313** [Kumar-laxmi/Algorithms#802]
Merge sort is defined as a sorting algorithm that works by dividing an array into smaller subarrays, sorting each subarray, and then merging the sorted subarrays back together to form the final sorted array.

Bucket sort is mainly useful when input is uniformly distributed over a range
Feature :
Add bucket and merge sorting technique in java, C++ and Python.

Description of solution :
Will add merge sort and counting  Sorting algorithm with adequate comments for readers to get a clear understanding.
To add in java , C++ and Python.

Can you assign me this issue under SSoC '23  ?

**Comment by swastik-akhil** [comment]
@kritika2313 I am already working on Bucket sort as it's already assigned to me.

**Comment by Kumar-laxmi** [comment]
Kindly raise one issue per algorithm

**Comment by kritika2313** [comment]
@Kumar-laxmi  so could you pls assign me with merge sort?
