### ISSUE TITLE
House Robber problem - 1D Dynamic Programming

### ISSUE THREAD

**Issue by RohithBoppey** [Kumar-laxmi/Algorithms#805]
#### This is an important problem in understanding the _1D dynamic programming concepts_. The problem here is that there is security for a group of houses, but it only gets triggered when 2 consecutive house gets robbed. Each house contains **x** amount of gold. A professional robber has decided to rob the colony of houses. Find the **_maximum_** amount of gold he can rob without getting caught.

Consider the following example: 
There are 4 houses and the amount of gold present is: **[1,2,3,1]** respectively. In this case, the maximum amount would be 4 because: Rob house 1 (money = 1) and then rob house 3 (money = 3). Total amount you can rob = 1 + 3 = 4.

### Approach
This is the general idea of 1D Dynamic Programming. Consider he starts from position 0 and there are 4 houses starting from position 1. So the base diagram would look like this: 
![WhatsApp Image 2023-06-01 at 13 23 39](https://github.com/Kumar-laxmi/Algorithms/assets/73538974/b5500f0e-1a69-4f32-87ac-a797a63f88ce)

The problem is to find the max amount that can be stolen starting from position - 0. 
Let's counter the problem from behind.

If there are 'n' elements, then it is safe to say that if he is starting from position 'n' and above, he can steal nothing, so his max profit would be 0. 
And for the other indices, we can see that we have 2 choices - he can rob the next house and move to ```i + 2``` position or do not rob the house and move to ```i + 1``` position. For each position, we should find the maximum of these 2 choices.

Please consider the following images. (We are doing from last index just for the example sake)
![WhatsApp Image 2023-06-01 at 13 39 50](https://github.com/Kumar-laxmi/Algorithms/assets/73538974/04098b02-ba39-4f47-90bc-5202590d75f1)
![WhatsApp Image 2023-06-01 at 13 40 05](https://github.com/Kumar-laxmi/Algorithms/assets/73538974/c96c8d1b-efbb-4b0e-9fb7-630dcb95eea6)
![WhatsApp Image 2023-06-01 at 13 40 21](https://github.com/Kumar-laxmi/Algorithms/assets/73538974/1c5b5048-e10d-412e-bffc-6a0517365cb1)
![WhatsApp Image 2023-06-01 at 13 40 37](https://github.com/Kumar-laxmi/Algorithms/assets/73538974/43313a7d-e157-49b2-8a74-29ed7806d6d3)

I feel that this would be such a wonderful addition to the existing algorithms and I would like to take on the opportunity to be the one contributing towards it.

I would request you to assign me this issue @Kumar-laxmi and I will put on a PR for C++ language as soon as possible.

**Comment by Kumar-laxmi** [comment]
Kindly don't raise issue solving DSA questions from LeetCode, Gfg, HackerRank, HackerEarth, etc
