### ISSUE TITLE
Add Shortest Distance in a Binary Maze

### ISSUE THREAD

**Issue by Vidip-Ghosh** [Kumar-laxmi/Algorithms#806]
This problem uses Dijkstra algorithm to find the shortest path between source and destination cell. The path can be selected if its value is 1. 

I would like to work on this issue under SSOC'23.

**Comment by ishitagithub** [comment]
Greetings, I want to work on this issue. This problem can be solved using bfs. I want to work under SSOC'23

**Comment by dpvasani** [comment]
assign to me

**Comment by YourFatherDumb** [comment]
please assign  this issue to me
2

**Comment by YourFatherDumb** [comment]
It was shown in my quine as tasked to me.
