### ISSUE TITLE
Add Flood Fill Algorithm in C and C++.

### ISSUE THREAD

**Issue by rayyan-shaikh01** [Kumar-laxmi/Algorithms#808]
I was unable to find the famous Flood Fill Algorithm in the repo, and I want to be the person who solves this issue.
I would love to write the code for the Flood Fill Algorithm in C and C++ as I proficient in these languages.
These will come under the BFS topic, which in turn comes under the Recursion Folder.
I would also have to update the Readme.md files of the Recursion folder.

**Comment by Kumar-laxmi** [comment]
Assigned!
@XRegiGigaSX : C & C++
