### ISSUE TITLE
Add Sieve of Eratosthenes Algorithm for C and C++. 

### ISSUE THREAD

**Issue by XRegiGigaSX** [Kumar-laxmi/Algorithms#809]
I have found out the Sieve of Eratosthenes algorithm is missing in the Arrays folder of C and C++.
I would like to solve this issue.
These topics would come under the Arrays section of the C and C++ folders of the repo.

**Comment by 20a31a0538** [comment]
Hello sir/mam,
I would like to work on this issue.
Please assign me

Thank you
Pavan

**Comment by Kumar-laxmi** [comment]
Sorry this algorithm has been implemented in all four languages
