### ISSUE TITLE
ADD Pascal's Triangle in C++

### ISSUE THREAD

**Issue by Sh4dab** [Kumar-laxmi/Algorithms#812]
The **Pascal's Triangle** is a triangular array of binomial coefficients. Each number in the triangle is the sum of the two numbers directly above it.
for example-
        1
      1   1
    1   2   1
  1   3   3   1
1   4   6   4   1

Feature:
Add Pascal's Triangle Algorithm in C++.

Can you please assign me this issue under SSoC'23.

**Comment by SKSADIRUDDIN** [comment]
I can use PnC formula for solving this issue. Its a basic question on factorial . I can make a function where index will be passed and in that function I can do the necessary steps. For factorial , I can create a hash array , so when ever i want a factorial of a number it will be BigO(1) T.C.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Sh4dab : C, C++, Java & Python

**Comment by SKSADIRUDDIN** [comment]
@Kumar-laxmi  i can do it in all the languages
