### ISSUE TITLE
Intersection of two Linked Lists- Java

### ISSUE THREAD

**Issue by Monishka8303** [Kumar-laxmi/Algorithms#813]
There is implementation of this algorithm in C++. But I want to push its implementation in Java.
Can you please assign this issue to me @Kumar-laxmi as a part of SSoC'23

**Comment by 20a31a0538** [comment]
Hello mam,

AI would like to workn on this issue.

I appreciate you if you assign me this issue.
Please assign me

Thank you
Pavan

**Comment by Kumar-laxmi** [comment]
@Monishka8303 Since it is an easy issue, kindly implement this algorithm in ```C```, ```Java``` and ```Python```

**Comment by Kumar-laxmi** [comment]
Assigned!
@Monishka8303 : C, Java and Python

**Comment by tarunprakashporam** [comment]
Hi mam ,  I done this issue can you please assign me this .

**Comment by Kumar-laxmi** [comment]
@Monishka8303 What is the status on this issue?

**Comment by tarunprakashporam** [comment]
Hi can i work on this .
