### ISSUE TITLE
ALLOCATE MINIMUM NUMBER OF PAGES

### ISSUE THREAD

**Issue by shruti8302** [Kumar-laxmi/Algorithms#815]
### Problem Statement
Given number of pages in n different books and m students. The books are arranged in ascending order of number of pages. Every student is assigned to read some consecutive books. The task is to assign books in such a way that the maximum number of pages assigned to a student is minimum.

### Feature:
Add the above problem statement solution in Python and C++.

### Description of Solution:
I will add the solution of the problem with adequate comments, documentation for readers to get a clear understanding.
The solution is to be added in Python and C++.

Can you please assign me this issue under SSoC'23?

**Comment by Courage003** [comment]
**Problem Statement**
Given number of pages in n different books and m students. The books are arranged in ascending order of number of pages. Every student is assigned to read some consecutive books. The task is to assign books in such a way that the maximum number of pages assigned to a student is minimum.

**Feature**
I will add the most optimized and appropriate code in C,C++ and Python. I have solved more than 500 questions across all coding platforms.

**Solution**
I will also be adding required documentations for readers better understanding. Please assign this task to me under SSOC'2023
