### ISSUE TITLE
Hamming code algorithm

### ISSUE THREAD

**Issue by kadambari68** [Kumar-laxmi/Algorithms#818]
Hamming code is a set of error-correction codes that can be used to detect and correct the errors that can occur when the data is moved or stored from the sender to the receiver. 

I would like to explain the general algorithm of hamming code and how it is useful in error detection and error correction (single and limited multiple error correction) that may occur during the transmission of data. This ensures that the recipient receives the same data that was transmitted by the sender.

I can add the code for this algorithm in C, C++, and Python. (Ssoc'23)

**Comment by Siya8een** [comment]
i will resolve the issue please assign this to me

**Comment by HARSHSUHANE17** [comment]
@Kumar-laxmi I have made a pull request for this Hamming Code using C++.
Please check and merge it with the tag of SSOC'23.
Thankyou.

**Comment by Kumar-laxmi** [comment]
Assigned!
@kadambari68 : C, C++, Java & Python
