### ISSUE TITLE
LONGEST COMMON SUBSEQUENCE ,  MATRIC CHAIN MULTIPLICATION and TRAVELLING SALESMAN PROBLEM in PYTHON 

### ISSUE THREAD

**Issue by Niissh** [Kumar-laxmi/Algorithms#819]
There is no solution of these above mentioned DP problems in python . So , please assign me with this task , I will also explain the program step by step with clear cut definitions and clear code of conduct.

**Comment by Niissh** [comment]
@Kumar-laxmi Kindly assign me with this task . I would really like to contribute to these problems.

**Comment by Kumar-laxmi** [comment]
Kindly raise one issue per algorithm
