### ISSUE TITLE
Sliding Window algorithm in C and Python

### ISSUE THREAD

**Issue by kadambari68** [Kumar-laxmi/Algorithms#820]
Window Sliding Technique is a computational technique that aims to reduce the use of nested loops and replace it with a single loop, thereby reducing the time complexity.

I wish to add the code implementing the sliding window technique with proper comments where required in C and Python as I checked algo for the same in C++ and Java is already there.(Ssoc'23)

I can make an explanation video for the technique and include it in the ReadMe file to make it easier for beginners to understand the core concept.

**Comment by shravanii2308** [comment]
can you assign me this issue @Kumar-laxmi i can do it in all four laguages

**Comment by Yash493** [comment]
@Kumar-laxmi Kindly assign me with this task, I will do my best .
Under SSOC 23

**Comment by parthpishte** [comment]
you can assign to me this issue i can work it out on c , c++, python , java, rust

**Comment by SarthakJaindebugger** [comment]
I want to work on this issue! Pls assign...I know both Python and C

**Comment by Siya8een** [comment]
i will resolve the issue please assign this to me

**Comment by harshit7045** [comment]
Hello,

My name is Harshit Mishra, and I am a student at IIIT Una. I possess a strong understanding of data structures and algorithms and have the ability to write optimized code with explanatory comments. I kindly request to be assigned this issue.

**Comment by Kumar-laxmi** [comment]
@kadambari68 Sliding Window is a technique and not an algorithm, please open issue on specific algorithm (that may use sliding window technique)
