### ISSUE TITLE
Sorting a Linked List in C,C++,Python

### ISSUE THREAD

**Issue by hlw-aryan** [Kumar-laxmi/Algorithms#821]
The problem is to implement a sorting algorithm for a linked list.

I would like to implement a function **sort_linked_list** that takes a linked list as input and sorts it in ascending order. The function should rearrange the nodes of the linked list such that the values are in non-decreasing order.

Solutions

- One alternative solution is to use a classic sorting algorithm like Merge Sort (Top Down vs Bottom Up) or Quick Sort . These algorithms can be adapted to work with linked lists by manipulating the pointers of the nodes.
- Another alternative solution is to convert the linked list into an array, sort the array using a standard sorting algorithm, and then rebuild the linked list using the sorted values. This approach may be simpler to implement but requires additional memory to store the array.

Additional context
Consider handling edge cases such as an empty linked list or a linked list with a single node. Additionally, provide information about the time and space complexity of the chosen sorting algorithm and discuss any trade-offs associated with the implementation.

@Kumar-laxmi 
Please review the proposed implementation and provide feedback or suggestions for improvement.

**Comment by Venerablevivek** [comment]
Hey Mam,
I have the solution of this issue. I am excited to work on this as I am good at DSA. 
Please Assign this task to me.
I will give my best.

Thank You
Vivek Chaudhary

**Comment by Kumar-laxmi** [comment]
Assigned!
@hlw-aryan : C, C++, Java & Python
