### ISSUE TITLE
Merge K sorted Linked List in C,C++,Python

### ISSUE THREAD

**Issue by hlw-aryan** [Kumar-laxmi/Algorithms#822]
The problem is to implement a function that merges k sorted linked lists into a single sorted linked list.

I would like to implement a function **merge_k_lists** that takes an array of k sorted linked lists as input and merges them into a single sorted linked list. The function should return the head of the merged linked list.

Solutions

- One of a solution is to use a priority queue (min-heap) to efficiently select the smallest element from the k linked lists at each step and append it to the merged linked list. This approach ensures that the overall time complexity is optimized.
- Another alternative solution is to use a divide-and-conquer strategy. The function can repeatedly merge pairs of linked lists until only one remains. This approach reduces the problem to merging two sorted linked lists, which can be achieved using a simple merge algorithm.

Additional context
Consider handling edge cases such as an empty array of linked lists or linked lists with no nodes. Discuss the time and space complexity of the chosen approach, as well as any trade-offs associated with the implementation.

@Kumar-laxmi 
Please review the proposed implementation and provide feedback or suggestions for improvement.

**Comment by RashmiK35** [comment]
Would like to add java code for the same.

**Comment by Kumar-laxmi** [comment]
Assigned!
@hlw-aryan : C, C++, Java and Python

**Comment by Kumar-laxmi** [comment]
@hlw-aryan What is your status on this issue?

**Comment by hlw-aryan** [comment]
I'm around 80% done, and I'll soon post a pull request.
@Kumar-laxmi
