### ISSUE TITLE
Manhattan Distance Algorithm in c, c++ and python

### ISSUE THREAD

**Issue by patnaikankit** [Kumar-laxmi/Algorithms#824]
FEATURE:
The Manhattan distance algorithm is a method used to calculate the distance between two points in a grid-like system. It measures the total number of grid cells that need to be traversed horizontally and vertically to reach from one point to another.

The Manhattan distance between two points (x1, y1) and (x2, y2) is calculated using the following formula:

Manhattan distance = |x1 - x2| + |y1 - y2|

Here, |x1 - x2| represents the absolute difference between the x-coordinates of the points, and |y1 - y2| represents the absolute difference between the y-coordinates of the points.

APPROACH:
1. Identify the coordinates of the two points for which you want to calculate the Manhattan distance. Let's call them (x1, y1) and (x2, y2).

2. Calculate the absolute difference between the x-coordinates: |x1 - x2|. This represents the horizontal distance between the points.

3. Calculate the absolute difference between the y-coordinates: |y1 - y2|. This represents the vertical distance between the points.

4. Add the horizontal and vertical distances obtained in steps 2 and 3 to get the Manhattan distance: Manhattan distance = |x1 - x2| + |y1 - y2|.

5. The resulting value is the Manhattan distance between the two points.

I would like to contribute to this algorithm and can you please assign it to me under SSoC '23.

Thanking You,

**Comment by Kumar-laxmi** [comment]
Assigned!
@patnaikankit : C, C++, Java & Python
