### ISSUE TITLE
Fibonacci Number

### ISSUE THREAD

**Issue by KOMNOOB** [Kumar-laxmi/Algorithms#825]
**Is your feature request related to a problem? Please describe.**
Fibonacci sequence in python

**Describe the solution you'd like**
Could you assign me the recursion and arrays part? I can **contribute** to it.

**Additional context**
I can make it in other languages too.

**Comment by KOMNOOB** [comment]
Count this under ssoc 23.

**Comment by Kumar-laxmi** [comment]
What do you mean by ```Basic Algorithm```

**Comment by KOMNOOB** [comment]
I mentioned in Additional context.

**Comment by Kumar-laxmi** [comment]
You have mentioned multiple algorithm, kindly raise issue pertaining to one algorithm

**Comment by KOMNOOB** [comment]
Then I will do all the mentioned algorithms.

**Comment by KOMNOOB** [comment]
@Kumar-laxmi Check once again I will do all the mentioned algorithms.

**Comment by Kumar-laxmi** [comment]
@KOMNOOB You can work on Fibonacci Series using Dynamic Programming in all four languages

**Comment by Kumar-laxmi** [comment]
You can change the Issue title to Fibonacci Number and change the issue description as well

**Comment by Kumar-laxmi** [comment]
Assigned!
@KOMNOOB : C, C++, Python & Java
