### ISSUE TITLE
N-Queens problem in C, C++, Python

### ISSUE THREAD

**Issue by Kraizan** [Kumar-laxmi/Algorithms#827]
**Problem Statement**
The N Queen is the problem of placing N chess queens on an N×N chessboard so that no two queens attack each other.

**Solution Algorithm**
1. Start with an empty chessboard of size N×N.
2. Begin with the first column and iterate through each row in that column.
3. Place a queen in the current row of the current column.
4. Check if the queen placement is valid by ensuring it does not conflict with any previously placed queens.
- Check if any queen in the previous columns shares the same row.
- Check if any queen in the previous columns shares the same diagonal.
- Check if any queen in the previous columns shares the same anti-diagonal.
5. If the queen placement is valid, move to the next column and repeat steps 2-4.
6. If all columns are filled with valid queen placements, we have found a solution. Store it and stop the algorithm.
7. If the current column reaches N and there are no valid queen placements, backtrack to the previous column and move the queen to the next row in that column.
8. Repeat steps 4-7 until a solution is found or all possibilities have been explored.

Kindly assign me this issue under SSoC'23. I would like to contribute by solving this problem.

**Comment by Shankhadweep** [comment]
Please assign this issue to me

**Comment by Kraizan** [comment]
@Kumar-laxmi kindly assign this issue to me.

**Comment by RashmiK35** [comment]
Would like to contribute the code for N-queen problem in java using backtracking and arrays

**Comment by Kumar-laxmi** [comment]
refer #760
