### ISSUE TITLE
Set Matrix Zeroes in Java

### ISSUE THREAD

**Issue by KAPIL9027** [Kumar-laxmi/Algorithms#828]
**Is your feature request related to a problem? Please describe.**
Problem Statement: Given a matrix if an element in the matrix is 0 then you will have to set its entire column and row to 0 and then return the matrix.

**Describe the solution you'd like**
I would use the matrix's first row and col to know if there is any zero in the ith row and jth col if yes then just make the cell at (i,j) zero.

**Describe alternatives you've considered**
Use two arrays to know if there is any zero at ith row or jth col

**Comment by KAPIL9027** [comment]
@Kumar-laxmi, please assign me this issue. I would like to add this algorithm in Java.

**Comment by Kumar-laxmi** [comment]
Please don't raise issues to solve LeetCode, GFG or HackerRank, etc problems.

**Comment by KAPIL9027** [comment]
> Please don't raise issues to solve LeetCode, GFG or HackerRank, etc problems.

then what kind of problems are acceptable because these platforms covers all kind of problems?

**Comment by KAPIL9027** [comment]
#857 this is also a leet code problem, why it is acceptable?

**Comment by Kumar-laxmi** [comment]
> #857 this is also a leet code problem, why it is acceptable?

It has been closed

**Comment by Kumar-laxmi** [comment]
> #857 this is also a leet code problem, why it is acceptable?

Standard Algorithms or solutions related to them
