### ISSUE TITLE
Add Manacher's Algorithm

### ISSUE THREAD

**Issue by rituraj314** [Kumar-laxmi/Algorithms#833]
**Manacher's Algorithm:-**

Manacher's algorithm is used to find the longest palindromic substring in any string.
The problem statement it solves is: Given a string 's' with the length of 'n'. Find the longest palindromic substring in the given string.
This algorithm can be used to find the longest palindromic substring of any string in linear time/O(n) time.

I would like to add this algorithm in C++, Java & Python.

@Kumar-laxmi 
Please provide any feedback or improvements and Please assign me this issue.

**Comment by Kumar-laxmi** [comment]
Assigned!
@rituraj314 : C, C++, Java & Python
