### ISSUE TITLE
sudoku solver

### ISSUE THREAD

**Issue by sowmya061** [Kumar-laxmi/Algorithms#836]
given a N*N sudoku, N is a perfect square , write an algorithm which finds the perfect solution.

@Kumar-laxmi kindly assign me this issue

**Comment by SKSADIRUDDIN** [comment]
@Kumar-laxmi  pls assign me. I have solve similar issue before

**Comment by Kumar-laxmi** [comment]
Since this is an easy issue, kindly implement it in all four languages.

Assigned!
@sowmya061 : C, C++, Python and Java
