### ISSUE TITLE
Add Matrix Chain Multiplication in C

### ISSUE THREAD

**Issue by Shankhadweep** [Kumar-laxmi/Algorithms#837]
**Problem Statement:**_To Implement Matrix Chain Multiplication problem using Dynamic programming approach_

**What is the problem?**
Matrix Chain Multiplication is an algorithm that is applied to determine the lowest cost way for multiplying matrices. The actual multiplication is done using the standard way of multiplying the matrices, i.e., it follows the basic rule that the number of rows in one matrix must be equal to the number of columns in another matrix. Hence, multiple scalar multiplications must be done to achieve the product.
**How it can be done?**
Consider matrices A, B, C, and D, to be multiplied; hence, the multiplication is done using the standard matrix multiplication. There are multiple combinations of the matrices found while using the standard approach since matrix multiplication is associative. For instance, there are five ways to multiply the four matrices given above −

(A(B(CD)))

(A((BC)D))

((AB)(CD))

((A(BC))D)

(((AB)C)D)

Now, if the size of matrices A, B, C, and D are l × m, m × n, n × p, p × q respectively, then the number of scalar multiplications performed will be lmnpq. But the cost of the matrices change based on the rows and columns present in it. Suppose, the values of l, m, n, p, q are 5, 10, 15, 20, 25 respectively, the cost of (A(B(CD))) is 5 × 100 × 25 = 12,500; however, the cost of (A((BC)D)) is 10 × 25 × 37 = 9,250.

So, dynamic programming approach of the matrix chain multiplication is adopted in order to find the combination with the lowest cost.

@Kumar-laxmi please assign me this issue to me. I want to work on this issue for SSOC '23

**Comment by Kumar-laxmi** [comment]
refer #685

**Comment by swastik-akhil** [comment]
I can also implement its code but without the dynamic programming approach in JAVA.
