### ISSUE TITLE
Want to add height of the tree in c++

### ISSUE THREAD

**Issue by Kalivarapubindusree** [Kumar-laxmi/Algorithms#839]
I want to add algorithm related to tree to find the height if the tree in c++ language .
I am contributor under SSOC'23, SWOC'23 .

**Comment by SarthakJaindebugger** [comment]
I can do that, it's simple

**Comment by Yash493** [comment]
Is your feature request related to a problem? Please describe.
Yes, I would like to work on this algorithm.

Describe the solution you'd like
I will add appropriate comments in the code and also properly explain the algorithm

@Kumar-laxmi Kindly assign me with this task, I will do my best .
Under SSOC'23
