### ISSUE TITLE
Want to add pre order ,in order, post order algorithms in c,c++, Java. 

### ISSUE THREAD

**Issue by Kalivarapubindusree** [Kumar-laxmi/Algorithms#841]
I want to add pre order , inorder, post order algorithms for the tree in c,c++, java.
I am contributor under SSOC'23, SWOC'23.

**Comment by Yash493** [comment]
**Explanation**:
Preorder, Inorder, and Postorder are three different traversal methods used to visit and process the nodes of a binary tree.

Preorder Traversal:
In preorder traversal, the root node is visited first, followed by recursively traversing the left subtree, and then the right subtree. The visit order for each node is Root-Left-Right.

Inorder Traversal:
In inorder traversal, the left subtree is visited first, then the root node, and finally the right subtree. The visit order for each node is Left-Root-Right. In case of a binary search tree, an inorder traversal visits the nodes in ascending order.

Postorder Traversal:
In postorder traversal, the left subtree is visited first, then the right subtree, and finally the root node. The visit order for each node is Left-Right-Root.

I am passionate programmer , I can solve this issue problem 
@Kalivarapubindusree Please assign this issue to me

**Comment by Kumar-laxmi** [comment]
refer #768
