### ISSUE TITLE
Add a folder of Bit-Manipulation Algorithms

### ISSUE THREAD

**Issue by AK3847** [Kumar-laxmi/Algorithms#842]
**Is your feature request related to a problem? Please describe.**
This is rather a very common and frequently used technique in Computer Field, even knowing the basic bit-manipulation techniques can help a programmer do efficient coding.

**Describe the solution you'd like**
Please add a folder for the Bit-Manipulation Algorithm in all the languages, and I will add the following basic algorithms:

1.  How to swap two numbers without using a third variable?
2.  To check whether the given number is power of 2 or not.
3.  To find the smallest power of 2 greater than or equal to the given number
4.  Gray to Binary and Binary to Gray conversion
 and many others..

**Describe alternatives you've considered**
  

**Additional context**
 @Kumar-laxmi Please assign me this task under SSOC'23, I have a good knowledge about this topic since I am a competitive programmer. 
- 4 Star on [Codechef](https://www.codechef.com/users/abdulk_69)
- Specialist on [Codeforces](https://codeforces.com/profile/AbdulK_69)
Thanks for Consideration!

**Comment by Kumar-laxmi** [comment]
Bit-Manipulation algorithms are covered in ```maths``` folder

**Comment by AK3847** [comment]
So sorry my bad, I apologize for the inconvenience caused
