### ISSUE TITLE
Rat in a maze 

### ISSUE THREAD

**Issue by Vidip-Ghosh** [Kumar-laxmi/Algorithms#844]
A rat is placed at (0,0) in a square matrix of order N*N. It has to reach the final destination (N-1,N-1). We have to find all possible paths to reach from source to destination. A rat can move in four directions (Left, Right, Up, Down). 

I would like to work on this issue under SSOC'23.

**Comment by Kumar-laxmi** [comment]
Please don't raise issue to solve DSA questions available on LeetCode, HackerRank, etc
