### ISSUE TITLE
Reverse Nodes (of linked list) in group of K elements

### ISSUE THREAD

**Issue by dev-AshishRanjan** [Kumar-laxmi/Algorithms#845]
*Is your feature request related to a problem? Please describe.*
Reverse Nodes in group of K elements
It's a problem of Linked List
**LinkedList - vector - LinkedList Approach**

---
# Solution
*Describe the solution you'd like*

We use the LinkedList to vector to LinkedList approach.
The steps are :
- Create a new Vector or Array using the Linked list provided by simple iteration of the linked list.
- Solve the problem using the created array.
- Create a new or Modify the provided Linked List using values of modified vector or array.

---

**Comment by dev-AshishRanjan** [comment]
I am contributor of **SSoC** and would like to add **my approach of solving linked list questions** in this repo

**Comment by Kumar-laxmi** [comment]
refer #712
