### ISSUE TITLE
Binary Search in C++

### ISSUE THREAD

**Issue by Venerablevivek** [Kumar-laxmi/Algorithms#846]
**Is your feature request related to a problem? Please describe.**
In your Repo, the binary search is implemented in C++ is quite Complex. The variable used are not general or have some meaning, These are not beginner friendly.

**Describe the solution you'd like**
I have used some variables which every beginner used. and The code is quite easy to understand.

**Describe alternatives you've considered**
I will modify the variables used and Add some more comments to it.

**Additional context**
Please assign this issue to me...
@Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Sorry this algorithm has been implemented in ```C++```
