### ISSUE TITLE
Binary Search in cpp 

### ISSUE THREAD

**Issue by Vyshnavi21504** [Kumar-laxmi/Algorithms#85]
Hi , I am a contributor SWOC3.0 
please assign this issue to me

**Comment by MaYaNkKashyap681** [comment]
Assign this to me please.

**Comment by tejasri415** [comment]
Hello,I am contributer from SWOC 3.0 I request you to assign this issue to me ,Thank You.

**Comment by muskaanrajput14** [comment]
Please assign it to me. I want to contribute in C++ Language

**Comment by goyalh4164** [comment]
I am a contributor at SWOC3.0
please assign this issue to me 
I will make a valuable contribution in cpp Language with neat comments and logic

**Comment by Kumar-laxmi** [comment]
Sorry but this algorithm has been implemented in all four languages
