### ISSUE TITLE
Level Order Traversal in Tree is missing!!

### ISSUE THREAD

**Issue by Vikash0122** [Kumar-laxmi/Algorithms#852]
**Is your feature request related to a problem? Please describe.**
Given the root of the Binary Tree. The task is to print the Level order traversal of a tree is breadth-first traversal for the tree.

**Describe the solution you'd like**
Level Order Binary Tree Traversal Using Queue
For each node, first, the node is visited and then its child nodes are put in a FIFO queue. Then again the first node is popped out and then its child nodes are put in a FIFO queue and repeat until the queue becomes empty.

**Comment by Vikash0122** [comment]
@Kumar-laxmi 
Other traversal techniques like preorder, postorder and inorder are present in the tree folder, but Level Order Traversal is missing, so i want to work on this. Pls assign me this issue.

**Comment by triptisingla** [comment]
I work with trees quite frequently and I have a good knowledge of them. please assign me this level order traversal. I will code this in C++.

**Comment by triptisingla** [comment]
I have already resolved the issue, just assign me and i will generate the pr.
