### ISSUE TITLE
Prefix-Postfix-Inflix interconversion algorithm in C & Java

### ISSUE THREAD

**Issue by AnubhaSharma2709** [Kumar-laxmi/Algorithms#854]
Given string S representing a postfix expression, the task is to evaluate the expression and find the final value. Operators will only include the basic arithmetic operators like *, /, + and -.

**Comment by Kumar-laxmi** [comment]
Instead you could work on **Prefix-Postfix-Inflix** interconversion algorithm which is yet to be implemented in ```C``` & ```Java``` (refer algo. no. 66) 
refer: 
- https://github.com/Kumar-laxmi/Algorithms/blob/main/C%2B%2B/Maths/Infix_Postfix_Prefix_Interconversion.cpp
- https://github.com/Kumar-laxmi/Algorithms/blob/main/Python/Maths/prefix_infix_postfix_interconversion.py

**Comment by Kumar-laxmi** [comment]
Assigned!
@AnubhaSharma2709 : C & Java

**Comment by ManmayGhosh** [comment]
@Kumar-laxmi plz assign this to me as my first issue.

**Comment by Tanyamodi** [comment]
I would like to work on this issue, kindly assign this to me.
