### ISSUE TITLE
Solving 8 puzzle with A* algorithm in python 

### ISSUE THREAD

**Issue by ayushi-ras** [Kumar-laxmi/Algorithms#858]
**Is your feature request related to a problem? Please describe.**
8-Puzzle is an interesting game which requires a player to move blocks one at a time to solve a picture or a particular pattern.

**Describe the solution you'd like**
Algorithm used in this solution is A* -A* is a computer algorithm that is widely used in pathfinding and graph traversal, the process of plotting an efficiently traversable path between multiple points, called nodes. Noted for its performance and accuracy, it enjoys widespread use.
The key feature of the A* algorithm is that it keeps a track of each visited node which helps in ignoring the nodes that are already visited, saving a huge amount of time. It also has a list that holds all the nodes that are left to be explored and it chooses the most optimal node from this list, thus saving time not exploring unnecessary or less optimal nodes.

Now talks about solving it -:

We first move the empty space in all the possible directions in the start state and calculate the f-score for each state. This is called expanding the current state.

After expanding the current state, it is pushed into the closed list and the newly generated states are pushed into the open list. A state with the least f-score is selected and expanded again. This process continues until the goal state occurs as the current state. Basically, here we are providing the algorithm a measure to choose its actions. The algorithm chooses the best possible action and proceeds in that path. 

This solves the issue of generating redundant child states, as the algorithm will expand the node with the least f-score.

@Kumar-laxmi Please assign me under SSOC'23.

**Comment by ayushi-ras** [comment]
@Kumar-laxmi please assign me under SSOC'23

**Comment by Kumar-laxmi** [comment]
refer #787

**Comment by ayushi-ras** [comment]
But there is a difference between both issues that was only of A* algorithm but I am solving 8 puzzle problem with that approach then how can you label it as duplicate? @Kumar-laxmi
