### ISSUE TITLE
Longest Common subsequence in Python

### ISSUE THREAD

**Issue by Niissh** [Kumar-laxmi/Algorithms#859]
**Is your feature request related to a problem? Please describe.**
Yes, I would like to work on this algorithm.

**Describe the solution you'd like**
As it is still not coded in Python so I would like to code it in python.

@Kumar-laxmi  Kindly assign me with this task, I will do my best . 
Under SSOC 23

**Comment by Kumar-laxmi** [comment]
Assigned!
@Niissh : Python

**Comment by Niissh** [comment]
> Assigned! @Niissh : Python

Thank you for your kind consideration

**Comment by Niissh** [comment]
@Kumar-laxmi i sent pull request why was it reported as spam kindly tell

**Comment by Niissh** [comment]
so i can improve it the next time

**Comment by ManmayGhosh** [comment]
@Niissh plz assign this to me.
