### ISSUE TITLE
Krushkal's algorithm in C,C++,Python

### ISSUE THREAD

**Issue by hlw-aryan** [Kumar-laxmi/Algorithms#861]
The problem is to implement Kruskal's algorithm to find the minimum spanning tree of a connected, weighted graph.

I would like to implement a function **kruskal_mst** that takes a connected, weighted graph as input and returns the minimum spanning tree as a collection of edges. The function should use Kruskal's algorithm, which works by sorting the edges of the graph in non-decreasing order of their weights and gradually adding the edges to the minimum spanning tree while ensuring that no cycles are formed.

- One of the solution is to use Prim's algorithm to find the minimum spanning tree. Prim's algorithm starts from an arbitrary vertex and repeatedly adds the closest vertex to the current tree, greedily expanding the tree until it spans all vertices.
- Another alternative solution is to use **Boruvka's algorithm**, which works in a similar manner to Kruskal's algorithm but divides the graph into smaller components and merges them iteratively.

Additional context
Consider handling edge cases such as an empty graph or a graph with no edges. Discuss the time and space complexity of the chosen approach and any trade-offs associated with the implementation. 

@Kumar-laxmi 
Please review the proposed implementation and provide feedback or suggestions for improvement.

**Comment by Kumar-laxmi** [comment]
refer #683
