### ISSUE TITLE
Fenwick Tree

### ISSUE THREAD

**Issue by hlw-aryan** [Kumar-laxmi/Algorithms#865]
The problem is to implement a Fenwick tree (Binary Indexed Tree) data structure for efficient range queries and updates on an array.

I would like to implement a Fenwick tree that supports the following operations:

- Building the Fenwick tree from an input array.
- Querying the sum, minimum, maximum, or any other operation over a given range [l, r] in the array.
- Updating the value of a specific element in the array and propagating the changes through the Fenwick tree.

Solution

- One of the solution is to use a brute-force approach that directly computes the query operation over the given range for each query, resulting in O(n) time complexity for each query. However, this approach is inefficient for repeated queries.
- Another alternative solution is to use a segment tree for range queries and updates. While segment trees are more versatile and can handle a wider range of operations, Fenwick trees are more space-efficient and can be more suitable for certain scenarios.

Additional context
Consider handling edge cases such as an empty array or invalid ranges. Discuss the time and space complexity of the Fenwick tree operations and any trade-offs associated with the implementation. It would be helpful to include details about the structure of the Fenwick tree, how the values are stored, and how the queries and updates are performed.

@Kumar-laxmi 
Please review the proposed implementation and provide feedback or suggestions for improvement.

**Comment by Kumar-laxmi** [comment]
Assigned!
@hlw-aryan : C, C++, Java & Python

**Comment by Kumar-laxmi** [comment]
@hlw-aryan Status?

**Comment by hlw-aryan** [comment]
Around 50% work is done.

**Comment by hlw-aryan** [comment]
@Kumar-laxmi However, I have already performed the assignment and was planning to submit a Pull Request for this.
Plz consider🙏
