### ISSUE TITLE
Strassen's Algorithm in C and C++

### ISSUE THREAD

**Issue by Abhinavcode13** [Kumar-laxmi/Algorithms#868]
**Describe the solution you'd like**
Here is the general approach to implementing Strassen's Algorithm:

Check if the given matrices are compatible for multiplication (i.e., the number of columns in the first matrix is equal to the number of rows in the second matrix). If not, return an error.

Divide each input matrix into four equally-sized submatrices (quarters) by halving the rows and columns.

Recursively compute seven different matrix products using the following formulas:

Compute recursively:
P1 = (A11 + A22) * (B11 + B22)
P2 = (A21 + A22) * B11
P3 = A11 * (B12 - B22)
P4 = A22 * (B21 - B11)
P5 = (A11 + A12) * B22
P6 = (A21 - A11) * (B11 + B12)
P7 = (A12 - A22) * (B21 + B22)
Compute four intermediate matrices using the above results:

C11 = P1 + P4 - P5 + P7
C12 = P3 + P5
C21 = P2 + P4
C22 = P1 - P2 + P3 + P6
Combine the four intermediate matrices to form the resulting matrix C.

Return the resulting matrix C as the matrix product of the input matrices A and B.

**Comment by Abhinavcode13** [comment]
Please assign this issue to me @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
refer #675
