### ISSUE TITLE
Parenthesis Checker

### ISSUE THREAD

**Issue by SwapnilGanguly** [Kumar-laxmi/Algorithms#871]
**This algorithm makes sure if a string consisting of parenthesis (including (), {}, []) is valid or not.**

**Describe the solution you'd like**
Example: [ { ( ) } ] is valid, but { } ) ( is invalid as the first brackets are wrongly placed.

**Comment by OWAIS-THEGREAT** [comment]
Name: Mohammed owais
Email: mohammedowais6361@gmail.com
I have complete knowledge of this issue.
It is one of the building block problems in the coding.
I can be solve in the complexity of(time - O(N) and space - O(1))
With or without stack
contributor - SSOC'23

**Comment by harshit7045** [comment]
Hello,

My name is Harshit Mishra, and I am a student at IIIT Una. I possess a strong understanding of data structures and algorithms and have the ability to write optimized code with explanatory comments. I kindly request to be assigned this issue.

**Comment by Vansh912** [comment]
Name: Vansh Tiwari
Email: vanshtiwari.912@gmail.com
I can solve this problem by using stack or without stack also 

contributor - SSOC'23

**Comment by JSWizard1** [comment]
Hiii @Kumar-laxmi.
I have a good command on DSA and algorithms in java language.
pls assign this problem to me  as contributor of SSOC'23.
I can solve this using stack in TC O(n).
