### ISSUE TITLE
Odd Even Linked List in java and python

### ISSUE THREAD

**Issue by RashmiK35** [Kumar-laxmi/Algorithms#874]
Given the head of a singly linked list, group all the nodes with odd indices together followed by the nodes with even indices, and return the reordered list.
For eg:-
Input :- head =[8,4,7,2,9]
Output :- [8,7,9,4,2]

**Comment by ishitagithub** [comment]
Greetings , Please assign me this issue. I will be able to solve it as I am having good knowledge of dsa concepts.
