### ISSUE TITLE
Add:  Binary to Grey conversion and vice-versa

### ISSUE THREAD

**Issue by AK3847** [Kumar-laxmi/Algorithms#875]
**Is your feature request related to a problem? Please describe.**
I haven't been able to find this algorithm in the folder and this is quite useful in Computer Architecture.

**Describe the solution you'd like**
 I would like to add this algorithm to the C++ Math folder.

**Additional context**
@Kumar-laxmi please assign me this issue as I have a great knowledge about this algorithm and good skills in C++. Thank your for considering.

**Comment by Kumar-laxmi** [comment]
Since this is an easy algorithm, so please implement this algorithm in all four languages. Kindly make use of matrices.

Assigned!
@AK3847 : C, C++, Python and Java
