### ISSUE TITLE
Find Unique in c++

### ISSUE THREAD

**Issue by debsouryadatta** [Kumar-laxmi/Algorithms#876]
**Is your feature request related to a problem? Please describe.**
Yes it is related to a problem on arrays, i.e. For finding the unique elements in an array.

**Describe the solution you'd like**
The solution will be in c++ , the solution will provide us only the unique elements in an array.

Hello @Kumar-laxmi , Kindly assign me this issue under SSOC'2.0.

**Comment by killer-mohit** [comment]
Hello @Kumar-laxmi, Kindly assign me this issue under SSOC'2.0.
I will do my best to provide you an optimal and shortest code possible for this issue.

**Comment by harshit7045** [comment]
Hello,

My name is Harshit Mishra, and I am a student at IIIT Una. I possess a strong understanding of data structures and algorithms and have the ability to write optimized code with explanatory comments. I kindly request to be assigned this issue.
