### ISSUE TITLE
Stock Buy and Sell (arrays)

### ISSUE THREAD

**Issue by ayan-joshi** [Kumar-laxmi/Algorithms#879]
**Is your feature request related to a problem? Please describe.**
Problem statement will be like , we willl be given an array of prices where prices[i] is the price of a given stock on an ith day.

**Describe the solution you'd like**
We  want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock. Return the maximum profit we can achieve from this transaction. If we cannot achieve any profit, return 0.

**Describe alternatives you've considered**
For the optimal solution of this problem we will use MAX_VALUE to solve the question.

**Additional context**
It's one of the important questions in topic of array data structures 
@Kumar-laxmi Please assign me this issue so that I can add this to the repository.

**Comment by Kumar-laxmi** [comment]
Please don't raise issues to solve problems from LeetCode, GFG or HackerRank
