### ISSUE TITLE
Binary Search using recursion 

### ISSUE THREAD

**Issue by divyansh14kr** [Kumar-laxmi/Algorithms#882]
As we know binary search is used to search for an element by dividing the array in half each time. This search can also be done via recursion.

Assuming the array taken as input is ordered array, we can apply binary search via recursion also.

Languages : c, java

**Comment by SKSADIRUDDIN** [comment]
Hello I want to contribute in C++, Java, C, Python . I have good knowledge in recursive programming .
pls assign me @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Sorry this algorithm has been implemented in all four languages
