### ISSUE TITLE
Median of 2 Sorted Arrays in C ,C++ and Python

### ISSUE THREAD

**Issue by Ikshvaku24** [Kumar-laxmi/Algorithms#883]
**Is your feature request related to a problem? Please describe.**
The problem is to implement a function **find_median** that takes two sorted arrays. This function returns median of the 2 sorted arrays in an efficient way.

**Describe the solution you'd like**
The solution uses modified binary-search by partitioning both arrays such that the number of elements on the left side of the combined array is equal to the number of elements on the right side of the combined array. This approach works in O(min(log M, log N)) time complexity which is the most efficient in time and space complexity. The solution will handle many edge cases including if the partition is in extremes.

**Additional context**
This problem is an important part of binary search as we are maintaining equal number of elements on both sides of combined array while partitioning them. 
[@Kumar-laxmi](https://github.com/Kumar-laxmi)
Please assign me this issue under SSOC'23.

**Comment by vaishnavi-bhogi19** [comment]
please assign this issue to me under ssoc'23
