### ISSUE TITLE
regarding algorithms of theory of computation

### ISSUE THREAD

**Issue by weaklogics** [Kumar-laxmi/Algorithms#885]
this feature is related to adding some new algorithms or codes into the repository
as the repository have loads of algorithms with concepts of data structures and operating systems but the subject toc or theory of computation is also a topic which students find challenging with its complex machine algorithms so in my way  i want to add some more algos into it to increase its functionality and make it easy for the people who are experiencing it.
That ends up in an easy and efficient way
For example a program or an algorithm to convert NDFA(Non-deterministic finite automata) to DFA(Deterministic finite automata).
etc these are one of the most important topics in computer Science and concurring of what's in the repository given.
I would like to request the project admin to assign me this issue under SSOC
I will resolve it with complete honesty and determination.
Thank you

**Comment by Kumar-laxmi** [comment]
Please mention a specific algo that you would like to contribute to
