### ISSUE TITLE
Add: Vector Pairs

### ISSUE THREAD

**Issue by shravanii2308** [Kumar-laxmi/Algorithms#887]
Is your feature request related to a problem? Please describe.
Vector Pairs are greatly used in solving problems

Describe the solution you'd like
I want to add Vector Pairs algorithm using an example,
I would like to add it with proper explanations and comments in C, C++, and Python.

Additional context
@Kumar-laxmi Please assign me this issue under SSOC'23. I have great knowledge about this topic and I have dealt with it in previous practice and competitive contests. Thanks for your consideration.

**Comment by Khushi-74** [comment]
I would like to work upon this issue under ssoc'23
I will provide code + explanation with comments in c c++

**Comment by SaketGudimella** [comment]
Hello @Kumar-laxmi , Kindly assign me this issue under SSOC'2.0.
