### ISSUE TITLE
Logistic Regression

### ISSUE THREAD

**Issue by dishamodi0910** [Kumar-laxmi/Algorithms#892]
It would include implementation as follows : 
- Using Scikit-Learn
- Without Scikit-Learn in Python

**Comment by Kumar-laxmi** [comment]
Sorry but this algorithm has been implemented in ```Python``` but yet to be done in ```Java``` and ```C```.
Would you like to implement it in ```Java``` & ```C```

**Comment by Khushi-74** [comment]
I would like to  implement in C and java please assign it to me under ssoc'23

**Comment by Kumar-laxmi** [comment]
Assigned!
@Khushi-74 : C & Java

**Comment by Khushi-74** [comment]
@Kumar-laxmi Would you please give more clarification regarding the implementation what all should it include

**Comment by Kumar-laxmi** [comment]
@Khushi-74  What is your update on this?

**Comment by Khushi-74** [comment]
I have the code but can you clarify what all I have to add in this like comments explanation
