### ISSUE TITLE
0/1 Knapsack Problem

### ISSUE THREAD

**Issue by rudra016** [Kumar-laxmi/Algorithms#894]
**Is your feature request related to a problem? Please describe.**
We are given N items where each item has some weight and profit associated with it. We are also given a bag with capacity W, [i.e., the bag can hold at most W weight in it]. The target is to put the items into the bag such that the sum of profits associated with them is the maximum possible. 

Input: N = 3, W = 4, profit[] = {1, 2, 3}, weight[] = {4, 5, 1}
Output: 3
Explanation: There are two items which have weight less than or equal to 4. If we select the item with weight 4, the possible profit is 1. And if we select the item with weight 1, the possible profit is 3. So the maximum possible profit is 3. Note that we cannot put both the items with weight 4 and 1 together as the capacity of the bag is 4.

**Describe the solution you'd like**
I like to add this in C++ and JAVA.

**Describe alternatives you've considered**
A simple solution is to consider all subsets of items and calculate the total weight and profit of all subsets. Consider the only subsets whose total weight is smaller than W. From all such subsets, pick the subset with maximum profit.

Optimal Substructure: To consider all subsets of items, there can be two cases for every item. 

Case 1: The item is included in the optimal subset.
Case 2: The item is not included in the optimal set.

**Additional context**
Note: Can be solved using Recursion, memoization & Dp.

**Comment by Kumar-laxmi** [comment]
Sorry this algorithm has been implemented in all four languages
