### ISSUE TITLE
Hamming Distance

### ISSUE THREAD

**Issue by rakshitdabral** [Kumar-laxmi/Algorithms#896]
**Is your feature request related to a problem? Please describe.**
I would like to work on this feature where we can find the hamming distance

**Describe the solution you'd like**
I would like to implement this feature using cpp as i was not able to find one under math category ...

Please assign it to me @Kumar-laxmi under SSOC 2023

**Comment by Yash493** [comment]
@Kumar-laxmi Kindly assign me with this task, I will do my best .
Under SSOC 23

**Comment by harshit7045** [comment]
Hello,

My name is Harshit Mishra, and I am a student at IIIT Una. I possess a strong understanding of data structures and algorithms and have the ability to write optimized code with explanatory comments. I kindly request to be assigned this issue.

**Comment by Kumar-laxmi** [comment]
Assigned!
@rakshitdabral : C, C++, Python and Java
