### ISSUE TITLE
Allocate Minimum Number of Pages

### ISSUE THREAD

**Issue by Courage003** [Kumar-laxmi/Algorithms#899]
Problem Statement
Given number of pages in n different books and m students. The books are arranged in ascending order of number of pages. Every student is assigned to read some consecutive books. The task is to assign books in such a way that the maximum number of pages assigned to a student is minimum.

Feature
I will add the most optimized and appropriate code in C,C++ and Python. I have solved more than 500 questions across all coding platforms.

Solution
I will also be adding required documentations for readers better understanding. Please assign this task to me under SSOC'2023

https://practice.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1
gfg code 

Topic:- Searching, Divide and conquer

**Comment by harshit7045** [comment]
Hello,

My name is Harshit Mishra, and I am a student at IIIT Una. I possess a strong understanding of data structures and algorithms and have the ability to write optimized code with explanatory comments. I kindly request to be assigned this issue.

**Comment by vivekpal24** [comment]
Sir kindly assign this to me i can solve this using C,Cpp and Python.
