### ISSUE TITLE
Vertical Order Traversal of a Binary Tree in java and python

### ISSUE THREAD

**Issue by RashmiK35** [Kumar-laxmi/Algorithms#901]
The vertical order traversal of a binary tree is a list of top-to-bottom orderings for each column index starting from the leftmost column and ending on the rightmost column. There may be multiple nodes in the same row and same column. In such a case, sort these nodes by their values.

**Comment by Yash493** [comment]
@Kumar-laxmi Please assign me this issue under SSOC'23. I have a great knowledge about this topic and have previously dealt with it in competitive Coding contests. Thanks for Consideration

**Comment by harshit7045** [comment]
Hello,

My name is Harshit Mishra, and I am a student at IIIT Una. I possess a strong understanding of data structures and algorithms and have the ability to write optimized code with explanatory comments. I kindly request to be assigned this issue.

**Comment by Vivek5501** [comment]
@Kumar-laxmi Please assign me this issue as I have decent Knowledge of Trees Data structure and I can explain it in detail.

**Comment by Vidip-Ghosh** [comment]
Please assign this issue to me as I have knowledge of Tree Data Structure.

**Comment by dhruti26** [comment]
Please assign this issue , I will do it for C++
