### ISSUE TITLE
Topological Sort and Kahn's Algorithm in C++ and Java

### ISSUE THREAD

**Issue by codeburn12** [Kumar-laxmi/Algorithms#902]
**Is your feature request related to a problem? Please describe.**
I was unable to find any Topological sort algorithm which is very famous algorithm in Graph. Both BFS and DFS technique use to solve this.

**Describe the solution you'd like**
In topological sorting, node u will always appear before node v if there is a directed edge from node u towards node v(u -> v). Kahn's algorithm which work on BFS while we can use DFS technique to solve the simple one.

**Describe alternatives you've considered**
A well commented code with easy understandable. I want to add this well known algorithm in C++ and Java.

**Additional context**
Topological sorting only exists in [Directed Acyclic Graph . If the nodes of a graph are connected through directed edges and the graph does not contain a cycle, it is called a directed acyclic graph(DAG). 

Can you please assign me this issue under SSoC'23 so that I can send a PR to it.

**Comment by Kumar-laxmi** [comment]
refer #709 & #710
