### ISSUE TITLE
ADD: house robber problem algorithm

### ISSUE THREAD

**Issue by Kaushik1903** [Kumar-laxmi/Algorithms#906]
**Is your feature request related to a problem? Please describe.**
 You are given an array of 'n' houses in a lane. Each house contains some amount of money depicted by the value of the array element. There is a robber who wants to rob the houses in such a way as to get the maximum loot money from the houses.

**Describe the solution you'd like**
I would like to solve it with dynamic programming top-down and bottom -up approach in c++ and java

Could you please assign this issue to me under SSoC'2023

**Comment by Kumar-laxmi** [comment]
Please don't raise issues to solve problems from LeetCode, GFG or HackerRank
