### ISSUE TITLE
Graph Coloring Algorithms

### ISSUE THREAD

**Issue by venom2003op** [Kumar-laxmi/Algorithms#909]
Greedy Coloring Algorithm: The greedy coloring algorithm assigns colors to vertices one by one, using the smallest possible color that is not used by any of its neighboring vertices. It is a simple and fast algorithm.

Backtracking Algorithms: Backtracking algorithms such as the DSatur algorithm and the Welsh-Powell algorithm aim to find the minimum number of colors required to color a graph by exploring different color assignments and backtracking when a conflict arises.

I would like to request the project admin to assign me this issue under SSOC
I would like to work on this issue under SSOC'23.

**Comment by kamalyash2002** [comment]
Please assign this issue to me.

**Comment by ManmayGhosh** [comment]
Please assign this issue to me.

**Comment by YourFatherDumb** [comment]
please assign this issue to me
