### ISSUE TITLE
Request for Adding Fibonacci Search Algorithm in Multiple Languages

### ISSUE THREAD

**Issue by derphalesh** [Kumar-laxmi/Algorithms#911]
Hi there!

I would like to request the addition of the Fibonacci search algorithm to the repository. This algorithm is a powerful and efficient search technique that can be used in various scenarios. It would be a valuable addition to the project.

I propose implementing the Fibonacci search algorithm in the following programming languages:

C
C++
Java
Python

The Fibonacci search algorithm combines the advantages of both binary search and Fibonacci numbers to search for an element in a sorted array efficiently. It has a time complexity of O(log n) and is particularly useful when the data is uniformly distributed.

I am eager to contribute to this feature and would be happy to take ownership of this issue. I will ensure the algorithm's correct implementation, thoroughly test it and provide comprehensive documentation for each language implementation.

Please assign this issue to me, and I will start working on it immediately. I look forward to collaborating with the community and making a meaningful contribution to the project.

Thank you!

Best regards,
Phalesh(Ssoc'23)

**Comment by Kumar-laxmi** [comment]
refer #690
