### ISSUE TITLE
ADD- Spiral Print Matrix Implementation in Java 

### ISSUE THREAD

**Issue by Swapnendu003** [Kumar-laxmi/Algorithms#912]
The algorithm of this particular program is present in C, C++, and Python but there is no JAVA code for this.

I will solve this algorithm in JAVA.

@Kumar-laxmi can you please assign me this issue for SSOC 2.0 so that I can send a PR request?

**Comment by swastik-akhil** [comment]
This issue has been already raised by me. Refer to issue #742.
