### ISSUE TITLE
ADD : Reverse Number Implementation in Java and C

### ISSUE THREAD

**Issue by sagnik-datta-02** [Kumar-laxmi/Algorithms#913]
**Is your feature request related to a problem? Please describe.**
I saw that the Reverse number in Maths Section was done only in Python and C++.

**Describe the solution you'd like**
I would like to do it in Java and C.

@Kumar-laxmi Can you please assign me this issue for SSOC 2.0 so that I can send a PR ?

**Comment by Yash493** [comment]
Is your feature request related to a problem? Please describe.
Yes, I would like to work on this problem.

Describe the solution you'd like
I will add appropriate comments in the code.

@Kumar-laxmi Kindly assign me with this task, I will do my best .
Under SSOC'23

**Comment by harshit7045** [comment]
Hello,

My name is Harshit Mishra, and I am a student at IIIT Una. I possess a strong understanding of data structures and algorithms and have the ability to write optimized code with explanatory comments. I kindly request to be assigned this issue.

**Comment by swastik-akhil** [comment]
This has already been implemented.
