### ISSUE TITLE
ADD- Rabin Karp Algorithm in Java and C

### ISSUE THREAD

**Issue by Swapnendu003** [Kumar-laxmi/Algorithms#914]
I have seen that this algorithm is solved in Python and C++ but there is no C and Java code for this algorithm

I will be solving this algorithm in C and Java language.

@Kumar-laxmi can you please assign me this issue for SSOC 2.0 so that I can send a PR request?

**Comment by Kumar-laxmi** [comment]
Assigned!
@Swapnendu003 : C & Java

**Comment by Mahendra-Lohar** [comment]
@Kumar-laxmi Please assign me this issue. I will do it C and java.
