### ISSUE TITLE
linear regression algorithm using python

### ISSUE THREAD

**Issue by mobtomc** [Kumar-laxmi/Algorithms#915]
many times brokers end up taking an unfair amount of commission whenever they are asked to evaluate a property .

i would like to evaluate the price of houses using this algorithm myself using linear regression algorithm and thus saving my hard-earned money.

**Comment by Yash493** [comment]
Is your feature request related to a problem? Please describe.
Yes, I would like to work on this algorithm.

Describe the solution you'd like
I will add appropriate comments in the code and also properly explain the algorithm

@Kumar-laxmi Kindly assign me with this task, I will do my best .
Under SSOC'23

**Comment by Kumar-laxmi** [comment]
Sorry this algorithm has been implemented in Python
