### ISSUE TITLE
Binary Search Tree

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#92]
This algorithm is available in the following languages:
- C++
- Java
- Python

**Comment by VishalS-HK** [comment]
Can I do this in C

**Comment by Kumar-laxmi** [comment]
Assigned!
@VishalS-HK : C

**Comment by ManavLohia945** [comment]
I can code it in java assign it to me sir

**Comment by mvpamansingh** [comment]
I am willing to work on this issue, can you please assign this issue in C++ and java

**Comment by ARCHITABHATTAD** [comment]
hey @Kumar-laxmi I can code it in C++ and python assign it to me

**Comment by Kumar-laxmi** [comment]
Assigned!
@ManavLohia945 : Java
@mvpamansingh : C++
@ARCHITABHATTAD : Python

**Comment by ManavLohia945** [comment]
Kumar sir someone has created a different issue for this and you have assigned it to them for java language. What should I do?
![image](https://user-images.githubusercontent.com/96055639/210688318-3362dcf5-c10d-4aa2-a5d1-748c1d0d2b66.png)

**Comment by Kumar-laxmi** [comment]
> Kumar sir someone has created a different issue for this and you have assigned it to them for java language. What should I do?
> 
> ![image](https://user-images.githubusercontent.com/96055639/210688318-3362dcf5-c10d-4aa2-a5d1-748c1d0d2b66.png)
> 
> 

I have closed that issue

**Comment by ManavLohia945** [comment]
Great!! Thank you

**Comment by Kumar-laxmi** [comment]
@ARCHITABHATTAD @ManavLohia945 What is your status on this issue?

**Comment by ManavLohia945** [comment]
Will complete this issue by next week.

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi can you assign me this for python?

**Comment by sumitkr2000** [comment]
Hey, @Kumar-laxmi is this issue available in C++? If not, please assign me this issue in C++.

**Comment by Kumar-laxmi** [comment]
> Hey, @Kumar-laxmi is this issue available in C++? If not, please assign me this issue in C++.

C++ is not available

**Comment by Kumar-laxmi** [comment]
Assigned!
@sitamgithub-MSIT : Python
