### ISSUE TITLE
Add : Happy Number Algorithm in Maths Section in Java Python C and C++

### ISSUE THREAD

**Issue by sagnik-datta-02** [Kumar-laxmi/Algorithms#921]
**Is your feature request related to a problem? Please describe.**
I want to include algorithm for Happy Number in Java , Python C and C++

**Describe the solution you'd like**

The happy number can be defined as a number which will yield 1 when it is replaced by the sum of the square of its digits repeatedly. If this process results in an endless cycle of numbers containing 4, then the number is called an unhappy number.

For example, 32 is a happy number as the process yields 1 as follows

3^2+2^2= 13
1^2+3^2= 10
1^2+0^2= 1

@Kumar-laxmi Please assign me the issue for SSOC . I will give proper documentation and complete it as soon as possible.

**Comment by Mahendra-Lohar** [comment]
@Kumar-laxmi Please assigne me the issue for SSOC. I will do it in java , python , C , C++

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir please assign me this issue. I want to work upon it using c, c++, java .As a beginner in open source i think this would be a good start for me.

**Comment by ishitagithub** [comment]
Greetings Sir, please assign me this issue, I will do it using both naive and effective approach.

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi please assign this task to me to contribute under the program SSoC 2.0.
I can solve this task in C, C++, PYTHON & JAVA programming languages.

**Comment by sagnik-datta-02** [comment]
@Kumar-laxmi please assign me this issue

**Comment by imrish4** [comment]
@Kumar-laxmi please assign me this issue, I will do it in Java, Python, C, and C++.

**Comment by tuhinsunny** [comment]
@Kumar-laxmi It would be really helpful if you could assign this issue to me . I would be able to do this in any language C, C++,Java or Python

**Comment by YourFatherDumb** [comment]
@Kumar-laxmi Pls assign me this issue, I have completed it in C, CPP, Java, Python. I just need to start the PR.

**Comment by Kumar-laxmi** [comment]
Assigned!
@sagnik-datta-02 : C, C++, Java & Python

**Comment by sagnik-datta-02** [comment]
@Kumar-laxmi Ok Thanks!
