### ISSUE TITLE
Chudnovsky algorithm

### ISSUE THREAD

**Issue by Mayureshd-18** [Kumar-laxmi/Algorithms#922]
@Kumar-laxmi , The Chudnovsky algorithm is a fast method for calculating the digits of π, based on Ramanujan's π formulae.
Please assign me this issue, I would implement it in python using binary splitting which can calculate 10000s of digits of pi in less than 0.0005 secs

**Comment by Kumar-laxmi** [comment]
Since this is an easy issue you need to implement this in all four languages.

Assigned!
@Mayureshd-18 : C, C++, Java & Python
