### ISSUE TITLE
add:Strassen's Matrix

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [Kumar-laxmi/Algorithms#927]
@Kumar-laxmi Strassen’s Matrix Multiplication is the divide and conquer approach to solve the matrix multiplication problems.The usual matrix multiplication method multiplies each row with each column to achieve the product matrix.Strassen’s method was introduced to reduce the time complexity from O(n3) to O(nlog 7). Please assign me this use under SSOC I would like to implement it in java and python

**Comment by Kumar-laxmi** [comment]
Sorry this algorithm has been implemented in all four languages
