### ISSUE TITLE
Add : Aho-Corasick Algorithm for Pattern Searching

### ISSUE THREAD

**Issue by Aarsh30** [Kumar-laxmi/Algorithms#928]
so this Aho-Corasick algorithm is  dictionary-matching algorithm that locates elements of a finite set of strings within an input text. It matches all strings simultaneously

I will be solving this algorithm 

@Kumar-laxmi can you please assign me this issue for SSOC 2.0 so that I can send a PR request?

**Comment by Kumar-laxmi** [comment]
Assigned!
@Aarsh30 : C, C++, Python and Java
