### ISSUE TITLE
KNN Algorithm 

### ISSUE THREAD

**Issue by ayan-joshi** [Kumar-laxmi/Algorithms#929]
**Is your feature request related to a problem? Please describe.**
K-Nearest Neighbors (KNN) is a simple and intuitive classification algorithm.

**Describe the solution you'd like**
The algorithm classifies a new instance by considering the class labels of its K nearest neighbors in the feature space.

**Describe alternatives you've considered**
I will add all it's steps in the readme file and explain with a coding explaination.

**Additional context**
@Kumar-laxmi Please assign me this issue I'm a SSOC contributor

**Comment by Kumar-laxmi** [comment]
In which two languages would you like to implement? (please don't use ML Libraries)

**Comment by Kumar-laxmi** [comment]
This algo. is yet to be implemented in Java & Python (please don't use ML Libraries)

Assigned!
@ayan-joshi : Java & Python

**Comment by ayan-joshi** [comment]
okay
