### ISSUE TITLE
ADD - Decimal <-> Binary Converter in C++ and Java

### ISSUE THREAD

**Issue by sagnik-datta-02** [Kumar-laxmi/Algorithms#930]
**Is your feature request related to a problem? Please describe.**
I saw there is no Java and C++ code for Decimal to Binary Converter

**Describe the solution you'd like**
I would like to add the Java and C++ code algos for this for SSOC. 

@Kumar-laxmi can you please assign me this for SSOC so that I can send a PR ?

**Comment by harshit7045** [comment]
Hello,

My name is Harshit Mishra, and I am a student at IIIT Una. I possess a strong understanding of data structures and algorithms and have the ability to write optimized code with explanatory comments. I kindly request to be assigned this issue.

**Comment by swastik-akhil** [comment]
This issue is already been there in the repository.

**Comment by sagnik-datta-02** [comment]
@Kumar-laxmi please assign me this issue for SSOC

**Comment by swastik-akhil** [comment]
@sagnik-datta-02 I've already made a PR on this issue.
