### ISSUE TITLE
Add SVM algorithm

### ISSUE THREAD

**Issue by ayan-joshi** [Kumar-laxmi/Algorithms#931]
**Is your feature request related to a problem? Please describe.**
Support Vector Machines (SVM) is a powerful supervised learning algorithm used for classification and regression tasks. 

**Describe the solution you'd like**
The algorithm finds the best hyperplane in a high-dimensional feature space that separates the data into different classes while maximizing the margin between the classes.

**Describe alternatives you've considered**
I will add all steps of the algorithm in the readme file and add code to explain it.

**Additional context**
@Kumar-laxmi Please assign me this issue

**Comment by Kumar-laxmi** [comment]
In which two languages would you like to implement? (please don't use ML Libraries)

**Comment by ayan-joshi** [comment]
I would like to do in C++ and Python

**Comment by Kumar-laxmi** [comment]
Assigned!
@ayan-joshi : C++ & Python
