### ISSUE TITLE
Level Order Traversal of Binary Tree in C++

### ISSUE THREAD

**Issue by Vivek5501** [Kumar-laxmi/Algorithms#934]
**Is your feature request related to a problem? Please describe.**
The problem is to implement level order traversal of Binary Tree.

**Describe the solution you'd like**
Level order traversal is a popular tree traversal algorithm that visits each node of a binary tree in a breadth-first manner, going through each level from left to right. It explores the tree level by level, starting from the root and moving to the nodes at the next level before traversing deeper.

@Kumar-laxmi  Please assign me this issue under SSOC'23

**Comment by killer-mohit** [comment]
I will support my code with proper documentation and explanation of the Level Order Traversal of Binary tree.
@Kumar-laxmi Kindly assign me this issue under SSOC'23

**Comment by Deepanshi177** [comment]
Please assign me this issue.

**Comment by chhavisharma30** [comment]
I can work on this issue. Kindly assign me this issue.
