### ISSUE TITLE
Zero sum subarray

### ISSUE THREAD

**Issue by black-shirt** [Kumar-laxmi/Algorithms#939]
**Is your feature request related to a problem? Please describe.**
Given an array of integers. We have to determine if there exists a subarray of sum zero.

**Describe the solution you'd like**
To solve this problem, we can use a set to keep track of the cumulative sum of elements encountered so far. As we traverse the array, we calculate the cumulative sum by adding each element to the current sum. If the cumulative sum becomes zero at any point or if we encounter a cumulative sum that is already present in the set, it means there is a subarray with a sum of zero. In such cases, we can immediately return True. If we traverse the entire array without finding any zero sum subarray, we return False.

**Additional context**
The algorithm can be implemented in C, C++, Python and Java.

Please assign this issue to me under SSoC' 23 so I can add a PR for it.

**Comment by Deepanshi177** [comment]
Please assign me this issue.

**Comment by Kumar-laxmi** [comment]
Assigned!
@black-shirt : C, C++, Python and Java
