### ISSUE TITLE
Maze Problem  (Recursion Question in Java)

### ISSUE THREAD

**Issue by Simranverma123** [Kumar-laxmi/Algorithms#942]
**Is your feature request related to a problem? Please describe.**
A given N × N sized maze exists. Top-left cell is the source location, and bottom-right cell is the destination location, respectively. Finding all the possible ways to reach destination

**Describe the solution you'd like**
I would like to apply recursion to solve this problem by breaking it into smaller subproblems

**Screenshot Attached **
![Java MazeProblemSS](https://github.com/Kumar-laxmi/Algorithms/assets/88669720/bd004972-e836-4074-bfca-059253320b8f)

**Comment by Tanyamodi** [comment]
I would like to work on this issue, kindly assign this to me.
