### ISSUE TITLE
ADDING GRAPH ALGORITHMS IN JAVA

### ISSUE THREAD

**Issue by SANKOJUKEERTHI** [Kumar-laxmi/Algorithms#947]
This folder doesn't consist of DFS and BFS. And many other vital algorithms need to be included in the graphs folder, like the topo sort and implementation of Dijkstra's algorithm using a set and priority queue. The bellman Ford, kruskal's , kosaraju's and so on..
All these can be included in the graphs folder in Java. Please assign this issue to me. I will make sure to make sure the folder is complete.

**Comment by Kumar-laxmi** [comment]
Please raise issue on a specific algorithm
