### ISSUE TITLE
ShellShort

### ISSUE THREAD

**Issue by harshit7045** [Kumar-laxmi/Algorithms#949]
I'm interested in contributing to your GitHub repository and would like to add a shell short whit proper comments to  the java short folder .Please let me know if you would be open to accepting this addition. I believe it will benefit the community. 
please assign me this issue @Kumar-laxmi

**Comment by swastik-akhil** [comment]
I can make my contribution in the Shell Sort algorithm in **JAVA**. Kindly assign me this under **SSOC'2**.
Admin- @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
refer #720
