### ISSUE TITLE
Kadane's Algorithm

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#95]
The algorithm is available is the following language:
- C
- C++
- Python
- Java

**Comment by MaYaNkKashyap681** [comment]
Assign this to me , i will can code it in C++ and C and Python.

**Comment by akshatjainei** [comment]
Kindly Assign it to me , I can add the algo in all the languages

**Comment by goyalh4164** [comment]
Assign this to me , I can code it in C++ with all comments

**Comment by Kumar-laxmi** [comment]
Assigned!
@MaYaNkKashyap681 : C
@goyalh4164 : C++
@akshatjainei : Python

**Comment by aradhya-10** [comment]
@Kumar-laxmi Could you assign this to me for the Java code?

**Comment by Soham-Chakraborty-8455** [comment]
Could you assign me the C++ code?

**Comment by akshatjainei** [comment]
@goyalh4164 are we supposed to take a test case as an example or we have to take input?

**Comment by goyalh4164** [comment]
@akshatjainei In my case you have to pass the size of the Array and then the elements then it returns the answer.

**Comment by vijay-kumar-yadav** [comment]
@Kumar-laxmi  please assign this issue in cpp to me as its been more than three days.

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi please assign this issue in cpp to me as its been more than three days.

The issue is active as PR on C++ is open (refer #107)

**Comment by vijay-kumar-yadav** [comment]
> > @Kumar-laxmi please assign this issue in cpp to me as its been more than three days.
> 
> The issue is active as PR on C++ is open (refer #107)

Okay

**Comment by GouravDutta-01** [comment]
@Kumar-laxmi ,As the PR for Java code implementation still has not been made,can I be assigned for it?

**Comment by Kumar-laxmi** [comment]
Due to inactivity I am unassigning @aradhya-10 @MaYaNkKashyap681 @akshatjainei this issue

**Comment by Kumar-laxmi** [comment]
Assigned!
@GouravDutta-01 : Java
@Soham-Chakraborty-8455 : C
@vijay-kumar-yadav : Python

**Comment by vijay-kumar-yadav** [comment]
@Kumar-laxmi  some one already written in pyhton and put it in math section
[Check this](https://github.com/Kumar-laxmi/Algorithms/blob/main/Python/Maths/KadaneAlgo.py)

what should I do ??

**Comment by MaYaNkKashyap681** [comment]
I have already made pull request for c code #327, and made changes you want, then why you have unassigned me.

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi some one already written in pyhton and put it in math section [Check this link](https://github.com/Kumar-laxmi/Algorithms/blob/main/Python/Maths/KadaneAlgo.py)
> 
> what should I do ?? Change its position please tell And I think the person who uploaded this was not assigned on this issue. I have done the required changes ready for pr.

Now check..

**Comment by Kumar-laxmi** [comment]
> I have already made pull request for c code #327, and made changes you want, then why you have unassigned me.

@MaYaNkKashyap681 That PR is for KMP algorithm and not Kadane Algo

**Comment by Kumar-laxmi** [comment]
@Soham-Chakraborty-8455 Due to your inactivity I am unassigning you this issue
