### ISSUE TITLE
Backtracking Algorithms

### ISSUE THREAD

**Issue by Tanvii26** [Kumar-laxmi/Algorithms#952]
Hii there! The available resources section does not currently have a backtracking category. I propose to add in one. We have many questions under this label as follows :

- N-Queens
- Subset Sum
- Hamiltonian Cycle
- Rat in a Maze
- Knights Tour
and more....

I hope you can assign this issue to me. First thing first, I can work upon the N-Queens problem for a quick start to this category.
Please assign this issue to me. Thank You.

**Comment by Kumar-laxmi** [comment]
Please raise one issue per algorithm (by the some of the mentioned algo. are already a part of open issues)
