### ISSUE TITLE
Want to add "Genetic Algorithm" in Python in Optimization folder

### ISSUE THREAD

**Issue by rayarka26** [Kumar-laxmi/Algorithms#957]
**Is your feature request related to a problem? Please describe.**
Genetic Algorithm is an optimization algorithm

**Describe the solution you'd like**
I helps to optimize and is widely used in various problems like Allocation problems, Transportation problem etc.

Please assign me under SSOC'23

**Comment by Kumar-laxmi** [comment]
refer #786
