### ISSUE TITLE
Adding Boyer Moore algorithm

### ISSUE THREAD

**Issue by kritika2313** [Kumar-laxmi/Algorithms#959]
i would like to add boyer moore algorithm ie a patter matching technique in this procedure, the substring or pattern is searched from the last character of the pattern. When a substring of main string matches with a substring of the pattern, it moves to find other occurrences of the matched substring. It can also move to find a prefix of the pattern which is a suffix of main string. Otherwise, it moves the whole length of the pattern.
i can code this in c++,java,c and python as well with proper documentation.
@Kumar-laxmi can u assign me this under ssoc 23?

**Comment by Kumar-laxmi** [comment]
Assigned!
@kritika2313 : C, C++, Python & Java

**Comment by Akshatverma01** [comment]
@Kumar-laxmi Hello sir, I am experienced working with this algorithm as recently I worked on it, solved some string problems based on it. I can perform this algorithm with good efficiency , time and space complexities. 
I am damn sure you will be satisfied with my solutions . Please assign it to me.
