### ISSUE TITLE
Rabin Karp Algorithm

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#96]
Rabin-Karp algorithm is an algorithm used for searching/matching patterns in the text using a hash function. Unlike Naive string matching algorithm, it does not travel through every character in the initial phase rather it filters the characters that do not match and then performs the comparison.

This algorithm is available in the following language:
- C
- C++
- Java
- Python

**Comment by vijay-kumar-yadav** [comment]
please assign kandane algo in c++ to me.

**Comment by vijay-kumar-yadav** [comment]
Please Assign Rabin Karp algorithm in cpp to me.

**Comment by Kumar-laxmi** [comment]
Assigned!
@vijay-kumar-yadav : C++

**Comment by ManavLohia945** [comment]
Assign Rabin karp algorithm in java to me .

**Comment by Kumar-laxmi** [comment]
Assigned!
@vijay-kumar-yadav : C++
@ManavLohia945 : Java

**Comment by vijay-kumar-yadav** [comment]
@Kumar-laxmi  assign me for C

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi assign me for C

Sorry, but you have already contributed in C++.

Look for other algorithms

**Comment by Priyanshu-Singh-1** [comment]
Okay got it!

**Comment by Abhinavkar** [comment]
@Kumar-laxmi assign me in c i have already created and ready to merge

**Comment by Kumar-laxmi** [comment]
Assigned!
@ManavLohia945 : Java
@Abhinavkar : C

**Comment by Kumar-laxmi** [comment]
@ManavLohia945 It has been 3 days of your assignment, what is your status

**Comment by ManavLohia945** [comment]
I am sorry but I won't be able to contribute to this issue you can unassign me this

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 
You can assign the issue that you have given to @ManavLohia945.
I am ready to contribute

**Comment by Kumar-laxmi** [comment]
Assigned!
@Priyanshu-Singh-1 : Java
@Abhinavkar : C

**Comment by Abhinavkar** [comment]
I have already made a pr

**Comment by muskan467** [comment]
Please assign Rabin Karp algorithm in Python to me. @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
@Abhinavkar @Priyanshu-Singh-1 What is your status on this issue?

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi I have already made the PR month ago 
Please have a look #260
