### ISSUE TITLE
 Adding Euler’s Totient function 

### ISSUE THREAD

**Issue by kritika2313** [Kumar-laxmi/Algorithms#961]
Euler’s Totient function Φ (n) for an input n is the count of numbers in {1, 2, 3, …, n-1} that are relatively prime to n, i.e., the numbers whose GCD (Greatest Common Divisor) with n is 1.
Φ(1) = 1  
gcd(1, 1) is 1

Φ(2) = 1
gcd(1, 2) is 1, but gcd(2, 2) is 2.

Φ(3) = 2
gcd(1, 3) is 1 and gcd(2, 3) is 1

Φ(4) = 2
gcd(1, 4) is 1 and gcd(3, 4) is 1

i can code this in c++,java and python with prorper documentation.
@Kumar-laxmi can you assign this to me unders ssoc23?

**Comment by Kumar-laxmi** [comment]
Assigned!
@kritika2313 : C, C++, Python and Java
