### ISSUE TITLE
Artifical Neural network by backpropogation algorithm

### ISSUE THREAD

**Issue by NikitaGupta-17** [Kumar-laxmi/Algorithms#964]
**Is your feature request related to a problem? Please describe.**
Build an artifical Neural network by implementing back propogation algorithm. 

**Describe the solution you'd like**
Using MLP classifier ANn can be build.

Language used - Python

**Comment by Kumar-laxmi** [comment]
Kindly do not use ML Libraries for it

Assigned!
@NikitaGupta-17 : Python

**Comment by Kumar-laxmi** [comment]
@NikitaGupta-17 What is your status on this issue?

**Comment by NikitaGupta-17** [comment]
Working on it. 
Please don't unassigned this issue from me.

**Comment by Kumar-laxmi** [comment]
@NikitaGupta-17 Now what is your status?
