### ISSUE TITLE
Maximum Width of a Binary Tree

### ISSUE THREAD

**Issue by moh1t-do** [Kumar-laxmi/Algorithms#968]
**Is your feature request related to a problem? Please describe.**
Hello, @Kumar-laxmi , I would wish to add **Maximum Width of a Binary Tree in C++**. Could you please allow me to do so!

I am contributor under SSOC'23

Thank You!

**Describe the solution you'd like**
The largest width of a binary tree corresponds to the highest value among all the widths at different levels. The width of a level is determined by the greatest number of nodes between the leftmost and rightmost node on that level, including the terminal nodes as well as any null nodes located between them.

**Describe alternatives you've considered**

**Additional context**
- will add the algorithm's time and space complexity

**Comment by Deepanshi177** [comment]
Please assign me this issue.

**Comment by Tanyamodi** [comment]
I would like to solve this issue, kindly assign this to me.
