### ISSUE TITLE
Naïve Bayes Classifier implementation in C++ & Python

### ISSUE THREAD

**Issue by Paritosh-J** [Kumar-laxmi/Algorithms#970]
**Is your feature request related to a problem? Please describe.**
- *Naïve Bayes Classifier* is a supervised learning algorithm based on Bayes theorem and used for solving classification problems.
- It is called *Naïve* because it assumes that the occurrence of a certain feature is independent of the occurrence of other features.

**Describe the solution you'd like**
Implementation of Naïve Bayes Classifier in **C++ & Python**.

I request to please assign me this issue.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Paritosh-J : C++ & Python

**Comment by Mahendra-Lohar** [comment]
@Kumar-laxmi  Please Assign me this issue . I will do it in C++ and python
