### ISSUE TITLE
Enhancement: Diffie-Hellman Key Exchange - Basic C Implementation

### ISSUE THREAD

**Issue by neeraj542** [Kumar-laxmi/Algorithms#971]
**Topic:** Diffie-Hellman Key Exchange in C Programming
**Difficulty Level of Algorithm:** Medium Level
**Time Complexity:**  O(log n)

**Is your feature request related to a problem? Please describe.**
The current implementation of the Diffie-Hellman Key Exchange algorithm in the GitHub repository lacks a basic C implementation. This hinders users who are looking for a simple implementation of this cryptographic algorithm to understand and experiment with the concept. Thus, there is a need to provide a basic C implementation of the Diffie-Hellman Key Exchange algorithm in the repository.

**Describe the solution you'd like**
It is suggested to add a basic implementation of the Diffie-Hellman Key Exchange algorithm in C language to the repository. This implementation should include the necessary functions and logic to generate private keys, calculate public keys, and compute the shared secret key between two parties. It should be well-documented and include appropriate comments to aid users in understanding and utilizing the algorithm.

**Describe alternatives you've considered**

- Utilizing an existing library: Instead of implementing the Diffie-Hellman Key Exchange algorithm from scratch, users could be directed to well-established cryptographic libraries like OpenSSL. However, providing a basic implementation in C would serve as a valuable learning resource and offer a starting point for those interested in understanding the algorithm.

**Additional context**
Including a basic C implementation of the Diffie-Hellman Key Exchange algorithm in the repository would be beneficial for users who prefer a lightweight and self-contained solution. It would foster learning and experimentation, allowing users to explore the algorithm's functionality and gain a better understanding of its cryptographic principles.

- Serve as a foundation for further enhancements and optimizations, with the potential for community contributions to improve the code, optimize performance, and handle edge cases.
- Empower users to have a hands-on experience and gain practical insights into the Diffie-Hellman Key Exchange algorithm by providing a clear and comprehensively documented implementation with usage instructions and examples.

**Comment by neeraj542** [comment]
Hello @96vksingh @rohitbabugaddeti @Hannibal404 @Kumar-laxmi,

I hope this message finds you well. I wanted to bring your attention to the issue I recently created titled "Enhancement: Diffie-Hellman Key Exchange - Basic C Implementation" in the "Algorithm" repository. I believe this issue is well-suited for the Social Summer of Code'23 program, and I am eager to contribute to it. Therefore, I kindly request that this issue be assigned to me for implementation.

Thank you for your consideration.

Best regards,
Neeraj Meena

**Comment by Kumar-laxmi** [comment]
refer #687
