### ISSUE TITLE
Add Reverse the Array Question solution

### ISSUE THREAD

**Issue by Abhay3819** [Kumar-laxmi/Algorithms#973]
**Description**
## Problem - Reverse the array

Examples:-

Input : 1, 2, 3, 4, 5
Output :5, 4, 3, 2, 1

Input : 10, 20, 30, 40
Output : 40, 30, 20, 10

Time Complexity - O(n)
Space Comlexity - O(1)

**Comment by Deepanshi177** [comment]
Please assign me this issue.

**Comment by HardikGoyal2003** [comment]
@Abhay3819 pls assign me. Its a good start problem, I can contribute to it...
Thanks

**Comment by TanishqPal-tech** [comment]
Please assign it to me as my first issue

**Comment by atinder11** [comment]
Please assign it to me to solve in c++

**Comment by Soumya6Tiwari** [comment]
@Kumar-laxmi  sir please assign me this issue . i can solve it using C,C++,JAVA.

**Comment by Kumar-laxmi** [comment]
I would suggest you to raise issue pertaining to standard algorithms rather than discrete operations
