### ISSUE TITLE
Quick Select Algorithm in C, C++, Python & Java

### ISSUE THREAD

**Issue by Trisha-tech** [Kumar-laxmi/Algorithms#979]
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to a problem. I would like to implement Quick Select algorithm using C, C++, Python and Java languages.

Quick Select is a selection algorithm to find the k-th smallest element in an unordered list. It is related to the 'Quick Sort' sorting algorithm. The difference is, instead of recurring for both sides (after finding pivot), it recurs only for the part that contains the k-th smallest element.

**Describe the solution you'd like**
I would like a solution that provides an implementation of the Quick Select algorithm using C, C++, Python and Java languages.

I would like to work on this issue under SSOC 2023. Please assign it to me.

**Comment by atinder11** [comment]
Can you assign this issue to me

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi Please /assign this task to me to contribute under SSoC'23 program.

**Comment by Kumar-laxmi** [comment]
@Trisha-tech What is your status on this issue?
