### ISSUE TITLE
Implement Decision Tree (without Library)

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#98]
Implement Decision Tree in the following languages:

- C
- C++
- Java
- Python

**Comment by ManavLohia945** [comment]
I can code it in java with comments assign it me to sir

**Comment by stiwari-ds** [comment]
I noticed that decision tree is already implemented in Python [here](https://github.com/Kumar-laxmi/Algorithms/blob/main/Python/Machine%20Learning/Decision%20Tree/decision_tree.py).
Please let me know in case you are looking for an alternative implementation or improvement in code quality/efficiency.
If the issue is closed for Python, I will work on another algorithm.

**Comment by Kumar-laxmi** [comment]
> I noticed that decision tree is already implemented in Python [here](https://github.com/Kumar-laxmi/Algorithms/blob/main/Python/Machine%20Learning/Decision%20Tree/decision_tree.py). Please let me know in case you are looking for an alternative implementation or improvement in code quality/efficiency. If the issue is closed for Python, I will work on another algorithm.

You are always welcomed to improve the code quality, would you like to improve the code

**Comment by stiwari-ds** [comment]
Let me inspect the existing code in detail and get back to you regarding scope of improvement.
I will first complete working on the issue that has already been assigned to me (Linear Regression) and then come back to this if it is still open.

**Comment by maheshbanagar** [comment]
i will implement decision trees in c,c++ and java.
@Kumar-laxmi could you please assign to me?

**Comment by Kumar-laxmi** [comment]
@stiwari-ds Would you like to implement in any language?

**Comment by khushigarg1** [comment]
I would like to solve this problem in C++ please assign it to me!

**Comment by Kumar-laxmi** [comment]
Assigned!
@khushigarg1 : C++

**Comment by Abhilash1781** [comment]
@Kumar-laxmi I would like to contribute in C

**Comment by Abhilash1781** [comment]
@Kumar-laxmi sir , I'm unable to work on this issue . Please unassign me , sorry for the inconvenience .

**Comment by Kumar-laxmi** [comment]
@khushigarg1 What is your status?
