### ISSUE TITLE
Boruvka's Algorithm (Graphs) in C, C++, Python and Java

### ISSUE THREAD

**Issue by Trisha-tech** [Kumar-laxmi/Algorithms#980]
Is your feature request related to a problem? Please describe.
Yes, my feature request is related to a problem. I would like to implement Boruvka's algorithm using C, C++, Python and Java languages.

Boruvka’s Algorithm is a greedy algorithm used for finding the minimum spanning tree of a weighted undirected graph. This algorithm is also known as Sollin’s algorithm. Boruvka’s Algorithm is slightly similar to Kruskal’s Algorithm.

Describe the solution you'd like
I would like a solution that provides an implementation of the Boruvka's algorithm using C, C++, Python and Java languages.

I would like to work on this issue under SSOC 2023. Please assign it to me.

**Comment by Kumar-laxmi** [comment]
Assigned!
@Trisha-tech : C, C++, Python & Java

**Comment by Kumar-laxmi** [comment]
@Trisha-tech What is your status on this issue?
