### ISSUE TITLE
Missing basic recursion algorithms

### ISSUE THREAD

**Issue by KOMNOOB** [Kumar-laxmi/Algorithms#982]
**Is your feature request related to a problem? Please describe.**
The recursion folder in Python is **empty**.

**Describe the solution you'd like**
I want to add _factorial calculation, the sum of natural numbers_ programs in Python.

**Additional context**
I can _also_ implement in C++ and C.

**Comment by Kumar-laxmi** [comment]
Factorial of a number has been done in all four languages (check the maths folder)
