### ISSUE TITLE
Tim Sort in C, C++, Java & Python

### ISSUE THREAD

**Issue by harshit7045** [Kumar-laxmi/Algorithms#987]
'Im interested in contributing to your GitHub repository and would like to add Tim short with proper comments in the java short folder  to enhance its functionality. Please let me know if you would be open to accepting this addition. I believe it will benefit the community. Thank you for your consideration.
@Kumar-laxmi please assign this issue to me.

**Comment by Kumar-laxmi** [comment]
Do you mean ```Tim Sort```?

**Comment by harshit7045** [comment]
yes sir sorry for the typo
