### ISSUE TITLE
Request for Implementation of Sudoku Solver Algorithm 

### ISSUE THREAD

**Issue by SaketGudimella** [Kumar-laxmi/Algorithms#988]
**Is your feature request related to a problem? Please describe.**
This feature request is to add algorithms to existing directories based on respective algorithmic topics. In this case, I would like to implement a Sudoku Solver Algorithm in the Backtracking Directory that is able to solve Sudoku puzzles efficiently and accurately.

**Describe the solution you'd like**
I would like to implement a Sudoku Solver Algorithm that handle various levels of difficulty of an incomplete Sudoku puzzle as input and provide the solution as output to the user within a reasonable time frame.

**Add any other context or screenshots about the feature request here.**

The tech stack for this includes, using Python, Data structures, Algorithmic Approach and Development Tools (like Visual Studio Code, other libraries). 

I have great knowledge in this area and have implemented this while doing mini-projects at my college. 

 **@Kumar-laxmi** please assign this issue to me under SSoC'23 and I will complete this problem with proper documentation and within a proper timeframe.

**Comment by SaketGudimella** [comment]
- [ ]

**Comment by Kumar-laxmi** [comment]
refer #836
