### ISSUE TITLE
Monotonic array in c++

### ISSUE THREAD

**Issue by Nikita06211** [Kumar-laxmi/Algorithms#996]
**Is your feature request related to a problem? Please describe.**
i want to create the algorithm for monotonic array problem. It will check if an array is monotonically increasing or decreasing

**Describe the solution you'd like**
The solution will be in c++.

kindly assign me this issue under ssoc2.0

**Comment by Soumya6Tiwari** [comment]
Input: arr[] = {1, 2, 2, 3}
Output: Yes
Explanation: Here 1 < 2 <= 2 < 3. 
The array is in increasing order. Therefore it is monotonic.

Input: arr[] =  {6, 5, 4, 3}
Output: Yes
Explanation: Here 6 > 5 > 4 > 3. 
The array is in decreasing order. So it is monotonic.

@Kumar-laxmi  sir please assign me this issue . I would like to solve this using JAVA, C.

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi sir is it first come first serve process that the one who first ask for assigning the task will only be assigned?

@Soumya6Tiwari Yeah
