### ISSUE TITLE
Bloom Filter Algorithm in C++ and Python

### ISSUE THREAD

**Issue by thakurdiwakar** [Kumar-laxmi/Algorithms#997]
**Bloom Filter**

A Bloom filter is a space-efficient probabilistic data structure that is used to test whether an element is a member of a set. False positive matches are possible, but false negatives are not – in other words, a query returns either "possibly in set" or "definitely not in set". Elements can be added to the set, but not removed (though this can be addressed with the counting Bloom filter variant); the more items added, the larger the probability of false positives.

Bloom filters are often used to test whether a string is present in a large set of strings, such as a password database or a list of banned words. They are also used in web browsers to check whether a URL has been visited before, and in email servers to check whether an email address has been used before.

A Bloom filter is a bit array of m bits, where m is the number of elements that can be stored in the filter. When an element is added to the filter, its hash value is computed and used to set bits in the bit array. When a query is made to the filter, its hash value is computed and used to check if the corresponding bits in the bit array are set. If they are, then the element is probably in the filter; if they are not, then the element is definitely not in the filter.

**Describe the solution you'd like**
I wanted to add the solution in  Python.
You can find about it more [here](https://www.enjoyalgorithms.com/blog/bloom-filter)

**Here's a basic overview of how a Bloom Filter works:**

Initialization: Create a bit array of length m and set all bits to 0.

Adding elements: To add an element to the filter, hash it using k different hash functions, which generate k different indices in the bit array. Set the corresponding bits at these indices to 1.

Membership query: To check if an element is in the set, hash it using the same k hash functions and check if all the corresponding bits in the bit array are set to 1. If any of the bits are 0, the element is definitely not in the set. If all the bits are 1, the element is probably in the set (but there's a chance of false positives).

**Comment by Jagan-45** [comment]
would you assign this issue  under ssoc2023  @thakurdiwakar

**Comment by Kumar-laxmi** [comment]
@thakurdiwakar What is your status on this issue?

**Comment by thakurdiwakar** [comment]
> @thakurdiwakar What is your status on this issue?

check : https://github.com/Kumar-laxmi/Algorithms/pull/1144
